### ISSUE TITLE
关注UP的主页没有动态列表，看不到UP以往的动态

### ISSUE THREAD

**Issue by ZZZWfW** [Richasy/Bili.Uwp#1002]
### Bug 描述

关注UP的主页没有动态列表

### 复现问题的步骤

```plain text
1、打开哔哩UWP
2、点击个人头像，点击关注数
3、打开关注UP的主页
4、发现没有动态列表
```

### 预期行为

我想看到UP主页的动态列表

### 截图

![QQ截图20220404073611](https://user-images.githubusercontent.com/102930566/161453850-14ea8c00-e8a2-4bde-ae68-8ded195e3d35.png)
![QQ截图20220404073647](https://user-images.githubusercontent.com/102930566/161453852-41192852-0988-4988-892b-12685eb0bfec.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

Windows10 21H2 (Build 19044)

### 运行设备

桌面/台式机

**Comment by Richasy** [comment]
这不是bug，该功能尚未支持，将与 #679 合并处理
