### ISSUE TITLE
功能需求建议[Feature] 我的标题

### ISSUE THREAD

**Issue by XiaoNNNNNNNN** [Richasy/Bili.Uwp#1008]
### 问题描述

是否能将“稍后再看”与“我的收藏”独立到导航栏中？这样就不用老是去二级菜单里了

### 描述解决方案

不用进入二级菜单就行。谢谢

### 附加信息

希望哔哩越做越好~

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
#1013 也许可以部分解决你的问题。但将登录后功能放在侧边导航栏是我尽力在避免的设计
