### ISSUE TITLE
[Bug] 视频播放帧数很低

### ISSUE THREAD

**Issue by Do7and** [Richasy/Bili.Uwp#1010]
### Bug 描述

无论打开什么视频，帧数都很低，目测不到30帧，ppt的感觉，网页端b站正常，试了两个版本的哔哩都不行（2.2204.2.0和之前的一个老版本上面没找到版本号）。调整分辨率也没用，360p也是帧数很低。 跟着常见问题的解决方案没找到，因为我这个不全屏也帧数低且在n卡控制面板3d设置里没找到监视器设置的选项。自带的笔记本显示屏和外接显示屏切换过试了也没效果。 神舟笔记本  显卡gtx1070    cpu inteli7-7700hq 
3月19日看视频还是正常的，然后最近突然就这样了

### 复现问题的步骤

```plain text
1.打开应用
2.任意点一个视频进去播放
3.播放帧数很低
```

### 预期行为

正常帧数播放

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 其它来源

老版本是微信公众号推荐，新版是自己去github下的

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [X] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2022-04-04.log](https://github.com/Richasy/Bili.Uwp/files/8416283/applog.2022-04-04.log)
[applog.2022-04-05.log](https://github.com/Richasy/Bili.Uwp/files/8416284/applog.2022-04-05.log)
[Log - 20220404.log](https://github.com/Richasy/Bili.Uwp/files/8416286/Log.-.20220404.log)
[Log - 20220405.log](https://github.com/Richasy/Bili.Uwp/files/8416287/Log.-.20220405.log)

### 人人为我，我为人人

是的，我希望我的代码出现在哔哩中

**Comment by XMD0718** [comment]
同样，21H2，使用v2.2204.4.0版本，帧率很低

**Comment by gqjony** [comment]
ppt是吧？
去显卡控制面板里打开哔哩垂直同步。
在程序的"帮助&支持"里有写到这个。
