### ISSUE TITLE
[Bug] 打开新窗口关闭后遗留重复声音

### ISSUE THREAD

**Issue by xpader** [Richasy/Bili.Uwp#1012]
### Bug 描述

首先想感谢一下作者，App 做的很漂亮，很好用。但在使用中遇到一些问题，比如新窗口关闭后遗留声音。视频画面不随App放大而同比放大，打开时一直初始化的问题。

### 复现问题的步骤

```plain text
第一个问题打开新窗口后再关闭视频遗留的问题：
在视频画面左下角的新窗口打开按钮点击后不等新窗口内容完全加载，直接关闭新窗口，该窗口仍在后台加载，并且过一会就会听到声音，除非关闭整个App不然关不掉此声音。

第二个视频画面不随窗口最大化而同比放大，这一点应该只是体验问题。

第三点就是每次打开时App初始化都要很长时间。
```

### 预期行为

窗口关闭后，该窗口内容应立即停止加载。

### 应用来源

- [ ] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

**Comment by Richasy** [comment]
你用的是旧版吧，新版不支持开多个播放窗口

**Comment by xpader** [comment]
@Richasy 不是开多个窗口，而是开一个窗口立即关闭，然后在原窗口内播放。
