### ISSUE TITLE
[Bug] 在Xbox上播放视频会闪退

### ISSUE THREAD

**Issue by avialae** [Richasy/Bili.Uwp#1017]
### Bug 描述

在Xbox Series X上使用哔哩时，打开任意视频均会闪退

### 复现问题的步骤

```plain text
1. 打开应用
2. 点开视频
```

### 预期行为

正常播放视频

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

Xbox最新版

### 运行设备

Xbox

### 备注

Xbox Series X，打开允许25HZ、允许50HZ、ALLM、VRR、4K（120HZ）、HDR10、未开启Dolby Vision、DV for gaming。

找到Xbox系统的日志后将会上传日志。

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
没有复现这个问题，是不是系统没更新？
