### ISSUE TITLE
[Feature] 希望可以添加Xbox选框支持

### ISSUE THREAD

**Issue by avialae** [Richasy/Bili.Uwp#1018]
### 问题描述

如果未适配Xbox，将会以兼容模式运行，无法使用像遥控器一样的上下左右的选框操作，类似于在Xbox上运行Microsoft Edge的体验，只能使用光标。

### 描述解决方案

若适配可参考Microsoft Store的Xbox版本UI

### 备选方案

还可参考别的流媒体平台的UI

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
精力有限，目前还是桌面优先。XBOX只是力所能及的情况下修一修，UI我是不准备再整了
