### ISSUE TITLE
[Bug+Feature] 收藏与投币功能界面、动态与分享方式上的问题

### ISSUE THREAD

**Issue by Pairman** [Richasy/Bili.Uwp#102]
## Bug/Feature 描述

bug:
1. 在视频详情页中“点击收藏按钮-打开收藏菜单-选定收藏夹”进行收藏时，不会高亮显示被选定的收藏夹（也就是点击后仍然和其他收藏夹以相同的状态显示）导致很难分清自己到底选择了哪个/是否已经选择

feature:
1. 收藏后收藏按钮的五角星仍是空心的、投币后投币按钮也是空心的，希望增加对这两个图标的优化，这样就可以知道自己有没有投币或收藏了
2. 在动态界面里点击磁贴右下角分享按钮不会产生任何动作；在视频详情页中点击分享按钮后获取的分享菜单中没有通过bilibili动态分享的方式；请问动态功能是正在建设中吗？
3. 希望能加入“当推荐/热门/直播/动态等页面已经到最顶端时，通过持续下滑鼠标滚轮来刷新页面”的功能，这样更加方便
4. 希望在设置中可以复制版本号，这样提交issue时更加方便

## 复现步骤

已是最新版

重现问题的步骤：

1. 打开应用
2. 随便打开一个视频进行管控
3. 点击收藏或投币；点击分享
4. 收藏或投币后按钮图标均无用来指示“已收藏”的状态变化、收藏过程中收藏夹列表中不会高亮已选条目；分享列表中没有通过bilibili动态分享的选项

## 预期的行为

希望选择收藏夹、收藏/投币后图标能指示出“已收藏/已投币”的状态；希望分享(甚至动态)功能可以进一步完善；希望可以在视频/动态列表中通过鼠标滚轮刷新；希望可以复制版本号

## 截图

不好意思，暂无相关截图，请谅解

## 环境

应用来源：

- [ ] Microsoft Store
- [X] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}
    2.2109.1801.0
系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [X] Windows 11 (22000.184)
- [ ] 内测版本 ({系统版本})

运行设备：

- [X] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录

是功能不足而不是程序错误，故未抓取log。

## 备注

软件很美观

**Comment by Richasy** [comment]
关于高亮与feature 1：按钮有选中状态，即整个按钮会变成系统主题色，你观察的不明显可能是你的主题色是灰色或者其它和当前界面背景相仿的颜色。

feature2: 是的，目前分享按钮仍在建设中

feature3: 滚动问题是bug，且已在PR #104 中修复，会在下一个更新中放出

feature4: 收到

---

另外，希望下次bug和feature可以分开发，这样便于追踪
