### ISSUE TITLE
[Feature] 在笔记本电脑上首页推荐视频封面显示内容过小，希望能调整列数

### ISSUE THREAD

**Issue by 850710247liu** [Richasy/Bili.Uwp#1020]
### 问题描述

首页推荐现在是一行是5列，在笔记本电脑上封面显示过小

### 描述解决方案

希望能判断一下是否是笔记本电脑而调成4列。

### 备选方案

如果无法判断 手动设置也可

### 附加信息

现在的情况是，如果不最大化，手动把屏幕拉满是4列，然而一点最大化就是5列了，估计是代码问题

**Comment by Richasy** [comment]
列数的调整是应用根据窗口大小来判断的，而不是根据设备。按照你的描述，你的屏幕大小应该是正好处于一个临界点。但很遗憾，我无法为某个单独设备来进行调整
