### ISSUE TITLE
[Bug] 鼠标侧键会控制视频暂停和播放

### ISSUE THREAD

**Issue by abrclano** [Richasy/Bili.Uwp#1022]
### Bug 描述

鼠标侧键会控制视频暂停和播放。

### 复现问题的步骤

```plain text
播放视频时，点击鼠标侧键的前进键时会导致视频暂停，而点击侧键的返回键时会同时完成返回和暂停两个动作（若视频播放结束时点击侧键的返回键将会重播视频并返回）。
```

### 预期行为

使鼠标侧键不能控制视频的播放和暂停。

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
侧键前进键目前行为和鼠标左键单击一样，单击暂停，双击全屏，我不觉得这是一个问题。
返回键的话，我不理解你说的暂停并返回的意思，侧键返回键就是退出当前的页面，退出页面前应用会暂停视频，这也是预期的行为
