### ISSUE TITLE
[Bug] 媒体传输控件控制模式设置失效

### ISSUE THREAD

**Issue by sotcit** [Richasy/Bili.Uwp#1023]
### Bug 描述

[四月更新 - 定](https://github.com/Richasy/Bili.Uwp/releases/tag/v2.2204.4.0)，版本号（v2.2204.4.0），媒体传输控件控制模式设置失效，不管设置为自动还是手动，打开视频播放时，控件的显隐是都是自动的。

### 复现问题的步骤

```plain text
1. 打开应用
2. 进入设置
3. 找到媒体传输控件控制模式设置，修改为手动
4. 打开视频播放页面，控件的显隐是自动的，设置并无作用
5. 找到问题，可复现
```

### 预期行为

在媒体传输控件控制模式设置为手动时，应该手动控制控件的显隐，而不是自动。

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 备注

卸载重装后，同样可以复现问题。

**Comment by Richasy** [comment]
该设置已经事实性失效，忘了移除，下个版本会移除掉
