### ISSUE TITLE
[Bug] 弹幕云屏蔽配置没有真正屏蔽

### ISSUE THREAD

**Issue by Maxdontron** [Richasy/Bili.Uwp#1026]
### Bug 描述

不能同步屏蔽词并对弹幕进行屏蔽，即使打开了弹幕云屏蔽

### 复现问题的步骤

```plain text
1 打开应用
2 打开任意一个视频
3 打开弹幕
4 问题出现
```

### 预期行为

能正确屏蔽个人屏蔽词列表中的屏蔽词并对弹幕进行处理

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-04-07.log](https://github.com/Richasy/Bili.Uwp/files/8442618/applog.2022-04-07.log)

**Comment by Richasy** [comment]
我注意到ios上好像已经没有了弹幕云屏蔽的选项，所以暂时先移除（解决不了问题就解决出问题的模块(～￣▽￣)～）
