### ISSUE TITLE
[Feature] “海外加速”

### ISSUE THREAD

**Issue by 3F3Feng** [Richasy/Bili.Uwp#1028]
### 问题描述

b站官方UWP应用有海外视频加速按钮，实际上是一键翻墙回国，让国外的大会员可以正常观看b站大会员资源。不知道是通过什么做的，但是现在这个功能几乎已经失效了。

### 描述解决方案

使用浏览器翻墙b站网页版时，真正需要翻墙的只有获取视频地址的步骤，加载视频内容的时候关了翻墙插件反而可以加速加载。不知道有没有办法可以绕过获取视频地址之前查ip的步骤。

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
关于这个，我其实有个疑惑。就像国内看海外视频一样，挂个梯子就可以看本来看不了的内容。海外想看国内的应该也是要挂梯子。那么这样一来，解除哔哩的网络环回（参见Wiki里的常见问题）后，应该就可以使用你自己的翻墙工具再翻回来了吧

**Comment by Extreme-Icer** [comment]
> 关于这个，我其实有个疑惑。就像国内看海外视频一样，挂个梯子就可以看本来看不了的内容。海外想看国内的应该也是要挂梯子。那么这样一来，解除哔哩的网络环回（参见Wiki里的常见问题）后，应该就可以使用你自己的翻墙工具再翻回来了吧

很抱歉挖个坟。原版uwp的海外加速是将哔哩哔哩的某些域名拉入代理软件的proxy路由，然后开启海外加速开关，就可以看境内番剧和海外番剧（而不一定是只能看港澳台番剧）。当前版本我测试了下，港澳台番剧播放似乎没反应（没加载），境内番剧就是地区受限。不过那个海外加速解除不了电影分区的地区限制，可能有些还是搜不到。
可以参考下要不要把这个功能移植进来
