### ISSUE TITLE
[Bug] 调整视频大小出现黑屏和布局偏移

### ISSUE THREAD

**Issue by 1061875478** [Richasy/Bili.Uwp#103]
## Bug 描述

使用媒体控件调整视频大小时大概率出现黑屏，有音频无画面，特别是全屏。
小窗模式在复位时整体布局会往右移动。

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 随意点击一个视频
3. 点击 '全屏模式'进入全屏模式
4. 点击 '全屏模式'复位
5. 点击 '小窗模式'进入小窗模式
6. 点击 '小窗模式'复位

## 预期的行为

进入全屏模式时画面变黑，有时候是再次点击复位时变黑，有声音。
再次通过其他调整也无法显示画面，只能重新加载，其他两个模式概率较小，全屏模式接近百分之90。

进入小窗模式在复位整体向右偏移。

## 截图
![全屏](https://user-images.githubusercontent.com/68525017/133915240-35bf1511-bcc2-4a5a-b818-74584d0d3a57.jpg)
![全屏复位](https://user-images.githubusercontent.com/68525017/133915247-43a9df70-4ab2-4d17-9f79-49b3197bb878.jpg)

![小窗复位](https://user-images.githubusercontent.com/68525017/133915281-c2d3670c-05c4-4b94-a975-a5eb7a0cac26.jpg)
## 环境

应用来源：

- [ ] Microsoft Store
- [ x ] Github
- [ ] 其他来源（请注明来源）

应用版本：{2.2109.1801.0}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ x ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [ x ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录
[applog.2021-09-19.log](https://github.com/Richasy/Bili.Uwp/files/7190967/applog.2021-09-19.log)

## 备注
cpu 5800x
gpu 2070s

我不清楚显卡是否有影响，至少在我的笔记本和我台式机在使用1060的时候哔哩第一个版本没有任何问题。
换成2070s之后哔哩第一个版本100%出现视频画面卡住，是否可能是隐藏的遗留问题。
我在进行复现时本来想使用开发者的最新一期视频作为例子，但是我发现复现的概率比较低，是否也有可能是视频分辨率的问题。

**Comment by ZhangTianrong** [comment]
遇到相似情况，改变播放器大小就会黑屏。

**Comment by 1061875478** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by ZhangTianrong** [comment]
补充一下，我这边设备也是AMD的CPU，是5800H，显卡是3050Ti. 日志没有有用信息，切换至全屏100%黑屏。

**Comment by Richasy** [comment]
如果是黑屏问题，那我这边与 #747 合并处理

**Comment by ZhangTianrong** [comment]
> 如果是黑屏问题，那我这边与 #747 合并处理

如果要合并处理建议修改 #747 的标题和描述。这个 issue 并不局限于直播，而且明确由调整视频大小如 toggle 全屏触发， #747 并不能与之契合。
