### ISSUE TITLE
[Feature] 自动播放下一集时记住上次窗口状态

### ISSUE THREAD

**Issue by Cielstar** [Richasy/Bili.Uwp#1033]
### 问题描述

设置里选择播放器显示为默认后，在播放视频时打开全窗口模式，当自动切换到下一集时窗口又会变回默认

### 描述解决方案

希望可以自动记住上一个视频的窗口显示状态

**Comment by Richasy** [comment]
你用的是哪个版本？最新版应该修了这个问题，请详细描述

**Comment by Cielstar** [comment]
> 你用的是哪个版本？最新版应该修了这个问题，请详细描述

最近几个测加载版本都有这个问题啊
现在版本是2.2204.4.0
![bili](https://user-images.githubusercontent.com/43376740/163716163-ea0245a0-97dd-47a6-9852-d4f065f29873.gif)


再反馈一个问题，有时候播放着或者切集会卡死，只有声音，并且最大化那三个按钮有用，其他按钮没用，这是今天的日志

2022/04/17 21:00:59.120|Info|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
控制器加载完成
|
2022/04/17 21:03:18.988|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:03:25.868|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:03:37.690|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:04:44.352|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|Windows.UI.Xaml.LayoutCycleException: Setting the Template property on a UserControl is not supported.
Setting the Template property on a UserControl is not supported.
2022/04/17 21:04:45.288|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:05:10.638|Info|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
控制器加载完成
|
2022/04/17 21:05:21.706|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:05:24.123|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|Windows.UI.Xaml.LayoutCycleException: Setting the Template property on a UserControl is not supported.
Setting the Template property on a UserControl is not supported.
2022/04/17 21:05:25.139|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:05:38.551|Info|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
控制器加载完成
|
2022/04/17 21:05:58.486|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|Windows.UI.Xaml.LayoutCycleException: Setting the Template property on a UserControl is not supported.
Setting the Template property on a UserControl is not supported.
2022/04/17 21:05:59.657|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:08:27.172|Info|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
控制器加载完成
|
2022/04/17 21:10:23.514|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:10:34.445|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:21:09.377|Info|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
控制器加载完成
|

**Comment by Cielstar** [comment]
> 你用的是哪个版本？最新版应该修了这个问题，请详细描述

最近几个测加载版本都有这个问题啊
现在版本是2.2204.4.0
![bili](https://user-images.githubusercontent.com/43376740/163716163-ea0245a0-97dd-47a6-9852-d4f065f29873.gif)


再反馈一个问题，有时候播放着或者切集会卡死，只有声音，并且最大化那三个按钮有用，其他按钮没用，这是今天的日志

2022/04/17 21:00:59.120|Info|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
控制器加载完成
|
2022/04/17 21:03:18.988|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:03:25.868|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:03:37.690|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:04:44.352|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|Windows.UI.Xaml.LayoutCycleException: Setting the Template property on a UserControl is not supported.
Setting the Template property on a UserControl is not supported.
2022/04/17 21:04:45.288|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:05:10.638|Info|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
控制器加载完成
|
2022/04/17 21:05:21.706|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:05:24.123|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|Windows.UI.Xaml.LayoutCycleException: Setting the Template property on a UserControl is not supported.
Setting the Template property on a UserControl is not supported.
2022/04/17 21:05:25.139|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:05:38.551|Info|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
控制器加载完成
|
2022/04/17 21:05:58.486|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|Windows.UI.Xaml.LayoutCycleException: Setting the Template property on a UserControl is not supported.
Setting the Template property on a UserControl is not supported.
2022/04/17 21:05:59.657|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:08:27.172|Info|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
控制器加载完成
|
2022/04/17 21:10:23.514|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:10:34.445|Error|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2022/04/17 21:21:09.377|Info|
系统信息：10.0.22598.1 | Windows.Desktop | X64
应用信息：2.2204.4.0 | 中文(简体，中国)
--------
控制器加载完成
|

**Comment by Richasy** [comment]
不能复现播放结束窗口自动返回的问题，你可以尝试下一个更新版本（2.2204.5.0），预计在明天更新
