### ISSUE TITLE
[Bug] 视频无法播放

### ISSUE THREAD

**Issue by Sha-Gao** [Richasy/Bili.Uwp#1036]
### Bug 描述

BV1Q4411777L
可加载出关联视频、评论，无法加载视频内容

### 复现问题的步骤

```plain text
BV1Q4411777L
```

### 预期行为

。

### 截图

![image](https://user-images.githubusercontent.com/58065956/162564591-b1326652-51a5-4967-8468-57a6b6ad41ba.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [X] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Lanturewen** [comment]
我也是这样，播放失效~

**Comment by xpader** [comment]
估计是接口被限了，我也出现这种情况。
