### ISSUE TITLE
[Bug] 全屏时字幕尾部字符丢失

### ISSUE THREAD

**Issue by dv3lood** [Richasy/Bili.Uwp#1037]
### Bug 描述

在观看某些影片时，全屏或最大化的全窗口模式下字幕会出现吞字的内容。

### 复现问题的步骤

```plain text
1. 打开应用
2. 进入<a target="_blank" style="text-decoration:underline;" href="https://www.bilibili.com/video/BV1GY411E7Jr">BV1GY411E7Jr</a>
3. 移动到0：22，此时字幕应显示“先弄清楚一件事”
4. 开启全屏模式或最大化的全窗口模式，“事”字丢失；退出全屏模式后字幕恢复正常。
```

### 预期行为

正确显示字幕文字

### 截图

![屏幕截图 2022-04-09 172813](https://user-images.githubusercontent.com/6133401/162565579-38c19437-b63a-410b-8c94-cb672b04836a.png)
![屏幕截图 2022-04-09 172829](https://user-images.githubusercontent.com/6133401/162565595-a1931233-b102-4d5c-9678-0c9e9b5f1db4.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by Curious-r** [comment]
啊这，应该跟我刚提的issue是同一个问题，目前的解决方法是把弹幕样式设置为阴影或无描边。

**Comment by dv3lood** [comment]
> 啊这，应该跟我刚提的issue是同一个问题，目前的解决方法是把弹幕样式设置为阴影或无描边。

感谢回复，但是是字幕而不是弹幕。修改弹幕样式对字幕没有影响。

**Comment by Curious-r** [comment]
> > 啊这，应该跟我刚提的issue是同一个问题，目前的解决方法是把弹幕样式设置为阴影或无描边。
> 
> 感谢回复，但是是字幕而不是弹幕。修改弹幕样式对字幕没有影响。

好的，不好意思没看清楚
