### ISSUE TITLE
[Feature] 希望小窗模式增加弹幕功能

### ISSUE THREAD

**Issue by a1239750460** [Richasy/Bili.Uwp#1039]
### 问题描述

1.希望小窗模式能增加弹幕功能，还有不限制小窗模式的大小，添加置顶按钮；
2.在看视频中不小心点出去了，在点进去后又要从头开始播放

### 描述解决方案

希望添加播放记忆功能，能记到播放节点，再次进入的话能自动跳转到播放位置

**Comment by Richasy** [comment]
小窗模式不会添加弹幕，另外UWP应用对CompactOverlay模式下的窗口大小有限制，这不是应用能处理的。小窗模式就意味着置顶，其它模式窗口无法置顶。

历史记录会在你播放视频后在视频右下角提示你，点击即可跳转
