### ISSUE TITLE
[Bug] 应用不会自动清理缓存在本地的视频封面文件，占用大量磁盘空间

### ISSUE THREAD

**Issue by longtvonairplane** [Richasy/Bili.Uwp#1040]
### Bug 描述

应用缓存目录中有过多的图片（视频封面）缓存

### 复现问题的步骤

```plain text
1. 删除应用数据目录下 LocalCache\ImageExCache 中的全部数据
2. 打开应用
3. 在首页推荐向下滚动以刷新数据
4. 关闭应用
5. 再次打开应用
6. 再次打开应用数据目录下的 LocalCache\ImageExCache 目录
7. 可以看到有很多未删除的封面缩略图，问题复现
```

### 预期行为

这个文件夹中不应有过多的图片缓存

### 截图

![image](https://user-images.githubusercontent.com/79362411/162598428-57b67ff4-729e-47cc-8e89-273340d8880d.png)
![image](https://user-images.githubusercontent.com/79362411/162598430-c6e1a2d9-41c1-439b-baa3-bed1e7563e68.png)
![image](https://user-images.githubusercontent.com/79362411/162598476-9eead605-a211-4710-836f-50a5c28ca846.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

Windows 10 Enterprise LTSC 2021 (Build 19044)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
可以在应用设置里清除缓存

**Comment by longtvonairplane** [comment]
有事不在，见信尽快回复～
