### ISSUE TITLE
[Bug] 弹幕设置为描边样式时，部分弹幕存在切边

### ISSUE THREAD

**Issue by Curious-r** [Richasy/Bili.Uwp#1043]
### Bug 描述

弹幕设置为描边样式时，部分字母数字弹幕存在切边，设置为阴影和无描边样式时显示正常。
描边样式下，进入全屏模式暂停视频，再退出全屏后，部分大字号弹幕字体未正确缩放至合适大小，导致字体下半部分存在切边。在播放中退出全屏不存在此问题。

### 复现问题的步骤

```plain text
1.打开哔哩
2.搜素BV1vF411s7Ds，全屏播放，弹幕样式设置为描边
3.定位至00:00:36,观察弹幕“u3wo”的o右侧是否显示不全

缩放问题：
1.上述视频全屏播放，定位至00:00:35，暂停
2.退出全屏模式
3.观察“实际是来白嫖的”弹幕是否未按预期缩放
```

### 预期行为

弹幕正常显示

### 截图

字母弹幕截图：
弹幕样式描边：
![image](https://user-images.githubusercontent.com/19733878/162790393-03c7e2c4-b6fa-483b-86dd-ef20ba6cb6be.png)
样式设置为阴影：
![image](https://user-images.githubusercontent.com/19733878/162790276-d61a08d6-a16a-451d-ba18-c0b9cb55eb90.png)

描边样式退出全屏，大字号弹幕未正常缩放：
![image](https://user-images.githubusercontent.com/19733878/162792898-2100008e-917f-4472-8584-932b5bfc980a.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

dev 22593.1

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-04-12.log](https://github.com/Richasy/Bili.Uwp/files/8466295/applog.2022-04-12.log)

**Comment by Richasy** [comment]
目前暂不好解决该问题，描边弹幕实际上是创建了一个字符形状，是一个图形。在视频显示区域发生变化时，不能重新渲染，所以会产生切边。
如果以后有更好的解决思路，会再进行尝试，目前先搁置该问题

**Comment by Curious-r** [comment]
> 目前暂不好解决该问题，描边弹幕实际上是创建了一个字符形状，是一个图形。在视频显示区域发生变化时，不能重新渲染，所以会产生切边。 如果以后有更好的解决思路，会再进行尝试，目前先搁置该问题

收到🫡
