### ISSUE TITLE
[Bug] 应该算吧 应用预启动问题

### ISSUE THREAD

**Issue by blibilijojo** [Richasy/Bili.Uwp#1045]
### Bug 描述

我开了预启动的时候开的时候加载时间长，甚至可能一直加载，需要重启好几次
但是我今天发现我如果关了反而进入速度加快，这是我电脑的问题还是本来就有的bug（电脑很老，配置贼低）

### 复现问题的步骤

```plain text
1.打开应用
2.打开预启动
3.关闭应用
4.打开应用（看一下启动速度）
5.关闭预启动
6.关闭应用
7.打开应用（看一下启动速度）
```

### 预期行为

不知道

### 截图

![image](https://user-images.githubusercontent.com/102420734/162867040-a532ccf2-8fbd-4fbc-ba39-6047515e4684.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
启动速度是个玄学，资源调配是由系统来决定的。如果系统认为你当前的计算资源紧张，即便设置了预启动也没用。所以该问题不会从应用侧来修复
