### ISSUE TITLE
[Feature] 为啥播放控件的亚克力效果没了？

### ISSUE THREAD

**Issue by BeLozmen** [Richasy/Bili.Uwp#1049]
### 问题描述

为啥播放控件的亚克力效果没了？

现在变成半透明了，和视频内容混合在一起不容易看清，不知是不是bug？一起的亚克力效果多美观啊

如果出于性能考虑禁用了亚克力，是否可以考虑做成不透明的？现在的半透明真的看起来有些吃力。

### 描述解决方案

控件恢复亚克力效果

### 备选方案

控件做成不透明效果

**Comment by BeLozmen** [comment]
刚刚看了下更新日志，是为了不遮挡字幕。我不是很在乎这个，希望能自己手动设置控制器的效果，实在很喜欢原来的亚克力效果。

**Comment by blibilijojo** [comment]
> 刚刚看了下更新日志，是为了不遮挡字幕。我不是很在乎这个，希望能自己手动设置控制器的效果，实在很喜欢原来的亚克力效果。

额，你是触屏用户吧，原来的的设计对于鼠标来说简直是地狱设计

**Comment by blibilijojo** [comment]
> 刚刚看了下更新日志，是为了不遮挡字幕。我不是很在乎这个，希望能自己手动设置控制器的效果，实在很喜欢原来的亚克力效果。

鼠标如果设置是手动显隐会很麻烦容易误触，自动的话得等很久才会自动隐藏，所以很容易遮挡字幕
