### ISSUE TITLE
[Bug]直播画面消失

### ISSUE THREAD

**Issue by gilliantguo** [Richasy/Bili.Uwp#105]
## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入直播
3. 点击已关注直播浮窗
4. 只有声音没有画面，弹幕随缘有，切换视频源也不行

## 预期的行为

视频画面

## 截图
![image](https://user-images.githubusercontent.com/32230893/133915669-81755211-e2c6-43ae-9cc5-7165b70b762b.png)
![image](https://user-images.githubusercontent.com/32230893/133915709-6887c06b-7adf-4f25-95f6-479eae4c8cc6.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本2.2109.1801.0}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录

说起来这个日志一大半都是网络问题，代理忘切换了
[applog.2021-09-19.log](https://github.com/Richasy/Bili.Uwp/files/7190984/applog.2021-09-19.log)

**Comment by Richasy** [comment]
关闭代理后，直播是否可以正常播放？
是特定于某个直播间出现，还是所有直播间都是如此？

**Comment by haoey** [comment]
> 关闭代理后，直播是否可以正常播放？
> 是特定于某个直播间出现，还是所有直播间都是如此？
这个主播的直播间就不行，其他似乎都没问题

![image](https://user-images.githubusercontent.com/70797176/133917792-f6f14db2-6e5a-47b4-a7b2-b19805e4330d.png)

**Comment by gilliantguo** [comment]
> > 关闭代理后，直播是否可以正常播放？
> > 是特定于某个直播间出现，还是所有直播间都是如此？
> > 这个主播的直播间就不行，其他似乎都没问题
> 
> ![image](https://user-images.githubusercontent.com/70797176/133917792-f6f14db2-6e5a-47b4-a7b2-b19805e4330d.png)

有些直播间的确可以看，但是不能看的也不止一个😂
![image](https://user-images.githubusercontent.com/32230893/133918767-95601610-65a6-43c5-8247-69552d51fe18.png)

**Comment by gilliantguo** [comment]
是关闭代理看的

**Comment by Richasy** [comment]
可以搜索并尝试安装一下HEVC的解码器

**Comment by wmdhs12138** [comment]
> 可以搜索并尝试安装一下HEVC的解码器

一些直播间能看，一些不能看，win10安装 设备制造商的hevc扩展 后这个bug还在

**Comment by Richasy** [comment]
从报错日志来看，这是个显卡问题，应用难以解决，请尝试给显卡降频或者更新显卡驱动

**Comment by Richasy** [comment]
暂时关闭这个问题，有需要可以再打开
