### ISSUE TITLE
[Bug] 输入法被推荐列表遮挡

### ISSUE THREAD

**Issue by wqcblog** [Richasy/Bili.Uwp#1052]
### Bug 描述

我使用的是搜狗输入法，会出现推荐列表被遮挡的情况出现

### 复现问题的步骤

```plain text
1.打开应用
2.点击搜索
3.输入关键字
4.推荐列表会遮挡输入法候选框
```

### 预期行为

输入法正常显示，不被遮挡

### 截图

![image](https://user-images.githubusercontent.com/82157125/163323309-36aca25e-ba15-478b-84c8-1e3f1f73bb14.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
所有UWP应用都有这个问题，很难界定到底算系统来修复还是输入法来修复。但不管怎么说，应用都无法对此进行修复，我只能说UWP还是跟默认输入法更匹配
