### ISSUE TITLE
关于流畅性的反馈

### ISSUE THREAD

**Issue by XiaoNNNNNNNN** [Richasy/Bili.Uwp#1056]
### Bug 描述

在很多界面中滑动时，都会出现明显的掉针。不知道是哪里没有优化好

### 复现问题的步骤

```plain text
容易掉针
```

### 预期行为

只要能流畅的浏览视频就可以了

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 备注

希望哔哩做的越来越好~

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
刚修掉，下个版本会发，请耐心等待
