### ISSUE TITLE
[Bug] 在一些移动设备上CPU调度似乎并不正常

### ISSUE THREAD

**Issue by MaxDYF** [Richasy/Bili.Uwp#1059]
### Bug 描述

使用设别Surface Pro3 i5 8G RAM，操作系统为Windows11 Pro 22000.556.

在以HEVC编码观看4k视频时出现异常卡死掉帧现象，通过XTU查看CPU锁死在4W左右功耗，GPU负载不高，此时并没有触发系统功耗墙。

经测试网页端4k播放与fpu测试都不存在这种异常现象，怀疑是bili解码器调度的问题。

AVC编码的4k/1080p视频暂时没有此现象。

### 复现问题的步骤

```plain text
打开应用，进入任意HEVC视频，有概率出现解码卡死现象
```

### 预期行为

解决调度不正常问题

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
应用使用系统提供的MediaPlayer播放视频，所以这种功耗及调度问题不是哔哩能解决的。为保证效果，可以使用较低清晰度观看
