### ISSUE TITLE
[Feature] 能否在tap栏增加每个视频（直播）的快捷静音开关

### ISSUE THREAD

**Issue by forchannot** [Richasy/Bili.Uwp#1062]
### 问题描述

能否像浏览器那样，对每个视频或者直播或者网页增加单独的静音开关，如图
![image](https://user-images.githubusercontent.com/100580891/163713312-f15d49b1-0ba0-42a5-8bb7-7809711f9bbc.png)

### 描述解决方案

在标签栏增加音量开关

### 备选方案

或者在标签栏可以通过右键调用功能列表包含静音等功能，如浏览器这种
![image](https://user-images.githubusercontent.com/100580891/163713350-6a8ec4a2-95b5-448b-bda5-6aa7cbb243df.png)

**Comment by Richasy** [comment]
网页行为不可直接套搬到应用上，另外提feature需要描述原因
