### ISSUE TITLE
[Bug]严重bug,视频不能播放

### ISSUE THREAD

**Issue by Lanturewen** [Richasy/Bili.Uwp#1071]
### Bug 描述

视频基本都不能播放,x86和x64的版本都试了,老版本也测试了.其他的都有(比如首页动态等),就是点进视频不能播放时间进度条一直显示是0:00:0,请问是接口受限制了吗?另外另一个同学也是这样,使用的是校园网,clash的uwp网络设置好了,关闭后也是这样.

### 复现问题的步骤

```plain text
点击视频,不能播放,时间进度是0:00:0.
```

### 预期行为

能播放视频

### 截图

![image](https://user-images.githubusercontent.com/18157343/163753085-323c2564-11a0-437c-a063-fa06318055cf.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [X] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2022-04-18.log](https://github.com/Richasy/Bili.Uwp/files/8503393/applog.2022-04-18.log)

### 备注

1.另一个同学也是这样,使用的是校园网,clash的uwp网络设置好了,关闭后也是这样.排除科学上网的原因
2.测试了老版本以及最新的04-18的x64和x86版本都不行.

**Comment by Richasy** [comment]
这可能是单纯的网络问题，首先，接口没被限制，在正常的网络条件下也可以播放。你可以试试其它的哔哩哔哩客户端，或者网页。不排除是校园网对相关的端口进行了限制
