### ISSUE TITLE
無法正確安裝

### ISSUE THREAD

**Issue by jj30462281** [Richasy/Bili.Uwp#1074]
### 问题描述

![image](https://user-images.githubusercontent.com/61258096/163832833-ee9878b4-ba06-4d21-8fe2-a85a1b829b64.png)

### 描述解决方案

查了一下錯誤代碼 依舊無法解決

**Comment by Richasy** [comment]
请提供你的系统版本，另外如果脚本安装不行，可以尝试安装说明中的手动安装步骤

**Comment by Richasy** [comment]
长时间未回复，暂时关闭这个问题，后续有需要可以再打开
