### ISSUE TITLE
[Feature][视频进度控制不精确] 对于短视频，左右方向键调进度会跳过很长一段时间，导致进度控制不够精确

### ISSUE THREAD

**Issue by Resunny** [Richasy/Bili.Uwp#1076]
### 问题描述

[视频进度控制不精确] 对于短视频，左右方向键调进度会跳过很长一段时间，导致进度控制不够精确。

哔哩哔哩网页似乎是根据视频的长短来确定每次跳跃的时间多少。长视频按一次左右方向键跳过的时间多，短视频跳的时间少。

### 描述解决方案

根据视频的长短来确定每次跳跃的时间多少

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
关于这个……你可以通过光标在视频空白区域拖动（按着鼠标左键向左向右滑动）来进行跳转。左右键是固定的时长，可以在设置->播放器设置->单次快进/快退时长 里调整
