### ISSUE TITLE
[Feature][收藏列表全部播放] 每个收藏中的内容希望一键全部播放

### ISSUE THREAD

**Issue by Resunny** [Richasy/Bili.Uwp#1077]
### 问题描述

[收藏列表全部播放] 每个收藏中的内容希望一键全部播放。

这个也是官方哔哩哔哩本身具备的功能，很方便。

### 描述解决方案

每个收藏中的内容希望一键全部播放。

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
与 #534 合并处理
