### ISSUE TITLE
关于简介区过大的建议

### ISSUE THREAD

**Issue by qcknhaa** [Richasy/Bili.Uwp#1080]
### 问题描述

目前哔哩的功能已经较为完善，但仍然存在着一些问题和一些能够改进的地方。
打开视频，**简介区就占了屏幕的三分之一**，使视频本体太小。这种布局可能更适用于16：10以及4：3的屏幕，**而对16：9 ， 21：9乃至更高长宽比的屏幕不太友好**，希望作者能够改进一下，或者可以在设置里添加相关选项来调节简介区大小。

### 预期内容

希望作者能够改进一下，使之更适应16：9或更高长宽比的屏幕。

### 人人为我，我为人人

是的，我希望其他人看到我写的文档

**Comment by Richasy** [comment]
简介区域的大小目前没有修改的必要，默认视图下，视频播放只是预览，如果你停留在这个模式，那么按照预期你是希望查看简介或者浏览右侧信息流的。如果想要看完整视频，可以进入全窗口模式，你也可以在设置里对进入播放页面后的行为进行调整

**Comment by C-Rosemary** [comment]
> 简介区域的大小目前没有修改的必要，默认视图下，视频播放只是预览，如果你停留在这个模式，那么按照预期你是希望查看简介或者浏览右侧信息流的。 如果想要看完整视频，可以进入全窗口模式，你也可以在设置里对进入播放页面后的行为进行调整
@Richasy 那能不能将简介区移动到右侧信息流呢？我平时使用的时候基本不会使用全屏，但是默认视图的播放界面太小了也不太合适，看起来太痛苦了
