### ISSUE TITLE
关于简介区的建议

### ISSUE THREAD

**Issue by qcknhaa** [Richasy/Bili.Uwp#1081]
### 问题描述

目前哔哩的功能已经较为完善，但仍然存在着一些问题和一些能够改进的地方。
打开视频，**简介区就占了屏幕的三分之一**，使视频本体太小。这种布局可能更适用于16：10以及4：3的屏幕，**而对16：9 ， 21：9乃至更高长宽比的屏幕不太友好**，希望作者能够改进一下，或者可以在设置里添加相关选项来调节简介区大小。

### 描述解决方案

希望作者能够改进一下，使之更适应16：9或更高长宽比的屏幕。

### 人人为我，我为人人

是的，我希望我的代码出现在哔哩中

**Comment by Richasy** [comment]
在你上一个issue中已经回复，这里不再赘述
