### ISSUE TITLE
[Bug] 偶现搜索栏输入卡顿

### ISSUE THREAD

**Issue by St-Cai** [Richasy/Bili.Uwp#1087]
### Bug 描述

偶现搜索栏输入卡顿，暂不知道触发条件，重启应用可以解决

### 复现问题的步骤

```plain text
暂时无法找到必定复现的方法
```

### 预期行为

修复bug

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

**Comment by Richasy** [comment]
这个卡顿可能是渲染建议列表时造成的。也就是当你按下键盘时，此时搜索建议正好弹出，可能会出现一些像卡顿的情况。虽然体验不算好，但目前可能没有比较好的解决方法
