### ISSUE TITLE
[Feature] 利用B站官方的图片格式化后缀降低图片画质，提高页面加载速度

### ISSUE THREAD

**Issue by xyl23333** [Richasy/Bili.Uwp#1088]
### 问题描述

此哔哩客户端在首页加载视频封面的速度不理想，加载一页的速度非常快，但是加载32个封面需要2-3秒左右的时间。同样网速下，移动端只需要1秒不到的时间。这些根据B站官方的图片格式化后缀降低分辨率以及并行加载的策略，可能可以进一步提升封面加载速度。

此外，对于大多数用户而言，Windows的显示缩放比例往往只有100%，导致显示用户头像的面积非常小，加载全分辨率头像一般是一种浪费，所以头像的横向分辨率一般设置为50-75就可以了

### 描述解决方案

根据 [图片格式化](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/other/picture.md) 文章：

原始图片

http://i1.hdslb.com/bfs/archive/e5fff1472bad1c0c6bcb3004205f9be23b58ffc0.jpg

![](http://i1.hdslb.com/bfs/archive/e5fff1472bad1c0c6bcb3004205f9be23b58ffc0.jpg)

高度限制为100

http://i1.hdslb.com/bfs/archive/e5fff1472bad1c0c6bcb3004205f9be23b58ffc0.jpg@100h

![](http://i1.hdslb.com/bfs/archive/e5fff1472bad1c0c6bcb3004205f9be23b58ffc0.jpg@100h)

此方法可能适用于会员头衔等需要png背景透明的场景，以及头像、封面这个固定小分辨率的场景

### 备选方案

转换格式为webp

http://i1.hdslb.com/bfs/archive/e5fff1472bad1c0c6bcb3004205f9be23b58ffc0.jpg@.webp

![](http://i1.hdslb.com/bfs/archive/e5fff1472bad1c0c6bcb3004205f9be23b58ffc0.jpg@.webp)

转换为webp图片质量为1%

http://i1.hdslb.com/bfs/archive/e5fff1472bad1c0c6bcb3004205f9be23b58ffc0.jpg@1q.webp

![](http://i1.hdslb.com/bfs/archive/e5fff1472bad1c0c6bcb3004205f9be23b58ffc0.jpg@1q.webp)

这个可能适用于头像等场景，更适用于动态图片，对于分辨率本来就很小、又不需要透明背景的场景，使用限高意义可能不如这个大

### 附加信息

但是经过我的测试，图片限高和降画质好像是鱼和熊掌不可兼得的。

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
你说的这些哔哩正在做：[code](https://github.com/Richasy/Bili.Uwp/blob/c29dd9ab8ff05ed86536929702b7b1f930567923/src/ViewModels/ViewModels.Uwp/Common/VideoViewModel/VideoViewModel.cs#L392)

不光使用宽高后缀来限制图片大小，同时在应用内部也通过限制分辨率来降低内存占用。

但网络环境及UWP自身的线程策略是外部制约，目前暂时无法解决
