### ISSUE TITLE
[Bug] 用密码登录无法点击获取验证码的按钮和输入框

### ISSUE THREAD

**Issue by jipa233** [Richasy/Bili.Uwp#1092]
### Bug 描述

用密码登录无法点击获取验证码的按钮和输入框

### 复现问题的步骤

```plain text
用密码登录无法点击获取验证码的按钮和输入框
```

### 预期行为

可以点击获取验证码的按钮和输入框

### 截图

视频链接: https://pan.baidu.com/s/1XmRQzzehBi2wVLHRzxbPFw
提取码: w36r

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
这应该是特定于Win10的bug，Win11应该是正常的，请确定你用的是Windows11（我看你的报告里写的系统是Win11）？Win10的话请使用扫码登录

**Comment by jipa233** [comment]
> 这应该是特定于Win10的bug，Win11应该是正常的，请确定你用的是Windows11（我看你的报告里写的系统是Win11）？Win10的话请使用扫码登录

抱歉，选错了，是Win10 20H2，顺便问一下，请问打算修复这个bug吗

**Comment by Richasy** [comment]
> > 这应该是特定于Win10的bug，Win11应该是正常的，请确定你用的是Windows11（我看你的报告里写的系统是Win11）？Win10的话请使用扫码登录
> 
> 抱歉，选错了，是Win10 21H2，顺便问一下，请问打算修复这个bug吗

在有其它备选方式的情况下，暂时不打算修了，以后会视情况逐步放弃对win10的支持
