### ISSUE TITLE
[Feature] 增加UID快速直达功能

### ISSUE THREAD

**Issue by xyl23333** [Richasy/Bili.Uwp#1094]
### 问题描述

此客户端支持输入av号来直接呼出具体视频，好评（以av7为例）
![客户端直接呼出av号](https://user-images.githubusercontent.com/46397979/164686608-1f8a9e99-e117-4519-9268-9301b1117238.png)

但是，根据UID来快速转到用户也是一个很常见的操作，比如说时常光顾站长的视频，或者用站长的号来方便调试。此功能也可以加上。

![网页端直达uid功能](https://user-images.githubusercontent.com/46397979/164685293-38d027c8-39a4-46ff-82aa-fe67ba51a09f.png)

### 描述解决方案

增加对uid+数字类关键词的识别。既然有对av、bv的识别，那么uid貌似......也可以？

### 备选方案

搜索时弹出B站搜索网页。比如`https://search.bilibili.com/all?keyword=uid2`

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
输入uid跳转到用户的核心诉求是什么？

根据你的描述，我想可能是你想通过这种方式来快速定位一个用户，并打开他/她的视频列表。

如果是这样，那么搜索uid并跳转依然是一个不好的体验，它并不能解决实际问题，反而还要求你记住某个用户的Id，站长的Id固然好记，但是其它UP主的恐怕不行。

我倾向于更进一步地解决这个问题，你可以在正常搜索后，点开用户面板，点击 `固定UP`

![image](https://user-images.githubusercontent.com/27713596/164859496-9251f7e2-75b6-4320-9660-951b7b252ecb.png)

这样该用户会在你的导航栏顶部出现，下次你可以直接点击并打开用户面板，我觉得这比直接搜uid要更方便一些。

#1098 这个PR会在五月更新，支持固定更多的内容，以帮助用户实现短期高效追踪的能力

**Comment by xyl23333** [comment]
> 输入uid跳转到用户的核心诉求是什么？
> 
> 根据你的描述，我想可能是你想通过这种方式来快速定位一个用户，并打开他/她的视频列表。
> 
> 如果是这样，那么搜索uid并跳转依然是一个不好的体验，它并不能解决实际问题，反而还要求你记住某个用户的Id，站长的Id固然好记，但是其它UP主的恐怕不行。
> 
> 我倾向于更进一步地解决这个问题，你可以在正常搜索后，点开用户面板，点击 `固定UP`
> 
> ![image](https://user-images.githubusercontent.com/27713596/164859496-9251f7e2-75b6-4320-9660-951b7b252ecb.png)
> 
> 这样该用户会在你的导航栏顶部出现，下次你可以直接点击并打开用户面板，我觉得这比直接搜uid要更方便一些。
> 
> _我注意到你的截图中已经固定了UP主，那么是这种方式不能满足你的需求吗？_
> 
> #1098 这个PR会在五月更新，支持固定更多的内容，以帮助用户实现短期高效追踪

啊这，方便性上确实不如固定up。
不过好像还有一个很常见的作用，一般挂人的时候喜欢挂uid而不是名称，因为他们总是会更名，如果经常家访也可以挂起来。但是如果想要直接在客户端弹出他们的主页，而不是到网页端搜索再复制id，那么这个估计也会有用

**Comment by Richasy** [comment]
> 啊这，方便性上确实不如固定up。 不过好像还有一个很常见的作用，一般挂人的时候喜欢挂uid而不是名称，因为他们总是会更名，如果经常家访也可以挂起来。但是如果想要直接在客户端弹出他们的主页，而不是到网页端搜索再复制id，那么这个估计也会有用

咳咳，这个理由够硬。不过你知道的，如果是这个原因，那么于情于理，我都没有理由在应用中为这种行为提供便捷操作
