### ISSUE TITLE
[Bug] 不能使用鼠标滚轮浏览

### ISSUE THREAD

**Issue by smdsbz** [Richasy/Bili.Uwp#110]
## Bug 描述

rt 所有页面不能使用鼠标滚轮，只能用拖滚动条

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 尝试使用鼠标滚轮

## 预期的行为

滚不动

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：2.2109.1801.0

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 10 var.21H1 (19043)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

~~Visual Studio 版本:~~

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录

都是播放成功

**Comment by monsterxcn** [comment]
不，评论区还是可以滚轮滚的（

还有预期的行为应该是滚的动

**Comment by Richasy** [comment]
问题重复，且该问题已被修复，将随着下一次更新发布
