### ISSUE TITLE
[Bug] 播放任何视频均出现持续性花屏频闪、绿屏

### ISSUE THREAD

**Issue by voidoath** [Richasy/Bili.Uwp#1101]
### Bug 描述

播放任何视频，无论选择何种清晰度，均在视频下方区域出现绿屏，且视频画面错乱频闪。设备信息写在备注里。

### 复现问题的步骤

```plain text
打开应用播放视频
```

### 预期行为

视频正常播放

### 截图

![图片](https://user-images.githubusercontent.com/53803262/164883345-35056999-da67-4fe6-b1ce-3555ad27c15c.png)
![图片](https://user-images.githubusercontent.com/53803262/164883370-acfec724-7f2c-40b7-84de-fad90090499c.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [x] 其它 (需注明)

### 其它系统版本

windows 11 dev build 22598

### 运行设备

桌面/台式机

### 备注

cpu：AMD R3 3100
GPU：RX560XT （驱动版本22.3.1）
哔哩版本为v2.2204.5.0

**Comment by Richasy** [comment]
啊这……出现这种情况只能说显卡有问题了。同样的，你可以试试其它的哔哩哔哩客户端，或者使用 Win11 自带的新版媒体播放器放下视频看看

**Comment by voidoath** [comment]
> 啊这……出现这种情况只能说显卡有问题了。同样的，你可以试试其它的哔哩哔哩客户端，或者使用 Win11 自带的新版媒体播放器放下视频看看

浏览器播放视频正常，win11新版媒体播放器播放正常，微软商店 哔哩哔哩官方uwp版应用也正常，应该不是显卡问题吧[doge]

**Comment by Richasy** [comment]
> 浏览器播放视频正常，win11新版媒体播放器播放正常，微软商店 哔哩哔哩官方uwp版应用也正常，应该不是显卡问题吧[doge]

这么神奇？不过老实说这问题我解决不了，发布至今算上你只收到了两例类似报告（另外一个通过升级显卡驱动整好了）。你可以尝试在设置页面切换解码方式。如果实在不行，那只能改换其它的客户端了😂

**Comment by voidoath** [comment]
> > 浏览器播放视频正常，win11新版媒体播放器播放正常，微软商店 哔哩哔哩官方uwp版应用也正常，应该不是显卡问题吧[doge]
> 
> 这么神奇？不过老实说这问题我解决不了，发布至今算上你只收到了两例类似报告（另外一个通过升级显卡驱动整好了）。你可以尝试在设置页面切换解码方式。如果实在不行，那只能改换其它的客户端了😂

这么玄学的吗orz，我也先更换一下驱动版本试试吧

**Comment by mirrordg** [comment]
你看看你编解码器用的哪个，如果是默认avc应该没啥问题，如果是av1，看看是否在微软商店安装了av1的编解码扩展，我也有这个问题，不过我是网页端遇到的，后来我改成默认为avc就再也没遇到过了

**Comment by StudentTang** [comment]
我也有，不过是全屏之后，过段时间就会电脑下半四分之一花屏，旧版（2021）和新的都有，所以我一直用全窗口模式，笔记本是1660+10750，系统现在win10 H1（其实旧版1803也用一直没升级）不知道是不是上面哪个av1编码

**Comment by StudentTang** [comment]
我也有，不过是全屏之后，过段时间就会电脑下半四分之一花屏，旧版（2021）和新的都有，所以我一直用全窗口模式，笔记本是1660+10750，系统现在win10 H1（其实旧版1803也用一直没升级）不知道是不是上面哪个av1编码
