### ISSUE TITLE
[Feature] Xbox端视频界面有时过于小

### ISSUE THREAD

**Issue by Pneuma970** [Richasy/Bili.Uwp#1103]
### 问题描述

如果视频tag，简介太多，小窗播放会特别小，如图.
![IMG_1004](https://user-images.githubusercontent.com/103899931/164884109-9661ebf3-3d59-4d71-ab45-f2dbb9315127.JPG)

### 描述解决方案

设置一个固定的小窗播放大小，其余部分变为滚动页面。

### 备选方案

删除xbox版的tag和简介

**Comment by Richasy** [comment]
对于XBOX，也许以后会适配，但就目前来说属于能跑就行。你可以在应用设置里把默认的播放器显示模式调整为全屏，下次播放时就可以直接打开。
但就目前来说，哔哩还是桌面优先，我没有更多精力去适配XBOX了
