### ISSUE TITLE
漫游无论用哪个服务器都是PGC内容请求失败

### ISSUE THREAD

**Issue by forchannot** [Richasy/Bili.Uwp#1117]
### Bug 描述

把漫游提供的公共服务器都试了下，都会提示PGC内容请求失败，能搜索但看不了，这些服务器在手机上是能正常用的，本身没问题
![image](https://user-images.githubusercontent.com/100580891/164953498-a9230b8e-374b-42ec-9f6a-9e5f2d48c833.png)

### 复现问题的步骤

```plain text
如题
```

### 预期行为

能正常使用

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

win11 22H2 22598

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
我们用的API不一样，目前公开的大多数服务支持的是旧的Web API，如果想寻找哔哩可用的服务，要么自建，要么右转在 [BiliLite](https://github.com/xiaoyaocz/biliuwp-lite/blob/master/src/BiliLite.UWP/Api/ApiHelper.cs#L26) 中找寻

**Comment by YangSuGuo** [comment]
不在中。。。
