### ISSUE TITLE
[Bug] 最新PreRelease版本中弹幕云屏蔽功能消失

### ISSUE THREAD

**Issue by EvatsugDnalloR** [Richasy/Bili.Uwp#1123]
### Bug 描述

在最新的2.2205.0.0_x64版本中替换了新的弹幕引擎，但在选项里云屏蔽配置没有了，并且可以确定云屏蔽没有实现，希望能把云屏蔽加回来（最好顺便适配一下硬核会员弹幕...）

### 复现问题的步骤

```plain text
在最新2.2205.0.0_x64版本中随便打开一个弹幕较多的视频并播放，可以在弹幕设置里看到没有云屏蔽的选项，并且与网页端进行弹幕对比可以确定云屏蔽没有实现。
```

### 预期行为

云屏蔽不工作

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

**Comment by Richasy** [comment]
之前的虽然有云屏蔽按钮，但是也并没有实际实现屏蔽功能。事实上，现在的API取自ios客户端，而最新客户端已经没有云屏蔽了（好像变成弹幕优选了？），硬核会员的API还拿不到，短时间内屏蔽功能难以实现，可能在以后会支持本地正则屏蔽吧
