### ISSUE TITLE
[Bug] 主页固定Up主消失

### ISSUE THREAD

**Issue by Maxdontron** [Richasy/Bili.Uwp#1124]
### Bug 描述

刚升级完五月更新，发现主页以前固定的Up主没了

### 复现问题的步骤

```plain text
1 打开应用
2 问题出现于左侧Tab栏
```

### 预期行为

更新完能正常显示以前版本已固定的Up主

### 截图

![固定，旧](https://user-images.githubusercontent.com/91769391/164975724-940ef1a6-bb39-4712-9f98-6ca32b0f63ea.png)
![固定，新](https://user-images.githubusercontent.com/91769391/164975727-e9a7a4ef-654d-4626-920e-08674ad4ad9c.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-04-24.log](https://github.com/Richasy/Bili.Uwp/files/8549619/applog.2022-04-24.log)

**Comment by Richasy** [comment]
固定方式更新了，需要重新固定一下

**Comment by Maxdontron** [comment]
好👌
