### ISSUE TITLE
[Bug] 弹幕样式无法显示

### ISSUE THREAD

**Issue by Maxdontron** [Richasy/Bili.Uwp#1125]
### Bug 描述

无法设置弹幕显示样式，例如阴影那些
（我知道删了云屏蔽配置，但是不是删多了🤔

### 复现问题的步骤

```plain text
1 打开应用
2 打开任意一个视频
3 显示弹幕控制器
4 打开弹幕设置
5 问题出现
```

### 预期行为

能显示弹幕样式，并能设置阴影、白边、无描边

### 截图

![弹幕，新](https://user-images.githubusercontent.com/91769391/164975974-109883b3-65f3-4a8e-9214-c4a16fc3d149.png)
![弹幕，旧](https://user-images.githubusercontent.com/91769391/164975980-1799672d-c749-4247-af45-1e6f34a39277.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-04-24.log](https://github.com/Richasy/Bili.Uwp/files/8549640/applog.2022-04-24.log)

**Comment by Richasy** [comment]
并不是删多了，事实上之前做弹幕样式是为了在不同的环境下可以切换效果以保证弹幕可视。但是升级引擎后，自带的描边已经可以满足这个需求。再者，该弹幕引擎目前也不支持样式设置，我也不认为还有必要再加

**Comment by Maxdontron** [comment]
> 并不是删多了，事实上之前做弹幕样式是为了在不同的环境下可以切换效果以保证弹幕可视。但是升级引擎后，自带的描边已经可以满足这个需求。再者，该弹幕引擎目前也不支持样式设置，我也不认为还有必要再加

那真是太可惜了  对于我这个喜欢无描边的😞
