### ISSUE TITLE
[Bug] 综合动态无法显示评论区

### ISSUE THREAD

**Issue by Maxdontron** [Richasy/Bili.Uwp#1126]
### Bug 描述

反正就是综合动态无法显示评论区，已确定不是网络原因，断网重连过也不行
（这次总不是我的问题了....吧？

### 复现问题的步骤

```plain text
1 打开应用
2 打开左侧Tab栏的"动态"
3 将页面切换至"综合"
4 点击一条综合动态的评论按钮
5 稍等一会问题出现
```

### 预期行为

综合动态正常显示评论区里的评论

### 截图

![屏幕截图 2022-04-24 203439](https://user-images.githubusercontent.com/91769391/164977262-836c5bff-fb60-4aea-8982-45e85b806d7f.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 日志记录

[applog.2022-04-24.log](https://github.com/Richasy/Bili.Uwp/files/8549705/applog.2022-04-24.log)

**Comment by Richasy** [comment]
#1119 已修复，下个版本更新
