### ISSUE TITLE
[Bug] 使用，发现了一些问题，并不像看上去那样好用、方便

### ISSUE THREAD

**Issue by jkqxl** [Richasy/Bili.Uwp#1138]
### Bug 描述

试用了一下，说一下发现的问题

1.最大的问题是，使用过程中不流畅，有卡顿，最明显的是打开关注的人界面、收藏界面等鼠标左键、右键点击操作有延迟
2.不能修改左侧项目，以进行特点的显示，有很多对于特定的人一般都用不上，或许可以增加收缩列表，另外添加收藏夹、关注的人等
3.在推荐等界面，多个视频显示画面偏小，或许可以更大一点，减小导航栏的宽度

4.关注的人、收藏的视频，无法调整位置，非常重要
5.关注的人、收藏的视频，点击打开经常误操作取消关注，我非常确定没有点击关注的按钮。而且通常打开收藏夹是为了查找信息，仅显示一行，效率极其低下，关注的人也有类似的情况

### 复现问题的步骤

```plain text
1.打开应用
2.在推荐界面下滑（卡顿）
3.右上角点击人物头像
4.点击关注数
5.点击Up主（出现误取消）
6.下滑视频（卡顿）
7.右上角点击人物头像
8.点击我的收藏
9.点击各个收藏行（卡顿）
10.打开我创建的收藏夹
11.查看详情
12.下滑视频（卡顿）
```

### 预期行为

在使用软件过程中能够比较丝滑，不会卡顿

能够随意的管理 关注的人、收藏的视频 ，可以批量调整他们的位置

导航界面，视频封面可以观看大图，下滑不卡顿

导航界面项目可以调整，增加经常使用的，特别关注的Up主界面等

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 其它来源

侧加载版

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

无

### 运行设备

桌面/平板或笔记本

### 日志记录

无

### 备注

相比同类UWP应用，唯一的优点可能就是，不会卡死、闪退，界面美观，但实际使用可能没有想象中那么好

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
感谢你的建议，但为了处理方便，还请将需要的功能拆分成独立的issue，即一个功能对应一个issue
