### ISSUE TITLE
[Bug] 直播弹幕出现出现串扰

### ISSUE THREAD

**Issue by Sha-Gao** [Richasy/Bili.Uwp#1141]
### Bug 描述

看完一个视频后切到直播间，出现了很多不相关的弹幕，切到同时间浏览器视角就没有
看了一会后发现是自己看的最后一个视频中出现的弹幕
（具体证据看截图）

### 复现问题的步骤

```plain text
被干扰的直播间https://live.bilibili.com/23625684
干扰视频来源BV1EB4y1m7Fc
```

### 预期行为

尽快修复吧，还挺吓人的😂

### 截图

![浏览器直播界面](https://user-images.githubusercontent.com/58065956/165716661-5205a8e6-29cb-4622-82b5-f01dab49d8fd.jpg)
![哔哩直播界面](https://user-images.githubusercontent.com/58065956/165716736-2192ab5d-0423-4f37-831a-c3518b14b2fa.jpg)
![最后观看的视频](https://user-images.githubusercontent.com/58065956/165716801-d2a9a0fb-6380-4946-bc3f-2dab897ba37b.jpg)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [X] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

2022/04/28 16:25:37.825|Info|
系统信息：10.0.18363.1556 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文（简体，中国）
--------
控制器加载完成
|

### 人人为我，我为人人

我更擅长发现问题

**Comment by Sha-Gao** [comment]
第一张截图是同时间浏览器显示界面
第二张截图是哔哩显示的直播间
第三张截图是干扰直播间的视频

**Comment by Richasy** [comment]
该问题在新版（六月更新）中应该被修复了
