### ISSUE TITLE
[Bug] 能切60帧和4K但是很明显就不是60帧和4K呀。。。

### ISSUE THREAD

**Issue by Think2twice** [Richasy/Bili.Uwp#1143]
### Bug 描述

切60帧和4K但是很明显就不是60帧和4K呀。。。
难道没有人反馈这个问题吗？都用的很正常？？？

### 复现问题的步骤

```plain text
60帧和4K是假的呀，如果没有的话，建议把这两个选项切换成会员才能使用吧。。。
```

### 预期行为

切换1080p60帧，肉眼可见的没有60帧。。。

### 截图

无

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

无

### 备注

无

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
播放源是从哔哩哔哩获取的，如果播放卡顿，可能是显卡设置原因（参照常见问题），如果是清晰度不够，那大概率是b站码率压的太狠了
