### ISSUE TITLE
[Bug] arm版打开收藏夹闪退

### ISSUE THREAD

**Issue by kittynnin** [Richasy/Bili.Uwp#1147]
### Bug 描述

surface pro x 打开收藏夹-显示全部会闪退

### 复现问题的步骤

```plain text
打开应用-我的收藏-默认收藏夹-查看全部-闪退
```

### 预期行为

查看全部收藏内容

### 截图

![屏幕截图 2022-04-29 131046](https://user-images.githubusercontent.com/39491909/165888364-f34265f4-31a5-4022-bfad-d817a418b8b1.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

ARM64 设备

### 日志记录

[Uploading applog.2022-04-29.log…]()

**Comment by Richasy** [comment]
该问题已经在新版本（六月更新）里得到了修复
