### ISSUE TITLE
[Bug] 我的标题

### ISSUE THREAD

**Issue by wangshanghai240** [Richasy/Bili.Uwp#1148]
### Bug 描述

消息推送弹窗的ui问题：不知道是Windows 11系统问题还是设计问题，上面是直角，下面是圆角

### 复现问题的步骤

```plain text
推送消息的弹窗ui不一致
```

### 预期行为

完整的圆角

### 截图

![image](https://user-images.githubusercontent.com/59947306/165891991-3031202d-77a5-4e07-80c5-51a52bde9c93.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
系统问题，等以后系统推送更新吧
