### ISSUE TITLE
直播原画画质

### ISSUE THREAD

**Issue by IM515BT** [Richasy/Bili.Uwp#1150]
### Bug 描述

直播切换原画画质失败，只有声音（高清、超清除外）

（感觉直播画质只有网页的功能----在登录状态下）

### 复现问题的步骤

```plain text
直播切换原画画质失败，只有声音（高清、超清除外）
另：进入直播间很慢很慢，要等待时间
```

### 预期行为

非常流畅的加载原画画质！！！！！！

### 截图

![屏幕截图 2022-04-29 202721](https://user-images.githubusercontent.com/59956201/165945013-e0c1e098-2f9d-4531-ae19-384c25599268.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [X] Windows 10 1809 (Build 17763)
- [X] Windows 10 1903 (Build 18362)
- [X] Windows 10 1909 (Build 18363)
- [X] Windows 10 2004 (Build 19041)
- [X] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by IM515BT** [comment]
整个软件体验下来让人感觉稍显缓慢，没有点到点的感觉

**Comment by IM515BT** [comment]
刚刚从商店安装版本体验了下，真的比官方的好太多！！
就是比github安装的少了很多功能。如果商店版本可以完善的话，在win10的流畅度应该好太多太多。
界面整体的视觉舒适度也很好。

加油

**Comment by Richasy** [comment]
可以试一下六月更新，该问题应该有一定的缓解
