### ISSUE TITLE
[Bug] 在特定视频中出现音画不同步

### ISSUE THREAD

**Issue by Kanagawa-Wave** [Richasy/Bili.Uwp#1157]
### Bug 描述

在使用任意解码器播放特定视频时出现音画不同步的现象
（这些视频在网页端均能够正常播放）
发现这种问题的视频包括：
up主 r6scpl 近期发布的所有视频
站内部分4K视频

### 复现问题的步骤

```plain text
1.打开应用
2.打开并播放特定的视频
3.播放时画面比音频延迟一段时间
```

### 预期行为

预期：音频和视频同步播放

### 截图

无

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

出现音画不同步时，日志没有记录任何错误

**Comment by XPRAMT** [comment]
目前只有30系顯卡和intel 7xx內顯支援AV1硬解

**Comment by Ben-YuqiLu** [comment]
> 目前只有30系顯卡和intel 7xx內顯支援AV1硬解

根据更新公告中所述，Bili只支持软解AV1，应该不是硬件兼容性问题吧

**Comment by XPRAMT** [comment]
> > 目前只有30系顯卡和intel 7xx內顯支援AV1硬解
> 
> 根据更新公告中所述，Bili只支持软解AV1，应该不是硬件兼容性问题吧

軟解AV1 4K掉幀很正常，性能開銷太大了

**Comment by Ben-YuqiLu** [comment]
刚刚又试验了一下，不是解码方式的问题
在播放特定视频时就会出现音画不同步现象（网页端/手机端均音视频同步正确）
都是在声音先出现后画面再出现，原因不明

**Comment by Richasy** [comment]
可以尝试通过 ffmpeg 模式播放
