### ISSUE TITLE
[Bug] 切换全屏屏时大几率出现白屏

### ISSUE THREAD

**Issue by HWSJka** [Richasy/Bili.Uwp#1161]
### Bug 描述

切换全屏屏时大几率出现白屏，已经尝试过所有的解码模式，解码插件也全装了。

### 复现问题的步骤

```plain text
打开视频 反复切换全屏
```

### 预期行为

可能是A卡的兼容原因，希望解决
[Report.txt](https://github.com/Richasy/Bili.Uwp/files/8598818/Report.txt)
。

### 应用来源

- [X] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

**Comment by Hamakaze1s** [comment]
我也遇到了相同问题，但我是N卡，似乎在NVIDIA控制面板里把垂直同步（全局或者单独设置）关了就行
A卡试试看有没有用

**Comment by Richasy** [comment]
可以试试六月更新预览版，如果问题依然存在，大概率是系统控件对显卡支持不到位，我这边可能无法解决
