### ISSUE TITLE
[Bug] 弹幕卡顿

### ISSUE THREAD

**Issue by lxdklp** [Richasy/Bili.Uwp#1163]
### Bug 描述

更换为寒霜弹幕使后弹幕帧率极低（旧版帧率正常），虽然说我是6代i5挺老的，不至于弹幕是卡的吧，而且仅仅弹幕卡，视频流畅播放

### 复现问题的步骤

```plain text
1。打开软件
2。播放视频
```

### 预期行为

优化弹幕帧率

### 截图

![image](https://user-images.githubusercontent.com/69453767/166187697-59fd0a63-9f13-4865-9350-f6e3e4607bc3.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

Windows11 21h2（build22598）dev渠道

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by tangqiu0205** [comment]
我的小新pro16弹幕也卡, 视频列表和评论列表其实滑动也挺卡的.

**Comment by Richasy** [comment]
六月更新中该问题应该得到了一定的缓解

**Comment by texsd123** [comment]
> 六月更新中该问题应该得到了一定的缓解

现在我用的是最新的github版本，同款cpu和gpu，但在开启1080p后任何视频仍然出现5秒一卡的问题，720p偶尔掉帧，480p正常，望修复。
