### ISSUE TITLE
[Bug] 视频暂停一段时间后显示播放失败

### ISSUE THREAD

**Issue by ghost** [Richasy/Bili.Uwp#1166]
### Bug 描述

在视频暂停一段时间之后再进行播放，没过多久会显示播放失败

### 复现问题的步骤

```plain text
1.播放视频
2.视频暂停后等待一段时间（具体时间不详，就之前测试情况而言一般在半小时到一小时左右）
3.再点击播放
4.显示播放失败（可能会延迟几秒）
```

### 预期行为

在暂停一小段时间后仍能正常播放视频

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

Windows 11 Dev (Build 22598.200)

### 运行设备

桌面/平板或笔记本

### 日志记录

2022/05/04 12:12:50.919|Error|
系统信息：10.0.22598.200 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: DecodingError |  | System.Exception: 已禁止(403)。 (Exception from HRESULT: 0x80190193)
2022/05/04 12:12:57.092|Error|
系统信息：10.0.22598.200 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: DecodingError |  | System.Exception: 已禁止(403)。 (Exception from HRESULT: 0x80190193)
2022/05/04 15:02:28.948|Error|
系统信息：10.0.22598.200 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: DecodingError |  | System.Exception: 已禁止(403)。 (Exception from HRESULT: 0x80190193)
2022/05/04 15:02:28.948|Error|
系统信息：10.0.22598.200 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: DecodingError |  | System.Exception: 已禁止(403)。 (Exception from HRESULT: 0x80190193)
2022/05/04 15:02:31.046|Error|
系统信息：10.0.22598.200 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: DecodingError |  | System.Exception: 已禁止(403)。 (Exception from HRESULT: 0x80190193)

### 备注

个人推测，暂停视频之后的一段时间视频资源加载的链接失效，再播放时由于没获取到新的链接导致播放失败

### 人人为我，我为人人

我更擅长发现问题

**Comment by BanShan-Alec** [comment]
这个问题很早就有了，其他作者的第三方UWP也会出现。

不知道加一个，失败后重新加载的机制，能否解决。
或者说暂停超过20分钟，视频页浮现一个刷新的按钮，用户手动刷新

**Comment by wuhang2003** [comment]
> 

就我个人感觉，用其他第三方 UWP 时并没感受到这样的问题。

另外我个人想的一个办法是在暂停后点击播放那一刻可以确认缓存链接是否失效，如果失效就自动重新加载视频获取新链接。

**Comment by wuhang2003** [comment]
> 这个问题很早就有了，其他作者的第三方UWP也会出现。
> 
> 不知道加一个，失败后重新加载的机制，能否解决。 或者说暂停超过20分钟，视频页浮现一个刷新的按钮，用户手动刷新

就我个人感觉，用其他第三方 UWP 时并没感受到这样的问题。

另外我个人想的一个办法是在暂停后点击播放那一刻可以确认缓存链接是否失效，如果失效就自动重新加载视频获取新链接。

**Comment by Richasy** [comment]
使用 ffmpeg 播放模式可以缓解这个问题
