### ISSUE TITLE
[Feature] 播放画质预设

### ISSUE THREAD

**Issue by bs-yang** [Richasy/Bili.Uwp#1168]
### 问题描述

现在播放视频的画质好像只能根据网络情况自己选择，不能自定义。
如果不打开画质优先，会记录上一次视频播放的画质，如果有的视频最高720P，但是下次播放有1080P的，还会加载上次720P画质的设定，每次打开视频之后还需要调整画质

### 描述解决方案

希望可以在设置中自定义播放的画质，每次播放的时候都按照自己设置的画质

**Comment by Richasy** [comment]
哔哩哔哩的视频清晰度并不是固定的，有的视频720p甚至更低，在设置中有画质优先的选项，选择后可以让哔哩始终以最高画质播放
