### ISSUE TITLE
有WP10版的吗，官方版的不能用了

### ISSUE THREAD

**Issue by gghh2007** [Richasy/Bili.Uwp#1169]
### 问题描述

有没有WP10版

### 描述解决方案

没有信息

### 备选方案

无信息

### 附加信息

没有信息

**Comment by Richasy** [comment]
WP已死，我的950已经裱起来了，不会考虑支持

**Comment by gghh2007** [comment]
你也用950啊



在 2022-05-06 23:57:01，"Richasy" ***@***.***> 写道：

WP已死，我的950已经裱起来了，不会考虑支持
