### ISSUE TITLE
[Bug] 播放控件不断循环“自动隐藏-显示”

### ISSUE THREAD

**Issue by CloudBank-3055** [Richasy/Bili.Uwp#1170]
### Bug 描述

播放控件不断循环自动隐藏-显示的bug会在以下三类情况出现：
a.[偶现]无论视频播放暂停与否，无论播放器的大小形态，只要鼠标指针/触控笔悬停在播放控件悬停在任意按钮上，播放控件会不断循环自动隐藏-显示；
b.[必现]按空格键切换暂停/播放状态，播放控件会立马消失然后立马出现；
c.[必现]在按钮上悬停至出现说明文字，指针上移到说明文字上方（未移出播放控件区域），播放控件也会立马消失然后立马出现。

### 复现问题的步骤

```plain text
1.打开应用
2.点击播放任意视频

情况a.
3.鼠标指针/触控笔悬停在播放控件悬停在任意按钮上
4.bug出现：播放控件会不断循环自动隐藏-显示

情况b.
3.按空格键切换暂停/播放状态
4.bug出现：播放控件会立马消失然后立马出现

情况c.
3.在按钮上悬停至出现说明文字，指针上移到说明文字上方（未移出播放控件区域）
4.bug出现：播放控件也会立马消失然后立马出现
```

### 预期行为

鼠标悬停在播放控件的任意按钮上/切换播放状态时能稳定地保持显示播放控件

### 截图

情况a在写issue前能触发，写issue时反而没法触发了

情况b：
![ezgif-5-9b1230bede](https://user-images.githubusercontent.com/90302622/166920629-18b8073d-7474-4da2-b7a4-64422739e380.gif)

情况c：
![ezgif-5-4ea6479614](https://user-images.githubusercontent.com/90302622/166920988-6f6817f5-3a11-4fc9-a17c-ab9ba1a79fa1.gif)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

10.0.22610.1

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-05-05.log](https://github.com/Richasy/Bili.Uwp/files/8630806/applog.2022-05-05.log)

### 备注

除了用传统的键鼠操作以外，用屏幕键盘输入弹幕也容易出现该bug

**Comment by Richasy** [comment]
该问题在六月更新的新版本中已经得到了缓解，可以尝试一下
