### ISSUE TITLE
[Feature] 建议提供双击导航栏刷新

### ISSUE THREAD

**Issue by diave971** [Richasy/Bili.Uwp#1171]
### 问题描述

![image](https://user-images.githubusercontent.com/60306114/167074788-bef353ee-7c76-4aa0-8c3f-b03b441c4515.png)
右上角的刷新用鼠标定位比较麻烦

### 描述解决方案

![image](https://user-images.githubusercontent.com/60306114/167074914-5c4ccf61-b9dd-40a1-bd97-67f4af4aa2aa.png)
双击导航栏刷新资讯比较便捷，更符合人性化

**Comment by Richasy** [comment]
已经有刷新按钮的情况下暂不考虑这种交互，双击标题栏在桌面应用中不是一种通用的交互行为
