### ISSUE TITLE
五月更新的版本最高分辨率只有1080了！

### ISSUE THREAD

**Issue by tjddbc** [Richasy/Bili.Uwp#1172]
### Bug 描述

最高1080

### 复现问题的步骤

```plain text
没有4k8k
```

### 预期行为

打开视频

### 应用来源

- [ ] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

**Comment by Richasy** [comment]
不是大会员看不了
