### ISSUE TITLE
[Bug] 无法使用哔哩漫游观看港澳台番剧

### ISSUE THREAD

**Issue by MYan0110** [Richasy/Bili.Uwp#1173]
### Bug 描述

无法使用应用内置哔哩漫游解锁地区限制

### 复现问题的步骤

```plain text
打开应用

打开设置，填写漫游代理服务器“https://api.qiu.moe”，点击保存

打开我的追番

点击仅限港澳台地区番剧

显示PGC内容请求失败
```

### 预期行为

能够正常观看港澳台地区番剧

### 截图

![哔哩 5_7_2022 6_02_22 PM](https://user-images.githubusercontent.com/67667700/167249700-b84a1642-ecc7-4001-897b-beb120b4a037.png)
![哔哩 5_7_2022 6_03_09 PM](https://user-images.githubusercontent.com/67667700/167249714-633ba51f-b5b2-4f3a-a07a-7940335cb298.png)
![哔哩 5_7_2022 6_02_53 PM](https://user-images.githubusercontent.com/67667700/167249724-378e807b-ceb9-4737-934f-0a3cc69e0d15.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机, 桌面/平板或笔记本

### 日志记录

[applog.2022-05-07.log](https://github.com/Richasy/Bili.Uwp/files/8644871/applog.2022-05-07.log)

**Comment by Richasy** [comment]
参考这篇文章 [简单地漫游一下](https://github.com/Richasy/Bili.Uwp/wiki/%E7%AE%80%E5%8D%95%E5%9C%B0%E6%BC%AB%E6%B8%B8%E4%B8%80%E4%B8%8B) 来配置自己的代理服务
