### ISSUE TITLE
[Bug] 搜索栏遮挡输入法

### ISSUE THREAD

**Issue by AAAbyZSX** [Richasy/Bili.Uwp#1181]
### Bug 描述

  在搜索栏中输入想要搜索的内容，比如关键词一下子输不完，分批输入，当首批内容输入之后，下面的推荐（联想搜索）会遮挡输入法，看不到输入法候选字体。
![HAK2IFEFBU U`S@R8RYY95A](https://user-images.githubusercontent.com/50429675/167828597-b94135d2-1e11-45e2-9dc9-f976b436ce89.png)

### 复现问题的步骤

```plain text
1.打开应用
2.点击应用上方搜索框
3.输入搜索关键词（关键词分批输入）
```

### 预期行为

输入法悬浮于联想搜索上方；或者再次输入关键词时暂时性收起联想搜索栏。

### 截图

![image](https://user-images.githubusercontent.com/50429675/167827857-2efd6319-8cd0-4a1a-94fd-884ff5bc75d4.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [X] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
第三方输入法不做处理，也无法处理，只能兼容微软输入法
