### ISSUE TITLE
[Bug] 不显示视频，但有弹幕和声音

### ISSUE THREAD

**Issue by TuanZiGit** [Richasy/Bili.Uwp#1183]
### Bug 描述

打开视频后灰蒙蒙一片看不到画面但有弹幕有声音

### 复现问题的步骤

```plain text
打开应用
进入任意视频
复现BUG
```

### 预期行为

正常播放

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

Windows Insider Preview ni_release 10.0.22610.1

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-05-12.log](https://github.com/Richasy/Bili.Uwp/files/8676374/applog.2022-05-12.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Hamakaze1s** [comment]
我也遇到了相同问题，刚刚试了一下，似乎在NVIDIA控制面板里把垂直同步（全局或者单独设置）关了就行
