### ISSUE TITLE
[Bug] 部分直播间打开后提示“无法获取正确的播放地址”

### ISSUE THREAD

**Issue by huanxingyou** [Richasy/Bili.Uwp#1184]
### Bug 描述

个别直播间无法打开，会一直提示“无法获取正确的播放地址”（反复尝试刷新及重新进入依旧如此），有聊天互动，无画面。

### 复现问题的步骤

```plain text
1.打开应用
2.点击 直播
3.点击 单机游戏（其他区也有这个问题）
4.随便点一个直播间进去，有的就会出现这个问题
```

### 预期行为

希望能正常看直播

### 截图

<img width="970" alt="截图_20220512163537" src="https://user-images.githubusercontent.com/65204158/168028781-8bdf67ca-c1d6-4e87-acbe-6156c960d53e.png">
<img width="970" alt="截图_20220512163715" src="https://user-images.githubusercontent.com/65204158/168028829-d70c980f-e21d-451a-ae38-16acde526c1e.png">

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-05-12.log](https://github.com/Richasy/Bili.Uwp/files/8676399/applog.2022-05-12.log)

**Comment by Richasy** [comment]
与 #1188 相同
