### ISSUE TITLE
要是能支持消息或私信回复和创作中心功能展示就好啦~

### ISSUE THREAD

**Issue by shawlj** [Richasy/Bili.Uwp#1185]
### 问题描述

要是能支持消息或私信回复和个人中心数据展示就好啦~类似WEB网页个人创作中心的系列功能抽取到软件里来就太棒了，以后就不用打开网页端了，直接用软件就替代网页所有操作，当然能支持投稿就更好了，好吧我需求过于多，打扰啦

### 描述解决方案

功能需求，酌情开发~

### 备选方案

鄙人个人想法~

**Comment by Richasy** [comment]
目前暂不考虑支持这系列功能，哔哩目前以看视频为主
