### ISSUE TITLE
[Bug] 我的标题

### ISSUE THREAD

**Issue by 283Gawin** [Richasy/Bili.Uwp#1186]
### Bug 描述

无法播放LL虹咲学院偶像同好会，出现不支持该视频源字样并且软件卡死点击首页排行榜皆无反应。

### 复现问题的步骤

```plain text
1.搜索Love Live
2.点击立即观看
3.无法播放
```

### 预期行为

能否解决该bug

### 截图

![image](https://user-images.githubusercontent.com/69577009/168066551-29949616-f9c7-4b54-9e3c-d15bb66b2cb0.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[Log - 20220512.log](https://github.com/Richasy/Bili.Uwp/files/8678706/Log.-.20220512.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
旧版本已经停止支持并且不再维护，请使用新版本
