### ISSUE TITLE
[Bug] 播放闪退

### ISSUE THREAD

**Issue by azumia-azu** [Richasy/Bili.Uwp#1187]
### Bug 描述

播放视频、直播后会在随机时间（瞬间到10秒左右）后闪退，闪退前程序会卡住。
使用AVC、HEVC解码都会导致问题，日志中没有有效信息

### 复现问题的步骤

```plain text
打开应用
点击任意视频、直播
```

### 预期行为

正常播放视频、或在日志中打印有用的信息

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录
```
2022/05/14 16:37:04.366|Info|
系统信息：10.0.22000.675 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文 (簡體，中國)
--------
控制器加载完成
|
2022/05/14 16:39:17.419|Info|
系统信息：10.0.22000.675 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文 (簡體，中國)
--------
控制器加载完成
|
2022/05/14 16:39:32.060|Info|
系统信息：10.0.22000.675 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文 (簡體，中國)
--------
控制器加载完成
|
2022/05/14 16:40:05.804|Info|
系统信息：10.0.22000.675 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文 (簡體，中國)
--------
控制器加载完成
|
2022/05/14 16:40:22.513|Info|
系统信息：10.0.22000.675 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文 (簡體，中國)
--------
控制器加载完成
|
```

### 人人为我，我为人人

是的，我希望我的代码出现在哔哩中

**Comment by Richasy** [comment]
可以尝试使用新的六月更新，我目前无法复现这个问题
