### ISSUE TITLE
[Bug] 无法获取正确的直播地址

### ISSUE THREAD

**Issue by huoyan1231** [Richasy/Bili.Uwp#1188]
### Bug 描述

尝试观看直播时提示无法获取正确的直播地址 
其他直播间无影响

### 复现问题的步骤

```plain text
观看特定直播
```

### 预期行为

打开并播放直播

### 截图

![Snipaste_2022-05-14_17-14-11](https://user-images.githubusercontent.com/53113734/168419388-e23079ef-1471-47a0-9d68-d6fe6c2733ed.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2022-05-14.log](https://github.com/Richasy/Bili.Uwp/files/8692623/applog.2022-05-14.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Hodpel** [comment]
6.15 同样出现此问题 直播页面有半数的直播无法获取正确的直播地址

**Comment by Richasy** [comment]
目前哔哩不支持对flv直播源的解析，新版本中有更明确的提示
