### ISSUE TITLE
[Feature] xbox视频播放页，视频超级小

### ISSUE THREAD

**Issue by yanjingtui** [Richasy/Bili.Uwp#1190]
### 问题描述

![BA1B21AC-E732-4B9B-8BBC-AC54F6AC5F03](https://user-images.githubusercontent.com/18437653/168452322-7093b72b-316d-4d7a-a786-dac1ecbcb2b7.jpeg)
现在xbox的视频观看页，视频超级超级小

### 描述解决方案

视频宽度等于左侧容器宽度，高度自动。左侧容器添加滚动条

**Comment by Richasy** [comment]
Xbox会在之后重新设计，目前你可以在设置中将默认的播放模式调整为全屏
