### ISSUE TITLE
[Bug]闪退

### ISSUE THREAD

**Issue by JyaKirinawa** [Richasy/Bili.Uwp#1191]
### Bug 描述

开全屏显示会直接闪退

### 复现问题的步骤

```plain text
刚开始使用时不会发生，几分钟后点开任意视频，直播 全屏播放软件会直接闪退
```

### 预期行为

可以正常全屏播放视频

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

内部版本为19044

### 运行设备

桌面/台式机

### 日志记录

[applog.2022-05-15.log](https://github.com/Richasy/Bili.Uwp/files/8694269/applog.2022-05-15.log)

### 备注

windows应用程序日志描述
错误应用程序名称: Richasy.Bili.App.exe，版本: 1.0.0.0，时间戳: 0x6268b965
错误模块名称: Microsoft.Graphics.Canvas.dll，版本: 1.26.0.0，时间戳: 0x6089b158
异常代码: 0xc0000005
错误偏移量: 0x00000000000510ad
错误进程 ID: 0x5de8
错误应用程序启动时间: 0x01d868088b3fbcbe
错误应用程序路径: C:\Program Files\WindowsApps\Richasy.Bili_2.2205.1.0_x64__0d2vm92gxvj9a\Richasy.Bili.App.exe
错误模块路径: C:\Program Files\WindowsApps\Richasy.Bili_2.2205.1.0_x64__0d2vm92gxvj9a\Microsoft.Graphics.Canvas.dll
报告 ID: 08e7dd8c-4379-4e90-ab20-b0c3c827593b
错误程序包全名: Richasy.Bili_2.2205.1.0_x64__0d2vm92gxvj9a
错误程序包相对应用程序 ID: App

### 人人为我，我为人人

我更擅长发现问题

**Comment by Aegiszhy** [comment]
老哥我也遇见这个问题了，在此奉上我的日志
[applog.2022-05-14.log](https://github.com/Richasy/Bili.Uwp/files/8699008/applog.2022-05-14.log)

**Comment by Richasy** [comment]
该问题应该已经在六月更新中被修复，可以使用新版本尝试
