### ISSUE TITLE
[Feature] 希望全屏播放下显示标题

### ISSUE THREAD

**Issue by TimmonSha** [Richasy/Bili.Uwp#1193]
### 问题描述

在全屏播放视频的情况下，鼠标移动会显示播放控件。有时候会突然想看看视频标题是什么，这个时候只能退出全屏，看标题，再全屏。

### 描述解决方案

希望在全屏播放视频的情况下，显示播放控件的时候能够显示标题。标题可以放在全屏返回键的旁边。像是网页端在显示播放控件的同时也会在顶部显示标题。

**Comment by Richasy** [comment]
桌面版暂时不会加入该功能，未来会在xbox上支持
