### ISSUE TITLE
[Feature] 希望能添加下历史进度，看番剧看一半退出下次重新打开并不会继续上次播放，而是从头开始◑﹏◐

### ISSUE THREAD

**Issue by lztymc** [Richasy/Bili.Uwp#1198]
### 问题描述

能否添加下历史进度，看番剧看一半退出下次重新打开并不会继续上次播放，而是从头开始◑﹏◐

### 描述解决方案

像商店版本那个那样可以记录历史记录，方便续看

**Comment by Richasy** [comment]
六月预览版已经添加
