### ISSUE TITLE
[Feature] 下载大更新建议

### ISSUE THREAD

**Issue by blibilijojo** [Richasy/Bili.Uwp#1201]
### 问题描述

每次下载视频时：
1.打开下载
2.生成指令
3.win+r
4.ctrl+v
5.回车
就显得过程有那么一丢丢的繁琐

### 描述解决方案

之前虽然说过不内置下载功能，但是可否不内置，只是联动呢，点击下载后台自动下载，如果没有安装bbdown就弹出弹窗提醒
并且吧下载与下载设置分开，将下载设置放到设置中，将视频的下载设置变成单纯的下载，直接点击就行的那种
并且可以在左侧栏加一个下载查看进度栏，当然了这样在正在观看视频的时候并不适合观看，所以我个人从人性化的角度来讲详细放在搜索栏右边是一个更好的选择，只需要一个简化的下载图标即可，点击后出现一个弹窗显示文件名，下载进度和是否关闭。文件大小等

### 备选方案

之前方案的简化版，直接将现在的生成命令改为立即下载，并于bbdown在后台下载，并且按照之前的想法加入下载内容查看

### 附加信息

作者大大好好休息啦，这辈子能更新就行，不能更这个或者是可以搞的话希望新建加入一个里程碑（不用写日期，只要是个目标就行），或者回复可不可以也行啊
幻神加油啊💪(ง •_•)ง

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
关于这个……怎么说呢，UWP不能直接调用命令行，所以很难做更深的结合了
