### ISSUE TITLE
[Bug] 卡顿问题

### ISSUE THREAD

**Issue by blibilijojo** [Richasy/Bili.Uwp#1202]
### Bug 描述

就是目前的卡片之类的只要我的鼠标稍微快一点就不会做出反应（并且这东西是是一会有反应一会没有的），除非我鼠标再次移动，就感觉很像是延迟(并且开久了还会更明显)，根据我在议题的长期观察我可以确定这是一个较为普遍的问题，，并且之前在较早版本并未出现，或许是判定问题？或者是视频卡片检测鼠标移动到之后的检查、动画、收回之类的较为复杂
如果作者无问题的话我认为也就是这几种原因了
1：我电脑太烂，但是通过任务管理器看我的各项并未满
2：驱动问题，2018年的
我认为这些问题概率应该都不算太大

### 复现问题的步骤

```plain text
1.打开应用
2.在一群视频中用鼠标快速移动
```

### 预期行为

没有延迟

### 截图

![GIF](https://user-images.githubusercontent.com/102420734/169683954-35e7f602-07ff-4833-9f32-5157f07720f0.gif)
![222](https://user-images.githubusercontent.com/102420734/169684116-a6f1fca7-59ec-433f-9422-2264c3776447.gif)

### 应用来源

- [ ] Microsoft Store
- [x] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
光标动画应该和系统资源有关（可以尝试在系统设置里关闭透明化），弹幕的问题在你的另一个bug中已经回复
