### ISSUE TITLE
[Bug] 视频短长度步进导致应用和可能的系统卡死

### ISSUE THREAD

**Issue by pboymt** [Richasy/Bili.Uwp#1205]
### Bug 描述

多次快进视频后应用卡死，之后第一次写 Issue 反馈的时候直接系统卡死了。

### 复现问题的步骤

```plain text
1. 打开应用
2. 进入番剧并播放（我观看的是《暂停查攻略》，全屏播放）
3. 连续多次按`→`键快进视频
4. 应用卡死（具体表现为视频卡死，弹幕卡死，音频在当时的2秒内反复循环，使用`Alt+Tab`切换出去后无法再切换回应用窗口）
5. 强制关闭窗口（通过任务栏关闭的，没通过任务管理器）
6. （不到 1 分钟后我自己电脑出现了）系统卡死
```

### 预期行为

能够多次快进到视频目标位置。

### 截图

<img width="412" alt="image" src="https://user-images.githubusercontent.com/10893582/169737207-90195010-3620-4650-9f0e-a9335c2caee0.png">

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [x] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-05-23.log](https://github.com/Richasy/Bili.Uwp/files/8751244/applog.2022-05-23.log)

### 备注

我系统卡死的时候恰好刚开始用QQ输入法打字，猜测后续系统卡死可能是应用崩溃和这个的共同作用。我不敢再尝试复现系统会不会再卡死了……

### 人人为我，我为人人

我更擅长发现问题

**Comment by XiaoLong2333** [comment]
遇到一样的bug

**Comment by Richasy** [comment]
可以尝试六月更新预览版，该问题应该有一定的缓解
