### ISSUE TITLE
[Bug] 拖拽窗口至其他显示器的时候视频短暂黑屏

### ISSUE THREAD

**Issue by pboymt** [Richasy/Bili.Uwp#1207]
### Bug 描述

播放视频中的窗口从一个显示器拖拽到另一个显示器的时候视频会短暂黑屏

### 复现问题的步骤

```plain text
1. 打开应用
2. 播放任意视频
3. 将播放中的窗口拖拽进入另一个显示器
4. 视频黑屏，声音仍在输出
5. 几秒后视频画面恢复（并且和音频是同步的）
6. 拖拽回也会这样
7. 每次跨屏幕拖拽都会这样
```

### 预期行为

视频正常播放不会短暂黑屏

### 截图

<img width="895" alt="image" src="https://user-images.githubusercontent.com/10893582/169738893-0213558e-7598-43d3-8231-4a99276b7d79.png">

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

没有输出新的错误日志

### 备注

猜测：可能是两个显示器使用的显卡不同？

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
这个不在应用的修复范围内，应该是系统控件的问题
