### ISSUE TITLE
[Bug] 视频播放存在画面定格问题

### ISSUE THREAD

**Issue by Octomouch** [Richasy/Bili.Uwp#1208]
### Bug 描述

播放视频时经常出现音轨继续播放但是画面定格的问题

### 复现问题的步骤

```plain text
1.打开应用
2.随便播放一个视频
3.很大概率复现上述问题
```

### 预期行为

视频画面不定格，正常播放

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [x] 其它 (需注明)

### 其它系统版本

Windows 11 22H2(Build 22621)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-05-25.log](https://github.com/Richasy/Bili.Uwp/files/8767610/applog.2022-05-25.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
目前无法复现该问题，可以尝试使用最新的六月更新看看问题是否还存在
