### ISSUE TITLE
切换直播视频清晰度时，画面卡住，只有声音正常

### ISSUE THREAD

**Issue by Kyving** [Richasy/Bili.Uwp#1211]
### Bug 描述

切换直播视频清晰度时，画面卡住，只有声音正常，具体是在观看 哔哩哔哩英雄联盟赛事 直播时出现的，看其他视频时无此问题。优点：软件界面实在漂亮，好评。

### 复现问题的步骤

```plain text
打开直播，选择 哔哩哔哩英雄联盟赛事，点击直播，切换清晰度，画面卡住。
```

### 预期行为

打开直播，选择 哔哩哔哩英雄联盟赛事，点击直播，切换清晰度，画面正常切换。

### 应用来源

- [ ] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

**Comment by Richasy** [comment]
可以试一下新的六月更新预览版
