### ISSUE TITLE
[Bug] 直播功能异常

### ISSUE THREAD

**Issue by sSkieri** [Richasy/Bili.Uwp#1215]
### Bug 描述

直播切换原画时会直接卡死  弹幕正常 画面上下出现细微黑边无法播放 不论是否登陆账号以及使用任意解码器 且部分直播间直接无法播放

### 复现问题的步骤

```plain text
打开哔哩
点击直播选项 
任意直播间
切换原画
```

### 预期行为

可以正常观看直播

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

**Comment by forevemoe** [comment]
有同样问题

**Comment by fxzxmicah** [comment]
解码，还有线路问题。
这个问题好久了。

**Comment by Richasy** [comment]
目前不支持flv片源，新的版本会给出更明确的提示，但目前暂时不打算进行处理

**Comment by fxzxmicah** [comment]
> 目前不支持flv片源，新的版本会给出更明确的提示，但目前暂时不打算进行处理

@Richasy 意思是原画和高清超清用的片源不同？那还有个问题，有的情况下是高清可以播放但是超清不行。
