### ISSUE TITLE
[Bug] 竖屏下默认播放器模式视频控制栏显示不全

### ISSUE THREAD

**Issue by tljk** [Richasy/Bili.Uwp#1216]
### Bug 描述

![image](https://user-images.githubusercontent.com/36393586/172079345-79177d93-c225-428d-96c4-84c248228f26.png)
![image](https://user-images.githubusercontent.com/36393586/172079462-85bf585b-5045-4209-8e10-4fde9ad8b03a.png)
![image](https://user-images.githubusercontent.com/36393586/172079533-e8c6a4fb-f48a-4e34-aea5-504aa575f636.png)

### 复现问题的步骤

```plain text
需要竖屏或者旋转显示器
最大化打开哔哩
默认播放器模式播放
窗口化后仍然显示不全
```

### 预期行为

![image](https://user-images.githubusercontent.com/36393586/172079725-9a8334ab-d1e3-4205-a850-530aecf54f21.png)
通过横屏下缩小窗口，再旋转到竖屏可以得到正常的结果

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
在最新的六月更新中已经重写了播放控制器，该问题得到了解决
