### ISSUE TITLE
[Bug] 界面触摸滑动卡顿

### ISSUE THREAD

**Issue by houzhaopeng** [Richasy/Bili.Uwp#1217]
### Bug 描述

surface pro 8 界面滑动时不流畅

### 复现问题的步骤

```plain text
在主界面滑动就很卡的了已经
```

### 预期行为

优化滑动体验和流畅度

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
可以试试新的六月预览版更新
