### ISSUE TITLE
[Bug] 在使用账号密码登录时，点击“获取验证码”应用无响应

### ISSUE THREAD

**Issue by ThinBuffalo** [Richasy/Bili.Uwp#1218]
### Bug 描述

在使用账号密码登录时，应用要求我验证账号安全输入验证码，点击内嵌网页中“获取验证码”应用无响应

### 复现问题的步骤

```plain text
1. 打开应用
2. 点击右上角头像按钮进入登录
3. 点击“用密码登录”
4. 输入账号和密码，应用要求我验证手机
5. 点击弹出内嵌网页中的“获取验证码”（无反应）
```

### 预期行为

 点击“获取验证码“应用应是有响应的

### 截图

![截图](https://s3.bmp.ovh/imgs/2022/06/17/e69f80866fed9b6d.jpg)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

```
2022/06/17 22:47:31.378|Info|
系统信息：10.0.19043.1237 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文(简体，中国)
--------
控制器加载完成
|
```

### 人人为我，我为人人

我更擅长发现问题

**Comment by tianbosong** [comment]
我都打不开登陆页面了

**Comment by Richasy** [comment]
控件不支持 Win10 使用该功能，所以 Win10 目前只能扫码登录
