### ISSUE TITLE
[Bug] 我播放某些视频的4k或hdr版本时，视频后半段画面加载不出来（但是有声音）

### ISSUE THREAD

**Issue by Z-Geisha** [Richasy/Bili.Uwp#1219]
### Bug 描述

播放某些视频的4k或hdr或8k版本时（感觉是码率高一点的视频），视频后半段画面加载不出来（但是有声音，弹幕也正常），重新打开视频时，弹幕和声音能从中断的地方继续播放，但视频一直卡住。另外，用hevc编码在播放了一小部分后画面卡死，av1编码在视频播放了大半部分后卡死。
![屏幕截图 2022-06-22 130847](https://user-images.githubusercontent.com/96930347/174948177-f752fad6-4d38-4b9e-b00c-2b147d00b7d5.png)

### 复现问题的步骤

```plain text
1、打开视频AV934637444（举例），画质选为hdr，hevc和AV1编码画面都会在2：15时卡住，声音和弹幕正常
```

### 预期行为

希望画面不要卡住，不要影响浏览体验

### 截图

![屏幕截图 2022-06-22 130847](https://user-images.githubusercontent.com/96930347/174948691-2b180eec-93bc-480b-b1d7-873b7decad4b.png)
下面是另外一个8k视频的卡住截图，第一张是av1编码卡住位置，第二张是hevc卡住的位置。
![image](https://user-images.githubusercontent.com/96930347/174949069-de7413e4-dfd6-4372-839e-420c82692ad3.png)
![image](https://user-images.githubusercontent.com/96930347/174949352-b70473c6-a411-441b-8bbe-05b8a7557aa2.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2022-06-22.log](https://github.com/Richasy/Bili.Uwp/files/8954558/applog.2022-06-22.log)
最后一条应该就是这个问题的描述。

### 备注

处理器	AMD Ryzen 9 5900X 12-Core Processor               3.70 GHz
机带 RAM	32.0 GB
版本	Windows 11 专业版
版本	21H2
操作系统版本	22000.739
显卡3080ti超龙
显驱版本516.40

**Comment by zhao-wuyan** [comment]
切换画质就可以动了

**Comment by Z-Geisha** [comment]
有不降低画质就可以让画面继续播放的办法吗（手动狗头）

**Comment by blibilijojo** [comment]
现在所有人都知道你有3080ti了/(ㄒoㄒ)/~~

**Comment by Z-Geisha** [comment]
> 现在所有人都知道你有3080ti了/(ㄒoㄒ)/~~

只是想让大佬排除配置上的原因（啊这

**Comment by Z-Geisha** [comment]
> 据说方法是到nVidia改该应用的垂直同步

应用垂直同步之后解决了画面帧数过低的问题，但是画面加载不出来还是没解决

**Comment by Z-Geisha** [comment]
七月份更新之后，问题解决，谢谢大佬
