### ISSUE TITLE
[Bug] windows 11 播放视频100%闪退

### ISSUE THREAD

**Issue by zhao-wuyan** [Richasy/Bili.Uwp#1221]
### Bug 描述

打开一个视频，播放一段时间，然后闪退。
百分百闪退，继续播放很大概率一点就马上闪退。
全屏，非全屏，全窗口都闪退

### 复现问题的步骤

```plain text
1.打开应用
2.选择一个视频
3.播放视频
4.等一段时间
5，闪退


1.打开应用
2.是否继续播放（继续）
3.观看历史（跳转）
4.马上闪退
```

### 预期行为

正常播放

### 应用来源

- [X] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

2022/06/24 12:51:58.251|Info|
系统信息：10.0.22000.739 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文(简体，中国)
--------
控制器加载完成
|
2022/06/24 13:02:06.339|Info|
系统信息：10.0.22000.739 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文(简体，中国)
--------
控制器加载完成
|
2022/06/24 13:04:41.310|Info|
系统信息：10.0.22000.739 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文(简体，中国)
--------
控制器加载完成
|
2022/06/24 13:04:49.641|Info|
系统信息：10.0.22000.739 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文(简体，中国)
--------
控制器加载完成
|
2022/06/24 13:05:01.327|Info|
系统信息：10.0.22000.739 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文(简体，中国)
--------
控制器加载完成
|
2022/06/24 13:05:54.875|Info|
系统信息：10.0.22000.739 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文(简体，中国)
--------
控制器加载完成
|
2022/06/24 13:09:40.535|Info|
系统信息：10.0.22000.739 | Windows.Desktop | X64
应用信息：2.2205.1.0 | 中文(简体，中国)
--------
控制器加载完成
|

**Comment by Richasy** [comment]
可以试试六月更新的版本
