### ISSUE TITLE
[Bug] v2.2206.1.0 BUG 汇总

### ISSUE THREAD

**Issue by NekoAria** [Richasy/Bili.Uwp#1227]
### Bug 描述

v2.2206.1.0 播放时方向键与空格键没反应，ESC 键正常

### 复现问题的步骤

```plain text
如上
```

### 预期行为

和旧版本的行为一致

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by NekoAria** [comment]
重启应用后恢复正常，日志里也没有报错信息，暂时无法复现。

**Comment by NekoAria** [comment]
唯一确定的是目前这个版本无法后退，只能快进。

**Comment by NekoAria** [comment]
有时候播放不加载弹幕，同时界面无法交互，只能通过 ALT + F4 等方式强制关闭。

**Comment by Richasy** [comment]
新版中不再支持向后退和返回上一集的功能，因为使用频率远不如跳进和下一集，相关需求可以通过调整进度条或者在播放列表中选择分集来处理。
弹幕的话，目前还在排查原因，但可以通过手动开关弹幕按钮来进行刷新

**Comment by NekoAria** [comment]
> 新版中不再支持向后退和返回上一集的功能，因为使用频率远不如跳进和下一集，相关需求可以通过调整进度条或者在播放列表中选择分集来处理。
> 弹幕的话，目前还在排查原因，但可以通过手动开关弹幕按钮来进行刷新

虽然后退的使用频率确实远低于快进，但是直接去掉我觉得过于激进。
返回上一集我确实没用过，这个没意见。
而直接拖动进度条的体验并不好，尤其是对于视频长度较长的视频来说，如果只是想后退十几秒的情况下，不小心就拖到了一两分钟前。
针对这点，我希望看看大伙的想法，比如发个讨论或者投票来决定。

**Comment by fxzxmicah** [comment]
> 

我也认为不应直接取消后退。返回上一级确实直接点击分集更好，但后退前进使用方向键比拖动进度条好多了。

**Comment by St-Cai** [comment]
同感，在一些长度较长的视频里依靠拖动进度条后退十几秒基本不可实现

**Comment by fxzxmicah** [comment]
@Richasy 你没想过用方向上下键来控制侧边栏相关视频以及评论的滚动，同时用方向左右建控制视频前进后退吗？这样更统一一些。

**Comment by Richasy** [comment]
@fxzxmicah 视频和评论的滚动是常规键盘导航的一部分，如果将焦点通过 Tab 转移到侧边栏条目上，自然可以上下切换及滚动，不需要全局捕获并专门用来处理侧边栏
