### ISSUE TITLE
播放控件问题

### ISSUE THREAD

**Issue by haoey** [Richasy/Bili.Uwp#123]
## Bug 描述

注意附件里鼠标点击位置

只有鼠标点击位置在控件会出现的地方时，控件才会悬停，而在其他位置，比如屏幕中央单击时，控件会一闪而过，是刻意这样设计还是？
## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '...'
3. 点击 '....'
4. 滚动至 '....'
5. 发现问题

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [ ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 备注

https://user-images.githubusercontent.com/70797176/133918149-cc50eb35-4577-4a60-a434-eb0ecd92f7da.mp4

**Comment by Richasy** [comment]
与问题 #99  重复，请在那个Issue中继续追踪这个问题
