### ISSUE TITLE
[Bug] 播放界面鼠标侧键功能逻辑混乱

### ISSUE THREAD

**Issue by St-Cai** [Richasy/Bili.Uwp#1230]
### Bug 描述

在v2.2206.1.0 preview版本中发现视频播放界面鼠标侧键大致按照以下逻辑：
若将界面播放器部分分为A区，将右侧“关联视频与评论”部分分为B区，其余部分为C区

1.鼠标焦点在A区，按住侧键后不拖动松开，返回上一级界面
2.鼠标焦点在A区，按住侧键后上下拖动，调节视频音量后暂停
3.鼠标焦点在A区，按住侧键后左右拖动，调节视频进度后暂停
4.鼠标焦点在B区，点击侧键，返回上一级界面
5.鼠标焦点在C区，点击侧键，无法实现任何功能

此外，在旧版本中也基本按照上述逻辑，但与新版本不同的是：
执行上述1和2操作时，调节音量或进度后，最后的动作不是暂停而是返回上一级界面

### 复现问题的步骤

```plain text
如上
```

### 预期行为

1.仅保留鼠标侧键的返回功能，避免误触
2.保持各个位置鼠标侧键功能的一致性

### 截图

分区示意图：
![分区示意图](https://user-images.githubusercontent.com/55645331/175772237-8f1b890f-ef56-4b33-a492-165a4d189244.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

Windows 11 22H2 (Build 22621)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
侧键返回的前提条件是在页面空白处，其它可交互的地方（比如卡片，或者播放器）则一律按单击处理。

所以我更在意你提到的B区不能正常返回的情况，目前已经提了一个PR来修复它

**Comment by St-Cai** [comment]
> 侧键返回的前提条件是在页面空白处，其它可交互的地方（比如卡片，或者播放器）则一律按单击处理。
> 
> 所以我更在意你提到的B区不能正常返回的情况，目前已经提了一个PR来修复它

感觉这种说法不是很符合使用习惯，目前我在使用侧键基本是在浏览器、资源管理器这类需要高频前进、后退操作的应用中，但是在这两个应用中并不会因为把鼠标放在一个可交互内容上而失去侧键的功能。
是否可以将其改为：
1.在普通窗口的任何内容上都可以使用侧键的返回功能。
2.在全屏、小窗、全窗口模式下，使用侧键可以返回普通窗口。

另外在最新的v2.2206.3.0版本中，如果把鼠标放在视频标题、视频标签、视频av/bv号等“低交互”内容上时，也无法使用侧键返回，而且把鼠标放在播放器上使用侧键依旧会误触为点击，也就是上述的1、2、3问题依旧会发生，这应该视为一个bug因为其与其他可交互内容上的行为不一样（其他位置为不触发任何操作），在我的使用过程中经常导致误触。
