### ISSUE TITLE
[Bug] 新版本播放音量异常，默认以100%音量播放

### ISSUE THREAD

**Issue by St-Cai** [Richasy/Bili.Uwp#1231]
### Bug 描述

打开视频后音量默认以100%播放，此时音量调节界面显示的并非100%，但实际播放音量为100%，进行一次音量调节后正常

### 复现问题的步骤

```plain text
打开任一视频均会复现
```

### 预期行为

修复bug

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

Windows 11 22H2 (Build 22621)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-06-25.log](https://github.com/Richasy/Bili.Uwp/files/8984634/applog.2022-06-25.log)

**Comment by St-Cai** [comment]
补充：若上次播放时调节为静音，则这次打开会正常静音播放

**Comment by Richasy** [comment]
我没有复现这个问题，请问你在调整了一次音量后，重启或重新打开应用还是会出现音量显示和实际不一致的情况吗？
