### ISSUE TITLE
[Bug] 最新6月版本无法登录

### ISSUE THREAD

**Issue by yiobai** [Richasy/Bili.Uwp#1232]
### Bug 描述

最新的6月预览版本无法使用右上角点击头像进行登录

### 复现问题的步骤

```plain text
无法点击登录的头像(无法登录)
```

### 预期行为

有空修一下吧

### 截图

<img width="408" alt="屏幕截图 2022-06-25 211044" src="https://user-images.githubusercontent.com/82246026/175774905-d711bb66-b9a2-4890-8663-e1430985c575.png">

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本, ARM64 设备

**Comment by amtoaer** [comment]
@Richasy 您好，我这边更新至`2.2206.2.0`后仍然无法登录账号，具体表现是点击右上角头像没有任何反应 😢
