### ISSUE TITLE
[Bug] Bili.Uwp_2.2206.2.0_x64 暗色主题不生效

### ISSUE THREAD

**Issue by ericclose** [Richasy/Bili.Uwp#1237]
### Bug 描述

更新 Bili.Uwp_2.2206.2.0_x64 后发现暗色主题失效

### 复现问题的步骤

```plain text
暗色主题更新后就失效
```

### 预期行为

随个人设定产生相应的效果

### 截图

![Snipaste_2022-06-26_14-59-22](https://user-images.githubusercontent.com/34526560/175803280-e4844eab-9769-4cf8-98bb-dd80e1afaeac.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by LeslieYon** [comment]
不只是暗色主题不生效，退出账号后也无法再登录了

**Comment by EdinMeow** [comment]
> 不只是暗色主题不生效，退出账号后也无法再登录了

21h2 ltsc一样无法登录
