### ISSUE TITLE
[Bug] 双击暂停失效

### ISSUE THREAD

**Issue by ndbcd** [Richasy/Bili.Uwp#1245]
### Bug 描述

现在触摸屏用户已经无法用双击来暂停视频.

### 复现问题的步骤

```plain text
在视频播放时,原先有的双击暂停功能现已不再生效.
```

### 预期行为

可以把双击暂停给加回来吗.

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
会在下周更新中修复这个问题
