### ISSUE TITLE
[Bug] 鼠标侧键返回依然不理想

### ISSUE THREAD

**Issue by diave971** [Richasy/Bili.Uwp#1248]
### Bug 描述

v2.2206.3.0版本鼠标侧键返回几乎找不掉区域触发

### 复现问题的步骤

```plain text
在播放界面点击鼠标侧键会暂停视频
而不是返回上一页，
在评论的二级页面点击鼠标侧键也不能实现返回上一页的效果。
```

### 预期行为

在全局界面点击鼠标侧键可以返回上一层

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
侧键返回仅适用于页面，不适用于播放器或者评论页面这种组件
