### ISSUE TITLE
[Bug] 漫游不能正常使用

### ISSUE THREAD

**Issue by googril** [Richasy/Bili.Uwp#1249]
### Bug 描述

服务器网页能用，v2.2206.3.0 UWP漫游不能正常使用

### 复现问题的步骤

```plain text
1.打开应用
2.进入设置
3.点击漫游开关
4.添加有效服务器地址
5.转港台区番视频播放信息请求失败
```

### 预期行为

UWP加分页，或者在播放设置加入漫游开关，来回找很久

### 截图

![Quicker_20220626_182216](https://user-images.githubusercontent.com/25705390/175809904-ca69d3c4-090d-4411-80a2-19cf84b31074.png)
![Quicker_20220626_182318](https://user-images.githubusercontent.com/25705390/175809911-ec8839f9-bdba-406d-9d81-9e0e096b0230.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

**Comment by Richasy** [comment]
参考 [番剧代理](https://github.com/Richasy/Bili.Uwp/wiki/%E7%95%AA%E5%89%A7%E4%BB%A3%E7%90%86)，目前不支持哔哩漫游的服务，相关名词在下个版本会改掉
