### ISSUE TITLE
[Bug] 分屏体验诡异

### ISSUE THREAD

**Issue by ndbcd** [Richasy/Bili.Uwp#1251]
### Bug 描述

在我分屏使用时，视频拉伸得很严重，

### 复现问题的步骤

```plain text
把此应用进行分屏，即可出现此效果。
```

### 预期行为

把视频拉伸成正常的比例。

### 截图

![屏幕截图 2022-06-26 190752](https://user-images.githubusercontent.com/101174232/175811285-6c10159f-874a-47c3-a26a-1c484dbdf43b.jpg)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by blibilijojo** [comment]
所以你不明白为啥又小窗口模式吗(虽然没有弹幕)

**Comment by Richasy** [comment]
非要这么窄播放吗……，按F10或F11全屏播放即可
