### ISSUE TITLE
[Doc] 建议减小Release文件大小

### ISSUE THREAD

**Issue by Oeaps** [Richasy/Bili.Uwp#1263]
### 问题描述

众所周知，从github上下177M的文件还是挺费时间的，而如果只是更新版本的话，只需要其中不到50M的.msixbundle文件

### 预期内容

建议把单独的安装包也放在Release里，方便更新应用

**Comment by Richasy** [comment]
目前这些文件是通过actions自动打包的，我并不想介入到这个过程中。下载问题可以通过安装 FastGithub 之类的工具来解决，或者在 Microsoft Store 下载
