### ISSUE TITLE
收集了一些界面上的小建议

### ISSUE THREAD

**Issue by JolyonJostar** [Richasy/Bili.Uwp#129]
1.评论区
评论区点更多回复后，楼层内容被安排到了界面中间，这视觉并不连贯，建议继续保持在右边
![image](https://user-images.githubusercontent.com/61088063/133921312-933e5a8f-5771-4159-b38b-b1858c91ac42.png)

2.播放器控件
![image](https://user-images.githubusercontent.com/61088063/133921377-b5e63e8c-23f9-4e16-b139-34c1b1970ad2.png)
-控件布局过宽，对于按钮的寻找并不友好
-自动隐藏只有第一次才有，如果重新唤起控件不会再自动隐藏，建议保持每次都自动隐藏

3.大会员字体颜色建议改成粉红色
![image](https://user-images.githubusercontent.com/61088063/133921420-65e13580-de9d-4bf6-b140-0b577ec0a77b.png)

4.全屏时首页内容过多，有点看不过来，可以考虑增大每个卡片，减少同屏的的视频数量（我自己测试4~5个比较舒适）
![image](https://user-images.githubusercontent.com/61088063/133921454-5122b457-9997-4f52-bfc2-0480a3ab4efd.png)

**Comment by MoeX1n** [comment]
![图片](https://user-images.githubusercontent.com/90125402/133925781-09dd2b96-7beb-4fed-aa71-f1e613d58447.png)
不知道是不是我win10问题还是什么，这个icon好模糊

**Comment by Curious-r** [comment]
这个评论详情的弹窗，用无阴影边框的亚克力感觉跟背景区分度太低了，都是一片白，看不到边界在哪里

**Comment by Richasy** [comment]
这里说一下，Issue里提的问题过多，最好一个Issue只说一个问题，这样便于追踪
