### ISSUE TITLE
[Bug] 视频进度条时间错误

### ISSUE THREAD

**Issue by HaoTian22** [Richasy/Bili.Uwp#1298]
### Bug 描述

观看视频的时候下方进度条的时间经常会卡住不动，导致时间显示错误
只有在暂停的时候显示的才是正确的时间（棕色进度条），播放的时候就是错误的时间（蓝色进度条）

### 复现问题的步骤

```plain text
随便打开一个视频
观看一会，期间就会随机出现这种情况
```

### 预期行为

进度条能跟随视频的播放进度变化

### 截图

鼠标指向进度条时（错误显示）
![image](https://user-images.githubusercontent.com/48882584/176980080-bd46d98d-85cc-4ef8-8383-3b0029006f71.png)

鼠标离开进度条时（正确显示）
![image](https://user-images.githubusercontent.com/48882584/176979882-a6e35f42-9911-4dee-9e4c-f64ba1839709.png)
这两张图是同一个画面，都是视频的结尾，期间我处理移动鼠标外没有做过任何操作

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [x] 其它 (需注明)

### 其它系统版本

Win11 22H2 22621.160

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by Kimaru-bili** [comment]
而且再点一次播放就会重头开始 我也遇到了
![屏幕截图 2022-07-09 123010](https://user-images.githubusercontent.com/40233772/178091649-1d217360-62c6-464f-8bfe-c35214e787e6.png)
