### ISSUE TITLE
直播bug

### ISSUE THREAD

**Issue by huxia86465** [Richasy/Bili.Uwp#1300]
### Bug 描述

在使用hevc播放直播会显示白色内容有弹幕有声音，画面都是**白色**的
在使用ac1播放时的时候一样的问题不过画面会出现**绿色**画面

### 复现问题的步骤

```plain text
.......
```

### 预期行为

......

### 截图

![image](https://user-images.githubusercontent.com/70738910/177000261-db5b59a0-b8cd-4141-a5d6-6d657d27404e.png)
![image](https://user-images.githubusercontent.com/70738910/177000263-7ca6cf69-5f14-4ff7-afe5-38af4c0015a2.png)

### 应用来源

- [ ] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [x] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 日志记录

欸嘿

### 备注

欸嘿

**Comment by Richasy** [comment]
大概率是显卡问题，我这边难以修复

**Comment by huxia86465** [comment]
那天是看游戏直播高峰期突然这样最近看又正常了还以为修复了呢
