### ISSUE TITLE
[Bug] 打开视频，1s后软件闪退，再次打开之后同样出现

### ISSUE THREAD

**Issue by hanlongzhifu** [Richasy/Bili.Uwp#1307]
### Bug 描述

如题，

### 复现问题的步骤

```plain text
1. 打开应用
2. 点击推荐页面视频
3. 应用闪退
```

### 预期行为

当然是可以正常播放了

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 日志记录

没有有用的信息：
2022/07/04 10:21:27.223|Info|Initializing to normal mode (.cctor)|
2022/07/04 10:21:46.001|Info|Initializing to normal mode (.cctor)|
2022/07/04 10:23:38.495|Info|Initializing to normal mode (.cctor)|
windows事件查看器中：
错误应用程序名称: Bili.App.exe，版本: 1.0.0.0，时间戳: 0x62bc5a94
错误模块名称: KERNELBASE.dll，版本: 10.0.19041.1741，时间戳: 0xe9b4a91b
异常代码: 0x00001007
错误偏移量: 0x000000000010fa32
错误进程 ID: 0x52f8
错误应用程序启动时间: 0x01d88f4cc3b111c4
错误应用程序路径: C:\Program Files\WindowsApps\60520B029E250.4264454043325_2.2207.1.0_x64__5aa7k9th7aafp\Bili.App.exe
错误模块路径: C:\Windows\System32\KERNELBASE.dll
报告 ID: 4d741af4-8dbd-4bfc-b545-2294beebb585
错误程序包全名: 60520B029E250.4264454043325_2.2207.1.0_x64__5aa7k9th7aafp
错误程序包相对应用程序 ID: App
事件查看器中有其他信息：
主机弹出窗口-Bili.App.exe-异常；message：特权指令

### 人人为我，我为人人

我更擅长发现问题

**Comment by xvzhenduo** [comment]
我是win11 22H2 25151.1010 没有问题

**Comment by Richasy** [comment]
无法复现该问题
