### ISSUE TITLE
[Bug] 弹幕卡顿

### ISSUE THREAD

**Issue by bellongyan** [Richasy/Bili.Uwp#1314]
### Bug 描述

在播放视频的时候，弹幕每间隔一段时间会有小卡顿

### 复现问题的步骤

```plain text
1. 打开哔哩
2. 点击任一视频
3. 打开弹幕播放
4. 等待一会并持续观察弹幕，发现有卡顿现象
```

### 预期行为

弹幕连续不卡顿

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [x] 其它 (需注明)

### 其它系统版本

Windows 10 21H2 (Build 19044)

### 运行设备

桌面/平板或笔记本

### 备注

可能是我自己电脑的原因，我目前只有这一台笔记本，不知道其他电脑是否有这种情况

**Comment by MINIPuffer** [comment]
我也有同样的问题，并且不止是弹幕，还要评论滚动和视频列表滚动都会卡顿

**Comment by meng-luo** [comment]
有时候视频也会向前回弹2秒左右，弹幕有时候会停顿

**Comment by JIDAOPENG** [comment]
我也有同样的问题
