### ISSUE TITLE
[Bug] 服务器时间是不是出错了？

### ISSUE THREAD

**Issue by wenhairu** [Richasy/Bili.Uwp#1319]
### Bug 描述

新视频打不开，提示7小时后

### 复现问题的步骤

```plain text
都是
```

### 预期行为

打开

### 应用来源

- [ ] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
具体的复现步骤，以及有截图之类的吗

**Comment by wenhairu** [comment]
这个显示确实是几小时后，但是播放不了不是这个原因。而是我在网页看完了，然后在软件打开这个视频的时候就自动跳转了，并没有等待5s

![7DBAX.png](https://img.wenhairu.com/images/2022/07/06/7DBAX.png)

**Comment by wenhairu** [comment]
> 具体的复现步骤，以及有截图之类的吗

提交点错了……😂
