### ISSUE TITLE
[Bug] 原生播放模式调节音量失效

### ISSUE THREAD

**Issue by NalCol** [Richasy/Bili.Uwp#1326]
### Bug 描述

FFmpeg模式现在Bug挺多的没法用
切回原生模式音量滑条调到任何位置都是一个音量
PS:哔哩自从六月更新后Bug数量激增（？

### 复现问题的步骤

1. 打开Bili.Uwp
2. 进入设置将播放模式选择为“原生”
3. 解码器偏好任意选择
4. 进入任意视频
5. 调节音量查看是否生效

### 预期行为

音量调节正常工作

### 截图

<video src="https://user-images.githubusercontent.com/58576200/177905939-dbae5423-a0a2-4d14-8cd0-bb9809ca3177.mp4">
</video>

### 应用来源

- [X] Github

### 系统版本

- [X] Windows 11 21H2 (Build 22000)

### 运行设备

桌面/台式机

**Comment by Richasy** [comment]
该问题应该已经修复，下次更新会发出
