### ISSUE TITLE
[Bug]几个BUG

### ISSUE THREAD

**Issue by Degate** [Richasy/Bili.Uwp#133]
## Bug 描述
/1--------------------------------------------------------
·视频控件中对于弹幕的设置更改会在重启应用后恢复，例如关掉弹幕加粗选项后重启哔哩，重启后弹幕加粗选项会是开启状态
![微信截图_20210919132518](https://user-images.githubusercontent.com/19262167/133924389-d2fb4927-b48a-4e5f-8e93-9334344e9b9a.png)

/2--------------------------------------------------------
在软件冷启动后开启的第一个视频内容时，会有较长时间的等候才会开始播放视频，关闭该视频后再点开其他视频则是很快就开始播放

/3--------------------------------------------------------
所有瀑布流页面鼠标滚轮无法滚动页面，评论列表和关联视频列表可以正常滚动，另外在番剧中，整个页面不能响应滚轮纵向滚动，但是分栏中却可以响应横向滚动，另外在电影详情弹出面板中，演员表无法响应滚轮滚动
![微信截图_20210919142701](https://user-images.githubusercontent.com/19262167/133924548-99ed7ebd-ac81-4864-aed6-5a1d5c9ae430.png)
![微信截图_20210919142834](https://user-images.githubusercontent.com/19262167/133924554-8bcd5529-bf15-433a-8d43-86012254f430.png)

/4--------------------------------------------------------
在直播聊天互动面板中，进入直播间后默认是始终向上滚动聊天列表的，但是当鼠标在面板上方进行滚轮滚动定位信息后，即使把列表拉至最下方，列表仍然不会再进入自动滚动状态，新的聊天信息将只会向屏幕下延伸。
![微信截图_20210919144946](https://user-images.githubusercontent.com/19262167/133924672-9747fd54-9f67-4733-b794-45d2174acd6d.png)

/5--------------------------------------------------------
应用在使用一段时间后，会出现沉积现象，点选操作会短时间卡住，程序会在音量合成器中占用多个程序位置（音量合成器中的问题在上个版本中也存在），个人感觉可以在左上角返回按钮中加入对播放相关的资源清理相关代码

## 预期的行为

无，

## 环境

版本	Windows 10 专业版
版本号	21H1
安装日期	‎2020/‎07/‎08
操作系统内部版本	19043.1237
体验	Windows Feature Experience Pack 120.2212.3530.0

应用来源：

- [ ] Microsoft Store
- [X] Github
- [ ] 其他来源（请注明来源）

应用版本：UI焕新一版

运行设备：

- [X] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 备注

一下是功能上的建议，我挑选了几个自认为比较基础的但是目前没有的或者比较影响操作流程的流畅度的写一写，体验下策划的感觉/doge

1. 视频控件问题；高度略高、弹幕设置过于简化、没有字幕支持还有一个相对严重影响体验的问题就是控件自动隐藏太慢了，建议失去鼠标悬停焦点立即隐藏；

2. 弹出独立面板显示楼中楼；这个个人感觉很喜欢，比起上个版本中夹层底部添加关闭夹层的手法好用太多，但是独立面板以外区域目前是没有任何反应的，建议把这些区域设置为单击退出楼中楼面板；
![微信截图_20210919134402](https://user-images.githubusercontent.com/19262167/133925695-56d91e18-f2eb-4f01-b296-4e5ad1545645.png)

3. 长文本消息的简化与展开；两个体验不好的地方，一是按钮太小了，很容易被忽略，建议把三个点改成“展开”二字，二是这个地方使用了弹出独立窗口的设计不是很合理，评论中出现及其长篇大论的很少，跟随按钮弹出的面板会改变视线焦点，比较影响阅读体验，建议仍使用展开式，并且展开后该消息底部展开按钮变成收缩按钮；
![微信截图_20210919134611](https://user-images.githubusercontent.com/19262167/133925851-0b843923-69c7-4126-b3a6-8fa7c1d40f6a.png)

4.视频鼠标手势的支持；左侧上下调节亮度，右侧上下调节音量，横向滑动调节视频进度；

5.消息回复；调用楼中楼的面板来处理这个感觉更好些，点击后弹出对话历史和发送回复框，网页版我试过，B站有返回定位对话的信息参数另外如果在瀑布流卡片下方加上对话发生地就更加完美，如“于视频/专栏/投稿·······（标题）·”
![微信截图_20210919142032](https://user-images.githubusercontent.com/19262167/133926117-09889eb9-924d-46aa-98b9-59237b869aa5.png)

6.全局鼠标侧键的响应；上个版本养成的习惯，确实很好用，希望可以侧键做到在任何页面通过连续单击最终退至主页。

7.在播放页中，分享按钮附近添加稍后再看按钮，有时候看视频看到一半就要去做别的事了或者视频太长，安排到晚上再看，再有时间回来打开应用就会出现在历史记录里捞针的尴尬状况；

8.稍后再看页面中，添加删除已观看完成视频的按钮

##最后的最后！感谢！YES！

**Comment by Richasy** [comment]
提的问题过多，这样很难去逐个追踪，且标题也不具有辨识性，请尝试将其分割为几个Issue，一个Issue只描述一个问题

**Comment by Degate** [comment]
> 提的问题过多，这样很难去逐个追踪，且标题也不具有辨识性，请尝试将其分割为几个Issue，一个Issue只描述一个问题

已拆分，并且把有人提过的省略了，这个issue删了
