### ISSUE TITLE
[Bug] 视频播放信息请求失败，在发送请求时出现了异常

### ISSUE THREAD

**Issue by TexBlock** [Richasy/Bili.Uwp#1332]
### Bug 描述

启动后观看几个视频之后会产生此现象

### 复现问题的步骤

```plain text
1.打开应用
2.观看视频（数量不固定）
3.出现此错误
```

### 预期行为

应正常播放

### 截图

![Snipaste_2022-07-09_14-53-28](https://user-images.githubusercontent.com/65154269/178095366-91cab7fd-e480-4943-b0ad-d3931a58b844.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2022-07-09.log](https://github.com/Richasy/Bili.Uwp/files/9076027/applog.2022-07-09.log)

**Comment by Richasy** [comment]
刷新一下是否还有这个问题？

**Comment by TexBlock** [comment]
> 刷新一下是否还有这个问题？

最近倒是没这个问题了
