### ISSUE TITLE
外观

### ISSUE THREAD

**Issue by TYOPXN360** [Richasy/Bili.Uwp#1334]
### 问题描述

1.进度条的那个框框太大了，太挡视频了
2.当软件最大窗口化时，视频两边的黑边太影响美观了。

### 描述解决方案

1.将发弹幕的那个功能从进度条的那个框中分开，将发弹幕功能（以及弹幕设置按钮）移至视频外
2.将视频两边的黑边去除，变为软件背景。

### 附加信息

一点小小的建议，求求dalao能实现一下qwq

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
1. 控制器会隐藏且背景色半透明，不至于挡视频很久
2. 渲染视频跟渲染应用是两码事，黑边是必要的元素遮蔽，没有这层黑色背景，视频渲染会卡到飞起
