### ISSUE TITLE
[Feature] 我的标题

### ISSUE THREAD

**Issue by socrating** [Richasy/Bili.Uwp#1343]
### 问题描述

希望在主页面直接有我的收藏这个选项，平常打开看一些免费的网课能方便一些，当然只是建议，作者大大觉得麻烦的话不用加，哔哩真的超好用，希望云之幻大佬工作顺利！！！

### 描述解决方案

在主界面添加我的收藏选项

**Comment by Richasy** [comment]
你可以把你要看的网课（如果是视频的话）固定在首页，固定按钮在播放页有
