### ISSUE TITLE
[Bug] 繁體文本完全錯亂

### ISSUE THREAD

**Issue by AkazaRenn** [Richasy/Bili.Uwp#1358]
### Bug 描述

之前一直都好好的，文本沒有問題。今天好像是看了別的視頻之後點開了[這個視頻](https://www.bilibili.com/video/BV1XT411J7NM)，app 直接崩潰了。再啓動之後就變成這樣，連開始菜單裡的 app name 也變成「軟體主題」了。卸載重裝也沒有用。
但是如果把切成簡體中文就是正常的文本。日誌中沒有有用的信息。

### 复现问题的步骤

```plain text
不確定這樣能否復現，總之按照截圖 3 設置 Windows 11 的語言列表，然後安裝應用。如果沒有出現的話，可以嘗試把簡體中文拉到繁體中文上面，關閉應用重開，再重新拉到圖中的順序再重開試試。
```

### 预期行为

文本正常顯示

### 截图

![screenshot_2022-07-17_21-20-14](https://user-images.githubusercontent.com/8340896/179433229-4c1847dd-445d-416e-9d70-c5d77e860820.png)
![image](https://user-images.githubusercontent.com/8340896/179433375-355bb883-1c6a-405e-b167-93aea2a28a5a.png)
![image](https://user-images.githubusercontent.com/8340896/179433492-b550d622-6da1-46f6-9155-f0d893be1328.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

**Comment by 008exe** [comment]
XBOX版本相同问题+1

**Comment by AkazaRenn** [comment]
更新了新版本發現文本正常了，不清楚怎麼回事，我先把 issue 關了吧。等再發生我再開。
