### ISSUE TITLE
[Bug]刷新失败

### ISSUE THREAD

**Issue by CruelCold** [Richasy/Bili.Uwp#136]
## Bug 描述
点击刷新时一直转圈加载

## 复现步骤
在视频播放页面停留一段时间后，返回首页刷新

## 环境

应用来源：

- [ ] Microsoft Store
- [ ] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 11 (22000)

运行设备：

- [ ] 桌面/台式机

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录
[applog.2021-09-19.log](https://github.com/Richasy/Bili.Uwp/files/7192188/applog.2021-09-19.log)

**Comment by Richasy** [comment]
请使用新版本查看是否会出现这个问题

**Comment by CruelCold** [comment]
> 请使用新版本查看是否会出现这个问题

更新之后问题依然存在
