### ISSUE TITLE
[Bug] 弹幕显示区域问题

### ISSUE THREAD

**Issue by 6banlaobanzhang** [Richasy/Bili.Uwp#1367]
## 问题发现
某天我随机打开了一个视频
因为习惯问题，我将弹幕显示区域**设置为0.25**（不挡着 比较舒服）
然后发现**居中的弹幕**并没有按照0.25的显示区域显示
如图所示：
![image](https://user-images.githubusercontent.com/83630926/179925665-a229fea4-ce3a-4bc5-9ec2-548d39d7205e.png)
（PS：不存在调整后的弹幕滞留）

### 复现问题的步骤

```plain text
1. 随便开一个视频……
2. 然后把弹幕显示区域调整至0.25
即可见居中弹幕并没有调整为0.25显示区域
```

### 预期行为

把 Bug 修好

### 截图

![image](https://user-images.githubusercontent.com/83630926/179925994-64f21ae5-adb8-4514-a4ab-0d516cb4537d.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [x] 其它 (需注明)

### 其它系统版本

Windows 11 企业版 Insider Preview 22H2 25158.1000 

### 运行设备

桌面/台式机

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
区域限制仅针对滚动弹幕，所以这是预期的行为
