### ISSUE TITLE
播放黑屏，只有声音和弹幕

### ISSUE THREAD

**Issue by Passerby1011** [Richasy/Bili.Uwp#1372]
### Bug 描述

之前版本是使用独显播放黑屏，最新版无论是使用独显还是集显都黑屏，（使用的是nvidia控制面板中切换使用的显卡）只有声音没有画面，将播放器类型切换到ffmpeg，则显示不支持该源
电脑是笔记本gtx1660ti i5-9300h 不支持独显直连

### 复现问题的步骤

```plain text
打开应用
随意点击视频播放
```

### 预期行为

修复

### 截图

![image](https://user-images.githubusercontent.com/63802758/180171216-b8dbed8e-fd07-4dd1-88d4-f89dabec6025.png)
![image](https://user-images.githubusercontent.com/63802758/180170889-a560d16a-ff8d-4432-a313-21854dad2a00.png)

### 应用来源

- [x] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 日志记录

[applog.2022-07-21.log](https://github.com/Richasy/Bili.Uwp/files/9157750/applog.2022-07-21.log)

**Comment by Richasy** [comment]
哔哩 所使用的播放组件可能不适用于你的设备，如果尝试切换首选编码也无效，那么请使用网页看B站
