### ISSUE TITLE
关于哔哩最新版本的画质对比度不足问题

### ISSUE THREAD

**Issue by XiaoNNNNNNNN** [Richasy/Bili.Uwp#1385]
### Bug 描述

在观看同一视频的时候，我发现哔哩播放界面的视频的对比度没有网页端的高。不知道算不算哔哩的bug还是UWP的bug，因为之前在官方的UWP上看视频也发现视频对比度不足的问题。在此反馈

### 复现问题的步骤

```plain text
正藏播放界面时画面出现的问题
```

### 预期行为

尽量跟网页端相同

### 截图

![(9{{GU_7{)NEI}{6B}PAP%2](https://user-images.githubusercontent.com/96342243/180588555-148f1988-3030-4adf-97f3-8170a59879ee.png)

播放界面。左边是网页端，右边是哔哩。

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2022-07-23.log](https://github.com/Richasy/Bili.Uwp/files/9173002/applog.2022-07-23.log)

### 备注

无

### 人人为我，我为人人

我更擅长发现问题

**Comment by AkazaRenn** [comment]
試試用 ffmpeg，然後換換解碼器？

**Comment by XiaoNNNNNNNN** [comment]
![image](https://user-images.githubusercontent.com/96342243/180690540-4f6ff96e-e30c-4382-9c10-eeaf7fbaee8c.png)

**Comment by XiaoNNNNNNNN** [comment]
这样嘛？

**Comment by XiaoNNNNNNNN** [comment]
![image](https://user-images.githubusercontent.com/96342243/180691867-fafebf1b-ee8d-4269-be68-8d305ec54956.png)

感觉还是不够

**Comment by Richasy** [comment]
这个跟底层的解析器有关，已经不是哔哩能修复的范畴了
