### ISSUE TITLE
[Bug]滚动鼠标滚轮无效

### ISSUE THREAD

**Issue by Flashkong** [Richasy/Bili.Uwp#139]
## Bug 描述
各种视频列表界面，无法滚动鼠标滚轮

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）
- [ 在新版本中出现] 

重现问题的步骤：

1. 打开应用
2. 推荐界面就无法滚动滚轮上下翻页，只能滑动右侧的导航栏

应用来源：
- [] Github

应用版本：{应用版本}最新版本

系统版本：

windows10 20H2

运行设备：

- 笔记本

**Comment by Richasy** [comment]
这个问题应该已经被修复了，可以在release里下载最新版本查看
