### ISSUE TITLE
[Bug] 音画不同步

### ISSUE THREAD

**Issue by huoyan1231** [Richasy/Bili.Uwp#1397]
### Bug 描述

播放特定视频时音画不同步
网页端正常

### 复现问题的步骤

```plain text
打开程序
播放https://www.bilibili.com/video/BV1x3411F7pj
```

### 预期行为

正常播放

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2022-07-25.log](https://github.com/Richasy/Bili.Uwp/files/9177899/applog.2022-07-25.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
声音太混乱，我听不太出来。但特定于某个视频的bug不在修复范围内
