### ISSUE TITLE
[Feature] 可更换字体需求

### ISSUE THREAD

**Issue by ottocsb** [Richasy/Bili.Uwp#1399]
### 问题描述

个人系统使用macType渲染字体，无法渲染bili进程，和系统的字体不一致，导致显示效果不佳
贴张图，和系统的文件夹对比
![image](https://user-images.githubusercontent.com/83228451/180934323-73599c76-ff3d-4821-8cf3-5428596fd0ed.png)

### 描述解决方案

或许放开更换字体的功能？

**Comment by AkazaRenn** [comment]
> 上个正式发布的版本开始就已经集成了 dw 补丁了，但是 UWP 的启动方式十分怪异，目前都没有搞明白到底是怎么启动的，所以 UWP 程序并不能保证总是能渲染成功的。

https://github.com/snowie2000/mactype/issues/818#issuecomment-949223936

**Comment by Richasy** [comment]
MacType 并不在考虑范围内，更换字体也是
