### ISSUE TITLE
[Bug] 默认模式视频点进去看不到视频窗口

### ISSUE THREAD

**Issue by spirytuslove** [Richasy/Bili.Uwp#1400]
### Bug 描述

默认模式视频点进去看不到视频窗口只能看到标题 最大化才能看到视频窗口

### 复现问题的步骤

```plain text
打开应用默认模式点开任意视频看不到视频只能听到视频声音
```

### 预期行为

默认模式点进去可以正常看视频

### 截图

![屏幕截图 2022-07-26 173119](https://user-images.githubusercontent.com/64483414/180974927-95206036-8ae6-4e3c-9f31-b743208fc342.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

Windows 10 20H2 19044.1826

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-07-26.log](https://github.com/Richasy/Bili.Uwp/files/9188544/applog.2022-07-26.log)

**Comment by Richasy** [comment]
你的窗口太小了……建议把默认播放模式改为全窗口
