### ISSUE TITLE
[Bug]win11全屏视频四边出现白角

### ISSUE THREAD

**Issue by 850710247liu** [Richasy/Bili.Uwp#141]
## Bug 描述

在win11系统中全屏视频四边出现白角

## 复现步骤

重现问题的步骤：

1. 打开应用
2. 观看 视频
3. 点击 全屏
4. 发现问题

## 截图
注意下面截图中的4个边缘，我的屏幕是方的，而最四边是圆的，所以在圆和方之间出现了白底

![image](https://user-images.githubusercontent.com/59795360/133933585-ba2e6207-2840-4fdf-8b1f-422cd99641d5.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x ] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- x平板
- [ ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by Richasy** [comment]
请更新至新版本

**Comment by Alex-syz** [comment]
此问题在最新发布的重构版本中再次复现，目前我的两台设备都有，哔哩Preview 2.2206.3.0，均为win11 22H2
