### ISSUE TITLE
[Bug] 视频播放闪退

### ISSUE THREAD

**Issue by lxdklp** [Richasy/Bili.Uwp#1410]
### Bug 描述

在播放视频时会出现闪退现象

### 复现问题的步骤

```plain text
1打开应用
2打开视频
3闪退
详细看下面的视频链接
```

### 预期行为

不再闪退

### 截图

视频链接：https://lxdklp.lanzoul.com/iip1q08kbrna

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[Uploading applog.2022-07-28.log…]()

### 备注

不只是打开上次播放的视频会闪退

**Comment by XPRAMT** [comment]
用ffmpeg硬解很容易閃退，但4K 120fps視頻不用ffmpeg很難正常播放
