### ISSUE TITLE
最新版本点开新视频时总是从中间某个位置开始播放或者是直接播放结束了

### ISSUE THREAD

**Issue by mirrordg** [Richasy/Bili.Uwp#1411]
### Bug 描述

每次点开新视频要么就是播放完成要么就是从中间某个位置开始播放,就像是接着别人没看完的继续看是的,昨天刚刚安装上此软件时还没有这个问题,用了一段时间就开始这样了,而且是每次都如此

### 复现问题的步骤

```plain text
直接推荐页打开视频或者分集播放时都会遇到
```

### 预期行为

希望每次点开都是新视频,

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-07-29.log](https://github.com/Richasy/Bili.Uwp/files/9215748/applog.2022-07-29.log)

### 备注

无

**Comment by Richasy** [comment]
该问题会在8月更新中修复
