### ISSUE TITLE
分集视频不能正常连续播放

### ISSUE THREAD

**Issue by mirrordg** [Richasy/Bili.Uwp#1412]
### Bug 描述

设置当中开启了连续播放,自动播放关联视频为关闭状态,在观看分集视频时无法连续播放

### 复现问题的步骤

```plain text
每次都会发生
```

### 预期行为

可以正常连播

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 日志记录

[applog.2022-07-29.log](https://github.com/Richasy/Bili.Uwp/files/9215766/applog.2022-07-29.log)
[applog.2022-07-28.log](https://github.com/Richasy/Bili.Uwp/files/9215767/applog.2022-07-28.log)

### 备注

无

**Comment by AkazaRenn** [comment]
https://github.com/Richasy/Bili.Uwp/issues/1411 是這個問題嗎？我遇到的是這個

**Comment by mirrordg** [comment]
> #1411 是這個問題嗎？我遇到的是這個

这是两个问题,都出现了
