### ISSUE TITLE
[Bug] 专栏无法看

### ISSUE THREAD

**Issue by 454342265** [Richasy/Bili.Uwp#1418]
### Bug 描述

点进专栏会显示刷新，点了刷新但没用

### 复现问题的步骤

```plain text
1.打开应用
2.谁便找一个专栏
3.点进去显示刷新
4.点击刷新按钮后无用
```

### 预期行为

点进专栏正常加载

### 截图

![image](https://user-images.githubusercontent.com/88127352/181896672-8c78fe93-d335-46db-981a-431921dcbb27.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [x] 其它 (需注明)

### 其它系统版本

Windows 11 22H2（Build 25169.1000）

### 运行设备

桌面/台式机

### 日志记录

- [ ] 
[applog.2022-07-30.log](https://github.com/Richasy/Bili.Uwp/files/9225742/applog.2022-07-30.log)

**Comment by Richasy** [comment]
从报错来看是个网络问题，你开网络代理了？

**Comment by 454342265** [comment]
> 从报错来看是个网络问题，你开网络代理了？

没有，设置是显示关闭的

![image](https://user-images.githubusercontent.com/88127352/182024776-938f3bce-c053-4ca2-82c9-d950ec9514b2.png)
![image](https://user-images.githubusercontent.com/88127352/182024798-a3ab1815-568f-438b-87a3-b426fdae6da1.png)
![image](https://user-images.githubusercontent.com/88127352/182024818-19a31715-839c-42e5-a266-92ed9ba34e51.png)
