### ISSUE TITLE
只能全屏使用，不能缩小窗口

### ISSUE THREAD

**Issue by lalala-12138** [Richasy/Bili.Uwp#1422]
### Bug 描述

当缩小窗口的时候，布局会出现问题，无法观看

### 复现问题的步骤

```plain text
打开后缩小窗口
```

### 预期行为

可以缩小窗口观看

### 截图

![image](https://user-images.githubusercontent.com/101035003/181923644-1b15cf41-dcc6-40aa-830b-4cb0171f3666.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

win11 22h2 22621.232

### 运行设备

桌面/平板或笔记本

### 日志记录

无

**Comment by Richasy** [comment]
能放大就放大吧，不然就全窗口或小窗播放。我不是很想考虑各种极端情况
