### ISSUE TITLE
关于稍后再看功能的完善的建议[Feature]

### ISSUE THREAD

**Issue by XianYuDaXian** [Richasy/Bili.Uwp#144]
## 描述你想要解决的问题或者功能的使用场景

稍后再看按钮应布置在左侧导航并且可以列表播放

## 描述解决方案

稍后再看是一个颇为重要的功能，假如每个稿件的右下角可以一键加入稍后再看列表的话就很方便了，现在稍后再看里可以做的只是管理稍后再看列表，点击稿件只是单独开始播放。和平板上的hd app一样。纯属摆设了。希望能加入播放全部并且可以选择顺序或倒序播放，和网页端一样。

## 备注和截图

![Snipaste_2021-09-20_00-30-24](https://user-images.githubusercontent.com/20138259/133935307-f505e6c2-d0ef-4b0c-9634-3595849f006d.png)
![_20212720122742](https://user-images.githubusercontent.com/20138259/133935311-a374b8a6-f1bf-471a-aeed-9ad676741b5d.png)

**Comment by Richasy** [comment]
请右键单击视频卡片，会有加入稍后再看的菜单项弹出。

播放全部的功能可能在以后添加

**Comment by XianYuDaXian** [comment]
> 请右键单击视频卡片，会有加入稍后再看的菜单项弹出。
> 
> 播放全部的功能可能在以后添加

好的，我的意思就是右键加入稍后再看不够方便，和网页一样可以一键加入就好了

**Comment by Degate** [comment]
同想法，不过暂时看不着急，希望将来能考虑。

**Comment by Richasy** [comment]
与 #713 合并处理
