### ISSUE TITLE
[Bug] 播放视频不会从头开始播放

### ISSUE THREAD

**Issue by omoidesu** [Richasy/Bili.Uwp#1442]
### Bug 描述

任意打开一个视频播放后退出换另一个视频，播放进度会从上一个视频的进度继续播放

### 复现问题的步骤

```plain text
1. 点击任意视频
2. 播放一段时间
3. 退出视频
4. 点击另外任意视频
```

### 预期行为

恢复正常

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

Windows 11 22H2 (25174.1010)

### 运行设备

桌面/台式机, 桌面/平板或笔记本

### 备注

不清楚如何实现的，个人猜测有个记录进度的全局变量在退出后没有重置

**Comment by Richasy** [comment]
这个问题已经修复，但Store尚未更新，如果这个问题对你影响较大，可以下载Github的最新release
