### ISSUE TITLE
[Bug] 播放视频几秒后闪退

### ISSUE THREAD

**Issue by Lmzy233** [Richasy/Bili.Uwp#1454]
### Bug 描述

随便打开一个视频，播放几秒到几十秒之后会突然卡住，然后应用就闪退了

### 复现问题的步骤

```plain text
1.打开应用
2.任意打开一个视频并播放
3.播放几秒至几十秒后便出现问题
```

### 预期行为

希望能正常观看视频

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2022-08-13.log](https://github.com/Richasy/Bili.Uwp/files/9331083/applog.2022-08-13.log)

### 备注

我尝试过切换设置中播放器控制里的播放器类型和解码类型，无论是原生还是FFmpeg，无论是强制软解、强制硬解或是自动，均会出现此问题。
我使用的是独显（七彩虹GTX1660SUPER）

### 人人为我，我为人人

我更擅长发现问题

**Comment by panhaovue** [comment]
我也一样，打开视频，过两三秒就自动退出

**Comment by Richasy** [comment]
更新系统到最新的22h2应该可以修复
