### ISSUE TITLE
[Bug] 分区与视频列表重叠

### ISSUE THREAD

**Issue by StringNu11** [Richasy/Bili.Uwp#1463]
### Bug 描述

分区与视频列表重叠

### 复现问题的步骤

```plain text
将哔哩的宽度拖到最窄然后关闭软件，下次打开软件时，分区和视频列表就会重叠
```

### 预期行为

正常显示宽度较小时的布局

### 截图

![飞书20220819-102550](https://user-images.githubusercontent.com/68951745/185529347-f4679072-b498-4f6e-b8a7-fa4b4a1d274b.jpg)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
特定于 Win10 的bug，目前不打算处理
