### ISSUE TITLE
[Bug] 8月更新3，下载代码生成错误

### ISSUE THREAD

**Issue by xiaoji-wu** [Richasy/Bili.Uwp#1466]
### Bug 描述

如题，在此版本中解码器偏好选择除“任意”以外的格式时会出现下载代码生成错误，如：
BBDown -tv -token 307645c167e0dd9d3ba2de63e02e3c81 --encoding-priority av1 -mt --work-dir "E:\IDMDownloader" -ia -p 1 "BV1Ad4y1N7gE"
'av1' was not matched. Did you mean one of the following?
-av1
Unrecognized command or argument 'av1'
Unrecognized command or argument 'BV1Ad4y1N7gE'

### 复现问题的步骤

```plain text
下载选项中解码器偏好选择除“任意”以外的格式时，此bug必现
```

### 预期行为

修复下载代码生成

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
请更新 BBdown 至最新版
