### ISSUE TITLE
[Bug] 软件的视频封面以及账户头像等图片均无法显示，为白屏

### ISSUE THREAD

**Issue by sekurodesu** [Richasy/Bili.Uwp#1467]
### Bug 描述

如题

### 复现问题的步骤

```plain text
1、打开应用
```

### 预期行为

希望图片能够都正常显示

### 截图

![无标题](https://user-images.githubusercontent.com/51750095/185737301-b1810347-c863-4866-8702-47bc376b022d.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2022-08-20.log](https://github.com/Richasy/Bili.Uwp/files/9386555/applog.2022-08-20.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
网络问题，不是bug，请检查网络连接，是否开启了网络代理之类的
