### ISSUE TITLE
关于播放控件的建议

### ISSUE THREAD

**Issue by proximal-deluxemilk** [Richasy/Bili.Uwp#1478]
### 问题描述

最近放视频的时候发现，有些视频会选择将字幕放在底部或者底部画面复杂的时候半透明的播放控制器会和视频画面混在一起，不太好分辨，而且软件中本就有部分区域采用模糊的背景，软件风格不是特别统一

### 描述解决方案

我认为可以选择将播放控制器背景改为模糊，增强视频与控制器的区别同时增强界面的统一性

**Comment by proximal-deluxemilk** [comment]
![image](https://user-images.githubusercontent.com/95557083/186879493-0fbf3cba-48f4-4e38-8368-5b1722d987d1.png)
![image](https://user-images.githubusercontent.com/95557083/186879532-50aad901-7e44-41cc-9d1d-42fdc03aff7c.png)

**Comment by proximal-deluxemilk** [comment]
![image](https://user-images.githubusercontent.com/95557083/186880007-ae6d41b2-5263-4c42-99a1-a010a5424147.png)
![image](https://user-images.githubusercontent.com/95557083/186879998-7b3b40e8-13e7-429a-accb-f2b4dfa8c885.png)

**Comment by DevilHandCC** [comment]
+1

**Comment by Richasy** [comment]
不再将播放器控制条改为亚克力材质，该材质会遮挡字幕，造成功能性问题。比如你的这张图，改成亚克力之后，字幕你就看不见了。这将会引起更多人的反馈
