### ISSUE TITLE
技术预览版2（Bili.Uwp_2.2109.1901.0_x64）点击"设置-启动方式"后应用卡死

### ISSUE THREAD

**Issue by Curious-r** [Richasy/Bili.Uwp#148]
如题，卡死后几秒应用会闪退。
我的系统环境为win11 dev预览版，R5-3600 + RTX2070。
![image](https://user-images.githubusercontent.com/19733878/133937147-3342a475-6078-4bd3-a1d6-780679e51d94.png)

**Comment by Curious-r** [comment]
抱歉，没看到已经有这个issue了。

**Comment by Richasy** [comment]
与 #143 重复，请在那里追踪这个问题，我将关闭这个Issue
