### ISSUE TITLE
[Bug] 点击播放视频闪退

### ISSUE THREAD

**Issue by Oecan** [Richasy/Bili.Uwp#1481]
### Bug 描述

启动后点击上次关闭时正在播放的视频后闪退，再次启动后不点击上次播放的视频弹窗，点击首页视频闪退，第三次打开后不再显示上次关闭时正在播放的视频弹窗后播放视频不再闪退（可复现）

### 复现问题的步骤

```plain text
1.启动后点击上次关闭时正在播放的视频后闪退
2.再次启动后不点击上次关闭时正在播放的视频弹窗，点击首页视频闪退
3。第三次打开后不再显示上次关闭时正在播放的视频弹窗后播放视频不再闪退
```

### 预期行为

点击后可正常播放

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 日志记录

[applog.2022-08-27.log](https://github.com/Richasy/Bili.Uwp/files/9437229/applog.2022-08-27.log)
[applog.2022-08-20.log](https://github.com/Richasy/Bili.Uwp/files/9437230/applog.2022-08-20.log)
[applog.2022-08-21.log](https://github.com/Richasy/Bili.Uwp/files/9437231/applog.2022-08-21.log)
[applog.2022-08-22.log](https://github.com/Richasy/Bili.Uwp/files/9437232/applog.2022-08-22.log)
[applog.2022-08-23.log](https://github.com/Richasy/Bili.Uwp/files/9437233/applog.2022-08-23.log)
[applog.2022-08-24.log](https://github.com/Richasy/Bili.Uwp/files/9437234/applog.2022-08-24.log)
[applog.2022-08-25.log](https://github.com/Richasy/Bili.Uwp/files/9437235/applog.2022-08-25.log)
[applog.2022-08-26.log](https://github.com/Richasy/Bili.Uwp/files/9437236/applog.2022-08-26.log)

**Comment by Richasy** [comment]
问题有多次反馈，暂时关闭该问题，请在issue列表中查看已存在的闪退问题
