### ISSUE TITLE
[install]验证证书后无法安装

### ISSUE THREAD

**Issue by BugTD** [Richasy/Bili.Uwp#1482]
### Bug 描述

安装的是最新Github版本，首先使用mmc安装了压缩包内的证书，然后使用图形化安装程序尝试安装，但安装失败
![tmpFDE2](https://user-images.githubusercontent.com/99173935/187055136-0419c875-2bc4-4257-bb52-bc0e9962f31c.png)
删除后重新使用“安装证书”按钮
![tmpAB3A](https://user-images.githubusercontent.com/99173935/187055150-10d41f2b-7414-4837-9f00-ae8e4b038884.png)
安装证书后使用Powellshell安装install.ps1（开启了开发者模式，并进行了相应的设置）
![tmp32F9](https://user-images.githubusercontent.com/99173935/187055169-d9bb81e2-6c6a-42a8-9b63-e1d513976cf2.png)
但安装失败。
再次尝试图形化界面，还是安装失败
![tmp56D9](https://user-images.githubusercontent.com/99173935/187055217-642e208f-839c-4d9f-9687-fc417d4aa547.png)

### 复现问题的步骤

```plain text
1.进入releases板块
2.安装了最新(8月更新-3)的文件Bili.Uwp_2.2208.3.0_x64.zip
3.解压zip文件
4.尝试用mmc安装证书
5.使用App_2.2208.3.0_x64.msixbundle尝试安装
6.安装失败，提示证书不是信任的，但证书已经安装
7.删除项目文件
8.重复123步骤
9.尝试使用项目帮助文档中的安装证书方式安装证书
10.按照项目帮助文档设置了开发者模式和powellshell
11.尝试使用Powell shell运行install.ps1
12.安装失败，详见BUG描述的图片
13.尝试使用App_2.2208.3.0_x64.msixbundle再次安装，安装失败
14.删除项目文件
15.重复步骤1
16.安装了Source code (zip)文件
17.使用Visual Studio 2022打开了.sin文件
18.打开失败
```

### 预期行为

正常安装

### 截图

![tmp81E2](https://user-images.githubusercontent.com/99173935/187055082-0fe7a9b7-2acc-48f5-8634-805b794aaf67.png)
![tmp9A1F](https://user-images.githubusercontent.com/99173935/187055084-ad431618-a103-42fa-85dc-bc208fbf897b.png)
![tmpA56A](https://user-images.githubusercontent.com/99173935/187055087-415d2ba2-adf5-43b9-ad1a-7cdb702952e6.png)
![tmpF06A](https://user-images.githubusercontent.com/99173935/187055228-ccd35fa2-25f7-46a7-bfbc-4253987e20f3.png)
![tmp6472](https://user-images.githubusercontent.com/99173935/187055241-342826ec-e056-4ac6-8341-1db49a971308.png)
![tmpD118](https://user-images.githubusercontent.com/99173935/187055253-6a5be2a4-cfb6-4dd6-b02d-cf8a10a3a4cb.png)
![tmpEEA3](https://user-images.githubusercontent.com/99173935/187055255-db7bfe66-2469-425e-883c-d25289cfc387.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

无日志

### 备注

无

### 人人为我，我为人人

是的，我希望我的代码出现在哔哩中

**Comment by Richasy** [comment]
你的证书装到哪个文件夹去了？

**Comment by BugTD** [comment]
证书装到受信任的根证书颁发机构

**Comment by Richasy** [comment]
证书更新了，该问题关闭
