### ISSUE TITLE
[Bug] 当电脑使用代理时哔哩无法联网

### ISSUE THREAD

**Issue by meng-luo** [Richasy/Bili.Uwp#1487]
### Bug 描述

电脑开启v2ray自动配置系统代理，哔哩无法加载内容

### 复现问题的步骤

```plain text
开启v2ray自动配置系统代理
```

### 预期行为

能看正常使用

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

Windows11 22H2

### 运行设备

桌面/平板或笔记本

**Comment by AllesUgo** [comment]
关闭代理或者使用fiddler关闭UWP程序的网络隔离，开启代理时默认情况下所有uwp程序都无法联网。

**Comment by XgHao** [comment]
https://blog.csdn.net/ZUFE_ZXh/article/details/85157768
可以参考我的这个文章  这是UWP程序的原因。
较新版本的v2rayN已经继承这个功能了
![image](https://user-images.githubusercontent.com/40883019/191717656-be9c3148-d16d-4437-9d57-a574e6290f51.png)
