### ISSUE TITLE
[Bug] 接受Media_Play_Pause按键

### ISSUE THREAD

**Issue by heqyoufree** [Richasy/Bili.Uwp#1488]
### Bug 描述

如题，Media_Play_Pause（AHK命名）是键盘上附带的播放暂停键

### 复现问题的步骤

```plain text
1. 播放视频
2. 按下按键
3. 没有反应
```

### 预期行为

1.  播放视频
2.  按下按键
3.  切换播放状态

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [x] 其它 (需注明)

### 其它系统版本

Windows 11 22H@ (Build 25193)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
我使用的罗技键盘自带的播放按键可以正常触发播放器的对应功能，这个可能和键盘有关
