### ISSUE TITLE
[Bug] Flv视频流无法正常播放

### ISSUE THREAD

**Issue by Nerders** [Richasy/Bili.Uwp#1491]
### Bug 描述

多次遇到Flv格式的视频直播时播放异常

### 复现问题的步骤

```plain text
1. 打开应用
2. 点击左侧栏目“直播”
3. 随便点击正在直播的节目/进入【王者荣耀】频道点击正在直播的节目
4. 由于目前只发现FLV格式视频出现该问题，可以在搜索框按照截图中的关键字查询，方便精确定位。
```

### 预期行为

期望后续可以支持flv格式的直播，目前正在人工搜索FLV 视频格式拓展尝试解决，但未找到。

### 截图

![image](https://user-images.githubusercontent.com/56071530/189823273-77ffc55b-ab93-484d-85d6-4113de9e3b34.png)
![image](https://user-images.githubusercontent.com/56071530/189823291-2dedde0a-e2ce-472f-a5d5-5eb4f19f03aa.png)

### 应用来源

- [X] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

清除记录后手动复现，但没有相关有用的日志信息，全部信息如下：
2022/09/13 14:08:47.251|Info|Initializing to normal mode (.cctor)|

### 备注

开发者辛苦了👍

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
目前哔哩不提供对flv视频流的支持（主要是懒），flv的直播可以打开网页观看
