### ISSUE TITLE
21H2 今天突然什么视频都没法播放

### ISSUE THREAD

**Issue by H10629728** [Richasy/Bili.Uwp#1494]
### Bug 描述

之前是有的视频打开加载会闪退，但是多次进软件会好，现在是视频播放部分一直黑着，怎么重新打开都打不开

### 复现问题的步骤

```plain text
打开任意一个视频都是黑屏然后出现图片的画面
```

### 预期行为

希望能看

### 截图

![image](https://user-images.githubusercontent.com/36697279/190704230-c2477674-9f6d-4a79-8194-bfbb6cb1aa19.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
无法复现这个问题
