### ISSUE TITLE
能否增加动态磁贴效果

### ISSUE THREAD

**Issue by HZYbest123** [Richasy/Bili.Uwp#1496]
### 问题描述

习惯把常用应用都放在开始菜单里，没有动态磁贴效果的哔哩显得不太美观。

### 描述解决方案

磁贴可显示推荐视频的封面或者你最近观看过的视频

**Comment by Richasy** [comment]
不支持动态磁贴，因为这是一个过时的功能，哔哩主要支持Win11

**Comment by nljxlove** [comment]
这里也挖一下
