### ISSUE TITLE
[Bug] 证书已过期

### ISSUE THREAD

**Issue by Zhangxxl** [Richasy/Bili.Uwp#1497]
### Bug 描述

证书到期日是2022/9/18,截至今天2022/9/19已过期,导致app无法安装

### 复现问题的步骤

```plain text
运行 Add-AppDevPackage.ps1
```

### 预期行为

安装成功

### 截图

<img width="348" alt="image" src="https://user-images.githubusercontent.com/18618523/190947400-fe48994a-193c-4793-ad69-7896f54266ca.png">
<img width="818" alt="image" src="https://user-images.githubusercontent.com/18618523/190947447-fc6792ec-5176-4656-9db0-0876a9a1ab44.png">

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机, 桌面/平板或笔记本

### 日志记录

无

### 人人为我，我为人人

我更擅长发现问题

**Comment by fanceyh** [comment]
同样遇到证书过期的+1

**Comment by DrMagic099** [comment]
目前测试把日期往前调可以解决安装报错……

**Comment by tapppper** [comment]
跳到2020一样不行

**Comment by doncd-p** [comment]
> 跳到2020一样不行
我调到15号就可以了

**Comment by DrMagic099** [comment]
> 跳到2020一样不行

不用调到那么早，调到2022/9/15左右就行了

**Comment by tapppper** [comment]
感谢，调到2022/9/15确实可以成功安装
