### ISSUE TITLE
[Doc] 证书安装了，也无法安装

### ISSUE THREAD

**Issue by magican123** [Richasy/Bili.Uwp#1501]
### 问题描述

我进行安装证书，但是还是无法信任，我看到了证书有效期是到18号，今天是22号，我在想是不是跟证书有关系，我第一次提问问题，请多多包涵

### 预期内容

我觉得没有变化吧，我不是很懂计算机这方面

### 人人为我，我为人人

是的，我希望其他人看到我写的文档

**Comment by Richasy** [comment]
下载最新更新，并安装其中的证书
