### ISSUE TITLE
win11 dev系统下疯狂闪退

### ISSUE THREAD

**Issue by Michaelxia6** [Richasy/Bili.Uwp#1504]
### Bug 描述

经常刚打开软件点进一个视频就会闪退，最近几个软件版本一直都有这个问题

### 复现问题的步骤

```plain text
1.打开应用
2.随便点击一个推荐页视频进入播放页面
3.软件闪退
```

### 预期行为

点开视频不卡顿不闪退

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

Windows 11 22H2 (Build 25206)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
请更新系统到正式版后尝试，并确认自己使用的播放器是原生播放器。在 设置/播放器控制/播放器类型 中可以查看
