### ISSUE TITLE
[21H2] 视频黑屏无法播放

### ISSUE THREAD

**Issue by jeagerkira** [Richasy/Bili.Uwp#1506]
### Bug 描述

  可正常获取视频预览图片，但点击视频时出现黑屏无法播放**的情况。无声音、进度条不显示时间进度
  但可以正常观看直播

### 复现问题的步骤

```plain text
1.打开应用
2.点击一个视频
3.黑屏无法播放
```

### 预期行为

修复播放问题

### 截图

![屏幕截图 2022-09-24 220043](https://user-images.githubusercontent.com/114297831/192102595-81da85cb-bf46-414c-92a7-0b0144136ebd.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

**Comment by Richasy** [comment]
出现这个状态表示应用正常尝试获取数据流，这是一种网络请求，长时间卡在这里请检查网络情况，或者更换一个网络尝试
