### ISSUE TITLE
这软件挺喜欢的，但是能做个弹出画面功能吗

### ISSUE THREAD

**Issue by Myra009** [Richasy/Bili.Uwp#1509]
### 问题描述

这软件挺喜欢的，但是能做个弹出画面功能吗，就像是网页端那样，可以一边看这个视频，一边浏览推荐页里的其他内容

### 描述解决方案

可以一边看这个视频，一边浏览推荐页里的其他内容

**Comment by Richasy** [comment]
暂时无此计划，这与应用设计思路不符，我不太推荐这种“分心”的浏览方式
