### ISSUE TITLE
建议播放时禁用锁屏

### ISSUE THREAD

**Issue by spygg** [Richasy/Bili.Uwp#1510]
### 问题描述

当软件正在播放时可能会遇到屏保超时而锁屏

### 描述解决方案

只会用C++不了解uwp 
VC中的AIP (未做测试)
1. 禁用休眠::SetThreadExecutionState( ES_CONTINUOUS | ES_SYSTEM_REQUIRED | ES_DISPLAY_REQUIRED );
2. 恢复休眠::SetThreadExecutionState( ES_CONTINUOUS );
3. 去掉屏保 ::SystemParametersInfo(SPI_SETSCREENSAVEACTIVE, false, 0, 0); 
4. 恢复屏保::SystemParametersInfo( SPI_SETSCREENSAVEACTIVE, true, 0, 0 );

[xp、win7下如何取消屏保、取消电源管理](https://www.cnblogs.com/cswuyg/archive/2011/12/11/2284023.html)

找到一个uwp的解决方法
[How to prevent screen locks in your UWP apps](https://blogs.windows.com/windowsdeveloper/2016/05/24/how-to-prevent-screen-locks-in-your-uwp-apps)
看大佬能否合并到代码中去

### 备选方案

有修改注册表法,模拟按键法,不过都不是很优雅

**Comment by Richasy** [comment]
我不确定你碰到的是什么情况。但是bili就播放时已经通过 DisplayRequest 进行了处理。如果你的设备在播放时依然锁屏，请检查是否安装了什么第三方的锁屏软件或者其它系统层面的原因
