### ISSUE TITLE
全局播放速率·没有设置的地方

### ISSUE THREAD

**Issue by RichardZhang4** [Richasy/Bili.Uwp#1512]
### 问题描述

![image](https://user-images.githubusercontent.com/57562388/194066399-44ed9ccf-21cc-427b-bcb1-10951757d7c1.png)
希望这里能设置全局速率

### 描述解决方案

以前的版本没发现这个功能，可能是只有打开视频，选择速率，跳转选择另一个时有效？
不是我以为的所有视频都一个速度不用重新设置

**Comment by Richasy** [comment]
开启全局播放速率后，在任意视频播放时设置的播放速率对其他视频均有效，不必再额外设置一个播放速率
