### ISSUE TITLE
[Bug] SurfaceGo2播放直播失败，且无任何错误提示

### ISSUE THREAD

**Issue by TwooSix** [Richasy/Bili.Uwp#1513]
### Bug 描述

SurfaceGo2播放直播失败，且无任何错误提示，非flv直播流，如果是flv直播流会有不支持的提示，但不少直播间能在我台式机上正常通过哔哩观看，但无一能在我的surface上播

### 复现问题的步骤

```plain text
1.打开应用
2.从左侧侧边栏进入直播
3.进入任意一个直播间
```

### 预期行为

能正常观看直播

### 截图

![image](https://user-images.githubusercontent.com/62167519/194681435-715ccc7e-4a71-415c-96fb-e0351b22e25f.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows11 22H2

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-10-08.log](https://github.com/Richasy/Bili.Uwp/files/9738156/applog.2022-10-08.log)

**Comment by Richasy** [comment]
这个看上去是解码器有问题，你是否正常从商店下载安装了 Wiki 中所提及的视频解码器？

**Comment by TwooSix** [comment]
> 这个看上去是解码器有问题，你是否正常从商店下载安装了 Wiki 中所提及的视频解码器？

是的，wiki中提及的MPEG-2和VP9扩展，包括额外的HEVC和AV1扩展都是在商店正常下载的，设置中勾选的是 原生+H.264。视频都可以正常播放，但直播不行。

**Comment by zeroskyee** [comment]
不知道你有没有解决 我也是这个问题，在检查了文档里的wlan设置和自己设置的代理之后就解决了

**Comment by TwooSix** [comment]
> 不知道你有没有解决 我也是这个问题，在检查了文档里的wlan设置和自己设置的代理之后就解决了

感谢！已解决，确实是WLAN设置问题，在设置中打开允许手法的WLAN应用就可以了
