### ISSUE TITLE
[Bug] 无法安装新的版本

### ISSUE THREAD

**Issue by LollipopOuO** [Richasy/Bili.Uwp#1520]
### Bug 描述

即使安装了随安装包一起的安全证书，也无法安装

### 复现问题的步骤

```plain text
安装证书
选择为本地计算机
受信任的发布者
安装成功
打开安装包文件
显示如下
    无法验证此应用包的发布者证书。请与系统管理员或应用开发人员联系，以获取具有验证证书的新应用包。必须验证应用包中签名的根证书和所有直接证书(0x800B010A)
```

### 预期行为

怎么办啊

### 截图

![QQ截图20221010133858](https://user-images.githubusercontent.com/55724948/194804402-f3fca1f6-fb29-4f1a-81e9-8e09054e8414.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 Build 25217.1000

**Comment by Richasy** [comment]
安装证书到“受信任的发布者”并不能满足侧加载的需求，建议直接解压后通过右键install.ps1，使用Windows PowerShell运行该脚本进行安装
