### ISSUE TITLE
[Feature] 本地功能是否支持

### ISSUE THREAD

**Issue by wqcblog** [Richasy/Bili.Uwp#1523]
### 问题描述

Bili是一款UWP应用，播放类似Windows10的电影电视，Windows11的Media Player，请问是否支持一定的播放本地视频或者网络URL的功能？

### 描述解决方案

无

**Comment by Richasy** [comment]
为啥要支持这个？播放本地视频或者URL找MediaPlayer或者VLC呀，这个软件只用来看看B站视频就好
