### ISSUE TITLE
[Bug] 部分文字不显示

### ISSUE THREAD

**Issue by CreamPig233** [Richasy/Bili.Uwp#1525]
### Bug 描述

部分文字不显示 详见下面步骤描述

### 复现问题的步骤

```plain text
打开应用
点击视频
鼠标悬浮于视频使状态栏出现
点击倒数第二个齿轮
仅第三行“截图”显示，上面两行文字不显示
全屏再退出后问题消失
```

### 预期行为

文字正常显示

### 截图

![image](https://user-images.githubusercontent.com/39437424/195321769-47e4fc3b-ce78-4007-bf0a-898b08120aa1.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows 10 IoT 企业版 LTSC  21H2  19044.1889

### 运行设备

桌面/平板或笔记本

### 日志记录

无日志文件生成

**Comment by bmjlgenhao2** [comment]
看到这个issue和我遇到的性质差不多，就先在这里补一个了
### 复现方法
打开哔哩后首页视频随便选一个，然后右键；7月版本中有“稍后再看”，“用浏览器打开”两个选项，但10月更新后消失

### 截图
![image](https://user-images.githubusercontent.com/38559772/195483424-78df47c0-0e84-42d2-81c4-30dbe3ae58e4.png)

### 预期行为
同上

### 应用来源
Github Release

### 系统版本
Win10企业版 21H2 19044.2006
