### ISSUE TITLE
如果有4k之类的高于1080画质的视频可以默认显示最高的画质吗

### ISSUE THREAD

**Issue by 1liming2** [Richasy/Bili.Uwp#1526]
### 问题描述

如果有4k之类的高于1080画质的视频，打开视频的时候可以默认显示最高的画质吗

### 描述解决方案

可以打开视频的时候默认显示最高的画质吗，或者添加一个是否最高画质的选项

**Comment by Richasy** [comment]
设置里面有画质选项
