### ISSUE TITLE
[Bug] GitHub版本安装报错;Windows11 dev高频闪退.

### ISSUE THREAD

**Issue by QingyuQingxue** [Richasy/Bili.Uwp#1539]
### Bug 描述

1: 已安装GitHub 10月更新第一版,已开启开发者模式. 此次安装报错提示如下:
找到了捆绑: \Bili.Uwp_2.2210.2.0_x64\App_2.2210.2.0_Test\App_2.2210.2.0_x64.msixbundle
                                                                                                                        正在安装应用程序...                                                                                                     找到依赖项包:                                                                                                           \Bili.Uwp_2.2210.2.0_x64\App_2.2210.2.0_Test\Dependencies\x86\Microsoft.NET.Native.Framework.2.2.appx                                                                                                     \Bili.Uwp_2.2210.2.0_x64\App_2.2210.2.0_Test\Dependencies\x86\Microsoft.NET.Native.Runtime.2.2.appx                                                                                                       \Bili.Uwp_2.2210.2.0_x64\App_2.2210.2.0_Test\Dependencies\x86\Microsoft.VCLibs.x86.14.00.appx                                                                                                             \Bili.Uwp_2.2210.2.0_x64\App_2.2210.2.0_Test\Dependencies\x86\Microsoft.VCLibs.x86.14.00.Desktop.appx                                                                                                     \Bili.Uwp_2.2210.2.0_x64\App_2.2210.2.0_Test\Dependencies\x64\Microsoft.NET.Native.Framework.2.2.appx                                                                                                     \Bili.Uwp_2.2210.2.0_x64\App_2.2210.2.0_Test\Dependencies\x64\Microsoft.NET.Native.Runtime.2.2.appx
\Bili.Uwp_2.2210.2.0_x64\App_2.2210.2.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.appx
\Bili.Uwp_2.2210.2.0_x64\App_2.2210.2.0_Test\Dependencies\x64\Microsoft.VCLibs.x64.14.00.Desktop.appx
Add-AppxPackage : 部署失败，原因是 HRESULT: 0x80073CF9, 无法安装。请联系你的软件供应商。

从  (App_2.2210.2.0_x64.msixbundle)  使用程序包 Richasy.Bili_2.2210.2.0_neutral_~_0d2vm92gxvj9a 中的目标卷 C: 执行的部
署 Add 操作失败，错误为 0x80070490。有关诊断应用部署问题的帮助，请参阅 http://go.microsoft.com/fwlink/?LinkId=235160。

注意: 有关其他信息，请在事件日志中查找 [ActivityId] 71cb92c2-e6a9-0002-7b19-e071a9e6d801，或使用命令行 Get-AppPackageLo
g -ActivityID 71cb92c2-e6a9-0002-7b19-e071a9e6d801

所在位置 \Bili.Uwp_2.2210.2.0_x64\App_2.2210.2.0_Test\Add-AppDevPackage.ps1:522
字符: 13
+             Add-AppxPackage -Path $DeveloperPackagePath.FullName -Dep ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (\D..._x64.msixbundle:String) [Add-AppxPackage], IOException
    + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand

2:Windows11 DEV版本系统闪退较频繁.

### 复现问题的步骤

```plain text
信息如上,如需更多信息可随时联系
```

### 预期行为

可安装成功,无闪退现象.

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 dev preview 25227.1010

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
这种就从商店下载吧，方便省事

**Comment by fxzxmicah** [comment]
其实Github版本安装不需要执行安装脚本，也不需要开启开发者模式，安装证书后直接运行安装包本体即可。
