### ISSUE TITLE
[Feature] 求支持动态磁贴啊。

### ISSUE THREAD

**Issue by nljxlove** [Richasy/Bili.Uwp#1541]
### 问题描述

建议支持动态磁贴推送和推荐，很实用，win10、win11都用得到。

### 描述解决方案

动态磁贴YYDS

**Comment by Richasy** [comment]
磁贴在Win11中已不存在，未来有机会会支持Win11的Dashboard，但是不再考虑已经被砍掉的功能

**Comment by nljxlove** [comment]
ExplorerPatcher能恢复Win10开始菜单，磁贴还是多好用的。
(https://github.com/valinet/ExplorerPatcher)

**Comment by nljxlove** [comment]
挖一下
