### ISSUE TITLE
[Bug] XBOX 上无法找到该应用

### ISSUE THREAD

**Issue by xby020** [Richasy/Bili.Uwp#1555]
### Bug 描述

> 对于 XBOX 用户，请先在桌面设备中登录你的微软账户，并通过上面的方式进入哔哩的商店页面并获取应用，然后你就可以在 XBOX 中登录相同的账户，`并在 "我的应用" 中找到哔哩了`。

已经按照文档在桌面安装并正常打开，请问这个`我的应用`在哪，在我的Xbox上无法找到这个应用，MS Store里的`完整库`或者`应用`这两个标签页里没有这个应用；

### 复现问题的步骤

```plain text
按照文档流程在桌面设备商安装成功，在Xbox上无法找到这个应用
```

### 预期行为

在Xbox上安装应用

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Xbox,桌面设备Win10 21H2

### 运行设备

Xbox

**Comment by 2wchuang** [comment]
试试看把语言切换到简体中文  或者繁体 台湾
