### ISSUE TITLE
[Bug] 综合动态页提醒“ 请求动态失败”

### ISSUE THREAD

**Issue by iceMagi** [Richasy/Bili.Uwp#1557]
### Bug 描述

前几天都是好的，今天点开综合动态页面会提醒“请求动态失败 value was either too large or too small for an int32"
点开视频页没问题

### 复现问题的步骤

```plain text
应用——动态——综合动态——提示失败
```

### 预期行为

能成功看到动态

### 截图

![image](https://user-images.githubusercontent.com/64744343/201059656-5657f7bb-043e-45a7-bc94-1eb5e4c303e0.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-11-10.log](https://github.com/Richasy/Bili.Uwp/files/9979527/applog.2022-11-10.log)

**Comment by Richasy** [comment]
在 #1566 中修复
