### ISSUE TITLE
[Bug] 搜索栏候选内容会遮挡搜狗输入法输入候选

### ISSUE THREAD

**Issue by wulusai2333** [Richasy/Bili.Uwp#1562]
### Bug 描述

1.搜索栏候选内容会遮挡搜狗输入法输入候选
2.搜索候选无法复制,点击搜索后的`搜索 xxx` xxx也是无法复制的,我想应该有候选无法满足需求需要修改候选内容的需求,我想到的办法是输入框保留搜索内容或者标题可复制,或者预选内容时将选择的内容补充到搜索框
版本 preview 2.2210.2.0

### 复现问题的步骤

```plain text
1.搜索栏候选内容会遮挡搜狗输入法输入候选
切换输入法为搜狗输入法,搜索框输入想要的内容,候选提示内容,搜索框补充候选内容,此时输入法被遮挡
微软输入法无此问题
2.搜索候选无法复制
输入部分关键词等待搜索候选补充完整,点击需要的搜索候选内容,尝试复制刚才的候选标题,无法复制
```

### 预期行为

1.搜狗输入法在搜索框输入部分关键词出现候选内容,补充输入关键词,此时输入法候选在`哔哩`上方
2.点击搜索后,搜索标题可复制或在搜索框保留

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

**Comment by Richasy** [comment]
这个不是哔哩的问题，所有UWP都存在，无法在哔哩这边修复，建议使用系统输入法
