### ISSUE TITLE
[Bug] 无法获取动态

### ISSUE THREAD

**Issue by KrisowX** [Richasy/Bili.Uwp#1572]
### Bug 描述

点击动态时，显示：请求动态失败，没有数据返回。

### 复现问题的步骤

```plain text
1.打开应用
2.点击动态
```

### 预期行为

动态正常加载

### 截图

![image](https://user-images.githubusercontent.com/58591281/202361296-a117b7c9-82f5-437a-b4ac-fe5e67cce332.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 22H2(Build 22623)

### 运行设备

桌面/平板或笔记本

**Comment by Genicur** [comment]
+1

**Comment by RichardZhang4** [comment]
+1

**Comment by Koorye** [comment]
+1

**Comment by Richasy** [comment]
#1573 重复问题
