### ISSUE TITLE
[Bug] 动态刷新失败，没有数据返回

### ISSUE THREAD

**Issue by xue-mark** [Richasy/Bili.Uwp#1573]
### Bug 描述

从昨天晚上开始时常出现请求动态失败，多次点击刷新，目前偶有成功获取数据但只有三四次

### 复现问题的步骤

```plain text
1.打开应用，已登录账号
2.推荐栏信息流正常显示，点击右上角刷新重新获取，正常
3.点击动态栏，无论是视频还是综合动态，均显示“请求动态失败”
4.切换视频和综合动态，点击右上角的刷新，仍显示“请求动态失败”
```

### 预期行为

正常显示关注up主的动态信息流

### 截图

![QQ截图20221117131746](https://user-images.githubusercontent.com/23100317/202364954-0dfed463-01b8-4ecb-8c4d-777a9acb0b59.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows 10 21H2(Build 19044)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-11-17.log](https://github.com/Richasy/Bili.Uwp/files/10028336/applog.2022-11-17.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by laoskhei** [comment]
我也一样，昨天更新之后还能用，今天打卡就不行了。

**Comment by Ptilopsis01** [comment]
这边也有同样的问题

**Comment by AlierKitten** [comment]
我用上一个版本刷新几下还能出来，新版本完全不行了，阿B开始限制第三方了？

**Comment by fxzxmicah** [comment]
同样的问题。

> 我用上一个版本刷新几下还能出来，新版本完全不行了，阿B开始限制第三方了？

实际上老版本也刷新不出来了。

**Comment by Shinex1** [comment]
也遇到了一样的问题

**Comment by machinewx** [comment]
我也是，从昨天开始就不行了。

**Comment by 1lin-lcs** [comment]
我现在是是好是坏

**Comment by Samachurl** [comment]
same

**Comment by jianhaolan** [comment]
我的也是，大概率刷新不出来动态

**Comment by dxzm2013gmailcom** [comment]
+1
