### ISSUE TITLE
[Bug] 请求动态失败

### ISSUE THREAD

**Issue by Gloryphoenix** [Richasy/Bili.Uwp#1579]
### Bug 描述

请求动态失败，没有数据返回

### 复现问题的步骤

```plain text
1，打开应用
2，打开动态
3，请求动态失败，没有数据返回
```

### 预期行为

正常请求动态

### 截图

![image](https://user-images.githubusercontent.com/108907376/202832144-6a829ebe-563c-4788-ae24-0a902c11276b.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 22H2 22623.891

### 运行设备

桌面/平板或笔记本

### 日志记录

无日志

### 备注

无

**Comment by Richasy** [comment]
与 #1573 重复
