### ISSUE TITLE
建议直播像推荐那样增加一个刷新功能

### ISSUE THREAD

**Issue by tm0210** [Richasy/Bili.Uwp#158]
有了，刚才发现已经有了，不知道为啥昨天没有

**Comment by Richasy** [comment]
左边有个刷新按钮
![image](https://user-images.githubusercontent.com/27713596/133951229-f31653c9-8b22-4869-a545-8282da032238.png)

**Comment by tm0210** [comment]
> 右边![image](https://user-images.githubusercontent.com/27713596/133951229-f31653c9-8b22-4869-a545-8282da032238.png)

谢谢，刚发现已经有了，不知道为什么昨天没找到刷新按钮。另外，感谢作者开发这个软件
