### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by hukewei2001** [Richasy/Bili.Uwp#1580]
### Bug 描述

win11安装了证书安装还是灰的
![image](https://user-images.githubusercontent.com/71708679/202840867-1c2090b0-3fa2-49f6-8c77-51468019d534.png)

### 复现问题的步骤

```plain text
就是无法安装
```

### 预期行为

安装键是灰的

### 截图

![image](https://user-images.githubusercontent.com/71708679/202840870-81d669d9-206f-4444-a216-8b6e19d30cb2.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by jkqxl** [comment]
同样的问题

**Comment by hukewei2001** [comment]
已解决，用这个连接&nbsp;ms-windows-store://pdp/?productid=9mvn4nslt150 在微软商店可以安装



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月20日(星期天) 中午1:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Richasy/Bili.Uwp] 无法安装 (Issue #1580)





 
同样的问题

**Comment by mailset** [comment]
请安装解压目录的证书，具体看wiki的详细安装教程

**Comment by shundebo** [comment]
先解压出来
在资源管理器地址栏输入powershell回车
输入             .\install.ps1
y
给管理员权限
还是y
等待完成
