### ISSUE TITLE
[Bug] 启动应用后提示：鉴权失败，请联系账号组

### ISSUE THREAD

**Issue by KrisowX** [Richasy/Bili.Uwp#1581]
### Bug 描述

打开应用后提示：鉴权失败，请联系账号组
此时推荐视频没有加载，刷新后可以加载。

### 复现问题的步骤

```plain text
1.打开应用
2.看到提示
```

### 预期行为

正常加载主页推荐内容

### 截图

![image](https://user-images.githubusercontent.com/58591281/202858684-ddd8c649-4b32-4a14-b8f4-c55c474c5037.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 22H2(Build 22623)

### 运行设备

桌面/平板或笔记本

**Comment by jkqxl** [comment]
确实，已经无法更新最新的Up主视频了

**Comment by BlameTwo** [comment]
可能是官方的Appkey更新了吧
