### ISSUE TITLE
[Bug] 鉴权失败，请联系账号组

### ISSUE THREAD

**Issue by sw1313** [Richasy/Bili.Uwp#1583]
### Bug 描述

有概率出现，应该是扫码登入的通用问题，《bililite》扫码登入后也会出现，但是《bililite》可以用手机号和验证码登入，登入之后就是正常的。目前《哔哩》没有手机号验证码直接登入，密码登入框太小无法加载完全验证手机号的验证码点击界面（3个字选顺序的），后面步骤未知。

### 复现问题的步骤

```plain text
推荐界面，刷新几次
```

### 预期行为

加个手机验证码登入或者账号密码登入可用，或者扫码登入不弹错误也行

### 截图

![image](https://user-images.githubusercontent.com/28719204/202973483-09cd4468-920c-4d7c-8949-73365c3e7cb7.png)

### 应用来源

- [X] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 22H2(Build 22621)

### 运行设备

桌面/台式机

### 日志记录

[applog.2022-11-21.log](https://github.com/Richasy/Bili.Uwp/files/10053810/applog.2022-11-21.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by 1lin-lcs** [comment]
我也有这个问题

**Comment by asca0121** [comment]
逍遥橙子的uwp也有这个提示，估计官方又在打击第三方了吧，旧的安卓TV版也只有360p了。

**Comment by Richasy** [comment]
这个问题暂时修不了，源头在阿B那边

**Comment by CrepaRB** [comment]
今天的情人节更新修好了……这么说我还挺幸运的，刚好今天才听说这个客户端，又刚好在更新发布之后才遇到这个bug，直接更新用上去了www
