### ISSUE TITLE
[Bug] 强制踢出设备后导致哔哩瘫痪

### ISSUE THREAD

**Issue by mengguyi** [Richasy/Bili.Uwp#1589]
### Bug 描述

2022/11/26 20:20左右由于我的错误操作踢出了除手机以外的所有设备。这并没什么但我尝试重新登陆时发现哔哩的用户功能瘫痪，无法退出账户

### 复现问题的步骤

```plain text
在手机app上退出所有设备的登录
打开浏览器检查账户登录状态确保已经退出
打开哔哩发现右上角用户头像变成默认头像
点击用户头像之后一直转圈
```

### 预期行为

点击用户头像显示退出登录/未登录

### 截图

https://user-images.githubusercontent.com/73788063/204090625-6935516e-1765-41fc-a480-3adfadc8e371.mp4

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows 10 22H2

### 运行设备

桌面/平板或笔记本

### 日志记录

应用没有日志记录

### 备注

问一下，如何让哔哩在这种情况下退出用户登录

### 人人为我，我为人人

我更擅长发现问题

**Comment by AkazaRenn** [comment]
![screenshot_2022-11-26_11-13-45](https://user-images.githubusercontent.com/8340896/204098241-34f882f2-9c62-4757-b314-d20cbaba2f69.png)
在設置裡重置 app 試試

**Comment by mengguyi** [comment]
ok了，但是这引入了一个新bug

**Comment by mengguyi** [comment]
#1590
