### ISSUE TITLE
[Bug]直播有断流的问题

### ISSUE THREAD

**Issue by qiuyuyang910** [Richasy/Bili.Uwp#159]
## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '直播'
5. 然后会缓冲一次，然后断流，再等你按刷新然后再断流要么就是卡一下然后再恢复

## 预期的行为
可以流畅的播放直播

## 截图

![QQ截图20210920100442](https://user-images.githubusercontent.com/60593418/133951400-6b22d9b0-d36a-4ade-a89c-b5a6b3c558b5.png)
![QQ截图20210920100453](https://user-images.githubusercontent.com/60593418/133951404-52f8ee02-55bd-4d50-9319-d3d069f10c89.png)
## 环境
win10

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}
![QQ截图20210920101108](https://user-images.githubusercontent.com/60593418/133951491-a5668bd9-d4ad-4a8b-963c-3985cfc13fb6.png)
系统
版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [x] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录
|System.Exception: 播放失败: DecodingError |  | System.Exception: 媒体流无法处理更多的示例，因为流中没有更多的示例。 (Exception from HRESULT: 0xC00D3E84)
2021/09/20 09:57:56.762|Error|
系统信息：10.0.19043.1237 | Windows.Desktop | X64
应用信息：2.2109.1901.0 | 中文(简体，中国)

## 备注
还有，问一下为啥以前我哔哩入库了但是我却收不到最新版的推送，只能在github上下？

**Comment by fxzxmicah** [comment]
我的是直播一直在自动换线，几秒换一次几秒换一次，导致卡顿严重，不知道这个是不是bug。

**Comment by fxzxmicah** [comment]
> 我的是直播一直在自动换线，几秒换一次几秒换一次，导致卡顿严重，不知道这个是不是bug。

```
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2021/09/21 09:15:53.291|Error|
系统信息：10.0.19043.1237 | Windows.Desktop | X64
应用信息：2.2109.1901.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001
2021/09/21 09:46:32.959|Info|
系统信息：10.0.19043.1237 | Windows.Desktop | X64
应用信息：2.2109.2001.0 | 中文(简体，中国)
```
不知道这个日志有没有用。反正在我这里直播处于不可用状态。
