### ISSUE TITLE
[Bug]点「设置-启动方式」后闪退

### ISSUE THREAD

**Issue by aggjjfd** [Richasy/Bili.Uwp#160]
## Bug 描述

进入「设置」，点击「启动方式」后，软件闪退

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '设置'
3. 点击 '启动方式'
4. 发现问题

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：2.2109.1901.0

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 10 ver.20H2 (19042)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

[applog.2021-09-20.log](https://github.com/Richasy/Bili.Uwp/files/7193377/applog.2021-09-20.log)

2021/09/20 10:35:58.236|Error|
系统信息：10.0.19042.1052 | Windows.Desktop | X64
应用信息：2.2109.1901.0 | 中文(简体，中国)
--------
|System.NullReferenceException: Object reference not set to an instance of an object.
   at Richasy.ExpanderEx.Uwp.ExpanderExWrapper.CheckVisualState() + 0x20
   at Richasy.ExpanderEx.Uwp.ExpanderExMenuPanel.UpdateInternalWrapperLayout(Size, ExpanderExWrapper) + 0x1cb
   at Richasy.ExpanderEx.Uwp.ExpanderExMenuPanel.MeasureOverride(Size) + 0x467
   at Richasy!<BaseAddress>+0x3ab22ba
   at Richasy!<BaseAddress>+0x3904b10

**Comment by Stapxs** [comment]
#143

**Comment by Richasy** [comment]
问题重复，已关闭
