### ISSUE TITLE
[Bug] 应用播放视频时总是闪退，无法使用（Win 11 21H2，专业版）

### ISSUE THREAD

**Issue by Alexive-17** [Richasy/Bili.Uwp#1603]
### Bug 描述

播放视频总是闪退

### 复现问题的步骤

```plain text
打开应用
播放视频
```

### 预期行为

正常播放

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-11-28.log](https://github.com/Richasy/Bili.Uwp/files/10148319/applog.2022-11-28.log)

### 人人为我，我为人人

None

**Comment by AllesUgo** [comment]
所有视频都这样吗
