### ISSUE TITLE
[Bug] 获取追番列表失败

### ISSUE THREAD

**Issue by DeparturesNeko** [Richasy/Bili.Uwp#1609]
### Bug 描述

已经登陆（右上角有头像），开关代理、全局和非全局都试过，点击“我的追番”后提示“获取追番列表失败 -663”字样，具体影响的有“动漫”和“影视”两栏，视频和专栏不受影响，可以正常打开收藏夹。

### 复现问题的步骤

```plain text
点击“我的追番”后提示“获取追番列表失败 -663”字样
```

### 预期行为

正常显示追番、追剧列表

### 截图

![图片](https://user-images.githubusercontent.com/96569888/205962874-a9ffc55f-c00b-4aa1-a7c5-3756147187e9.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

win 11 22H2 开发者预览版22623.891

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-12-07.log](https://github.com/Richasy/Bili.Uwp/files/10168157/applog.2022-12-07.log)

### 备注

追番列表中含有港澳台番剧

### 人人为我，我为人人

我更擅长发现问题

**Comment by DeparturesNeko** [comment]
日志中同样有“鉴权失败”的记录，那个只需要刷新几次推荐页面就恢复正常了

**Comment by ShellShield** [comment]
我也遇到了，而且隔壁逍遥橙子的uwp也一样，感觉是b站又在打第三方了？

**Comment by lw-tech-soft** [comment]
> 我也遇到了，而且隔壁逍遥橙子的uwp也一样，感觉是b站又在打第三方了？

合理，很有可能
