### ISSUE TITLE
[Feature & Bug] 一些不重要的建议

### ISSUE THREAD

**Issue by Stapxs** [Richasy/Bili.Uwp#161]
## 描述你想要解决的问题或者功能的使用场景
1. 等待 UI 加载完成后开始播放，在设备卡顿的时候会出现 UI 还未加载完成、播放器画面还没有出来但是视频已经开始播放的问题
2. 设置界面，此处一级菜单右侧下拉框不应该和二级菜单一样缩进
![image](https://user-images.githubusercontent.com/42486439/133950983-47c4da94-66e0-45a0-9f11-038d8b9a027b.png)
3. 在 win10 平板模式下会在任务栏显示返回按键，如果可以的话兼容使用返回按键应用内返回（事实上我用过的大部分 UWP APP 都不支持）
4. 加载指示器，既然左边有个边距，右边也加个吧（强迫症行为 x）
![image](https://user-images.githubusercontent.com/42486439/133951212-08865d0e-7731-4b13-8071-64597a389541.png)
![image](https://user-images.githubusercontent.com/42486439/133951218-01a639b4-f68b-4cab-83c8-69a58aa894c0.png)
5. 观看进度恢复，看了一半退出去之后返回恢复观看进度
6. 搜索栏 AV、BV 号直接跳转
7. 右击点赞按钮三连（这是从另一个第三方端遗传过来顺手的功能）在 PC 设备上长按操作不符合直觉

**Comment by Richasy** [comment]
提的问题过多，这样后面有修复也不便于追踪，目前的标题也不具备辨识度，请将其拆分后再提交
