### ISSUE TITLE
[Bug] 无法加载直播、动态

### ISSUE THREAD

**Issue by AllesUgo** [Richasy/Bili.Uwp#1612]
### Bug 描述

无法加载直播、动态

### 复现问题的步骤

```plain text
直接打开即可
```

### 预期行为

正常显示

### 截图

![image](https://user-images.githubusercontent.com/67179426/206214478-e1ed957b-21e6-4835-aeec-243835451b1f.png)

![image](https://user-images.githubusercontent.com/67179426/206214551-acd4b0ce-802b-4f4f-b014-cbc399dac204.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 22H2 (Build 22621)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-12-07.log](https://github.com/Richasy/Bili.Uwp/files/10177233/applog.2022-12-07.log)

### 人人为我，我为人人

None

**Comment by qyxblog** [comment]
+1
