### ISSUE TITLE
[Bug] 打开视频闪退以及弹幕卡住，首页视频加载失败

### ISSUE THREAD

**Issue by BzhChara** [Richasy/Bili.Uwp#1613]
### Bug 描述

1.打开一个视频有可能（概率较大），如果我看见下面那个up的头像显示不出来我就晓得要闪退了，要重复好几次才能正常观看。
2.弹幕是放视频放着放着弹幕闪来闪去卡在那就是不消失，下一波弹幕也不来，必须关掉刷新才好，概率一般般，比上面那个小。上面那个我打开应用百分之八十要寄。
3.打开应用首页的推荐视频无法正常显示，刷新很多遍好了也只显示一点推荐内容。
WIN11 22H2家庭版

### 复现问题的步骤

```plain text
1.打开应用
2.看视频
3.闪退
4.重复打开直至正常
5.弹幕卡住
6.刷新正常
7.观看其他视频，也会闪退和弹幕卡死
```

### 预期行为

预期行为就是解决问题。

### 截图

![~L}NEMXOD{Y0(ZGQ)WYA5CJ](https://user-images.githubusercontent.com/102839345/206468177-7f883b04-0f6c-40e1-9ecb-7a830a00805d.png)
![2(I0N9K0PC)@UIOJU8SBW@1](https://user-images.githubusercontent.com/102839345/206470016-9411d92f-fbaa-4b39-bc57-430441ebe2a2.png)
![QYIO}PL8BPJ)@KYQH3WJFLK](https://user-images.githubusercontent.com/102839345/206470127-945a0d21-22e1-4f9a-b39c-a74413755b9a.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

WIN11 22H2

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by BzhChara** [comment]
弹幕那个不好截图，所以没发图片

**Comment by caoooooooooooooo** [comment]
对对对，我也是
