### ISSUE TITLE
[Bug] B站API变动导致首页信息流和右上角账户登录不稳定

### ISSUE THREAD

**Issue by s10wbro** [Richasy/Bili.Uwp#1615]
### Bug 描述

首页信息流获取不稳定，时不时报错，报错见附图。右上角账户登录也存在问题，会时不时转圈，关闭后重启App恢复正常。
简单搜索后发现其他使用B站API的人也有类似问题。见https://github.com/SocialSisterYi/bilibili-API-collect/issues/533 。里面有提议“检测appkey``appSec与sign的正确性，以及build等环境参数”。

### 复现问题的步骤

```plain text
打开应用即可复现
```

### 预期行为

稳定与接口通信

### 截图

<img width="86" alt="屏幕截图 2022-12-11 114637" src="https://user-images.githubusercontent.com/22630311/206885373-ece083e8-586f-4c34-b920-2ee2ada5bb0e.png">

<img width="1040" alt="屏幕截图 2022-12-11 114729" src="https://user-images.githubusercontent.com/22630311/206885391-88f49717-55ab-41af-ba28-41c8e341a62f.png">

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by JessBobby** [comment]
+1近期多次遇到这样的问题，包括xiaoyaocz的版本，也是出现“鉴权失败”，无法加载等问题

**Comment by Zeq-Liu** [comment]
今天是12月13日，我重启、刷新多次，依旧不能用

**Comment by PRO-2684** [comment]
2022.12.13，可登录，未登录时正常，但是登录后无法正常使用与账号相关功能，比如说推荐和个人信息
![image](https://user-images.githubusercontent.com/54608551/207323528-68e0f9a0-49c1-4822-bd38-c28f0b2cc28f.png)

**Comment by DSWE-4646** [comment]
同样有这问题

**Comment by Hti-0683** [comment]
同样如此，xiaoyaocz版(4.4.8.0)和该App(Preview 2.2211.1.0)都是这样......
![ApplicationFrameHost_QZyfsf0886](https://user-images.githubusercontent.com/66823771/208093275-e4a2a21d-b851-4f66-b3ee-d8ccb115730d.png)
![ApplicationFrameHost_XJmULSyEji](https://user-images.githubusercontent.com/66823771/208094018-74ae2456-3587-4254-833f-9db43c66ff3b.png)
