### ISSUE TITLE
[Bug] 推荐视频加载不出来

### ISSUE THREAD

**Issue by gzengg** [Richasy/Bili.Uwp#1617]
### Bug 描述

主页显示 
**推荐视频请求失败，鉴权失败，请联系账号组**
望修复，谢谢

### 复现问题的步骤

```plain text
1.打开应用
2.出错
```

### 预期行为

可以看见推荐视频

### 截图

![image](https://user-images.githubusercontent.com/95920777/207488759-c0331f2d-971e-4936-98e5-663fffb97496.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by qyxblog** [comment]
+1
