### ISSUE TITLE
[Bug] 打开应用显示“推荐视频请求失败”

### ISSUE THREAD

**Issue by ciao-cao** [Richasy/Bili.Uwp#1619]
### Bug 描述

打开应用后显示“推荐视频请求失败，鉴权失败，请联系帐号组”，然后b站的帐号也无法登录，点击帐号头像就一直转圈。具体应该是在安装最近两次更新后，就常出现

### 复现问题的步骤

```plain text
打开应用就如此，
```

### 预期行为

预期打开应用可以显示推荐视频，也可以正常打开帐号，显示播放记录等

### 截图

![image](https://user-images.githubusercontent.com/22006661/208810103-0bb82300-e5b7-43ee-a111-083c6eb46886.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows 10 21H2 19044.2364

### 运行设备

桌面/平板或笔记本

### 日志记录

无法上传，日志文件夹中没有当日的日志记录

### 人人为我，我为人人

None

**Comment by TIDEchiyuan** [comment]
+1

**Comment by lihansunbai** [comment]
+1

**Comment by ZhengWugeng** [comment]
+1我也是
