### ISSUE TITLE
推荐搜索页面显示失败

### ISSUE THREAD

**Issue by WcZaHr** [Richasy/Bili.Uwp#1622]
### Bug 描述

![image](https://user-images.githubusercontent.com/119170543/209671504-7949f253-25e1-4030-89aa-c54d0a429f6b.png)
![image](https://user-images.githubusercontent.com/119170543/209671597-c5f7b3a9-0d59-4c5c-826e-9ba3756c3d74.png)

### 复现问题的步骤

```plain text
打开哔哩
点击搜索
```

### 预期行为

正常的显示推荐内容和搜索的内容

### 截图

![image](https://user-images.githubusercontent.com/119170543/209671704-81f2b176-7725-4970-a53f-fe2a95b211d2.png)
![image](https://user-images.githubusercontent.com/119170543/209671730-08daff21-0b7b-49b5-9dc4-4f81c8aa1f2e.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

我更擅长发现问题

**Comment by net775** [comment]
同样有这样的问题，windows11
