### ISSUE TITLE
[Bug] 打开首页显示“鉴权失败，请联系账号组”

### ISSUE THREAD

**Issue by iKangnakamuyi** [Richasy/Bili.Uwp#1625]
### Bug 描述

登录账号之后打开首页显示“鉴权失败，请联系账号组”

### 复现问题的步骤

```plain text
打开应用，登录账号，进入首页
```

### 预期行为

显示推荐视频请求失败

### 截图

![图片](https://user-images.githubusercontent.com/47733293/210133193-684fc3a2-c3ac-4a13-935d-5aa615b1f86f.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 22623.1037

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by PRO-2684** [comment]
> [目前由于技术原因和个人精力原因，该项目不便再继续维护下去，请考虑使用哔哩哔哩官方客户端或网页](https://github.com/Richasy/Bili.Uwp/blob/main/README.md?plain=1#L15)

第三方bilibili客户端貌似都不维护了

**Comment by JimmyRespawn** [comment]
应该是账号鉴权那块挂了，懂鉴权的话自己改下咯（UWP用户日常）

**Comment by Xpya233** [comment]
怎么改啊 大佬就可以Fork一份吗（



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月18日(星期三) 晚上10:26
收件人: "Richasy/Bili.Uwp";
抄送: "Subscribed";
主题: Re: [Richasy/Bili.Uwp] [Bug] 打开首页显示“鉴权失败，请联系账号组” (Issue #1625)





 
应该是账号鉴权那块挂了，懂鉴权的话自己改下咯（UWP用户日常）
 
&mdash;
