### ISSUE TITLE
[Bug] 登录功能存在问题

### ISSUE THREAD

**Issue by JordanQD** [Richasy/Bili.Uwp#1626]
### Bug 描述

无法登录，并且登录后第二次打开时无法使用（先是视频，后图片）

### 复现问题的步骤

```plain text
登录、重启应用
```

### 预期行为

让它能用呗

### 截图

![哔哩 2023_1_1 23_59_18](https://user-images.githubusercontent.com/25655766/210177170-333cdb38-cdb4-4b13-b568-120ae1c6bb5a.png)

https://user-images.githubusercontent.com/25655766/210177345-aa4c42ae-2809-4f4b-a28d-dc23769be9b8.mp4

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 22H2

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2023-01-01.log](https://github.com/Richasy/Bili.Uwp/files/10329073/applog.2023-01-01.log)

### 人人为我，我为人人

None

**Comment by 2085886325** [comment]
我跟你问题一样，我也是Windows 11 22H2也是同样的问题

**Comment by aswindyy** [comment]
我跟你问题一样，我也是Windows 11 22H2也是同样的问题
