### ISSUE TITLE
[Bug] 无法播放大陆区番剧

### ISSUE THREAD

**Issue by smallg0at** [Richasy/Bili.Uwp#1639]
### Bug 描述

无法播放大陆区番剧。所有详情都可正常载入，唯独不可播放视频。

用 Fiddler 抓过包了，问题出在 mcdn 返回 403 上。详见日志记录。

### 复现问题的步骤

```plain text
1. 打开应用
2. 用任意方法尝试播放大陆区番剧
```

### 预期行为

正常播放

### 截图

![image](https://user-images.githubusercontent.com/30719670/218910743-aa6fc8d5-db56-4224-8074-0f2212c19db8.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 22H2 Dev 25295.1000

### 运行设备

桌面/平板或笔记本

### 日志记录

当日日志。当前问题产生时不会产生新日志，日志里应该是账号密码登陆没法用的问题。
[applog.2023-02-15.log](https://github.com/Richasy/Bili.Uwp/files/10738589/applog.2023-02-15.log)

Fiddler 导出的请求例子。
[17_Full.txt](https://github.com/Richasy/Bili.Uwp/files/10738614/17_Full.txt)

### 人人为我，我为人人

None

**Comment by Looong01** [comment]
@Richasy 类似问题，无法播放任何电影，如《流浪地球》
哔哩版本：情人节更新
操作系统版本：Win 11 22H2 22622.598
