### ISSUE TITLE
[Bug] 无法播放 番剧 电视剧 纪录片 电影

### ISSUE THREAD

**Issue by wen-wen520** [Richasy/Bili.Uwp#1665]
### Bug 描述

无法播放 番剧，电视剧，纪录片，电影的视频。

进入以上详情界面后，无法播放视频，但是除了视频以外的其他信息（例如 封面,简介,评论,相关内容等）都可以加载出来。

### 复现问题的步骤

```plain text
1. 打开应用
2. 尝试播放番剧，电视剧，纪录片，电影
```

### 预期行为

视频会播放

### 截图

![屏幕截图 2023-03-30 074835](https://user-images.githubusercontent.com/94116517/228696442-9a5a0241-364f-4914-92df-0de9cc89409f.png)
![屏幕截图 2023-03-30 074747](https://user-images.githubusercontent.com/94116517/228696446-edbcb1b3-32fa-4986-9e18-bcb5a5ad3857.png)
![屏幕截图 2023-03-30 074653](https://user-images.githubusercontent.com/94116517/228696448-1c30c976-b3bc-42a5-abd4-a36aa6702d2b.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows 11 22H2 (Build 22621.1485)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2023-03-30.log](https://github.com/Richasy/Bili.Uwp/files/11106550/applog.2023-03-30.log)

### 人人为我，我为人人

我更擅长发现问题

**Comment by ahsisnwk** [comment]
我也是这样
