### ISSUE TITLE
[Bug] arm64 商店版本无法登录

### ISSUE THREAD

**Issue by Grosser-Kurfuerst** [Richasy/Bili.Uwp#1684]
### Bug 描述

arm64微软商店版本无法登录，二维码与密码登录都失败

### 复现问题的步骤

```plain text
1. 登录
2. 失败
```

### 预期行为

希望可以正常登录，希望四月更新可以解决这个问题

### 截图

![image](https://user-images.githubusercontent.com/91124738/233820734-20272790-bec0-4167-9312-ba7ee7d71019.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Windows11 22H2 (Build 22621.1616)

### 运行设备

ARM64 设备

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
目前ARM64版本的二维码生成存在一定的问题，如果你是win11，请在github下载x64版本安装

**Comment by maokwen** [comment]
github 下载最新的 2023.6 的 arm64 版本，实测可以成功登录了
