### ISSUE TITLE
[Bug] 个人空间显示视频

### ISSUE THREAD

**Issue by Shaddoll126** [Richasy/Bili.Uwp#1685]
### Bug 描述

进入up主个人空间后不显示视频及头像等信息

### 复现问题的步骤

```plain text
右键视频-点击进入up主个人空间,无法加载出视频,头像等等
```

### 预期行为

能和以前一样看到个人空间里的视频

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 人人为我，我为人人

None

**Comment by LJLlw** [comment]
+1

**Comment by hjkgy** [comment]
+2

**Comment by Oceanlzj** [comment]
花了一点时间，擅自fork代码 用拙劣地手段把这个问题解决了
（可以去我fork的仓库试一下qwq
https://github.com/Oceanlzj/Bili.Uwp

**Comment by Shaddoll126** [comment]
OAO纯小白,具体是要怎么操作呢

**Comment by Oceanlzj** [comment]
> OAO纯小白,具体是要怎么操作呢

我也没有弄得很好 今天用的时候发现了一些小问题（
想要试试的话可以clone我的仓库编译安装一下
不过主要是为了自己在surface上用 滑动手势进退幅度改得很小QwQ
在[release](https://github.com/Oceanlzj/Bili.Uwp/releases/tag/fix)里安装一下试一下吧 问题还是有的（（（

**Comment by Oceanlzj** [comment]
> > OAO纯小白,具体是要怎么操作呢
> 
> 我也没有弄得很好 今天用的时候发现了一些小问题（ 想要试试的话可以clone我的仓库编译安装一下 不过主要是为了自己在surface上用 滑动手势进退幅度改得很小QwQ 在[release](https://github.com/Oceanlzj/Bili.Uwp/releases/tag/fix)里安装一下试一下吧 问题还是有的（（（

我看到了一个问题，原来只能加载第一页
我又稍微改了改，现在应该可以加载个人主页里更多的内容了
（或许（？

另外忘了说怎么解决这个问题的了
原来的请求里是带上了用户Token的，带上token的请求会导致“鉴权失败”
所以我是在构建请求的接口中加了一个forceNoToken的选项，如果为True就强制不使用token去请求
因为不登录就能加载出来（捂脸
（（对不起 不应该乱改接口定义的
![image](https://github.com/Richasy/Bili.Uwp/assets/31043955/6b6e995d-3659-4891-956e-a08fd3e4b9c7)

**Comment by Shaddoll126** [comment]
确实只能显示第一页的视频😂

**Comment by BLdada** [comment]
交一个Pull Request吧，球球了😍

**Comment by Oceanlzj** [comment]
> 交一个Pull Request吧，球球了😍
虽然但是，这方面我也是…纯小白，具体是要怎么操作呢（雾
（没太弄明白pull reqest的操作xxx
