### ISSUE TITLE
无法加载个人主页

### ISSUE THREAD

**Issue by inkPen-tea-lover** [Richasy/Bili.Uwp#1688]
### Bug 描述

无法加载个人主页

### 复现问题的步骤

```plain text
无法加载个人主页
```

### 预期行为

加载个人主页

### 截图

![image](https://user-images.githubusercontent.com/130156907/235303994-b912d594-49c1-4643-a945-54aa9d0de33d.png)

### 应用来源

- [x] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

None

**Comment by muzinicemoon** [comment]
+1

**Comment by Timearroworz** [comment]
+1

**Comment by 1lin-lcs** [comment]
+1

**Comment by inkPen-tea-lover** [comment]
应该是b站改过接口了，隔壁腕上哔哩也废了

**Comment by wen-wen520** [comment]
同样问题

**Comment by DokkouMonogatari** [comment]
一样的问题

**Comment by Oceanlzj** [comment]
这个问题目前有临时的解决方案可以去这个[isuue](https://github.com/Richasy/Bili.Uwp/issues/1685)下看看
