### ISSUE TITLE
希望添加记忆画质选择的功能

### ISSUE THREAD

**Issue by tiny-andr** [Richasy/Bili.Uwp#169]
希望播放视频的时候**记忆之前选择的画质**，例如选择1080P 高帧率之后，就一直保持高帧率。不用每次都重新选。或者提供一个选项：总是选择当前账号所能选择的最高画质（没有大会员可能无法选择）。

## 描述可能的替代方案
如果无法实现自动选择所能选择的最高画质，那就记忆之前选择的画质，如1080P 60帧，**若有些视频画质没有这么高**（如只有720P  480P甚至360P），就自动选择这个视频所能提供的最高画质。

![image](https://user-images.githubusercontent.com/71067099/133959219-5910b3ee-b6a0-418e-8ec9-93d1cf38be87.png)

**Comment by Richasy** [comment]
现在就是这样的行为啊

**Comment by Degate** [comment]
> 现在就是这样的行为啊

测试之后感觉是使用了上个视频播放的清晰度，是否与在上个视频中手动选择清晰度有关系不能确定，
例如我观看了一个最高只有360P的视频，那么下一个我观看的视频默认播放的清晰度就会是360P的，即使该视频有更高清晰度可选。

**Comment by Richasy** [comment]
目前暂时没有进一步的计划，先关闭这个问题，有需要可以再打开
