### ISSUE TITLE
显示不出其他up个人主页

### ISSUE THREAD

**Issue by chvysosk** [Richasy/Bili.Uwp#1698]
### Bug 描述

显示不出其他up个人主页

### 复现问题的步骤

```plain text
点up头像进个人主页后加载不出来，空白一片
```

### 预期行为

完整的主页

### 截图

![屏幕截图 2023-05-11 215053](https://github.com/Richasy/Bili.Uwp/assets/114557555/457c23e9-07ed-4cfb-a46f-621845f6e4a5)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

windows 11 22H2 内部版本22621.1755

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2023-05-11.log](https://github.com/Richasy/Bili.Uwp/files/11452897/applog.2023-05-11.log)

### 人人为我，我为人人

None

**Comment by chvysosk** [comment]
好应用

**Comment by Oceanlzj** [comment]
这个问题目前有临时的解决方案可以去这个[#1685 ](https://github.com/Richasy/Bili.Uwp/issues/1685)下看看

**Comment by chvysosk** [comment]
谢谢！！！

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年5月12日 13:12
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Richasy/Bili.Uwp] 显示不出其他up个人主页 (Issue #1698)


这个问题目前有临时的解决方案可以去这个#1685 <https://github.com/Richasy/Bili.Uwp/issues/1685> 下看看

―
