### ISSUE TITLE
无法播放视频 但是有声音

### ISSUE THREAD

**Issue by XiaoLeCN** [Richasy/Bili.Uwp#171]
无法播放视频 但是有声音
![image](https://user-images.githubusercontent.com/74437699/133962383-6906c7ab-9566-42e6-b559-1613b1281b46.png)

**Comment by Richasy** [comment]
是不是用的HEVC解码？这个需要额外安装解码器的，可以在设置里切回AVC/H264

**Comment by zhou-dingkun** [comment]
我也有这个问题，已经设置成avc/h264，日志文件显示|System.Exception: 播放失败: Unknown |  | System.Exception: Exception from HRESULT: 0x80700001

**Comment by Richasy** [comment]
@zhou-dingkun 请尝试更新下显卡驱动

**Comment by zhou-dingkun** [comment]
> @zhou-dingkun 请尝试更新下显卡驱动
显卡驱动为最新的了，nvdia设置中首选图形处理器修改为自动就好了

**Comment by watchingfun** [comment]
我遇到了同样的问题，不过是直播原画没有画面，只有高清有，系统设置里设置为使用n卡就没问题
![image](https://user-images.githubusercontent.com/22067924/135193797-cd04cfff-f2d0-49db-a9a4-4174948b1f27.png)

**Comment by ricardo-hash** [comment]
|System.Exception: 播放失败: DecodingError |  | System.Exception: 请求无效，因为已调用了 Shutdown()。 (Exception from HRESULT: 0xC00D3E85)

**Comment by StarsbySea** [comment]
这个问题在强制播放av1编码的视频时候也有遇到，解决方案是安装商店中的av1解码扩展
https://www.microsoft.com/store/productId/9MVZQVXJBQ9V
@Richasy 可否考虑下第1次播放时检测解码器安装情况，并提示安装呢？
