### ISSUE TITLE
[Bug] 在XBOX Series S上无法看电视剧

### ISSUE THREAD

**Issue by shawnwongx** [Richasy/Bili.Uwp#1711]
### Bug 描述

无法播放bilibili的电视剧，已经尝试过原生播放器和mmpeg，视频编码也尝试更换，均无法播放

### 复现问题的步骤

```plain text
搜索半泽直树，筛选电影，点击半泽直树，里面不会出现选集，而是直接打开黑屏无法播放
```

### 预期行为

修复该bug，使电视剧能够正常播放

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [X] 其它 (需注明)

### 其它系统版本

Xbox Series S最新版系统

### 运行设备

Xbox

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
该问题已经修复，但是由于商店政策原因，无法推送更新。XBOX客户端基本宣告终止维护了😓
