### ISSUE TITLE
bili uwp 应用联网故障

### ISSUE THREAD

**Issue by zxz4514** [Richasy/Bili.Uwp#174]
9.20 日下午 16:30
bili应用无法联网，显示在发送请求时出现异常

**Comment by Richasy** [comment]
参考 [代理网络下无法连网](https://github.com/Richasy/Bili.Uwp/discussions/70)。
如果未开代理，请打开系统设置->网络&Internet->WLAN->选择可以使用网络的应用，在里面把哔哩勾选上。
如果上述解决方法都不行，这属于网络问题，并不在应用的处理范围内

**Comment by Glavo** [comment]
@Richasy 我看 Bilibili 官方客户端在内的很多 UWP 应用都会主动申请 WLAN 权限，所以 Bili 可以实现主动申请吗？
