### ISSUE TITLE
[Feature]希望增加应用置顶和分屏播放功能

### ISSUE THREAD

**Issue by Q1313103q** [Richasy/Bili.Uwp#176]
## 应用置顶功能对多开党相当重要。打游戏 看B站  或者码字 看B站之类的

##希望增加类似平板上的分屏播放功能，右侧播放视频的时候，左侧能选择浏览别的列表。

**Comment by Richasy** [comment]
小窗播放即为置顶（对UWP来说，就是进入CompactOverlay模式），除此之外，UWP应用无法置顶自身，这是框架限制。

分屏播放也不在目前的计划范围内，UWP对于多窗口的支持并不友好
