### ISSUE TITLE
[Bug] 软件无法卸载

### ISSUE THREAD

**Issue by frcgty** [Richasy/Bili.Uwp#1764]
### Bug 描述

软件无法卸载!!!

### 复现问题的步骤

```plain text
卸载-卸载应用时出错
```

### 预期行为

正常卸载软件

### 截图

![屏幕截图 2023-09-02 110943.png](https://pic3.58cdn.com.cn/nowater/webim/big/n_v21fda5be77fc14f28b22cd0f5d148f435.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 人人为我，我为人人

None

**Comment by Richasy** [comment]
你这是拿啥卸载的……UWP是最好卸载的了，直接在开始菜单右键图标点击卸载就行

**Comment by frcgty** [comment]
感谢，已解决。
