### ISSUE TITLE
[Bug] 侧载10月版本x64客户端无法登录

### ISSUE THREAD

**Issue by SUBearH** [Richasy/Bili.Uwp#1779]
### Bug 描述

侧载10月版本x64客户端无法登录

### 复现问题的步骤

```plain text
正常打开客户端发现主页正常加载
点击访客头像进入登陆页面
使用密码登录提示:密码登录方式失败，请用二维码登录
在密码登录界面随便输入内容提示：密码登录方式失败，请用二维码登录
手机客户端扫描二维码提示：不受支持的二维码！
```

### 预期行为

可以正常登录并访问动态列表

### 截图

![image](https://github.com/Richasy/Bili.Uwp/assets/65080584/f442808f-d751-42cb-bdf9-2729cdacf8b8)

### 应用来源

- [ ] Microsoft Store
- [x] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [x] 其它 (需注明)

### 其它系统版本

Windows 11 23H2 (Build 22635)

### 日志记录

因未知原因，日志未正常生成

### 人人为我，我为人人

None

**Comment by SUBearH** [comment]
原因是哔哩哔哩概念版没法识别云视听小电视的登录二维码，换大陆普通版即可

**Comment by 20171213** [comment]
谷歌版的哔哩哔哩也无法扫描登录
