### ISSUE TITLE
[Bug] 点击设置中的启动方式后，应用闪退

### ISSUE THREAD

**Issue by wmdhs12138** [Richasy/Bili.Uwp#180]
## Bug 描述
如标题所述，打开应用，点击设置中的启动方式后，应用闪退

## 复现步骤
打开应用，点击设置中的启动方式，应用闪退

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '设置'
3. 点击 '启动方式'
4. 发现问题

## 预期的行为
闪退

## 截图
无

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [x] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录
[applog.2021-09-20.log](https://github.com/Richasy/Bili.Uwp/files/7195399/applog.2021-09-20.log)

**Comment by Richasy** [comment]
与 #143 重复，该问题已修复，会在下次更新时放出
