### ISSUE TITLE
[Bug]在设置界面单击启动方式闪退

### ISSUE THREAD

**Issue by xvzhenduo** [Richasy/Bili.Uwp#182]
## Bug 描述

在设置界面单击启动方式闪退

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '设置'
3. 点击 '启动方式'
5. 应用卡顿约2秒，随后闪退

## 预期的行为

看到切换启动方式的菜单

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：2.2109.1901.0

系统版本：

Windows 11 (22000.194)

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录
[applog.2021-09-20.log](https://github.com/Richasy/Bili.Uwp/files/7195432/applog.2021-09-20.log)

文件内容：
2021/09/20 19:37:26.541|Error|
系统信息：10.0.22000.194 | Windows.Desktop | X64
应用信息：2.2109.1901.0 | 中文(简体，中国)
--------
|System.NullReferenceException: Object reference not set to an instance of an object.
   at Richasy.ExpanderEx.Uwp.ExpanderExWrapper.CheckVisualState() + 0x20
   at Richasy.ExpanderEx.Uwp.ExpanderExMenuPanel.UpdateInternalWrapperLayout(Size, ExpanderExWrapper) + 0x1cb
   at Richasy.ExpanderEx.Uwp.ExpanderExMenuPanel.MeasureOverride(Size) + 0x467
   at Richasy!<BaseAddress>+0x3ab22ba
   at Richasy!<BaseAddress>+0x3904b10

**Comment by wmdhs12138** [comment]
#180 
重复了

**Comment by xvzhenduo** [comment]
抱歉，发issue之前因为时间着急，大概的看了一眼，没发现有重复的，我先把我的issue关了

**Comment by xvzhenduo** [comment]
> #180
> 重复了

貌似你已经关闭了你的issue但我没看到，把我的也管比例😂

**Comment by Richasy** [comment]
与 #143 重复，该问题已修复，会在下次更新时放出
