### ISSUE TITLE
[Feature]视频控件自动隐藏速度加快

### ISSUE THREAD

**Issue by Degate** [Richasy/Bili.Uwp#187]
控件自动隐藏太慢了，建议失去鼠标悬停焦点立即隐藏；

**Comment by xvzhenduo** [comment]
我觉得应该在加一个自动隐藏时间的设置，毕竟每个人需要的延迟不一样

**Comment by Degate** [comment]
就我个人而言，我用的播放器是potplayer，感觉失去焦点立即隐藏挺合理的；
另外我挨个测试了几大平台网页版的设置，腾讯视频立即隐藏，优酷视频大约2秒后隐藏，哔哩哔哩网页立即隐藏，爱奇艺立即隐藏，YouTube立即隐藏，HBO立即隐藏，甚至还去P站特意看了一下，大约3秒/doge；
希望有参考价值

**Comment by Degate** [comment]
> 我觉得应该在加一个自动隐藏时间的设置，毕竟每个人需要的延迟不一样

就我个人而言，我用的播放器是potplayer，感觉失去焦点立即隐藏挺合理的；
另外我挨个测试了几大平台网页版的设置，腾讯视频立即隐藏，优酷视频大约2秒后隐藏，哔哩哔哩网页立即隐藏，爱奇艺立即隐藏，YouTube立即隐藏，HBO立即隐藏，甚至还去P站特意看了一下，大约3秒/doge；
也希望对开发者有参考价值

**Comment by diave971** [comment]
大佬应该是为了照顾触屏设备，
不过目前这个自动隐藏时间确实过长了，对鼠标用户很不友好

**Comment by x1aohui** [comment]
非常希望减少自动隐藏时间 太遮挡啊

**Comment by Richasy** [comment]
与 #654 合并处理
