### ISSUE TITLE
[Feature]评论楼中楼面板改动建议

### ISSUE THREAD

**Issue by Degate** [Richasy/Bili.Uwp#188]
这个新样式个人感觉很喜欢，比起上个版本中夹层底部添加关闭夹层的手法好用太多，但是独立面板以外区域目前是没有任何反应的，建议把这些区域设置为单击退出楼中楼面板；
![微信截图_20210919134402](https://user-images.githubusercontent.com/19262167/133925695-56d91e18-f2eb-4f01-b296-4e5ad1545645.png)

**Comment by Richasy** [comment]
现阶段暂不考虑这种点击关闭的方式，可以用esc快捷键关闭
