### ISSUE TITLE
[Feature]希望支持互动视频

### ISSUE THREAD

**Issue by xvzhenduo** [Richasy/Bili.Uwp#189]
建议：希望支持互动视频
适用场景：观看互动视频时

## 描述解决方案

旧版的不就支持吗

## 描述可能的替代方案

无

## 备注和截图

使用旧版播放互动视频时会有选项
![image](https://user-images.githubusercontent.com/74353173/134015276-80f0e26a-a7ba-4ab9-94ed-61f6d8692e63.png)

**Comment by Richasy** [comment]
与 #23 重复
