### ISSUE TITLE
[Feature]长文本消息的收缩与展开改动建议

### ISSUE THREAD

**Issue by Degate** [Richasy/Bili.Uwp#190]
两个体验不好的地方，一是按钮太小了，很容易被忽略，建议把三个点改成“展开”二字，二是这个地方使用了弹出独立窗口的设计不是很合理，评论中出现及其长篇大论的很少，跟随按钮弹出的面板会改变视线焦点，比较影响阅读体验，建议仍使用展开式，并且展开后该消息底部展开按钮变成收缩按钮；
![微信截图_20210919134611](https://user-images.githubusercontent.com/19262167/133925851-0b843923-69c7-4126-b3a6-8fa7c1d40f6a.png)

**Comment by texsd123** [comment]
同意。读到一半了展开后又需要寻找中断的内容，确实不太方便。
