### ISSUE TITLE
[Feature]个人消息的处理方式改进建议

### ISSUE THREAD

**Issue by Degate** [Richasy/Bili.Uwp#191]
调用楼中楼的面板来处理这个感觉更好些，点击后弹出对话历史和发送回复框，网页版我试过，B站有返回定位对话的信息参数另外如果在瀑布流卡片下方加上对话发生地就更加完美，如“于视频/专栏/投稿·······（标题）·”
![微信截图_20210919142032](https://user-images.githubusercontent.com/19262167/133926117-09889eb9-924d-46aa-98b9-59237b869aa5.png)

**Comment by Richasy** [comment]
已在 PR #175 中修复
