### ISSUE TITLE
[Bug] 设置页展开启动方式Expansion崩溃

### ISSUE THREAD

**Issue by ShiinaManatsu** [Richasy/Bili.Uwp#196]
## Bug 描述

设置页展开启动方式Expansion崩溃

## 复现步骤

导航到设置页, 点击"启动方式"

## 截图

![image](https://user-images.githubusercontent.com/20186095/134029837-27e6e839-e032-4ab8-8221-48dd7c8ab27f.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{2.2109.1901.0}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [x] 内测版本 ({22000.194})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录

2021/09/20 23:34:01.551|Error|
系统信息：10.0.22000.194 | Windows.Desktop | X64
应用信息：2.2109.1901.0 | English (United States)
--------
|System.NullReferenceException: Object reference not set to an instance of an object.
   at Richasy.ExpanderEx.Uwp.ExpanderExWrapper.CheckVisualState() + 0x20
   at Richasy.ExpanderEx.Uwp.ExpanderExMenuPanel.UpdateInternalWrapperLayout(Size, ExpanderExWrapper) + 0x1cb
   at Richasy.ExpanderEx.Uwp.ExpanderExMenuPanel.MeasureOverride(Size) + 0x467
   at Richasy!<BaseAddress>+0x3ab22ba
   at Richasy!<BaseAddress>+0x3904b10

**Comment by Richasy** [comment]
请使用新版本
