### ISSUE TITLE
[Bug]google play 版本bilibili 扫码失败

### ISSUE THREAD

**Issue by DanceToThis1** [Richasy/Bili.Uwp#199]
## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）
- [ ] google play 中bilibili 版本为8月5号更新的新版本

重现问题的步骤：

1. 打开应用
2. 使用Google play 中的bilibili扫码登陆
5. 发现问题

## 环境

应用来源：

- [ ] Microsoft Store
- [ 1] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})
- [ ] windows 10 21h1

运行设备：

- [ ] 桌面/台式机
- [ ] 笔记本
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

**Comment by Richasy** [comment]
这不是我能处理的问题，请使用国内的b站移动端扫码或者使用账号密码登录
