### ISSUE TITLE
[挂TiZi]

### ISSUE THREAD

**Issue by WXT080805** [Richasy/Bili.Uwp#200]
## Bug 描述
启动科学上网时候，显示无网络状态。请求失败。

## 截图
![image](https://user-images.githubusercontent.com/48269151/134100350-53f2d25e-0cde-4ed1-aa19-0dbaf4907204.png)

应用版本：{应用版本}
![image](https://user-images.githubusercontent.com/48269151/134100499-432f2338-9fb7-4b41-bd6e-f50600aafbf6.png)

运行设备：
![image](https://user-images.githubusercontent.com/48269151/134100443-f919eaee-3a3c-4f71-8338-fa1c5ef8c732.png)

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 备注

感觉这个修复与否无所谓。个人只是下载时候启动的科学上网，安装好没关偶然发现的问题。
[applog.2021-09-21.log](https://github.com/Richasy/Bili.Uwp/files/7199660/applog.2021-09-21.log)

**Comment by Stapxs** [comment]
开启 UWP 应用网络回环就行了（
自行百度

**Comment by sddpljx** [comment]
请问是否在“UWP Loopback”中勾选了哔哩UWP?
![image.png](https://i.loli.net/2021/09/21/RvaNeyQgACsSwlG.png)

**Comment by WXT080805** [comment]
> UWP Loopback

ok，已解决，感谢

**Comment by WXT080805** [comment]
> 开启UWP应用网络回环就行了（
> 百度自己

ok，已解决，感谢

**Comment by Stapxs** [comment]
> > 开启UWP应用网络回环就行了（
> > 百度自己
> 
> ok，已解决，感谢

顺手把 issue 关了省的麻烦作者（
