### ISSUE TITLE
[Feature]希望可以改善滚动视图的流畅性

### ISSUE THREAD

**Issue by exlife1** [Richasy/Bili.Uwp#213]
## 描述你想要解决的问题或者功能的使用场景

可能是由于视频加载的问题，导致滚动视图(滚动条拖动&鼠标滚轮)较为卡顿，希望得以改善

## 备注和截图

Ver: Bili.Uwp_2.2109.2001.0_x64
Sys:  Windows 10

**Comment by X0980** [comment]
应该是一次加载的视频数量太少了，滚一下就又得加载一次，显得很卡

**Comment by Richasy** [comment]
用的是移动端的API，它只会返回固定数量（一般是8个）的视频条目，这一点短期内得不到改善
