### ISSUE TITLE
[Feature]想添加“方向键”控制声音的功能，设置中添加 设置键盘“快进/后退”秒数 的功能。

### ISSUE THREAD

**Issue by tianjiangqiji** [Richasy/Bili.Uwp#217]

**Comment by Richasy** [comment]
方向键控制声音暂时没有计划

前进后退的秒数设置已存在
![image](https://user-images.githubusercontent.com/27713596/134160745-5314f932-1ff1-4663-b947-e977a9d36cec.png)
