### ISSUE TITLE
[Feature]设置观看分集视频时，当前视频结束后自动跳转到下一集

### ISSUE THREAD

**Issue by zzs20020430** [Richasy/Bili.Uwp#225]
## 描述你想要解决的问题或者功能的使用场景

在技术预览3中，观看分集视频时，当前集结束后播放器没有自动跳至下一集，播放设置里目前没有找到相关设置，观看完需要一集一集地去点击

## 描述解决方案

希望在视频播放界面的右下角小齿轮菜单里加入 自动播放下一集/单集循环/循环播放列表 选项

## 描述可能的替代方案

可以先加入自动播放下一集功能

## 备注和截图

![mmexport1632235918911](https://user-images.githubusercontent.com/16655090/134194141-fcbcd905-7ac1-4e41-a924-13ed165a0b08.png)
![mmexport1632235906155](https://user-images.githubusercontent.com/16655090/134194162-4007f28b-51b8-4a34-a486-96fa5e039e2f.png)

**Comment by Richasy** [comment]
与 #94 重复
