### ISSUE TITLE
[Feature] 卡片UI 改善

### ISSUE THREAD

**Issue by DreamOfStars** [Richasy/Bili.Uwp#227]
## 描述你想要解决的问题或者功能的使用场景

现有UI卡片图片纵横比会导致缩略图下半区域部分信息被遮盖，与手机和网页端显示略有出入，导致观感不佳。
卡片文字部分背景为不透明区域，在满屏是卡片时，那块不透明区域十分显眼（尤其是在黑暗主题配色下）。
用户浏览时会将重心放在图片上，有必要增加图片在视觉区域的比重，提高空间利用率。

## 描述解决方案

可以学习借鉴一下 Edge 新标签页的卡片风格，或者是 win11 的小组件的设计方法。
它们都是在图片和文字中间加了一个 gradient 渐变，让过渡更加自然，用户可获取的信息更多，同时不失易读性。

## 备注和截图

**现阶段 哔哩 截图 （版本： 2.2109.2001.0）**

![image](https://user-images.githubusercontent.com/25294404/134205767-0031a94d-2fe0-4525-944f-91e6b4b44a04.png)

**UI 优化思路**

**例 （小组件）**
![image](https://user-images.githubusercontent.com/25294404/134206240-8cd1b98f-b69e-474b-9917-9bd45a1cc007.png)

**（Edge 新标签页）**
![image](https://user-images.githubusercontent.com/25294404/134206406-e19bb954-7a12-447e-9b17-a59d5025a331.png)

**Comment by Richasy** [comment]
这曾经是设计方案之一，但效果不理想。如果想实现不错的效果，我需要用到一些图像计算的知识，而目前没有足够精力处理这个问题
