### ISSUE TITLE
挂vpn时，无法加载数据

### ISSUE THREAD

**Issue by Bian-Sh** [Richasy/Bili.Uwp#232]
挂vpn时，无法加载数据

**Comment by Bian-Sh** [comment]
![image](https://user-images.githubusercontent.com/24520547/134277266-7e1bf369-7ec7-4844-a50f-79603c020c7d.png)

**Comment by rico-chen** [comment]
如果是用Clash，把哔哩加入UWP回环就行，就用那个AppContainer Loopback Exemption Utility
