### ISSUE TITLE
[Doc]关于xbox部分的

### ISSUE THREAD

**Issue by SaikiCrimson** [Richasy/Bili.Uwp#235]
## 描述

希望能够在xbox上使用，我并没有xbox开发者账号。

## 预期的内容

希望能够上架xbox应用商店或者用其他方式实现。

**Comment by Richasy** [comment]
法律问题（不可能上架应用商店），暂不考虑XBOX平台

**Comment by SaikiCrimson** [comment]
这真的太遗憾了，谢谢您的回复



发送自我的盖乐世



-------- 原始信息 --------
发件人： Richasy ***@***.***>
日期: 2021/9/22 12:50 (GMT+08:00)
收件人： "Richasy/Bili.Uwp" ***@***.***>
抄送： SaikiCrimson ***@***.***>, Author ***@***.***>
主题： Re: [Richasy/Bili.Uwp] [Doc]关于xbox部分的 (#235)


法律问题（不可能上架应用商店），暂不考虑XBOX平台

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRichasy%2FBili.Uwp%2Fissues%2F235%23issuecomment-924581101&data=04%7C01%7C%7Cc20e4f57846b4313e7fc08d97d846e3f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637678830001046338%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yQHhL1Eg3evwzdBMwOOXU7VXEwRgW%2F2uqIWya6IKIAE%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVXTB6O6GS6YWXUX4E325K3UDFN7LANCNFSM5EQJZRBQ&data=04%7C01%7C%7Cc20e4f57846b4313e7fc08d97d846e3f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637678830001056326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CQCRGd4b3HM2xJobZnW6eL921aO2%2BACOkTCrFK%2FO0gU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cc20e4f57846b4313e7fc08d97d846e3f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637678830001066327%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tp2qT9grIKOJgb%2Bez0m11NOqkorFjHE9O3Z94qgmtj0%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7Cc20e4f57846b4313e7fc08d97d846e3f%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637678830001066327%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YZbWc321gR8E%2BG4p6pcRbex48oYmf%2BbOcZ9UgXrMa2c%3D&reserved=0>.
