### ISSUE TITLE
[Bug]添加到稍后再看失败

### ISSUE THREAD

**Issue by rico-chen** [Richasy/Bili.Uwp#237]
## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '推荐/热门/排行榜'
3. 邮件点击其中一个视频
4. 添加到稍后再看

## 截图

![image](https://user-images.githubusercontent.com/49147551/134280370-6fae692b-b438-4d6a-b6cf-e69011e7f81c.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{2.2109.2001.0}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [x] 内测版本 ({22458})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

[applog.2021-09-22.log](https://github.com/Richasy/Bili.Uwp/files/7207573/applog.2021-09-22.log)

**Comment by Richasy** [comment]
根据报错结果，你这个属于稍后再看列表满了，清理一下吧
