### ISSUE TITLE
[Bug]无法显示cc字幕

### ISSUE THREAD

**Issue by 1061875478** [Richasy/Bili.Uwp#240]
## Bug 描述

cc字幕没有显示，也没有找到相关设置

## 复现步骤

- [ x ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 查找有cc字幕的视频
3. 播放视频

## 预期的行为

无字幕显示

## 截图

网页端有字幕
![image](https://user-images.githubusercontent.com/68525017/134295477-ccf3f2e6-fc25-46fa-a365-c43ae4f65dd2.png)
哔哩无字幕
![image](https://user-images.githubusercontent.com/68525017/134295608-50886a9f-8a66-4c3b-ae15-26acf01dce66.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [ x ] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ x ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [ x ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录

[applog.2021-09-22.log](https://github.com/Richasy/Bili.Uwp/files/7208274/applog.2021-09-22.log)

## 备注
如有相关设置望告知。

**Comment by Richasy** [comment]
与 #25 重复
