### ISSUE TITLE
[Bug]无法观看直播

### ISSUE THREAD

**Issue by UxNeas** [Richasy/Bili.Uwp#242]
## Bug 描述

<进入直播间无法观看直播，显示’请求直播播放信息失败‘，同时聊天互动一栏一直空白>

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '直播'
3. 点击 '直播间'
4. 等待播放
5. 发现无法播放直播，和聊天互动不显示

## 预期的行为

<可以看到直播>

## 截图

<
![unknown](https://user-images.githubusercontent.com/23080096/134301991-3501993f-f4f9-415d-a42f-89fbd0ecd499.png)
>

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [x] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录

<
[applog.2021-09-22.log](https://github.com/Richasy/Bili.Uwp/files/7208691/applog.2021-09-22.log)
>

## 备注

<现在在海外，同时用两台电脑，各装着win10 和win11，都出现同样的情况，怀疑可能是境外IP导致的问题，从网页端看B站直播无类似问题>

**Comment by UxNeas** [comment]
[applog.2021-09-22.log](https://github.com/Richasy/Bili.Uwp/files/7208721/applog.2021-09-22.log)
这是新的日志文件，之前那个可能没用

**Comment by Richasy** [comment]
网络问题，而且是IP端口造成的问题，这一点毫无疑问。
但目前无法修复，因为我无法干预播放组件（ffmpeg）的解析，可以尝试使用翻墙软件“翻回来”
