### ISSUE TITLE
[bug]无法显示画面

### ISSUE THREAD

**Issue by lueluelue2333** [Richasy/Bili.Uwp#244]
直播画面不显示以及在h265下视频画面也会不显示，但可以听到视频或直播声音

**Comment by Richasy** [comment]
请问装HEVC解码器了吗

**Comment by lueluelue2333** [comment]
安了解码器直播还是没画面，只听得见声音，在切换线路时会卡出来半秒的画面，然后继续白屏或黑屏

**Comment by Richasy** [comment]
感觉是显卡的问题，你是否调整过显卡的设置？可以尝试切换垂直同步，或者更新显卡驱动

**Comment by Richasy** [comment]
两天未回，暂时关闭问题，有需要可以再打开
