### ISSUE TITLE
很多很多视频点开后就是一直加载，看不了，我是surface pro 7[Bug]

### ISSUE THREAD

**Issue by 8996544556778** [Richasy/Bili.Uwp#249]
## Bug 描述

如题

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '...'
3. 点击 '....'
4. 滚动至 '....'
5. 发现问题

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [ ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

**Comment by 8996544556778** [comment]
- [ ] 
![image](https://user-images.githubusercontent.com/91193537/134337816-a1527c80-0564-4c62-acd3-45f5261c271a.png)
![image](https://user-images.githubusercontent.com/91193537/134337893-eec9ab54-513c-4769-8628-f8938a32a2fb.png)
不是网络问题  我用浏览 看没问题

**Comment by Richasy** [comment]
用的视频解码是什么，是不是用了HEVC？显卡驱动是否更新了？

**Comment by longshaoyou** [comment]
我也是这样 surface pro 7 用的是avc 显卡驱动都更新了

**Comment by longshaoyou** [comment]
> 用的视频解码是什么，是不是用了HEVC？显卡驱动是否更新了？
我也是这样 surface pro 7 用的是avc 显卡驱动都更新了

**Comment by Richasy** [comment]
我自己也有SP7，一切正常，应该可以排除是设备问题。你是否开了网络代理？

也许可以尝试下载扩展 [mpeg-2 extension](https://www.microsoft.com/en-us/p/mpeg-2-video-extension/9n95q1zzpmh4?activetab=pivot:overviewtab)

**Comment by Richasy** [comment]
长时间未回复，暂时关闭这个问题
