### ISSUE TITLE
[Bug] 打开设置中的“启动方式”闪退，打开设置中的“日志记录”有概率闪退

### ISSUE THREAD

**Issue by yeahjack** [Richasy/Bili.Uwp#273]
## Bug 描述

打开设置中的“启动方式”闪退，打开设置中的“日志记录”有概率闪退

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '设置'
3. 点击 “启动方式”或“日志记录”
4. 程序闪退

## 预期的行为

自由设置其中内容。

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

2.2109.1901.0

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [x] 内测版本 ({系统版本})

版本	Windows 11 专业版 Insider Preview
版本	Dev
安装日期	‎2021/‎9/‎24
操作系统版本	22463.1000
体验	Windows Feature Experience Pack 1000.22463.1000.0

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录

2021/09/24 03:42:49.108|Error|
系统信息：10.0.22463.1000 | Windows.Desktop | X64
应用信息：2.2109.1901.0 | 中文(简体，中国)
--------
|System.NullReferenceException: Object reference not set to an instance of an object.
   at Richasy.ExpanderEx.Uwp.ExpanderExWrapper.CheckVisualState() + 0x20
   at Richasy.ExpanderEx.Uwp.ExpanderExMenuPanel.UpdateInternalWrapperLayout(Size, ExpanderExWrapper) + 0x1cb
   at Richasy.ExpanderEx.Uwp.ExpanderExMenuPanel.MeasureOverride(Size) + 0x467
   at Richasy!<BaseAddress>+0x3ab22ba
   at Richasy!<BaseAddress>+0x3904b10
## 备注

在我的Surface Pro 6上不会出现该问题，只会在我的PC上出现。Surface的系统版本与PC完全一致
[applog.2021-09-24.log](https://github.com/Richasy/Bili.Uwp/files/7220461/applog.2021-09-24.log)
。

**Comment by Richasy** [comment]
这个不是最新版本，请在Release中下载最新版，这个问题已经被修复
