### ISSUE TITLE
[Bug]直播自动切线路问题再次出现

### ISSUE THREAD

**Issue by Degate** [Richasy/Bili.Uwp#279]
直播自动切线路问题再次出现，但是并不是所有直播间都能稳定复现这个问题，另外有几率出现重复进入同一直播间，在第二次进入后直播间没有直播流，需要手动切换线路才会开始接收直播流。

## 截图
录屏一分钟
https://www.bilibili.com/video/BV1ef4y1E7ta/

## 环境

应用来源：

- [ ] Microsoft Store
- [X] Github
- [ ] 其他来源（请注明来源）

应用版本：PR5

系统版本：

版本	Windows 10 专业版
版本号	21H1
安装日期	‎2020/‎07/‎08
操作系统内部版本	19043.1237
体验	Windows Feature Experience Pack 120.2212.3530.0

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录
[applog.2021-09-24.log](https://github.com/Richasy/Bili.Uwp/files/7222465/applog.2021-09-24.log)

**Comment by tm0210** [comment]
我今天也遇到了，退出直播间再进去会没有画面😂
