### ISSUE TITLE
[Feature]希望动态可以选择其他排列方式

### ISSUE THREAD

**Issue by WrXu233** [Richasy/Bili.Uwp#282]
## 描述你想要解决的问题或者功能的使用场景
希望动态能够选择以列表的形式呈现

## 备注和截图
![image](https://user-images.githubusercontent.com/69620730/134641284-a43b2097-d3c3-4dfe-9313-02e14e818653.png)

**Comment by Richasy** [comment]
信息密度太低，目前暂不考虑
