### ISSUE TITLE
[Bug]打开推荐里面的视频出来pcs请求失败重启后又能看了

### ISSUE THREAD

**Issue by zxa959** [Richasy/Bili.Uwp#283]
## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '...'
3. 点击 '....'
4. 滚动至 '....'
5. 发现问题

## 环境

应用来源：

- [ ] Microsoft Store
- [ ] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [x] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [x] 内测版本 ({系统版本})

运行设备：

- [ ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

**Comment by Richasy** [comment]
没有完整描述，不太明白意思，请提供完整说明并重新发Issue
