### ISSUE TITLE
[Feature]希望支持视频字幕

### ISSUE THREAD

**Issue by skyhua0224** [Richasy/Bili.Uwp#286]
## 描述你想要解决的问题或者功能的使用场景
在观看带字幕的视频时（如港澳台番剧），无法显示字幕
## 描述解决方案
添加字幕图标，可选择开启或关闭字幕
## 描述可能的替代方案
默认挂载字幕
## 备注和截图
<img width="2560" alt="image" src="https://user-images.githubusercontent.com/91328606/134683922-89408ca7-bbcb-44ea-9566-3e7afbbadc3b.png">
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/91328606/134684035-ef1fd61a-976c-453e-8875-68e89f5a4d04.png">

下方无字幕显示

**Comment by Richasy** [comment]
与 #25 重复
