### ISSUE TITLE
[Bug]播放器问题

### ISSUE THREAD

**Issue by WhatDamon** [Richasy/Bili.Uwp#288]
## Bug 描述
Windows 10再全屏上优化很差，视频全窗口下有圆角（这不应该再全窗口中出现）并且方向键快进太过了

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '视频（最好是可以占满屏幕的视频）'
3. 点击 '全窗口模式'
5. 发现问题

## 预期的行为

没有奇怪的圆角，并且视频快进上不要这么突然奇怪
##### 单角
![屏幕截图 2021-09-24 223127](https://user-images.githubusercontent.com/59256766/134692103-e2326885-4c56-499d-87a3-cc3185a26680.png)

##### 全窗口
![屏幕截图 2021-09-24 223223](https://user-images.githubusercontent.com/59256766/134692111-b69534af-bdd5-4ec4-8fea-431a9e588c68.png)

###### 全屏单角
![屏幕截图 2021-09-24 223045](https://user-images.githubusercontent.com/59256766/134692131-1c0c0e8a-2750-40f7-891a-8d5b7d910f0a.png)
## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [x] Windows 10 ver.2004 (19043.1202)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录

属于播放器问题，影响用户体验的问题，但程序可以正常运行，所以没有相关日志可供查看
## 备注

在我短期使用发现大量奇奇怪怪但又不影响程序运行的BUG
不再细写

**Comment by cnoim** [comment]
win11下也存在着相同问题（应用全屏）

**Comment by Richasy** [comment]
用最新版呀兄弟们，Release现在都出到5了，这个应该是老版本的问题了

**Comment by cnoim** [comment]
> 用最新版呀兄弟们，Release现在都出到5了，这个应该是老版本的问题了

可是我更新了预览版6这个问题仍然存在（是全窗口模式啊！）
![屏幕截图(3)](https://user-images.githubusercontent.com/52961523/134793698-e6175a15-259b-4247-ae0e-7fe85bc02896.png)

**Comment by Richasy** [comment]
我的错，已经修了，下次更新发布
