### ISSUE TITLE
[Bug]专栏无法使用鼠标滚动

### ISSUE THREAD

**Issue by DreamUniverse843** [Richasy/Bili.Uwp#289]
## Bug 描述

如题，随意打开一个专栏，鼠标无法在专栏内滚动。

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入任意一个专栏
3. 发现问题

## 预期的行为

专栏预期应可以通过鼠标滚动进行翻页。

## 截图

![image](https://user-images.githubusercontent.com/53889721/134697546-a55e67b4-f705-49d9-b2bf-d9d8a9217734.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{2.2109.2301.0}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [x] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录

`2021/09/24 23:06:05.879|Info|`
`系统信息：10.0.19043.1237 | Windows.Desktop | X64`
`应用信息：2.2109.2301.0 | 中文(简体，中国)`
`--------`
`控制器加载完成`
`|`

**Comment by Richasy** [comment]
无法复现这个问题

**Comment by DreamUniverse843** [comment]
https://user-images.githubusercontent.com/53889721/134755186-19ffb3a3-7f8f-4b9d-b856-31911b7a879c.mp4

如图，我是按照正常的侧加载方式安装的，刚才也重新安装了，好像还是不对。
专栏始终没有拖动控制条。

**Comment by Richasy** [comment]
@DreamUniverse843 你所指的到底是专栏不能滚动还是专栏详情没有侧边的滚动条？如果是后者，这是设计，因为UWP的网页视图的滚动条和整体应用设计不符，且样式无法修改，我只能隐藏

**Comment by DreamUniverse843** [comment]
抱歉，可能我措辞有问题，我所指的是前者，根本无法滚动。

**Comment by Richasy** [comment]
没有滚动条是我通过样式隐藏掉了，这并不是故障。
但你提到的无法滚动，这很奇怪，我没有在我这台设备上复现这个问题，你确认下载的是最新版本吗？预览版 - 5？

**Comment by DreamUniverse843** [comment]
是的。

**Comment by DreamUniverse843** [comment]
我刚刚安装了预览版 - 6，专栏仍然无法滚动。
```
2021/09/26 09:35:57.190|Info|
系统信息：10.0.19043.1237 | Windows.Desktop | X64
应用信息：2.2109.2501.0 | 中文(简体，中国)
--------
控制器加载完成
|
```
