### ISSUE TITLE
[Bug]打开视频就闪退

### ISSUE THREAD

**Issue by aLIEz-xue** [Richasy/Bili.Uwp#291]
## Bug 描述

安装完，随便打开个视频就闪退

## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '推荐'
3. 点击 '随便一个视频'
4. 闪退

## 环境

应用来源：

- [ ] Microsoft Store
- [ x ] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}
![image](https://user-images.githubusercontent.com/59567929/134753377-7fd3dce0-5ee3-4dc0-b5a8-0e8acde8f8af.png)

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ x ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})
![image](https://user-images.githubusercontent.com/59567929/134753402-455c282d-fb2f-4e45-806f-c7af45bf17e7.png)

运行设备：

- [ x ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录

[applog.2021-09-25.log](https://github.com/Richasy/Bili.Uwp/files/7228968/applog.2021-09-25.log)

## 备注

界面文字描述有误，选项处的单词拼错。
![image](https://user-images.githubusercontent.com/59567929/134753437-334a8415-2422-437e-ae7a-8ff4a1c0e014.png)

**Comment by Richasy** [comment]
尽管有一些相似的报告，但是目前尚不清楚具体的原因，我也无法在设备上复现，请提供更为具体的设备信息，比如显卡型号，是否更新了显卡驱动等

**Comment by aLIEz-xue** [comment]
> 尽管有一些相似的报告，但是目前尚不清楚具体的原因，我也无法在设备上复现，请提供更为具体的设备信息，比如显卡型号，是否更新了显卡驱动等

![image](https://user-images.githubusercontent.com/59567929/134754560-ef744f0b-c26f-482d-b950-f637dd4ae81f.png)
只有集显，显卡驱动是联想管家里最新的
![VXLN0`){J3PXC G@~W@KQKT](https://user-images.githubusercontent.com/59567929/134754664-436f5a01-f951-4776-9993-1807976c4439.png)

**Comment by Richasy** [comment]
是否安装了扩展 [MPEG-2](https://www.microsoft.com/store/productId/9N95Q1ZZPMH4) ？它也许有用

**Comment by aLIEz-xue** [comment]
> 是否安装了扩展 [MPEG-2](https://www.microsoft.com/store/productId/9N95Q1ZZPMH4) ？它也许有用

刚装了，没用，还是闪退，昨天发布的最新版

**Comment by dylumian** [comment]
2021/09/28 10:34:39.465|Info|
系统信息：10.0.22000.194 | Windows.Desktop | X86
应用信息：2.2109.2501.0 | 中文(简体)
--------
控制器加载完成
|
2021/09/28 10:34:41.755|Error|
系统信息：10.0.22000.194 | Windows.Desktop | X86
应用信息：2.2109.2501.0 | 中文(简体)
--------
|Windows.UI.Xaml.Markup.XamlParseException: 无法找到与此错误代码关联的文本。

Cannot create instance of type 'Richasy.Bili.App.Controls.BiliPlayerTransportControls' [Line: 0 Position: 0]
2021/09/28 10:34:52.070|Info|
系统信息：10.0.22000.194 | Windows.Desktop | X86
应用信息：2.2109.2501.0 | 中文(简体)
--------
控制器加载完成


一样的问题，X64日志只有控制器加载完成，换成X86的有日志了

**Comment by Richasy** [comment]
我会在版本7尝试修复这个问题

**Comment by aLIEz-xue** [comment]
> 我会在版本7尝试修复这个问题

版本7还是这个问题，x64闪退，且日志只显示加载控制器。
[applog.2021-09-28.log](https://github.com/Richasy/Bili.Uwp/files/7241076/applog.2021-09-28.log)

**Comment by Richasy** [comment]
> > 我会在版本7尝试修复这个问题
> 
> 版本7还是这个问题，x64闪退，且日志只显示加载控制器。
> [applog.2021-09-28.log](https://github.com/Richasy/Bili.Uwp/files/7241076/applog.2021-09-28.log)

好吧，我换了5个设备，都没能复现这个问题，目前不清楚这个问题的具体原因，我会继续调查这个问题

**Comment by dylumian** [comment]
我的问题好像是安装的时候使用powershell运行，并没有弹出提升管理员权限的行为，（证书我都是按照安装教程的第二种导入的）切到administrator用户安装 都很正常也能点开视频播放，但是一切换到正常的用户（隶属于administrator）就闪退，而且我到..\App_2.2109.2501.0_Test\Dependencies\x64这里面的这个手动安装Microsoft.VCLibs.x64.14.00.appx安装总是不成功，其他的都能正常安装，我尝试关闭了系统的照片，音乐，开始菜单应用，还是会有最后两行的client错误，还是错误0x80073D02

App installation failed with error message: 错误 0x80073D02: 无法安装，因为需要关闭以下应用: Microsoft.Windows.Photos_2021.21090.20001.0_x64__8wekyb3d8bbwe Microsoft.Windows.StartMenuExperienceHost_10.0.22000.37_neutral_neutral_cw5n1h2txyewy Microsoft.ZuneVideo_10.21061.10121.0_x64__8wekyb3d8bbwe MicrosoftWindows.Client.CBS_1000.22000.194.0_x64__cw5n1h2txyewy MicrosoftWindows.Client.WebExperience_421.20031.315.0_x64__cw5n1h2txyewy

**Comment by dylumian** [comment]
![image](https://user-images.githubusercontent.com/37278466/135188918-7428e1f6-68a7-4061-ba8e-63b039219efe.png)

**Comment by Richasy** [comment]
> 我的问题好像是安装的时候使用powershell运行，并没有弹出提升管理员权限的行为，（证书我都是按照安装教程的第二种导入的）切到administrator用户安装 都很正常也能点开视频播放，但是一切换到正常的用户（隶属于administrator）就闪退，而且我到..\App_2.2109.2501.0_Test\Dependencies\x64这里面的这个手动安装Microsoft.VCLibs.x64.14.00.appx安装总是不成功，其他的都能正常安装，我尝试关闭了系统的照片，音乐，开始菜单应用，还是会有最后两行的client错误，还是错误0x80073D02
> 
> App installation failed with error message: 错误 0x80073D02: 无法安装，因为需要关闭以下应用: Microsoft.Windows.Photos_2021.21090.20001.0_x64__8wekyb3d8bbwe Microsoft.Windows.StartMenuExperienceHost_10.0.22000.37_neutral_neutral_cw5n1h2txyewy Microsoft.ZuneVideo_10.21061.10121.0_x64__8wekyb3d8bbwe MicrosoftWindows.Client.CBS_1000.22000.194.0_x64__cw5n1h2txyewy MicrosoftWindows.Client.WebExperience_421.20031.315.0_x64__cw5n1h2txyewy

这个问题很奇怪，我无法复现，我使用了standard用户，但是一切正常

**Comment by iPixelOldC** [comment]
我也遇到了这种问题，我是按`常规：使用应用安装程序 (App Installer)`安装的（出现问题后，还用mmc删除过证书，卸载软件，用第一种ps来安装，问题一样）。现在也是一点视频就闪退，解码器选的也是HEVC（确认电脑已安装解码器，安装的是以前那个免费的OEM的那个）。至于日志，这个日志应该去哪里找啊？谢谢

**Comment by delay1** [comment]
问题+1，设备是surface pro 7，打开视频就闪退

**Comment by Three-taile-dragon** [comment]
我也是同样的问题，系统为
版本	Windows 11 家庭中文版 Insider Preview
版本	Dev
安装日期	‎2021/‎9/‎30
操作系统版本	22468.1000
体验	Windows Feature Experience Pack 1000.22468.1000.0
设备:联想拯救者R9000P

**Comment by joesphsam** [comment]
同样的问题，Windows11，CPU也是瑞龙5PRO的4000系列（4650U），MPEG-2、VP9、HEVC都已经安装，显卡驱动已重装（AMD的集成显卡），点任意视频直接卡住然后闪退，日志也是显示控制器加载完成。

**Comment by zangxx66** [comment]
我的是AMD Ryzen 7 4800H，看了上面的评论好像基本都是A卡闪退，不会是L3缓存的锅吧  
![QQ截图20211016145637](https://user-images.githubusercontent.com/14540861/137577254-d6921ee6-3860-45d0-9c86-f0836e4da767.png)

**Comment by duangvps** [comment]
我的是AMD Ryzen 7 5800H 同样有闪退的问题
