### ISSUE TITLE
[Feature]关于在左侧菜单中添加稍后再看、关注、收藏、历史记录的建议

### ISSUE THREAD

**Issue by dfgggg233** [Richasy/Bili.Uwp#295]
## 描述解决方案
个人认为稍后再看、收藏、我的关注。、历史记录等功能较为常用且重要。而目前这些功能仅能通过点击右上角的用户头像后展开的二级菜单打开，略显繁琐。

## 描述可能的替代方案
无

## 备注和截图
作者大大开发维护辛苦啦

**Comment by Richasy** [comment]
这些都是和用户有关的功能，需要放在用户面板中。目前暂不考虑移至左侧。
对于部分小屏设备，侧边栏的滚动同样麻烦。

我会在以后发布更好的解决方法以满足用户的自定义需求

**Comment by ReoKodama** [comment]
我也想要这个，感觉很实用啊，麻烦作者大大再考虑下，辛苦了
