### ISSUE TITLE
[Doc] 一些问题

### ISSUE THREAD

**Issue by heartacker** [Richasy/Bili.Uwp#297]
1. 请问这个会覆盖旧版的吗？
   - 这个是旧版本的更新吗？我安装之后为什么会出现两个哔哩
2. 这个会在商店发布吗？

**Comment by Richasy** [comment]
这些是需要添加在“常见问题”里的内容吗？

**Comment by heartacker** [comment]
谢谢，我安装之后看到了，帮助里面说后续会个更新。但是我现在安装之后，出现了两个哔哩，就这个没搞明白

**Comment by Richasy** [comment]
现在是技术预览版，还没有上商店，为了给大家一个回退的渠道，所以允许两者共存
