### ISSUE TITLE
[Bug] 设备surface pro 7 出现无法播放视频bug 

### ISSUE THREAD

**Issue by longshaoyou** [Richasy/Bili.Uwp#310]
## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 点击视频，然后视频无法播放
3. 点击直播，一开始也无法自动播放，然后点一下那个开始，就能播放了

## 环境
x

应用来源：

Github

应用版本：{应用版本} 2.2109.2501.0

系统版本：

- [ ] Windows 11 (22000)

运行设备：

surface pro 7

## 日志记录

|System.Exception: 播放失败: SourceNotSupported |  | System.Exception: 请求无效，因为已调用了 Shutdown()。 (Exception from HRESULT: 0xC00D3E85)

**Comment by longshaoyou** [comment]
10次里面能成功加载出一次

**Comment by Richasy** [comment]
与 #247 重复
