### ISSUE TITLE
Windows 10/11 S模式下是否无法使用?

### ISSUE THREAD

**Issue by ErrorPower2001** [Richasy/Bili.Uwp#315]
## 描述你想要解决的问题或者功能的使用场景

拥有一台处于Windows **S模式**的Surface Go 2, 通过应用安装程序安装_哔哩_, 将证书安装至`本地计算机`-`受信任的根证书颁发机构`, 且通过UAC验证. 安装_哔哩_后无法允许, 弹出与**非S模式允许的应用**同样的提示.

## 备注和截图

<img width="960" alt="屏幕截图 2021-09-26 213822" src="https://user-images.githubusercontent.com/45718918/134810579-12ec35eb-e981-43f9-8b84-c736cd9852b1.png">

**Comment by Richasy** [comment]
通过侧加载方式安装应用是要打开开发者模式的。
这不是应用能解决的问题

**Comment by ErrorPower2001** [comment]
> 通过侧加载方式安装应用是要打开开发者模式的。
> 这不是应用能解决的问题

是打开了开发者模式。确实不能从非MsStore安装Uwp
