### ISSUE TITLE
[Bug]专栏无法滚动

### ISSUE THREAD

**Issue by 0xc0000142** [Richasy/Bili.Uwp#331]
## Bug 描述

专栏无法滚动
不出现侧边滚动栏

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '专栏'
3. 点击 '顺便一个专栏'
4. 滚动至 '不用滚动'
5. 发现问题

## 预期的行为

鼠标滚轮能够正常滚动专栏内容

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [x] Windows 10 ver.2004 (19042.1237)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

太少了就不当作附件了
```
2021/09/28 17:58:30.347|Info|
系统信息：10.0.19042.1237 | Windows.Desktop | X64
应用信息：2.2109.2801.0 | 中文(简体，中国)
--------
控制器加载完成
|
2021/09/28 17:59:05.609|Info|
系统信息：10.0.19042.1237 | Windows.Desktop | X64
应用信息：2.2109.2801.0 | 中文(简体，中国)
--------
控制器加载完成
|
```

**Comment by lingxd** [comment]
我的鼠标不能响应
