### ISSUE TITLE
[Bug] 无法打开视频详情页

### ISSUE THREAD

**Issue by ClewenWei** [Richasy/Bili.Uwp#333]
## Bug 描述

无法打开任何一个视频的详情页。点击任意一个视频均会导致应用卡住不动，无法操作，最后自动退出。

## 复现步骤

- [x] 该问题在目前的最新版依然可以重现

重现问题的步骤：

1. 打开应用
2. 点击任意一个视频
3. 应用卡住无法操作
4. 应用自动退出

## 预期的行为

可以正常打开并播放视频

## 截图

这是可靠性监视程序的相关截图：
![图片](https://user-images.githubusercontent.com/57256934/135094985-324b3f06-d8e8-449a-8480-68186bbf435c.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：2.2109.2801.0

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

[applog.2021-09-28.log](https://github.com/Richasy/Bili.Uwp/files/7244351/applog.2021-09-28.log)

## 备注

除了此应用之外，我在 Microsoft Store 里下载的同一个作者开发的 RSS 追踪也有类似的在可靠性监视程序中和 SharedLibrary.dll 有关的问题，不过表现在打开 RSS 追踪后显示包括应用图标的启动页面后立即自动关闭。

**Comment by Richasy** [comment]
请尝试重装一下显卡驱动，目前暂不能复现这个问题
