### ISSUE TITLE
[Bug] 在打开clash翻墙的状态下，无法联网

### ISSUE THREAD

**Issue by panxlhe** [Richasy/Bili.Uwp#338]
## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开clash
2. 打开应用，首页一直转圈

## 截图
![image](https://user-images.githubusercontent.com/77908984/135187615-fce40be0-354e-4c2e-92b2-4f0ebe8a5399.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [x] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by Creatoria** [comment]
是否启用了uwp loopback呢？

**Comment by Richasy** [comment]
参见wiki中的常见问题自行解决
