### ISSUE TITLE
[Bug]视频画面卡住，音频任在正常播放

### ISSUE THREAD

**Issue by MioAkiyamaQAQ** [Richasy/Bili.Uwp#343]
## Bug 描述
视频画面突然卡住，音频任正常播放

应用版本号：2.2109.2801

重现问题的步骤：

1. 打开应用
2. 进入 BV11q4y1o7wj
3. 点击 播放
4. 滚动至 1:24
5. 发现问题

## 预期的行为
希望修复bug

## 截图
![image](https://user-images.githubusercontent.com/91041333/135253320-df64c76f-3e5b-43ef-9ad8-543817f2793f.png)

![屏幕截图 2021-09-29 183508](https://user-images.githubusercontent.com/91041333/135252936-1e75d3d7-d5f4-472c-8de1-d2121913ec48.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{2.2109.2801}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by Richasy** [comment]
可能是清晰度太高（该视频支持4K），由于带宽不够，或者视频解析能力不足导致卡顿，建议切换至1080P播放
