### ISSUE TITLE
[Feature] 评论区增加楼层号显示

### ISSUE THREAD

**Issue by TigerCubDen** [Richasy/Bili.Uwp#345]
## 描述你想要解决的问题或者功能的使用场景

bilibili 官方为了更好的控评取消了评论区的楼层号显示与删除日志，但似乎仍可以通过一些办法获取到楼层号。故我希望将原本应有的功能加回来。

## 描述解决方案

显示每个评论的楼层号，包括楼中楼的楼层号。

## 描述可能的替代方案

实现方法可以借鉴已有的[脚本](https://greasyfork.org/zh-CN/scripts/403348-bilibili-%E7%BF%BB%E9%A1%B5%E8%AF%84%E8%AE%BA%E5%8C%BA)。

## 备注和截图

上述脚本实现效果：

![image](https://user-images.githubusercontent.com/55782476/135280182-dee3cbd3-38d3-4c43-9b03-ae5bc2107835.png)

**Comment by Richasy** [comment]
这个楼层号有什么用呢？

**Comment by tm0210** [comment]
鸡肋功能，想用的人装个脚本就好了

**Comment by tm0210** [comment]
一般人用不上，没必要添加。要用的，装个脚本就好了，没必要给哔哩添加。哔哩的目标应该是小而精，追求功能全面的用edge+网页版bilibili就好了。

**Comment by TigerCubDen** [comment]
不是所有视频的评论区都能反应观看者的真实看法。在存在争议内容的视频上，评论总数只有200多，但楼层却高达30000以上，例如 [BV13X4y137Ld ](https://www.bilibili.com/video/BV13X4y137Ld)、[BV1mi4y1T7UB](https://www.bilibili.com/video/BV1mi4y1T7UB)、[BV1UQ4y1Y7D2](https://www.bilibili.com/video/BV1UQ4y1Y7D2) 这样的例子比比皆是。所以我认为楼层号并不是可有可无，也跟评论内容本身一样有着举足轻重的作用。

![image](https://user-images.githubusercontent.com/55782476/135399947-3ed75446-bf27-4256-bc48-4c0970471a2e.png)

**Comment by TigerCubDen** [comment]
> 一般人用不上，没必要添加。要用的，装个脚本就好了，没必要给哔哩添加。哔哩的目标应该是小而精，追求功能全面的用edge+网页版bilibili就好了。

看不出来会造成任何臃肿，往里面添加会员购、直播打赏之类的才是追求大而全的产物。

**Comment by Richasy** [comment]
@TigerCubDen  从需求来看，这并不是一个会影响到大部分人的需求。楼层号的添加并不能带来直观的结论，通过对楼层号的分析也许可以得出视频是否控评，但这对哔哩来说并不是优先考虑的事情，目前暂不会将该功能加入到哔哩之中
