### ISSUE TITLE
[Bug]观看视频结束时卡死

### ISSUE THREAD

**Issue by fxzxmicah** [Richasy/Bili.Uwp#363]
## Bug 描述
有比较大的几率在视频播放完毕时导致程序卡死。

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 播放视频（暂时没有感觉到卡死与特定视频的关系）
3. 正常播放至结束（也暂不清楚如果快进会不会导致这个问题）
4. 软件整个界面卡死
5. 发现问题

## 预期的行为

播放至结束以后可以正常操作，正常退出以观看其它视频，而不是卡死无法操作，只能重启应用。

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：2.2110.1.0

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [x] Windows 10 ver.2004 (19041)
（准确来说是21H1:19043）
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

[applog.2021-09-30.log](https://github.com/Richasy/Bili.Uwp/files/7267237/applog.2021-09-30.log)
[applog.2021-10-01.log](https://github.com/Richasy/Bili.Uwp/files/7267239/applog.2021-10-01.log)

**Comment by Richasy** [comment]
无法复现这个问题，请更新系统或升级应用

**Comment by fxzxmicah** [comment]
![image](https://user-images.githubusercontent.com/48860358/141620450-fd9d3c83-e625-461a-bd8c-81f40721efd9.png)
最新版应用，成功复现了。
我个人觉得可能和切换虚拟桌面有关？因为这个应用程序的旧版和逍遥橙子的新版都曾经出现过切换虚拟桌面再切换回来导致整个应用界面卡死的情况。
