### ISSUE TITLE
[Bug] 无法账号密码登录

### ISSUE THREAD

**Issue by JohnsonRan** [Richasy/Bili.Uwp#364]
## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 打开账号密码登录
3. 登录后窗口退出并没有登录
5. 发现问题

## 预期的行为

登陆成功
## 截图

https://user-images.githubusercontent.com/89735151/135642802-23fe005d-8686-490e-9d9a-27db05c316a3.mp4

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 备注

扫码登录可正常登录，账号密码不行

**Comment by Richasy** [comment]
不能复现这个问题，请确认输入的账户密码正确。
另外，使用扫码登录是推荐的方式，安全且高效。由于第三方性质，账户密码登录会逐渐废弃
