### ISSUE TITLE
[Bug]打开视频后黑屏无法加载，切换清晰度后才能正常播放

### ISSUE THREAD

**Issue by St-Cai** [Richasy/Bili.Uwp#372]
## Bug 描述

对于大部分视频，打开后加载不出来，无法播放，必须切换一次清晰度后才能正常播放。

## 复现步骤

最近版本都是这样，包括最新版本

重现问题的步骤：

例如：
1. 打开应用
2. 首页点击视频BV16R4y1n7bj (此时默认1080p)
3. 播放器黑屏无法正常加载
4. 切换到720p，视频正常播放
5. 退出到首页重新点击该视频 (此时默认720p) 依旧无法播放
6. 再次切换到1080p，视频正常播放

希望修复bug

## 截图

![image](https://user-images.githubusercontent.com/55645331/135708439-944bfe23-b582-4637-85fd-4312a530b040.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：2.2110.1.0
系统版本：WIN10 21H1 (19043)

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

[applog.2021-10-02.log](https://github.com/Richasy/Bili.Uwp/files/7271078/applog.2021-10-02.log)

**Comment by Richasy** [comment]
与  #747 类似，将合并处理
