### ISSUE TITLE
[Bug]直播就是黑屏，应该不会是代理的问题

### ISSUE THREAD

**Issue by FoLeaf** [Richasy/Bili.Uwp#378]
## Bug 描述

直播无法播放 黑屏 手机和浏览器正常 有弹幕有音频无视频

## 复现步骤

- [ x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '直播'
3. 点击 '随意一个直播间'
4. 滚动至 '....'
5. 发现问题

## 预期的行为

被
修复

## 截图

![QQ截图20211002230828](https://user-images.githubusercontent.com/58499391/135722403-5e885eb7-1e79-4b7f-91f7-2c369f0e73de.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x ] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ x] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by Aoesun** [comment]
我是推荐直播点进去可以正常显示画面，从“关注的直播间”里点进去的只有弹幕和声音没有画面
系统版本是Windows11
其他一样

**Comment by Richasy** [comment]
暂时无法复现，请根据wiki里的常见问题检查下显卡设置或者解码器配置
