### ISSUE TITLE
[Feature]对于功能上的一些小建议

### ISSUE THREAD

**Issue by GaroneHuang** [Richasy/Bili.Uwp#382]
云之幻大佬做的哔哩太好看了吧！

就是提一些在功能上的小建议（我平时用的比较多的，不代表大家的需求）：
1. 收藏中的追番和追剧都是分为“想看”“在看”“看过”三个part的，但是哔哩好像只能看到在看的。
2. 弹幕边框的粗细可否加一个调节选项呢。
3. 目前点开某个up主的头像时，好像无法查看ta的动态，ta发布的视频也可否加一个搜索功能呢。
4. 其他的一些uwp应用好像可以看到港澳台的番剧（不需要挂梯子），而且也能看到哔哩哔哩出差的视频列表，哔哩好像和手机端一样屏蔽了这些番剧，想请问大佬是因为技术上的原因吗。

**Comment by Richasy** [comment]
感谢支持，但请先阅读Issue发布流程
