### ISSUE TITLE
直播功能配合v代理无法使用

### ISSUE THREAD

**Issue by M0st3rKiller** [Richasy/Bili.Uwp#383]
## Bug 描述

使用v2ray开启全局代理后任何直播间均提示请求播放信息失败，但聊天内容可以加载，且视频可以正常观看

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？

重现问题的步骤：

1.使用v2ray代理
2.点击任意直播间

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：2.2110.1.0

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [x] 内测版本 (22000.132)

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

[applog.2021-10-04.log](https://github.com/Richasy/Bili.Uwp/files/7276335/applog.2021-10-04.log)

**Comment by Richasy** [comment]
直播情况比较特殊，不建议开着代理观看，或者参见[常见问题](https://github.com/Richasy/Bili.Uwp/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%BD%BF%E7%94%A8%E4%BA%86%E4%BB%A3%E7%90%86%E6%88%96vpn)关闭网络环回

**Comment by M0st3rKiller** [comment]
> 直播情况比较特殊，不建议开着代理观看，或者参见[常见问题](https://github.com/Richasy/Bili.Uwp/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E4%BD%BF%E7%94%A8%E4%BA%86%E4%BB%A3%E7%90%86%E6%88%96vpn)关闭网络环回

网络环回已经关了，并且根据v2ray的日志来看，所请求的broadcastlv.chat.bilibili.com:443也是直连，或许直播还有其他链接需要开白名单？
