### ISSUE TITLE
[Bug]应用卡死问题

### ISSUE THREAD

**Issue by pxxcjp** [Richasy/Bili.Uwp#388]
## Bug 描述

调整弹幕设置时视频播放完成应用就会卡死
## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）
是最新版本
重现问题的步骤：

1. 打开应用
2. 进入 任意视频
3. 点击 弹幕字体设置
4. 等待视频播放完成
5. 发现问题

## 预期的行为

视频播放完成以后应用就会完全点不了，没有任何反应
## 环境

应用来源：

- [ ] Microsoft Store
- [X ] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

2.2110.1.0

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [X ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by Richasy** [comment]
暂时无法复现这个问题，请升级系统或更新版本后再尝试
