### ISSUE TITLE
[Bug]用 GooglePlay 源的Bilibili APP手机扫码登录显示“不支持的二维码”

### ISSUE THREAD

**Issue by qiansen1386** [Richasy/Bili.Uwp#389]
## Bug 描述

用 GooglePlay 源的 BilibiliAPP 扫码显示：
![a42440ff65ecca1e9fe4789758c063a](https://user-images.githubusercontent.com/1759658/135957214-b5d5e4d9-a809-4ecf-ab14-d7045c04f072.jpg)

## 复现步骤

- [x] 这个问题是否能在最新版本中复现

重现问题的步骤：

1. 打开应用
2. 点击 头像图标
4. 用 GooglePlay 源的 Bilibili app 扫码
5. 发现问题

## 预期的行为

在手机上打开登录授权页面，授权后可以登录 Bili

## 截图

![a42440ff65ecca1e9fe4789758c063a](https://user-images.githubusercontent.com/1759658/135957214-b5d5e4d9-a809-4ecf-ab14-d7045c04f072.jpg)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 10 ver.21H1 (19043)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

略

**Comment by qiansen1386** [comment]
就是反馈一下，优先度为0

**Comment by Richasy** [comment]
这个不是我能修复的问题，你可以用国内版本，或者是使用账号密码登录
