### ISSUE TITLE
[Feature]可滚动区域的左侧也应当支持滚动

### ISSUE THREAD

**Issue by northword** [Richasy/Bili.Uwp#395]
## 描述你想要解决的问题或者功能的使用场景

![Snipaste_2021-10-05_20-48-52](https://user-images.githubusercontent.com/44738481/136026537-bc605e85-d23b-41c1-a5af-b0723f1058d2.png)

如图所示，当前的滚动区域时黄色矩形，在内容区域右侧的空白处也是可以通过滚轮滚动列表的。但是在左侧（红色矩形范围内）却无法滚动，感觉这不符合直觉，也不对称，我每次都是鼠标放在红色范围内滚轮，发现划不动，之前旧版本的哔哩也是这样。

## 描述解决方案

红色区域也可以滚动

## 描述可能的替代方案

暂无

## 备注和截图

上图

**Comment by SelfEnough** [comment]
左侧点击某个选项卡，如果直接激活滚轮状态就好了。这样对于飞鼠用户特别舒服，
目前飞鼠用户需要先把鼠标移动到楼主所说的区域，点击，才能激活这块区域的滚轮
