### ISSUE TITLE
[Bug]打开视频闪退

### ISSUE THREAD

**Issue by SilenceAkarin** [Richasy/Bili.Uwp#396]
## Bug 描述
![bug](https://user-images.githubusercontent.com/74251339/136030581-73f320dd-d5ef-4cfc-b11b-19ffe9edb526.gif)
在搜索页面搜索番剧，从番剧页面点开想看的番后闪退

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 10 ver.21H1 (19043)
- [ ] Windows 11 (22000)

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 备注

无

**Comment by Richasy** [comment]
请尝试重装一下显卡驱动
