### ISSUE TITLE
[Bug]第一次可以打开视频，但是再重新打开或者打开其他视频无法显示但有声音

### ISSUE THREAD

**Issue by ricardo-hash** [Richasy/Bili.Uwp#417]
## Bug 描述

第一次可以打开视频，但是再重新打开或者打开其他视频无法显示但有声音   任何模块都是如此

## 复现步骤

本人使用最新版

重现问题的步骤：

1. 打开应用
2. 进入 任意视频
3. 点击 返回
4. 重新进入视频
5. 无法打开视频

## 预期的行为

问题被解决

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：2.2110.10

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

2021/10/07 18:54:33.083|Error|
系统信息：10.0.22000.194 | Windows.Desktop | X64
应用信息：2.2110.1.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: DecodingError |  | System.Exception: 请求无效，因为已调用了 Shutdown()。 (Exception from HRESULT: 0xC00D3E85)

**Comment by Richasy** [comment]
根据网友反馈，重装显卡驱动可以解决这个问题，建议尝试

**Comment by Richasy** [comment]
暂时关闭这个问题，有需要可以再次打开
