### ISSUE TITLE
[Bug] 网络正常时提示网络连接异常

### ISSUE THREAD

**Issue by sduoduo233** [Richasy/Bili.Uwp#434]
## Bug 描述

开代理了，也设置了哔哩的loopback

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 已连接wifi，但是被windows错误的识别为无internet
2. 启动哔哩
3. 提示无网络

## 预期的行为

不根据系统的wifi状态判断是否有网

## 截图

<img width="1080" alt="捕获" src="https://user-images.githubusercontent.com/85996970/136535680-5fd1f2f2-85fd-428b-91a9-d706acd69a11.PNG">

<img width="720" alt="捕获2" src="https://user-images.githubusercontent.com/85996970/136535710-038be6d5-fe7f-4e2e-9078-433eea5a4953.PNG">

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：2.2110.2.0

系统版本：

Windows 10 21H1(19043)

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

[applog.2021-10-08.log](https://github.com/Richasy/Bili.Uwp/files/7310310/applog.2021-10-08.log)

**Comment by Richasy** [comment]
参看Issue置顶的常见问题进行处理
