### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by jackylai111** [Richasy/Bili.Uwp#445]
完全无法登录，包括使用二维码和密码登录，尝试多个版本都无法登录（包括最新版本）

复现步骤 ：

1. 打开应用
2. 进入二维码登录
3. 手机显示“无效的二维码”
4. 使用密码登录
5. 显示“用户名或密码错误”

应用来源：

- [x ] Microsoft Store
- [ ] Github
- [ ] 其他来源（请注明来源）

应用版本：2.2110.2.0

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [ x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

![image](https://user-images.githubusercontent.com/92164776/136563936-d0d312bb-27fb-4cd3-804b-540e10742835.png
![1633698464824](https://user-images.githubusercontent.com/92164776/136564041-6844ba43-626a-48eb-9aff-41e40dc604b4.jpg)

**Comment by Richasy** [comment]
用户名密码错误我没辙。
但是无效的二维码这个，你可以用国内的APP扫码试试
