### ISSUE TITLE
希望增加弹幕显示区域和弹幕速度

### ISSUE THREAD

**Issue by jwy090815** [Richasy/Bili.Uwp#464]
首先感谢开发者开发uwp版的bilibili，希望能做的更好
希望对弹幕有更详细的设置，像B站官方一样增加弹幕1/4,1/2的显示设置和弹幕的速度设置
还有就是增加鼠标滚轮调节音量的功能

**Comment by Richasy** [comment]
- 与 #448 #168 重复
- 不合发布规范
