### ISSUE TITLE
[Feature]请求增加历史记录直接从之前看到的时间点开始播放的功能

### ISSUE THREAD

**Issue by VincentChance0120** [Richasy/Bili.Uwp#466]
## 描述你想要解决的问题或者功能的使用场景

和网页端和手机端一样，从历史播放点进视频后直接从之前看到的时间点开始播放。

## 描述可能的替代方案

历史播放页面显示之前播放到的时间点

**Comment by Richasy** [comment]
已修复，会在下个版本更新
