### ISSUE TITLE
[Bug]开启垂直同步的情况下，全部播放直播会有卡顿1s，同时弹出媒体传输控件1s左右。

### ISSUE THREAD

**Issue by billowssun** [Richasy/Bili.Uwp#475]
问题
开启垂直同步的情况下，全部播放直播会有卡顿0.5s，同时弹出媒体传输控件0.5s左右。

复现步骤
1打开bilibili直播
2进入全屏模式
3平均1-2分钟复现一次

目前使用最新版本

重现问题的步骤：

应用来源Github

应用版本：2110.2.0

系统版本：windows11 22000.258

运行设备：台式机

**Comment by Richasy** [comment]
这个不算是应用的问题，事实上这个问题也无法通过应用来解决
