### ISSUE TITLE
[Bug]打开任意视频或直播间即闪退

### ISSUE THREAD

**Issue by omoidesu** [Richasy/Bili.Uwp#492]
## Bug 描述
打开任意视频、番剧、直播间之后应用闪退

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 打开任意视频或任意直播间
3. 发现问题

## 预期的行为

能够正常使用

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [x] Windows 11 专业版 Insider Preview(22449.1000.0)

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

[applog.2021-10-16.log](https://github.com/Richasy/Bili.Uwp/files/7357040/applog.2021-10-16.log)
## 备注

与系统版本应该无关，surface同样用过这个测试版然而应用使用正常

**Comment by Richasy** [comment]
与 #291 重复

**Comment by omoidesu** [comment]
系统更新至22478.1012该问题消失，目前可以正常使用
