### ISSUE TITLE
[Bug]视频播放完毕后卡死

### ISSUE THREAD

**Issue by shacha086** [Richasy/Bili.Uwp#508]
## Bug 描述

视频播放完毕后整个界面卡死，但不显示未响应

## 复现步骤

- [y] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入视频
3. 点击弹幕字体设置
4. 停留在此界面，直到视频播放完毕
5. 发现问题

## 预期的行为

界面卡死不动

## 截图

![image](https://user-images.githubusercontent.com/50512232/137610380-2ba9bdac-5e2f-478e-a434-7cf8d8c372de.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：2.2110.3.0

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

[applog.2021-10-17.log](https://github.com/Richasy/Bili.Uwp/files/7358695/applog.2021-10-17.log)

**Comment by Richasy** [comment]
与 #792 合并处理
