### ISSUE TITLE
[Doc]证书可以安装至“受信任人”

### ISSUE THREAD

**Issue by SpecterShell** [Richasy/Bili.Uwp#521]
## 关联文档

[下载并安装哔哩的详细说明](https://github.com/Richasy/Bili.Uwp/wiki/%E4%B8%8B%E8%BD%BD%E5%B9%B6%E5%AE%89%E8%A3%85%E5%93%94%E5%93%A9%E7%9A%84%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E)

## 描述

证书可以安装至“受信任人”，至少比安装到“受信任的根证书颁发机构”安全。

![image](https://user-images.githubusercontent.com/56779163/138190948-e32db5a7-bb64-42d7-be0c-7862f29526ea.png)

## 预期的内容

> 选择 `将所有的证书都放入下列存储`，并点击 浏览，选择 `受信任人`，点击 确定，再点击 下一页。

## 备注

安装脚本也可以改一下。

**Comment by kettly1260** [comment]
为什么我添加到受信任人之后还是不行啊
