### ISSUE TITLE
[Bug]可以播放视频，但是仅限软件打开之后播放的第一个视频

### ISSUE THREAD

**Issue by jblfm** [Richasy/Bili.Uwp#525]
## Bug 描述

<可以播放视频，但是仅能正常播放打开ump之后播放的第一个视频，之后的视频只能播放声音>

## 复现步骤

- [可以] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 随便打开一个视频
3. 关闭并切换一个视频
4. 发现问题

## 预期的行为

<黑屏或者出现上个视频的一张图片并正常播放声音>

## 截图

![image](https://user-images.githubusercontent.com/67527715/138539082-e8e5ab4b-c185-435a-b4a4-2e0670d791d4.png)
第一个视频
![image](https://user-images.githubusercontent.com/67527715/138539111-601da5bc-670e-474c-a620-7435d5003ad0.png)
之后的视频

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：2.2110.3.0
系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录
|System.Exception: 播放失败: DecodingError |  | System.Exception: 请求无效，因为已调用了 Shutdown()。 (Exception from HRESULT: 0xC00D3E85)
2021/10/23 10:17:01.788|Error|
系统信息：10.0.22000.258 | Windows.Desktop | X64
应用信息：2.2110.3.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: DecodingError |  | System.Exception: 请求无效，因为已调用了 Shutdown()。 (Exception from HRESULT: 0xC00D3E85)
2021/10/23 10:23:12.018|Info|
系统信息：10.0.22000.258 | Windows.Desktop | X64
应用信息：2.2110.3.0 | 中文(简体，中国)

**Comment by Richasy** [comment]
与 #747 可能是相同问题，将合并处理
