### ISSUE TITLE
[Feature]在动态中以已更新up主添加分类

### ISSUE THREAD

**Issue by XiaoMouz** [Richasy/Bili.Uwp#556]
## 描述你想要解决的问题或者功能的使用场景

能够像网页端/手机端的动态那样显示已更新up主与已开播up主头像，并且能选中这些up主单独查看更新内容（包括动态）

## 备注和截图
以网页端截图为例
![image](https://user-images.githubusercontent.com/54032212/139527315-31771792-c0f5-4659-9524-dec3d40f631d.png)

**Comment by AngelaCooljx** [comment]
求同，按up主分类功能算是b站使用频率较高的功能了，但一直没办法在客户端实现，只能在网页端浏览查看。
