### ISSUE TITLE
[Doc]使用Powershell一键安装时还需要进行一个步骤

### ISSUE THREAD

**Issue by XiaoMouz** [Richasy/Bili.Uwp#557]
## 关联文档

[下载并安装哔哩的详细说明](https://github.com/Richasy/Bili.Uwp/wiki/%E4%B8%8B%E8%BD%BD%E5%B9%B6%E5%AE%89%E8%A3%85%E5%93%94%E5%93%A9%E7%9A%84%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E)

## 描述

除了需要启动开发者模式，应当还需要在`开发者选项>Powershell`将`更改执行策略，以允许本地PowerShell脚本在未签名的情况下运行。远程脚本需要`选项打钩并且单击应用

## 预期的内容

>4.向下找到`PowerShell`标题，将`更改执行策略，以允许本地PowerShell脚本在未签名的情况下运行。远程脚本需要`选项打钩并应用

## 备注

若不允许则有可能在PowerShell安装时出现
```
Install.ps1 : 无法加载文件 Install.ps1，因为在此系统  上禁止运行脚本。有关详细信息，请参阅 https:/go.microsoft.com/fwlink/?LinkID=135170 中的 about_Execution_Policies。
所在位置 行:1 字符: 1
+ F:\Downloads\App_2.2110.5.0_Test\Install.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) []，PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```
错误

**Comment by Richasy** [comment]
感谢指出，已更新
