### ISSUE TITLE
[Doc]Wiki启动开发者模式步骤表述不清，可能导致用户无法找到选项

### ISSUE THREAD

**Issue by XiaoMouz** [Richasy/Bili.Uwp#558]
## 关联文档

[下载并安装哔哩的详细说明](https://github.com/Richasy/Bili.Uwp/wiki/%E4%B8%8B%E8%BD%BD%E5%B9%B6%E5%AE%89%E8%A3%85%E5%93%94%E5%93%A9%E7%9A%84%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E)

## 描述

开发者设置位置在Windows10与11中略有不同，需要修改一下，并且未指明打开哪个选项，实则打开开发人员模式中的`从任意源(包括松散文件)安装应用`即可

## 预期的内容

>1.进入`设置`。
>2.打开`隐私和安全性`页面，在Windows 10中打开`更新和安全`页面。
>3.选择`开发者选项`选项(子列表)。
>4.将`开发人员模式`下的`从任意源(包括松散文件)安装应用`选项打开

## 备注

如您采纳了 #557 中的建议，那么可以将PowerShell相关设置列为第五步，在该issue中我说明了为何需要启用该项

**Comment by Richasy** [comment]
感谢你的建议，目前文档已更新
