### ISSUE TITLE
视频结束时返回或者点击别的界面经常会卡住

### ISSUE THREAD

**Issue by Michaelxia6** [Richasy/Bili.Uwp#570]
## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '...'
3. 点击 '....'
4. 滚动至 '....'
5. 发现问题

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [x] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by AAA-obj** [comment]
我也是，播放完一个视频后直接卡死

**Comment by heartacker** [comment]
我的也是啊

**Comment by heartacker** [comment]
有人知道这是咋回事吗？我的是win 11
|||
|-|-|
版本	|Windows 11 专业版 Insider Preview
版本	|Dev
安装日期	‎|2022/‎1/‎28
操作系统版本|	22543.1000
体验	|Windows Feature Experience Pack 1000.22543.1000.0

**Comment by Richasy** [comment]
与 #792 应是同一问题，合并处理
