### ISSUE TITLE
[Bug]重新打开之后，点击第一个视频会卡顿一会

### ISSUE THREAD

**Issue by shadowlaser** [Richasy/Bili.Uwp#575]
1. 启动哔哩版本2.2110.5.0。
2. 点击推荐页中的任何一个视频，程序会卡顿一会才进入
3. 之后再点击其他视频没有卡顿就进入。
4. 关闭哔哩，重新打开，点击一个视频，程序会卡顿一会。

打开的哔哩第一个视频点击之后，都会卡顿一会才进入，其他时候不会。

**Comment by Richasy** [comment]
新版本会有所缓解，请在新版发布后再看看效果，预计周末发布

**Comment by JasonWei512** [comment]
还是有这个问题
