### ISSUE TITLE
[Feature] 搜索候选列表

### ISSUE THREAD

**Issue by hez2010** [Richasy/Bili.Uwp#581]
## 描述你想要解决的问题或者功能的使用场景

在搜索框输入部分关键字时，希望能弹出一个补全列表提供搜索候选项目可以直接点击进行搜索，这样用户不需要输入完整的关键词就可以进行更精确的搜索

## 描述解决方案

用一个 Timer 当在用户停止输入 100 毫秒后在后台进行搜索，并将其中几个搜索结果的标题提供在补全列表中以便用户进行选择

## 截图

类似这样的东西：

![image](https://user-images.githubusercontent.com/14960345/139850937-2d705cc5-a2de-44d8-8323-e77f54366ff8.png)

**Comment by Richasy** [comment]
已添加，将在下个版本放出
