### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by 1014831410** [Richasy/Bili.Uwp#590]
## Bug 描述

在搜索框中，使用搜狗双拼输入法无法正常输入文字
## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 点击顶部搜索框
4. 输入xian
5. 无法输入西安

## 环境

应用来源：

- [ ] Microsoft Store
- [ x] Github
- [ ] 其他来源（请注明来源）

应用版本：{最新}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ x] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by Richasy** [comment]
输入法不在修复范围内（我也修复不了），要避免类似问题，请使用微软输入法
