### ISSUE TITLE
[Doc] 安装文档图片链接格式纠正

### ISSUE THREAD

**Issue by Xnor-bear** [Richasy/Bili.Uwp#593]
## 关联文档

[下载并安装哔哩的详细说明](https://github.com/Richasy/Bili.Uwp/wiki/下载并安装哔哩的详细说明)

## 描述

安装文档图片链接格式纠正，见下图。
将「下载并安装哔哩的详细说明.md」中 `![**](./images/install/****.***) ` 改为 `![**](./images/Install/****.***) `  即可。
其他页面暂无此问题。

## 预期的内容

![20211104](https://user-images.githubusercontent.com/54651817/140290896-ca2f3e87-6bb6-4de5-9c54-b2ac36d7595d.gif)

## 备注

貌似是 `raw.githubusercontent.com` 本身问题，在手机上复现。
当然文档本就还在编写中，有问题挺正常……

以及
_Footer 提示可以提交 PR 协助修改，但网页上貌似并没有开放权限，直接 Fork 仓库一起 PR 提示没有变动，直接 Push 提示没有权限。
![image](https://user-images.githubusercontent.com/54651817/140293190-efd93040-3a12-4517-ad03-76c6778c8861.png)
<hr>

![image](https://user-images.githubusercontent.com/54651817/140293708-d514b901-77bd-4d52-9a1c-51dc72584318.png)
<hr>

![image](https://user-images.githubusercontent.com/54651817/140293365-ab19cb15-0ef4-4eb3-911c-31734ea5b6da.png)
<hr>

刚学习 Git 没多久 望赐教

**Comment by Richasy** [comment]
感谢提醒，现已修正，并公开权限
