### ISSUE TITLE
[Bug] 可以播放第一个视频，但在看其他视频就黑屏

### ISSUE THREAD

**Issue by Uiisland** [Richasy/Bili.Uwp#594]
## Bug 描述
可以播放第一个视频，但在看其他视频就黑屏
有声音，有弹幕，但是是黑屏状态，已经安装了解码器

## 复现步骤
重启应用随意点击一个视频，可以正常观看，推出当前视频，在选择其他视频就黑屏
- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

## 截图
`<a href="https://ibb.co/R0k5v01"><img src="https://i.ibb.co/R0k5v01/2021-11-04-193637.png" alt="2021-11-04-193637" border="0"></a>`
[https://ibb.co/R0k5v01](url)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

系统版本：2200.282

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录
[applog.2021-11-04.log](https://github.com/Richasy/Bili.Uwp/files/7482491/applog.2021-11-04.log)
[applog.2021-11-05.log](https://github.com/Richasy/Bili.Uwp/files/7482493/applog.2021-11-05.log)

## 备注

今天又试了一下，还是这个问题，但是可以通过切换不同的清晰度让黑屏视频变正常

**Comment by Three-taile-dragon** [comment]
我也遇到的同样的问题

**Comment by xiaoxi654** [comment]
可以复现，从播放第二个视频开始，视频会黑屏，切换清晰度可解决
log 中的报错如下

```log
2021/11/13 12:36:53.417|Error|
系统信息：10.0.22494.1000 | Windows.Desktop | X64
应用信息：2.2110.5.0 | 中文(简体，中国)
--------
|System.Exception: 播放失败: DecodingError |  | System.Exception: 请求无效，因为已调用了 Shutdown()。 (Exception from HRESULT: 0xC00D3E85)
```

**Comment by Richasy** [comment]
与 #747 可能是相同问题，将合并处理
