### ISSUE TITLE
[Bug]直播那边，在点击关注的直播间内的主播后，无法进直播，但可以听到声音。

### ISSUE THREAD

**Issue by iPixelOldC** [Richasy/Bili.Uwp#595]
## Bug 描述

1. `直播`那边，在点击`关注的直播间`内的主播后，无法进直播，但可以听到声音。
2. 有时点这个`关注的直播间`内的主播图标太快的话，会显示无法获取用户关系，然后软件卡死。
3. 但是从下面的推荐里进，是一切正常的

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '直播'
3. 点击 '关注的直播间内的主播'
5. 发现问题

## 预期的行为
打开直播间

## 环境

应用来源：

- [ ] Microsoft Store
- [X] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}
App_2.2111.1.0_Test
系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [X] Windows 10 19042.1288
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [X] 笔记本
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

<!-
[applog.2021-11-04.log](https://github.com/Richasy/Bili.Uwp/files/7474673/applog.2021-11-04.log)
- 应用会记录一些网络请求错误和运行时错误的日志，
请在应用设置中打开 日志记录 面板，打开日志文件夹，选取问题发生当日的日志记录作为 Issue 的附件上传。
上传就是将日志文件拖拽到当前的输入框内即可 -->

## 备注

我编码器选的是HEVC，关了pCDN

综上，谢谢:D

**Comment by Richasy** [comment]
与 #747 合并处理
