### ISSUE TITLE
快捷键需求，希望可以快捷键操作全窗口模式和全屏模式

### ISSUE THREAD

**Issue by AAAAAnguslu** [Richasy/Bili.Uwp#596]
## 描述你想要解决的问题或者功能的使用场景
全窗口模式、全屏模式和返回都需要进行点击，如果可以快捷键操作就好了，目前清晰度选项还没有4K选项，有计划加上么

全窗口模式、全屏模式和返回都需要进行点击，如果可以快捷键操作就好了。目前遇到一点小bug，鼠标放在视频区域，按空格键有时候无法暂停视频。

## 描述解决方案
比如按W键打开/关闭全窗口模式，按Enter打开/关闭全屏模式，按Ctrl+W关闭视频窗口进入主页面等等快捷键操作。目前Enter是暂停视频，可以改成打开/关闭全屏模式。开发者幻哥准备什么时候在清晰度加上4K选项呢😂

**Comment by Richasy** [comment]
快捷键在帮助&支持页面里有写，F10是全窗口，F11是全屏。至于4K，视频支持4K就能显示（当然，你要是大会员才行）

**Comment by AAAAAnguslu** [comment]
幻哥，F10和F11对笔记本操作可能有点麻烦，笔记本Fxx键都有特定功能，按Fn+F10/F11跨度有点大，可以考虑把快捷键放在键盘左边区域的组合键么
