### ISSUE TITLE
从铺满窗口恢复到常规窗口有时会出现如图现象

### ISSUE THREAD

**Issue by AAAAAnguslu** [Richasy/Bili.Uwp#598]
## Bug 描述
1，从铺满窗口恢复到常规窗口时有时候会出现如图闪屏情况
2，从铺满窗口切换到全屏，有明显卡顿
3，看直播时，经常动不动就卡，win11系统，核显，网速也挺快
4，播放控制条改为手动时，经常出现点一下视频区域出现控制条又自动消失，这个出现频率很高很高

## 复现步骤
目前用的最新版，以上问题基于win11正式版最新版，核显，哔哩最新版
![IMG20211104232916](https://user-images.githubusercontent.com/89283966/140378912-5a83fc7b-7e84-4801-b12d-f7eac14df2bc.jpg)

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '...'
3. 点击 '....'
4. 滚动至 '....'
5. 发现问题

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by hez2010** [comment]
闪屏和app无关，考虑可能是显卡驱动的bug
