### ISSUE TITLE
快捷键F10/F11操作全窗口和全屏对笔记本用户不太方便

### ISSUE THREAD

**Issue by AAAAAnguslu** [Richasy/Bili.Uwp#600]
## 描述你想要解决的问题或者功能的使用场景
幻哥，F10/F11的快捷键操作对笔记本有点难搞，笔记本F1-F12本身有功能的（声音和亮度控制的几个F功能键比较常用），每次按Fn+F10/F11来操作全窗口和全屏有点难操作，跨度略大，有打算利用键盘左边区域的组合键进行快捷操作么

## 描述解决方案
建议用键盘左边区域的组合键进行全窗口和全屏操作

**Comment by heartacker** [comment]
建议更换电脑/ 😄

**Comment by qianrongze** [comment]
建议外接键盘/调整视频默认播放模式设置

**Comment by AnLazyOtter** [comment]
建议将电脑键盘FN功能键默认值调整为fn而非功能。
