### ISSUE TITLE
[Bug]无法登录，显示账号冻结

### ISSUE THREAD

**Issue by MisakaSakura** [Richasy/Bili.Uwp#603]
## Bug 描述

重置了一回电脑，重置前能正常使用，另一个UWP版可以正常登录，网页版手机客户端也能正常使用

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

## 截图

![image](https://user-images.githubusercontent.com/30547550/140504651-ec779abb-8bfe-4b30-8ba8-4ceb07c926fe.png)

## 环境

![image](https://user-images.githubusercontent.com/30547550/140504704-4b777bc3-7ed2-42e8-a5ad-b562b2a5ed29.png)

应用来源：

Github

应用版本：{应用版本}
2.2111.1.0以及上版本
系统版本：

- [x] Windows 11 (22000)

运行设备：

 桌面/台式机

**Comment by Richasy** [comment]
😂这个我没辙，你可以试试扫码登录

**Comment by MisakaSakura** [comment]
> 😂这个我没辙，你可以试试扫码登录

我用play版扫码显示不支持，不过多次重复登录有几率登入，可能是b站作了限制
