### ISSUE TITLE
[Bug]视频播放帧率太低，小窗模式帧率正常

### ISSUE THREAD

**Issue by SakuraCodes** [Richasy/Bili.Uwp#604]
## Bug 描述

 点开视频可以明显感到帧率不足24帧，切换到小窗模式帧率恢复正常 

我用过的所有第三方B站，都有这情况（装过很多版本的Windows都有这情况，可以排除系统版本问题，会不会是调用接口的问题）

应用来源：

- [x] Github

应用版本：Bili.Uwp_2.2111.1.0_x64

系统版本：（以前用过专业版不清楚版本号了）

- [x] Windows 10 ver.19043.1288 （工作站版本）

运行设备：

- [x] 桌面/台式机

**Comment by hez2010** [comment]
如果你屏蔽了核心显卡那就会出现这个问题

**Comment by hez2010** [comment]
如果你屏蔽了核心显卡那就会出现这个问题

**Comment by SakuraCodes** [comment]
> 如果你屏蔽了核心显卡那就会出现这个问题，会导致所有调用系统播放组件的帧数低于20，应用这边无法处理。

我的是无核显有英特尔独显，请问如何切换独显运作，或者调用potplayer

**Comment by hez2010** [comment]
虽然不知道是否有效，可以试试在系统的图形设置中把哔哩设置为高性能看看。

**Comment by SakuraCodes** [comment]
> 虽然不知道是否有效，可以试试在系统的图形设置中把哔哩设置为高性能看看。

不行，网上的控制面板方法也试了，我再去找找看，就不麻烦了哈

**Comment by juzijun233** [comment]
之前看到说从英伟达控制面板中关闭gsync，你可以试试。
但我这边没有这个选项，只能在Windows设置中将uwp应用改为节能：使用英特尔和核显来播放。这样确实就好了，但是对于没有核显的好像挺难办了

**Comment by SakuraCodes** [comment]
> 之前看到说从英伟达控制面板中关闭gsync，你可以试试。 但我这边没有这个选项，只能在Windows设置中将uwp应用改为节能：使用英特尔和核显来播放。这样确实就好了，但是对于没有核显的好像挺难办了

哇~解决了（关闭gsync），3Q~

**Comment by SakuraCodes** [comment]
> 之前看到说从英伟达控制面板中关闭gsync，你可以试试。 但我这边没有这个选项，只能在Windows设置中将uwp应用改为节能：使用英特尔和核显来播放。这样确实就好了，但是对于没有核显的好像挺难办了

 哇~解决了（关闭gsync），3Q~
