### ISSUE TITLE
[Bug]拖动进度条的时候视频经常会莫名鬼畜加速然后进度条就结束

### ISSUE THREAD

**Issue by Michaelxia6** [Richasy/Bili.Uwp#609]
## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '...'
3. 点击 '....'
4. 滚动至 '....'
5. 发现问题

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [x] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by YexuanXiao** [comment]
同样问题，视频快进错误

**Comment by Richasy** [comment]
该问题由MediaPlayerElement控件引起，需等 WinUI 团队修复
