### ISSUE TITLE
[Bug] 使用鼠标滚轮无法使得页面滚动

### ISSUE THREAD

**Issue by WuMortal** [Richasy/Bili.Uwp#61]
## 复现步骤

鼠标无法滚动

重现问题的步骤：

打开应用软件所有页面使用鼠标滚动滚无法滚动，但是可以使用鼠标拖拽滚动

## 预期的行为

鼠标滚动条可以使页面滚动

## 环境

台式机
设备名称	DESKTOP-QHKCPN2
处理器	Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz   3.60 GHz
机带 RAM	16.0 GB (15.8 GB 可用)

应用来源：

- [x] Github

应用版本：Bili.Uwp_2.2109.1801.0

系统版本：

- [ ] Windows 10 ver.1904 (19043.1165)

运行设备：

- [ ] 桌面/台式机

## 日志记录
[applog.2021-09-18.log](https://github.com/Richasy/Bili.Uwp/files/7189829/applog.2021-09-18.log)

## 备注
![image](https://user-images.githubusercontent.com/25811487/133887962-1e426484-1ea3-4044-b28e-a0e672c8f195.png)

有调整注册中的 FlipFlopWheel 值（达到鼠标滚轮反向）

**Comment by WuMortal** [comment]
打开 视频详情页面 【关联视频】和 【评论】鼠标滚轮使用正常

**Comment by Richasy** [comment]
如果将注册表里的数值调整为默认值，表现是否正常？

**Comment by Richasy** [comment]
另外，请修改一下Issue标题，以阐明问题

**Comment by WuMortal** [comment]
> 如果将注册表里的数值调整为默认值，表现是否正常？

我还原了注册表中的数值，滚轮还是无效

**Comment by Richasy** [comment]
目前收到的报告都是关于Windows 10的，我会尝试找机子进行测试，尽快修复这个问题

**Comment by WuMortal** [comment]
> 目前收到的报告都是关于Windows 10的，我会尝试找机子进行测试，尽快修复这个问题

好的，感谢作者，辛苦了

**Comment by TTvTT** [comment]
我的win10也没有办法滚动

**Comment by Pengkaniu** [comment]
win10专业版2004SurfacePro7 右边插件部分可以滚动，主页面无法滚动。
