### ISSUE TITLE
[Bug]观看长时间视频，界面卡死

### ISSUE THREAD

**Issue by niu164** [Richasy/Bili.Uwp#616]
## Bug 描述
看视频看久了之后，软件里面按钮全部失效，但是放下，关闭能点，视频进度条虽然点不了，但是还能双击播放暂停，关闭后重新打开恢复正常

## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '...'
3. 点击 '....'
4. 滚动至 '....'
5. 发现问题

## 截图
![image](https://user-images.githubusercontent.com/76257039/140883132-6c35613c-e6ef-4fb6-91f4-732698a8f4bd.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [x] Windows 10 ver.2004 (19043)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 
[applog.2021-11-09.log](https://github.com/Richasy/Bili.Uwp/files/7502907/applog.2021-11-09.log)
备注

**Comment by heartacker** [comment]
同样问题

**Comment by CMingXiang** [comment]
发现同样问题

**Comment by Richasy** [comment]
与 #792 合并处理
