### ISSUE TITLE
[Doc] 建议文档添加说明，区分 PowerShell Core 和 Windows PowerShell

### ISSUE THREAD

**Issue by LiamSho** [Richasy/Bili.Uwp#62]
## 关联文档

[下载并安装哔哩的详细说明](https://github.com/Richasy/Bili.Uwp/blob/main/how_to_install.md)

## 描述

`Install.ps1` 在 PowerShell Core 中执行失败，文档中建议提及一下，区分 PowerShell Core 和 Windows PowerShell

![image](https://user-images.githubusercontent.com/28832398/133889308-58c40584-9786-4cce-9b07-7d455701fce9.png)

## 预期的内容

注明区分 PowerShell Core 和 Windows PowerShell

## 备注

（微软一直在推 PowerShell Core 然而这玩意在需要 Windows 平台功能的时候却不好使。。。

**Comment by win98se** [comment]
PowerShell Core 理应是可用的，在安装前运行该命令即可：
```powershell
Import-Module Appx -UseWinPS
```
