### ISSUE TITLE
[Feature]关于评论发布时间格式的改善

### ISSUE THREAD

**Issue by dfgggg233** [Richasy/Bili.Uwp#623]
## 描述你想要解决的问题或者功能的使用场景
在浏览视频评论区时发现评论的时间仅为几时几分的格式,无法确切分清评论的时间

## 描述解决方案
像旧版一样显示几小时前或者几天前,也可加上详细的时间

## 备注和截图
目前![image](https://user-images.githubusercontent.com/91085662/141259553-beed9ab9-6566-4474-a675-50b87ef89ba7.png)
期望![image](https://user-images.githubusercontent.com/91085662/141259689-0ec21ab5-ba1c-49e1-bb72-37ee64f90012.png)

**Comment by Richasy** [comment]
光标移上去即可显示完整时间
