### ISSUE TITLE
[Bug] 部分视频播放失败

### ISSUE THREAD

**Issue by zxc110** [Richasy/Bili.Uwp#624]
## 复现步骤

重现问题的步骤：

部分视频无法播放一直加载，h265播放只有声音没画面

## 环境

Windows 11 (22000.318)
[applog.2021-11-13.log](https://github.com/Richasy/Bili.Uwp/files/7531263/applog.2021-11-13.log)

运行设备：

HP EliteBook 735 G5 / AMD Ryzen 5 PRO 2500U w/ Radeon Vega Mobile Gfx

## 日志记录
|System.Exception: 播放失败: SourceNotSupported |  | System.Exception: 请求无效，因为已调用了 Shutdown()。 (Exception from HRESULT: 0xC00D3E85)
2021/11/13 09:24:26.067|Error|
系统信息：10.0.22000.318 | Windows.Desktop | X64
应用信息：2.2111.1.0 | 中文(简体，中国)

## 备注
尝试了在常见问题中的各种解决办法，还是不管用，h265播放只有声音没画面，常见问题中的视频解码器都安装了

**Comment by Richasy** [comment]
和 #627 合并处理
