### ISSUE TITLE
[Bug]账号异常导致的退出会使软件无法退出和登录

### ISSUE THREAD

**Issue by rainyorange** [Richasy/Bili.Uwp#625]
## Bug 描述

如标题

## 复现步骤

- [x ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release]

重现问题的步骤：

账号出现异常导致需要修改密码重新登录
然后点击软件用户头像

## 预期的行为

可以正常登录

## 截图
![image](https://user-images.githubusercontent.com/36807368/141606092-e6f91dbe-3e62-4455-933a-20c7fbacff2f.png)

## 环境

应用来源：

- [x ] Github

应用版本：{2.2111.1.0}

系统版本：

- [x ] Windows 11 (22000)

运行设备：

- [ x] 桌面/台式机

**Comment by oh-ao** [comment]
我的两个设备都遇到了同样的问题，账号无法加载，头像框一直转圈圈，但能显示和播放首页推荐视频，之前登录的是会员账号，此时会员番剧也可以看，但是播放记录不会同步。
另外，在我对其中一个出现此问题的设备，设置页面里尝试重置和修复哔哩后，首页显示错误信息：发送请求失败，卸载重装问题仍然存在。
[applog.2021-11-23.log](https://github.com/Richasy/Bili.Uwp/files/7585768/applog.2021-11-23.log
![屏幕截图 2021-11-23 121734](https://user-images.githubusercontent.com/94884535/142970699-8af1420e-c82b-4499-8f19-2438dbf5687f.jpg)
)
