### ISSUE TITLE
[Bug]所有视频都无法播放

### ISSUE THREAD

**Issue by Brianwind** [Richasy/Bili.Uwp#629]
## Bug 描述
所有视频都无法播放。
其余所有的信息：包括评论、封面、个人账号信息以及收藏夹等部分的加载都没有问题。
但是点进去视频以后，视频播放栏下面的加载条就一直不消失，无法播放视频。

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 点击任意视频
3. 无法播放

## 截图
![Snipaste_2021-11-15_00-14-43.jpg](https://i.loli.net/2021/11/15/olvMu3Tq1aXe5sn.jpg)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{2.2111.1.0}

系统版本：
版本	Windows 11 家庭中文版
版本	21H2
操作系统版本	22000.282
体验	Windows 功能体验包 1000.22000.318.0

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：
联想Yoga14s 2020 笔记本
处理器	AMD Ryzen 7 4800U with Radeon Graphics            1.80 GHz
机带 RAM	16.0 GB (15.4 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

*有关网络环境：* 北京大学校园网
## 日志记录

[applog.2021-11-15.log](https://github.com/Richasy/Bili.Uwp/files/7534133/applog.2021-11-15.log)

## 备注
解码器都有安装好，在官方网页/app端播放没有问题。

**Comment by Richasy** [comment]
从日志来看是网络问题，作为测试，你可以尝试换一种网络环境（比如用手机开热点）

**Comment by Brianwind** [comment]
> 从日志来看是网络问题，作为测试，你可以尝试换一种网络环境（比如用手机开热点）

已经解决，非常感谢！！
原本我使用的是网线（经过type-c转接器）直接连接电脑，这样无法播放。
但是在换成 网线连接路由器，电脑再连接路由器的WiFi 后，就可以正常播放了。
如果不介意的话，想问问这是为什么呢？
通过路由器连接校园网的时候同样是先用电脑连上WiFi，再在设备上用账号密码登陆校园网。

**Comment by Richasy** [comment]
具体的原因我也不甚了解，UWP应用访问网络的方式和普通桌面应用不同，但这并不能解释为什么单单是视频无法播放。不管怎么说，解决了问题就好
