### ISSUE TITLE
[Bug] 播放控制界面问题

### ISSUE THREAD

**Issue by Peter1303** [Richasy/Bili.Uwp#63]
## Bug 描述

在显示播放控制界面的时候四个边角会出现白色圆形遮罩（截图似乎看不出来，实际上有的）

## 截图

![image](https://user-images.githubusercontent.com/13428400/133889869-f05dd99c-9ff6-4534-b07a-5f369c797196.png)

## 环境

应用版本：v2.2109.1801

系统版本：

- [ x] 内测版本 (Windows 11)

运行设备：

- [x ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by AnLazyOtter** [comment]
遇到了同样的问题，参见截图：
![Snipaste_2021-09-18_22-45-44](https://user-images.githubusercontent.com/40395191/133892739-927d738a-1648-420e-8c83-672da3f949c2.png)

Windows 11 21H2 22000.168

**Comment by lxdklp** [comment]
![D37F2AC5-A977-44A1-A1A9-02F1DE221DAC](https://user-images.githubusercontent.com/69453767/133893338-53ffeba9-1a32-4b11-a527-92326efd13f0.jpeg)
![CD499878-1AEC-4301-BFDB-2E0E51297FE3](https://user-images.githubusercontent.com/69453767/133893343-eb6fb9b3-4f89-48f8-bce9-db87c337b4e4.jpeg)
同
