### ISSUE TITLE
[Bug] 翻译错误

### ISSUE THREAD

**Issue by hez2010** [Richasy/Bili.Uwp#630]
## Bug 描述

翻译错误

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入视频播放页面
3. 发现问题

## 预期的行为

Cast to device -> 投影到设备

## 截图

![image](https://user-images.githubusercontent.com/14960345/141800332-9f520c39-5f5f-41b1-8559-24cf90ba8396.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{2.2111.1.0}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by Richasy** [comment]
该按钮由MediaTransportControls内部填充（不是应用问题），我在Style中做的修改会被覆盖。目前暂不处理
