### ISSUE TITLE
希望加入我的追番功能

### ISSUE THREAD

**Issue by qingfengmoyu** [Richasy/Bili.Uwp#632]
再番剧页面只有番剧推荐，但是没有我自己已经追番的列表，希望能够加入，有时候就只是想看看自己已追番剧的更新，每次都要搜索很麻烦，追番有点多而且有些名字又长，没记住，那就搜都不好搜索。我看到番剧内又有追番按钮，那为什么没有已追番点页面呢？希望能够加入我的追番页面

**Comment by hez2010** [comment]
点击头像——我的收藏里面即可看到自己的追番
