### ISSUE TITLE
海外党看番添加反向翻墙功能[Feature]

### ISSUE THREAD

**Issue by xBLACKICEx** [Richasy/Bili.Uwp#633]
## 描述你想要解决的问题或者功能的使用场景
海外党看番添加反向翻墙功能

## 描述解决方案

反向代理
## 描述可能的替代方案
油猴插件中的 “解除B站区域限制能不能移植过来”

**Comment by Richasy** [comment]
UWP难以控制网络代理，目前暂无法修复

**Comment by EAFFGH** [comment]
许多网络工具已能够解除UWP应用的网络隔离
所以拜托作者能继续把”解除B站区域限制“纳入开发计划

![UWP解除网络隔离](https://s1.328888.xyz/2022/04/06/LjcAC.png)
