### ISSUE TITLE
[Bug] 多分p视频无法记录上次观看和进度

### ISSUE THREAD

**Issue by lucinhu** [Richasy/Bili.Uwp#644]
## Bug 描述

多分p视频无法记录上次观看和进度

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '我的收藏'
3. 点击任意一个已收藏的多分p视频
4. 点击任意一个分p
5. 关闭应用
6. 打开应用
7. 再重新观看那个多分p视频
8. 出现 '上次观看: 第一分p 进度' 

## 预期的行为

出现 '上次观看: 上次观看的分p 进度' 

## 截图

![屏幕截图 2021-11-20 170052](https://user-images.githubusercontent.com/78008990/142721281-71e2195a-e69d-400a-9852-655e42218c9c.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{2.2111.2}  十一月更新 - 2  

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 备注

这个bug自从新版本(新UI)起, 一直都有
旧的1.31.12版本就没有此bug

**Comment by YexuanXiao** [comment]
这玩意貌似网页版的bilibili也没处理好，记录不了多p，希望bili.uwp能改进一下
