### ISSUE TITLE
[Bug]画面黑屏

### ISSUE THREAD

**Issue by 1061875478** [Richasy/Bili.Uwp#645]
## Bug 描述

看第二个视频时黑屏

## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 随便点击一个视频然后关闭
3. 再打开一个视频

## 预期的行为

画面卡住或黑屏

## 截图

![黑屏](https://user-images.githubusercontent.com/68525017/142724071-816fde08-9879-4bd8-8978-deb011fb2fd2.gif)

## 环境

应用来源：

- [ ] Microsoft Store
- [ x ] Github
- [ ] 其他来源（请注明来源）

应用版本：{2.21111.2.0}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ x ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [ x ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录
[applog.2021-11-20.log](https://github.com/Richasy/Bili.Uwp/files/7574431/applog.2021-11-20.log)

## 备注

当控制器隐藏时何有几率画面卡住

**Comment by Richasy** [comment]
最新版不能复现这个问题，可能已被修复。如果问题依然存在，请尝试更新系统
