### ISSUE TITLE
[Feature] 希望增加类似手机客户端的全屏进度条手势

### ISSUE THREAD

**Issue by MoetaYuko** [Richasy/Bili.Uwp#646]
## 描述你想要解决的问题或者功能的使用场景

希望增加类似手机客户端的全屏进度条手势，即全屏左右滑动控制进度条，左半屏右半屏上下滑动控制亮度和音量。这对surface等***触屏设备***非常有用

## 描述解决方案

给播放器控件增加`ManipulationMode="TranslateX,TranslateRailsX,TranslateY,TranslateRailsY"`属性并处理一下相应事件就好。

## 描述可能的替代方案

n/a

## 备注和截图

n/a

**Comment by Richasy** [comment]
应用已经提供了左右滑动控制进度的功能，请更新至最新版
