### ISSUE TITLE
[Bug]功能模块展示为白色

### ISSUE THREAD

**Issue by Dabaozimrz** [Richasy/Bili.Uwp#649]
## Bug 描述

功能模块展示为白色，黑色字体只有再点击的时候才能看到。
## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）
是的。
重现问题的步骤：
打开应用即可重现。

1. 打开应用
2. 进入 '...'
3. 点击 '....'
4. 滚动至 '....'
5. 发现问题

## 截图
![ad5095b6d8607aad1f091f6e7c5c1dc](https://user-images.githubusercontent.com/94798305/142771404-a22067cb-56c4-4ed6-a803-96e0647fe972.png)
![14f1e13822e3d39bdeaf05858dc7eab](https://user-images.githubusercontent.com/94798305/142771409-d7ebf7be-22ee-4f71-a00d-deaa68ff8ffa.png)
![bc6da441c1f3589d831efe400bdceea](https://user-images.githubusercontent.com/94798305/142771413-3823975f-4662-4281-988c-87344a6d2f0e.png)
![70295db349ddda880c3b69803c33f98](https://user-images.githubusercontent.com/94798305/142771417-b9020925-92b3-48ae-b3ac-281a32e5e085.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [ x] Github
- [ ] 其他来源（请注明来源）

应用版本：{2.2111.2.0}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ X] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [ x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 备注
[applog.2021-11-22.log](https://github.com/Richasy/Bili.Uwp/files/7576671/applog.2021-11-22.log)

**Comment by Richasy** [comment]
我没有复现这个问题，不过我是用Win11测试的，目前我手头上没有Win10的测试机。你可以尝试卸载重装Bili
