### ISSUE TITLE
[Feature]希望对视频评论区评论时间进行优化

### ISSUE THREAD

**Issue by JJrousi** [Richasy/Bili.Uwp#653]
## 描述你想要解决的问题或者功能的使用场景

希望对视频评论区评论时间进行优化
## 描述解决方案

评论时间具体到年-月-日-具体时间
## 描述可能的替代方案

评论时间具体到年-月-日-具体时间
## 备注和截图
![image](https://user-images.githubusercontent.com/42690700/142828975-6a289288-2f5b-486c-a23c-a9cecfba5ab0.png)

**Comment by Richasy** [comment]
光标移到时间上即可

**Comment by JJrousi** [comment]
> 光标移到时间上即可

感谢，之前没太注意
