### ISSUE TITLE
希望在设置手动开关播放器控件的情况下，增加自动隐藏功能

### ISSUE THREAD

**Issue by tikko-now** [Richasy/Bili.Uwp#654]
## 描述你想要解决的问题或者功能的使用场景
希望在设置手动开关控件的情况下，长时间不操作，也可以自动隐藏控件。其他的视频播放器好像都是这个样子，b站手机app逻辑就是可以手动控制控件的显隐，同时一段时间不操作的话也会自动隐藏控件

**Comment by gszshdzz** [comment]
这个确实应该加上，稍微动一动鼠标就出来挡字幕挺烦人的，或者可以把那个条的位置弄到边上（或者可以随便拖动那个条的位置）

**Comment by ShrekRyo** [comment]
我想，这两位用户的意思是，两个功能都有，既可以手动控制，也可以几秒后自动隐藏的逻辑。而不是只剩下自动隐藏。
