### ISSUE TITLE
[Bug]打开直播过几分钟会停止播放，再点击播放会报错

### ISSUE THREAD

**Issue by jianyuyanyu** [Richasy/Bili.Uwp#66]
## Bug 描述
打开直播过几分钟会停止播放，再点击播放会报错

重现问题的步骤：

1. 打开应用
2. 进入 '直播'
3. 找到“关注的直播间”，点击 进去一个
4. 等待几分钟
5. 发现会停止播放，再点击播放会报错，退出再进去扔报错

## 截图

![66Q1)2I7 BQ9(MOW ~XU`Q](https://user-images.githubusercontent.com/49836287/133890698-4d0f1b46-74e5-4072-b30f-070f5e7155b2.png)

## 环境

应用来源：

- [x] Github

应用版本：{Bili.Uwp_2.2109.1801.0_x64}

系统版本：

- [ ] Windows 10 ver.21H1(19043)

运行设备：

- [ ] 桌面/台式机

## 日志记录

[applog.2021-09-18.log](https://github.com/Richasy/Bili.Uwp/files/7189966/applog.2021-09-18.log)
## 备注
弹幕正常

**Comment by Richasy** [comment]
直播时遇到无法播放的源会自动切换播放线路，你也可以尝试手动切换一下播放线路，在清晰度按钮的旁边

**Comment by AnLazyOtter** [comment]
> 直播时遇到无法播放的源会自动切换播放线路，你也可以尝试手动切换一下播放线路，在清晰度按钮的旁边

个人认为并非此原因。
我这边同样出现了这个问题，复现的步骤：

1. 设定“加载完成后自动播放”为“开”；
2. 进入直播间
3. 数秒后，会自动切换到线路2，并自动停止播放；
4. 再次点击“播放”，则会在线路2上播放直播内容，但数秒后，会自动切换到线路3，并自动停止播放；
5. 再次点击“播放”，则会在线路3上播放直播内容，但数秒后，会自动切换到线路4，并自动停止播放；
6. 再次点击“播放”，则会在线路4上提示“错误：无法解码视频”。

附日志文件。
[applog.2021-09-18.log](https://github.com/Richasy/Bili.Uwp/files/7190130/applog.2021-09-18.log)

**Comment by jianyuyanyu** [comment]
最新版仍会自动切换播放线路而停止播放
