### ISSUE TITLE
[Bug]观看分辨率比较低的视频后，再看高分辨率视频的时候会默认使用低分辨率

### ISSUE THREAD

**Issue by GaroneHuang** [Richasy/Bili.Uwp#668]
## Bug 描述

观看分辨率比较低的视频后，再看高分辨率视频的时候会默认使用低分辨率

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 原来默认的分辨率为1080P高码率。
![image](https://user-images.githubusercontent.com/65281345/143730648-da3b69ea-c612-4e83-b589-bfc47d0d23a1.png)
2. 打开一个最高清晰度为720P的视频。
![image](https://user-images.githubusercontent.com/65281345/143730672-f1ef7562-f5e2-4d9f-b821-13eea5497172.png)
3. 回到原来的视频，会发现分辨率被自动切换到720P了。
![image](https://user-images.githubusercontent.com/65281345/143730688-088c41aa-fe98-4b25-a9d1-c65bd9426233.png)

## 预期的行为

如果不主动切换分辨率的话，希望软件不要自动记录默认选择的分辨率，这样看完低分辨率视频后就不会影响到其他视频的分辨率。

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{2.2111.2.0}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by Richasy** [comment]
在设置->播放器控制->打开画质优先
