### ISSUE TITLE
[Bug]画面卡住或者黑屏

### ISSUE THREAD

**Issue by 1061875478** [Richasy/Bili.Uwp#671]
## Bug 描述

很快啊，一更新我就来试试了。
shutdown的问题是解决了但貌似还有一个问题导致了画面卡住或者黑屏，可能是最后一个了QAQ

## 复现步骤

- [ x ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 随便打开一个视频
3. 等待或者切换窗口模式

## 预期的行为

等待一会，画面卡住，有声音。
直接切换窗口模式，黑屏，有声音。
换一个视频，直接黑屏，有声音。

## 截图

![image](https://user-images.githubusercontent.com/68525017/143733920-ab3aa436-3fe6-4fbf-8654-0586a8c66f2a.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [ x ] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ x ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [ x ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

[applog.2021-11-28.log](https://github.com/Richasy/Bili.Uwp/files/7613018/applog.2021-11-28.log)

**Comment by 1061875478** [comment]
应用版本忘记填了，是2.2111.3.0

**Comment by Richasy** [comment]
无法复现这个问题，可能已被修复。如果问题依然存在，请尝试更新系统或显卡驱动
