### ISSUE TITLE
播放视频时视频会自动过曝，点击视频界面后恢复，果断时间又会自动过曝

### ISSUE THREAD

**Issue by tuohuang** [Richasy/Bili.Uwp#673]
## Bug 描述

播放视频时视频会自动过曝（画面明显偏亮），点击视频界面后恢复，果断时间又会自动过曝

## 复现步骤

正常播放视频的时候视频界面会突然变得偏亮，点击视频显示控制栏后恢复正常，过一会还会出现这种情况

重现问题的步骤：

1. 打开应用
2. 进入 '某个视频'
3. 播放视频
4.让视频自己播放
5. 播放过程会频繁出现视频画面过曝光

## 环境

应用来源：

Github

应用版本：{应用版本}

系统版本：2.2111.3.0

Windows 11 (22000)

运行设备：

 桌面/台式机

**Comment by Richasy** [comment]
所有视频都会出现这个问题吗？这可能与显卡有关

**Comment by tuohuang** [comment]
> 所有视频都会出现这个问题吗？这可能与显卡有关

用这个软件很长时间了，经常发现这个问题，我电脑时 第五代 Surface Pro

**Comment by Richasy** [comment]
这个应该是电脑的自动处理，可能开启了动态亮度之类的设置，与应用无关，先关闭这个issue
