### ISSUE TITLE
[Bug] 显示账号被冻结

### ISSUE THREAD

**Issue by 213366** [Richasy/Bili.Uwp#674]
### Discussed in https://github.com/Richasy/Bili.Uwp/discussions/650

<div type='discussions-op-text'>

<sup>Originally posted by **213366** November 22, 2021</sup>
在登录时二维码扫描无效（手上一个vivo和ipad都扫不出来）
使用密码登陆提示账号被冻结。
但在网页端可以正常登录。

arm64版
设备华为Matebooke2019（骁龙850）
系统windows11 22000.348</div>

**Comment by ygjsz** [comment]
遇到了同样的Bug，设备是华硕畅370（骁龙835）

**Comment by oopstls** [comment]
一样的
galaxy book2 （骁龙850）
win11 arm64 22000.348

**Comment by Richasy** [comment]
ARM64支持有限，我手头上也没有ARM64的测试设备，以后有机会会尝试修复

**Comment by TZHinye** [comment]
遇到了相似的bug。arm应用二维码应用扫描无任何反应，期望早日修复
设备：Surface Pro X
系统：win11 arm 22504.1010

**Comment by zhzy0077** [comment]
我的 Surface Pro X 也能复现这个问题，我 debug 看看

**Comment by zhzy0077** [comment]
看上去是这一行的问题: https://github.com/micjahn/ZXing.Net/blob/89074c140f6d55f3ff4587df34e0d8bf03ad6c83/Source/lib/qrcode/encoder/MatrixUtil.cs#L287

`dataBits[bitIndex] ? 1 : 0` 这个的结果被错误的翻转了 我给 .NET Native 的人发邮件了 不知道是不是已知问题

**Comment by zhzy0077** [comment]
.NET Native 的人都在休圣诞假，但是基本确认是 .NET Native Code Opmization 的问题，如果急着用我可以构建一个未优化的包

**Comment by Vseann** [comment]
+1
设备Surface Pro 7
X64平台也一直提示账号被冻结，重装无用，求解

**Comment by lansama** [comment]
遇到了相似的bug。arm应用二维码应用扫描无任何反应，期望早日修复
设备：Galaxy book 2
系统：win11 arm 22000.376

**Comment by ericgao96uw** [comment]
经测试密码登录无论在哪个平台都会报错，经查应是b站的密码登录API目前需要额外的验证码，否则会throw exception

**Comment by lansama** [comment]
> 

哔哩哔哩漫画uwp之前无法登录也是因为这个，现在官方增加了验证码。希望arm能修复扫码登录捏

**Comment by zhzy0077** [comment]
https://github.com/Richasy/Bili.Uwp/releases/tag/v2.2111.4.0 二月的更新似乎能登陆了
