### ISSUE TITLE
[Bug]字幕吞字

### ISSUE THREAD

**Issue by xian2333** [Richasy/Bili.Uwp#680]
## Bug 描述

cc字幕在结尾有几率被吞字

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 'BV19L4y1p7Pr'
3. 跳转到 '3:35'
4. 发现问题

## 预期的行为

出现完整字幕：大部分人平时可能都接触不到

## 截图

![U_5~%@WXL7S0JDKR~06 %{K](https://user-images.githubusercontent.com/36266118/144230393-0e9bb10d-64bc-42c7-af44-550d2eeb88a4.png)
![1AGDQQ`3M6@S67ND)~MM9)O](https://user-images.githubusercontent.com/36266118/144230421-9ff95bc2-26e8-4f08-9082-ed3f16245832.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{2.2111.3.0}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

[applog.2021-12-01.log](https://github.com/Richasy/Bili.Uwp/files/7633583/applog.2021-12-01.log)

## 备注

繁体和简体都会被吞

**Comment by Richasy** [comment]
应该已经修复
