### ISSUE TITLE
[Feature]关闭弹幕、返回主页功能

### ISSUE THREAD

**Issue by mrltr** [Richasy/Bili.Uwp#681]
1、弹幕字体太大，热度高的视频常常被弹幕挡住视频本身内容
2、刷一会视频后想返回主页只能点左上角的退回按钮，看了多少个就得点多少次

## 描述解决方案

1、增加关闭弹幕选项或类似官方调节弹幕的功能
2、左上角增加返回主页按钮

**Comment by Richasy** [comment]
关于字幕调节，请点击播放控制器左侧的向下箭头以展开弹幕控制条。返回主页与 #622 重复
