### ISSUE TITLE
[Feature] B站支持8K视频了，软件可以支持8K视频播放吗？

### ISSUE THREAD

**Issue by wang93wei** [Richasy/Bili.Uwp#689]
## 描述你想要解决的问题或者功能的使用场景

希望播放器可以支持8K视频播放

## 备注和截图

https://www.bilibili.com/video/BV1qM4y1w716?spm_id_from=333.851.dynamic.content.click

![image](https://user-images.githubusercontent.com/6371053/144778954-3e3be62e-0142-4041-a2e8-99531e175069.png)

**Comment by Richasy** [comment]
等全面铺开，Edge浏览器也可以访问的时候，应用自然而然就可以显示
