### ISSUE TITLE
为啥不能登录[Bug]

### ISSUE THREAD

**Issue by susxl** [Richasy/Bili.Uwp#694]
## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '...'
3. 点击 '....'
4. 滚动至 '....'
5. 发现问题

## 环境

应用来源：

- [ ] Microsoft Store
- [ ] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [ ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by litefen** [comment]
+1

**Comment by juzijun233** [comment]
+1
最新版，点击头像后一直转圈

**Comment by susxl** [comment]
> +1 最新版，点击头像后一直转圈
> 
> #682
卸载重装就好了

**Comment by LStarlx** [comment]
我现在也登录不上了

**Comment by lansama** [comment]
扫码扫不出来

**Comment by Richasy** [comment]
目前无法复现这个问题，请完善bug说明，提供复现步骤及设备信息
