### ISSUE TITLE
[Feature]能否调整顶栏搜索框

### ISSUE THREAD

**Issue by Matepad11** [Richasy/Bili.Uwp#702]
## 描述你想要解决的问题或者功能的使用场景
在125%显示比例下，搜索栏太偏左了，偏到侧边栏了。

## 描述解决方案
调整搜索框的位置。

## 描述可能的替代方案
能否学习LyricEase这样的UI设计,将搜索栏和账号管理放在侧边栏。

## 备注和截图

![屏幕截图 2021-12-13 114900](https://user-images.githubusercontent.com/91136893/145749622-10992143-85d3-4ce0-9fb7-5ba0131dd126.png)

![屏幕截图 2021-12-13 115424](https://user-images.githubusercontent.com/91136893/145751056-d976d7b2-2dd0-45bc-be45-9a8e4d4f52d7.png)

**Comment by Richasy** [comment]
你可以把应用右上角三个系统按钮视作死区，在剩余空间内，搜索框相对居中。

另外，在哔哩中，搜索功能是一个优先级极高的功能，不会考虑将其折叠，必须放置在顶部
