### ISSUE TITLE
[Feature]希望添加稍后再看的全部播放功能,以及配合使用的列表循环播放和单集循环设置

### ISSUE THREAD

**Issue by SZCDSB** [Richasy/Bili.Uwp#713]
## 描述你想要解决的问题或者功能的使用场景

希望能在稍后播放里添加全部播放功能,平时使用的时候每次看完都得返回出去点下一个,非常麻烦,还有顺便提一个小细节,希望pc端能使用方向键调节音量

**Comment by NEKO-ii** [comment]
许多人习惯把想看的视频加入到稍后再看（包括我），然后在稍后再看的页面选择观看的视频，希望在播放稍后再看里视频的时候右侧的视频列表改成稍后再看的其他视频，就像B站网页的那个样子

**Comment by NEKO-ii** [comment]
nice
