### ISSUE TITLE
[Bug]打开视频是灰色的 重新进入也还是灰色的,有声音无画面, 多次调试清晰度后才可以正常观看

### ISSUE THREAD

**Issue by crushoi** [Richasy/Bili.Uwp#716]
## Bug 描述

打开视频是灰色的 重新进入也还是灰色的,有声音无画面, 多次调试清晰度后才可以正常观看

## 复现步骤
版本2.2111.3.0
- [ ] 这个问
重现问题的步骤：

1. 打开应用
2. 进入 '首页或者动态'
3. 点击 '任何视频'
4. 点击进入后'有声音无画面 呈灰色显示'
5. 发现问题

## 预期的行为

请修复该BUG

## 截图
![屏幕截图 2021-12-26 221230](https://user-images.githubusercontent.com/50801045/147410726-9ad57ba5-37d9-4ee3-9c86-2c6bb4770080.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [ x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：windows11 22483.1011
哔哩版本:2.2111.3.0

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [x ] 内测版本 ({系统版本})

运行设备：

- [ x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

[applog.2021-12-26.log](https://github.com/Richasy/Bili.Uwp/files/7777081/applog.2021-12-26.log)

**Comment by Accelerator9102** [comment]
和你一样的bug，我尝试了设置-播放器控制-解码器偏好-选择avc/h.264，解决了。

**Comment by crushoi** [comment]
> 和你一样的bug，我尝试了设置-播放器控制-解码器偏好-选择avc/h.264，解决了。

我也尝试了一下,偶尔可以观看视频了,但是切换全屏或者窗口模式,仍然是有声音无画面,退出视频重新进入也是这样的,不知道是什么问题.

**Comment by einsflash** [comment]
+1 更新显卡驱动 选264解码都没用 还是看不了视频

**Comment by LongMan98** [comment]
存在同样的问题

**Comment by Richasy** [comment]
与 #747 可能是相同问题，将合并处理
