### ISSUE TITLE
[Bug]单个视频多p连续播放时卡顿

### ISSUE THREAD

**Issue by AlicestCarol** [Richasy/Bili.Uwp#719]
## 复现步骤

这个问题能否在最新版本中复现？

能

重现问题的步骤：

1. 打开应用
2. 进入 '多p视频'
3. 观看到最后
4. 发现问题

## 预期的行为

修复卡死bug

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [x] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

[applog.2021-12-27.log](https://github.com/Richasy/Bili.Uwp/files/7779237/applog.2021-12-27.log)

**Comment by Richasy** [comment]
与 #792 应是相同问题，合并处理
