### ISSUE TITLE
[Feature] 返回按钮的位置设计

### ISSUE THREAD

**Issue by 4285f4** [Richasy/Bili.Uwp#727]
## 描述你想要解决的问题或者功能的使用场景

现行返回按钮并不是完全放置在屏幕边缘，而是存在一定的边距（见图 1）。每当我需要返回的时候，都要先将鼠标移动到左上角，然后再往屏幕内部移动几个像素才能真正地点击，跟之前 win11 将显示桌面设置为一条线并且不是贴边放置一样令人难受

## 描述解决方案

1. 扩大按钮的实际触发面积，按钮可视外形不变
2. 采用旧式 UWP 应用返回按钮设计（见图 2）
## 备注和截图

图 1.现行返回按钮设计
<img width="165" alt="93c1c0e8682454f5557039e99e73164" src="https://user-images.githubusercontent.com/36158676/147911038-a4c69edc-5d05-4811-9b61-3ad5ba34ff74.png">
图 2.旧式 UWP 返回按钮设计
<img width="246" alt="4dc42301fa1320aa3bc0ba7c7bc1454" src="https://user-images.githubusercontent.com/36158676/147912121-1fdd87bc-3dd5-448f-a73a-ea2b820905c1.png">

**Comment by luojunyuan** [comment]
打开win11的新版store，随便点击一个项目进去尝试点击左上角返回可以看到期望的效果，button响应的范围比较大，全屏时鼠标移动到最左上角也是可以点击的

**Comment by 4285f4** [comment]
> 打开win11的新版store，随便点击一个项目进去尝试点击左上角返回可以看到期望的效果，button响应的范围比较大，全屏时鼠标移动到最左上角也是可以点击的

确实可以，是我想要的那种效果哈哈哈
