### ISSUE TITLE
[Bug]有CC字幕的小窗播放在屏幕别处手写时概率出现小窗闪烁

### ISSUE THREAD

**Issue by CloudBank-3055** [Richasy/Bili.Uwp#728]
## 复现步骤

- [ 是 ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 任意带CC外挂字幕的视频
3. 点击 '小窗模式'
4. 在另一程序（如OneNote UWP、Office 365桌面版）中开启“绘图”并使用触控笔手写 /*但在画图、Photoshop里用触控笔画画却不会出现闪烁*/
5. 发现问题 每次手写落笔时概率出现闪烁

## 预期的行为

希望手写时不出现闪烁。
/*再提个有关小窗的，希望小窗大小调整能默认以视频画面比例缩放，减少反复拉动窗口来消除黑边的操作*/

## 截图

/*一瞬间闪黑又恢复，触发频率也不固定，太难截下来图了，希望大大见谅555*/

## 环境

应用来源：

- [ ] Microsoft Store
- [ x ] Github
- [ ] 其他来源（请注明来源）

应用版本：{ 应用版本 2.2111.3.0 }

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ x ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [ ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT
- [ x ] Surface Pro 7

## 日志记录

[applog.2022-01-05.log](https://github.com/Richasy/Bili.Uwp/files/7811638/applog.2022-01-05.log)

**Comment by Richasy** [comment]
这个应该并不是应用的问题，而是系统自己在处理媒体播放和画面渲染时的问题，从哔哩这边难以进行修复
