### ISSUE TITLE
[Bug]视频开始播放1s后，视频画面出现一层白色滤镜，画面对比度降低

### ISSUE THREAD

**Issue by henryfeng2022** [Richasy/Bili.Uwp#730]
## Bug 描述
视频开始播放1s后，视频画面出现一层"白色滤镜"，画面对比度降低

## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

问题毕现，任何视频打开都会有，直接打开视频播放即可，目前安装的是最新版本

## 预期的行为
希望去除画面”白色滤镜“，对比度恢复正常

## 环境

应用来源：

- [ ] Github

应用版本：{2.2111.3.0}

系统版本：

版本	Windows 11 家庭中文版
版本	21H2
安装日期	‎2021/‎10/‎7
操作系统版本	22000.376
体验	Windows 功能体验包 1000.22000.376.0

运行设备：

笔记本电脑

## 备注
处理器amd 4800h

**Comment by henryfeng2022** [comment]
全屏放大和缩小也会出现

**Comment by Kevinishd** [comment]
是amd处理器吗？如果是的话，这个是amd设置里的视频配置选项导致的，不是软件的问题

**Comment by domeniczz** [comment]
我的是amd处理器，最新版软件，没有这个问题
