### ISSUE TITLE
[Feature]能否增加一个英文的应用程序执行别名bili

### ISSUE THREAD

**Issue by Minelu** [Richasy/Bili.Uwp#732]
## 备注和截图
<img width="600" alt="Snipaste_2022-01-11_17-57-07" src="https://user-images.githubusercontent.com/34987057/148921192-9547accf-d945-42a5-b5ec-ff20685c24c5.png">
类似于这些应用，搜索并启动的时候会方便好多

**Comment by TigerHix** [comment]
同感+1
