### ISSUE TITLE
[Bug] 一月新番不显示正片

### ISSUE THREAD

**Issue by MoetaYuko** [Richasy/Bili.Uwp#733]
## Bug 描述

如https://www.bilibili.com/bangumi/media/md28235858/ 已经放出了第一话，但应用里仍只显示PV等

## 复现步骤

- [X] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入对应番剧页面
5. 发现问题

## 预期的行为

有正片

## 截图

![image](https://user-images.githubusercontent.com/5774651/148978806-f2dc12e5-3ac4-42ec-bcf3-3bbfee029442.png)
![image](https://user-images.githubusercontent.com/5774651/148978885-887e6847-d2b2-4105-839c-fa30dcbae8ed.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [X] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [X] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [X] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by Richasy** [comment]
时间有点长了，该问题无法复现，我这里可以看到正片。另外，请确认自己是大会员，具备看该番的条件

**Comment by MoetaYuko** [comment]
是大会员，只出到第一集（大会员限定）时看不到正片。出第二集，第一集免费之后一二集就都能看到了。建议4月新番更新时重新尝试复现

**Comment by MoetaYuko** [comment]
@Richasy 现在四月新番更新到第一话，可以复现了
![屏幕截图(2)](https://user-images.githubusercontent.com/5774651/161898600-2bba4942-6973-4ed9-8d04-536398a2a3fb.png)
