### ISSUE TITLE
[Bug] 部分直播黑屏（或白屏）

### ISSUE THREAD

**Issue by fxzxmicah** [Richasy/Bili.Uwp#747]
## Bug 描述

有极少数直播打开后只有声音，没有画面，例如：https://live.bilibili.com/426667

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入直播，例如：https://live.bilibili.com/426667
3. 发现问题

## 预期的行为

正常播放

## 截图

![image](https://user-images.githubusercontent.com/48860358/151824891-289ebaf5-27f8-4983-8c90-aa92b0dc1a27.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：2.2111.3.0

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

[applog.2022-01-31.log](https://github.com/Richasy/Bili.Uwp/files/7972091/applog.2022-01-31.log)

## 备注

切换清晰度可以恢复画面，所以我猜是解码的问题？

**Comment by inkdrak** [comment]
一样的问题，我也安装了解码器，但是原画、蓝光两个清晰度无法播放，超清和高清可以正常播放

**Comment by lindan2000** [comment]
似乎是不支持集显，我的游戏本调用独显就能观看，而我的二合一平板电脑只有集显......

**Comment by fxzxmicah** [comment]
> 

但是在我升级到win11之前使用集显貌似没有问题？

**Comment by Richasy** [comment]
@fxzxmicah 如果你尝试将哔哩设置为独显运行，是否还会出现这个情况？

**Comment by fxzxmicah** [comment]
> @fxzxmicah 如果你尝试将哔哩设置为独显运行，是否还会出现这个情况？

不会了

**Comment by Richasy** [comment]
我正在尝试使用移动版本的api，不能保证一定可以修复，但你可以尝试下一个版本

**Comment by fxzxmicah** [comment]
好的，谢谢。其实我最疑惑的是最开始在win10上使用的时候好像没有这个问题。

**Comment by fxzxmicah** [comment]
@Richasy 很遗憾，在2.2204.3.0问题并没有被修复。😭😭😭

**Comment by fxzxmicah** [comment]
详细测试了一下，应该有所缓解（譬如一个直播间原来超清必会黑屏或画面卡住，现在切换10次有8次**不**会卡住），但是问题依然存在（譬如原画依然必定会卡住）
