### ISSUE TITLE
[Feature]请增加清除缓存的选项

### ISSUE THREAD

**Issue by DoveBoy** [Richasy/Bili.Uwp#748]
## 描述你想要解决的问题或者功能的使用场景
长期使用后，app类似Android会存在大量的缓存，只能通过重置应用来清除，非常不方便，请在app设置中添加单独清除缓存功能

## 描述解决方案

app设置中添加单独清除缓存功能按钮
## 备注和截图
![image](https://user-images.githubusercontent.com/19201447/151908892-f4bdb060-0798-40d4-b464-3b4c31ccaae9.png)

**Comment by gitlikang** [comment]
目前我使用CCleaner Professional Edition v5.86.9258（Cracked）——选项——包括——添加C:\Users\gitlikang\AppData\Local\Packages\Richasy.Bili_0d2vm92gxvj9a\LocalCache\ImageExCache\路径(请根据自身环境修改)，来清除48/N小时后的缓存，结合“智能清理”功能条件大于等于500MB则自动清理，系统是Win10 Pro 21H1，UAC等级为最低，CCleaner一定要用安装版本，不然权限有可能不足已清理目标文件。

**Comment by DoveBoy** [comment]
@gitlikang 此方法搭配CCleaner确实有用，但是还是希望app本身能加入缓存清理功能会更方便

**Comment by biewenwoshishui021** [comment]
可以考虑使用搞机助手，一键清理全自动好几个G全部清理干净，不过需要root权限

**Comment by DoveBoy** [comment]
> 可以考虑使用搞机助手，一键清理全自动好几个G全部清理干净，不过需要root权限

root？还搞机助手？这是UWP应用，不是Android
