### ISSUE TITLE
[Bug]无法打开视频和直播页面

### ISSUE THREAD

**Issue by zilewang7** [Richasy/Bili.Uwp#75]
## Bug 描述
点击视频或者直播卡片后应用闪退

## 截图

https://user-images.githubusercontent.com/58734081/133892679-62d4c8b6-c192-40b3-87d3-5ada0056ed01.mp4

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：2.2109.1801.0

系统版本：22000.194

运行设备：桌面/台式机

## 日志记录

2021/09/18 22:44:07.088|Info|
系统信息：10.0.22000.194 | Windows.Desktop | X64
应用信息：2.2109.1801.0 | 中文(简体，中国)
--------
控制器加载完成
|
2021/09/18 22:44:13.465|Info|
系统信息：10.0.22000.194 | Windows.Desktop | X64
应用信息：2.2109.1801.0 | 中文(简体，中国)
--------
控制器加载完成
|

**Comment by Richasy** [comment]
请在新版本中查看该问题是否依然存在

**Comment by ghr1025** [comment]
还是存在该问题

**Comment by Richasy** [comment]
我无法在指定的系统和设备上复现这个问题，如果有其他人可以复现，有条件的小伙伴可以调试该项目以提供准确的问题发生原因

**Comment by Richasy** [comment]
虽然不知道问题的具体原因，但是可以尝试以下操作：
1. 更新显卡驱动
2. 将显卡的图形设置恢复为默认或自动
---

目前先关闭这个问题，有需要可以再打开
