### ISSUE TITLE
[Bug]覆盖安装或更新安装，时间轴都收不回来

### ISSUE THREAD

**Issue by ProgrammerMao** [Richasy/Bili.Uwp#757]
## Bug 描述
覆盖安装或更新安装，时间轴都收不回来

## 复现步骤

- [true] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 覆盖或更新应用
2. 进入任意视频
3. 点击视频画面，时间轴弹出(双击行为：播放/暂停)
4. 再次点击视频画面，时间轴无法收回
5. 发现问题

## 预期的行为
在覆盖安装或更新安装，再次点击视频画面时，能收回时间轴

## 环境

应用来源：

- [ ] Microsoft Store
- [true] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [true] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [true] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by Richasy** [comment]
无法复现这个问题

**Comment by YexuanXiao** [comment]
时间轴是自动收回的，不需要手动收回。而且时间轴也是自动弹出，不需要点击视频画面。
