### ISSUE TITLE
[Feature]希望视频播放组件半透明，会遮挡字幕

### ISSUE THREAD

**Issue by ChingyuanCheng** [Richasy/Bili.Uwp#762]
## 描述你想要解决的问题或者功能的使用场景
**1️⃣在视频播放的时候，视频播放组件会遮挡很多视频的字幕，会带来使用体验下降。**

## 描述解决方案
2️⃣视频播放控件区域由模糊效果改成半透明

## 描述可能的替代方案
3️⃣播放控件下移，不遮挡视频

## 备注和截图
![image](https://user-images.githubusercontent.com/94727401/154687871-46e0845f-cbef-4aa5-9a05-1cba1d032ae7.png)

**Comment by Michaelxia6** [comment]
你不会不知道这个可以隐藏吧
