### ISSUE TITLE
[Feature]关于视频缓存的落盘位置和方案

### ISSUE THREAD

**Issue by Alex-syz** [Richasy/Bili.Uwp#769]
软件虽然本身支持4k，但是缓存的落盘方式很奇怪，我测试了三台电脑上，似乎目前的缓存方式很随机，有时候会直接放在内存中，不写入硬盘，这样的好处是读写速度快但是容易爆内存，而且似乎windows对内存占用有限制，如果播放的4k视频超过一定大小就会卡死，无法缓存，需要结束runtime broker进程再进入就可以播放，有时候也会落盘，落盘位置在软件安装盘，但是好像也会导致突然卡死，不需要关闭哔哩进程，需要强制停止runtime broker进程即可恢复

目前的困扰就是会在看码率高的4k的时候卡死，影视飓风之类的up主的视频很容易出现，目前我的三台电脑都可以出现这个问题，但是不一定能每次都出现，系统都是win11 21H2，hevc解码器正常，显卡是英伟达2060和锐炬核显，cpu均为英特尔。

## 描述解决方案

我的设想方案是提供一个可选开关，由用户选择落盘方式，是放在内存中还是放在某个目录，默认设置在软件安装目录，毕竟不是所有人的设备都有32g乃至更高的内存容量(建议放于固态硬盘，我观察下来以哔哩的缓存方式，每秒钟读写可以上到50MB+)
## 描述可能的替代方案

以我的能力似乎还想不到更好的方式。
## 备注和截图
这种问题基本只在4k出现，所谓我认为是缓存的问题，而且我百度了runtime broker之后发现有很多人反馈这个进程占用内存过多，是否有可能是因为win系统对此进程施加了一些限制导致的，毕竟播放这块是直接调用的这个模块，当然我不是专业的开发人员，只是猜想

**Comment by Richasy** [comment]
视频播放这一块基本都委托给MediaPlayerElement这一控件来处理，我暂时无法对具体的缓存方式进行操作

**Comment by Alex-syz** [comment]
明白了，谢谢大佬解答，辛苦了

Richasy ***@***.***> 于2022年3月2日周三 19:56写道：
