### ISSUE TITLE
[Feature]希望我的收藏-番剧可以添加在看，已看的分类

### ISSUE THREAD

**Issue by Sena-nana** [Richasy/Bili.Uwp#771]
## 描述你想要解决的问题或者功能的使用场景
因为个人是番剧重度依赖者，番剧功能使用的最多，但是Bili.Uwp中番剧功能并不能像网页一样直观地查找在看、未看、已看的番剧。希望可以添加这些分类，这样可以更加方便地使用相关功能

## 描述解决方案
在我的收藏-番剧功能界面下，添加在看、已看的分类按钮

**Comment by Richasy** [comment]
与 #734 合并处理
