### ISSUE TITLE
[Bug]动态中的合集不能正确显示和指向该视频

### ISSUE THREAD

**Issue by HaoTian22** [Richasy/Bili.Uwp#776]
## Bug 描述
动态中的合集不能正确显示和指向该视频

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

收藏一个合集，等有人更新它的时候，它出现在动态里即会出现此状况

## 预期的行为
合集能够正确显示视频封面并指向对应的视频

## 截图
![image](https://user-images.githubusercontent.com/48882584/155838398-e8099bd4-49dd-4f14-b35f-e3365cba15e1.png)
在这个`原神生草系列`的合集中，合集里面的视频被指向了临近的其他视频

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：2.2202.2.0

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [x] 内测版本 (22557)

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by Richasy** [comment]
封面问题应该已经被修复，请在下一个版本（2.2204.5.0）尝试

**Comment by HaoTian22** [comment]
![image](https://user-images.githubusercontent.com/48882584/163893867-5227c92a-62ca-4099-8d02-94c6a24fac77.png)
看起来还是有问题啊？
