### ISSUE TITLE
[Feature] 窗口模式下若可供播放画面比例比视频的比例要高，则以顶部对齐方式播放视频，并重新设计返回按钮位置

### ISSUE THREAD

**Issue by YexuanXiao** [Richasy/Bili.Uwp#778]
## 若可供播放画面比例比视频的比例要高，则以顶部对齐方式播放视频

现在许多显示器已经不是16：9比例，而是19：10或者3：2，此时画面上下会有一部分未利用区域。

当前播放器在遇到这种情况下会居中对齐。

理由：顶部对齐能让控制栏尽可能少的遮挡视频
![image](https://user-images.githubusercontent.com/20025591/155851702-fc6b6b61-3602-40b0-bfd5-16d145a0346b.png)

## 返回按钮应该集成到控制栏

理由：
1. 返回按钮在左上角不利于控制，由于控制栏的存在，大部分用户的鼠标都会在控制栏的位置，而不是左上角
2. 遮挡画面

虽然在移动设备上左上角加入一个返回按钮是常见设计，但是屏幕越大，左上角就越难按到

例如我使用的Surface设备这种大尺寸，左上角的返回按钮永远不可能按到，无论是横屏还是竖屏

就算是传统使用鼠标的PC，进行跨屏幕大小的移动也是低效的。

Windows窗口的关闭按钮由于只需要暴力移动鼠标到右上角，在PC模式下就不存在问题；最小化和窗口化按钮虽然不能盲点，但是仍然在最顶部，相比于“无依靠”的按钮效率也是高的。

虽然用户可能不习惯返回按钮集成到控制栏，但熟悉之后，返回操作的效率是一定增加的，并且解决了顶部按不到的问题。

### 备选方案：将返回按钮设置到标题栏左上角

和 issue https://github.com/Richasy/Bili.Uwp/issues/727 类似，但是 **额外注意了遮挡画面的问题**：

![image](https://user-images.githubusercontent.com/20025591/155852115-598545c0-0136-4933-be6c-d118384c377e.png)

Windows自带的照片将全屏按钮设置到了标题栏，Bili.UWP也可采用类似设计，或者如 https://github.com/Richasy/Bili.Uwp/issues/727 中所述的老式UWP返回按钮。

并且该备选方案不与主要方案冲突，可以并行不悖。

**Comment by Richasy** [comment]
关于第一点，几乎所有的播放器都是画面居中，这本身就是一个让用户专注于内容的设计，顶部对齐或底部对齐都会让画面偏于一侧，在视觉上非常别扭。而至于控制器对画面的遮挡，控制器并不是常显的，隐藏掉就好了，它不是一个持续不断影响用户观看内容的东西。

关于第二点返回按钮，返回按钮用于退出当前的非标准状态（全屏/全窗口/小窗），但实际上，还有其他两种方式可以做到同样的事情：
1. 对于键盘用户，可以直接按Esc，这是符合用户操作习惯的简便方式
2. 相比起将返回按钮放在控制栏，事实上你可以点击被选中的非标准状态按钮，比如你截图中的蓝色的全窗口按钮，它同样可以退出当前状态。

所以我认为将返回按钮放在控制栏将会变成一个“重复功能入口”，这是不必要的
