### ISSUE TITLE
倍速播放的改进

### ISSUE THREAD

**Issue by lcx-0504** [Richasy/Bili.Uwp#779]
大多数情况下其实用不到0.1X这么精确的调整，建议在滑块的下面添加0.5x，1.0x，1.5x等按钮直达
另外希望支持键盘→键长按的3x快进，真的很方便啊，鼠标调整比较慢，直接+15秒又会漏内容
谢谢大佬，太喜欢哔哩啦。希望大佬在MS工作顺利

**Comment by Richasy** [comment]
与 #854 合并处理
