### ISSUE TITLE
[Bug]在任意评论中点击‘...’,显示的评论仍为第一个点开的视频中对应评论。

### ISSUE THREAD

**Issue by KrisowX** [Richasy/Bili.Uwp#789]
## Bug 描述

如题，若评论过长导致折叠，点击‘...’展开后的评论不是当前所浏览的评论，且仍为第一次点进去的视频评论。

## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？

可复现。

重现问题的步骤：

1. 打开应用
2. 进入一个视频
3. 进入评论，点击评论中的'...'展开评论，退出视频。
4. 再点开一个视频。打开评论区，点击‘...’
5. 发现问题

## 预期的行为

显示当前所浏览的正确评论。

## 截图

![image](https://user-images.githubusercontent.com/58591281/156597423-5e20fb5e-758f-4a6b-867a-743a5c29af7b.png)

## 环境

应用来源：

- [x] Microsoft Store
- [ ] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by lcx-0504** [comment]
我也存在这个bug

**Comment by lcx-0504** [comment]
> 我也存在这个bug

3月更新的版本仍存在问题

**Comment by fg2625182747** [comment]
我也是这样
