### ISSUE TITLE
[Bug]协助编写wiki的超链接失效了

### ISSUE THREAD

**Issue by AnLazyOtter** [Richasy/Bili.Uwp#790]
## 关联文档

![下载并安装哔哩的详细说明](https://github.com/Richasy/Bili.Uwp/wiki/%E4%B8%8B%E8%BD%BD%E5%B9%B6%E5%AE%89%E8%A3%85%E5%93%94%E5%93%A9%E7%9A%84%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E#%E5%8D%8F%E5%8A%A9%E7%BC%96%E5%86%99-wiki)

## 描述

底部”协助编写Wiki“部分，”Fork仓库并提交PR“的超链接失效了。
![image](https://user-images.githubusercontent.com/40395191/156608428-210ccd73-5e4c-40a2-8241-e32f9e5d7737.png)

## 预期的内容

正常情况下，应当点击后能跳转到一个不是提示”404“的页面。

**Comment by Richasy** [comment]
已修复
