### ISSUE TITLE
[Bug]搜索栏无法正常显示输入法的候选字

### ISSUE THREAD

**Issue by Kimaru-bili** [Richasy/Bili.Uwp#803]
## Bug 描述

我在搜索的时候 输入关键词显示推荐了 然后我在继续输入关键词 推荐会把我输入法的候选字盖住 我无法正常输入

## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）
复现了

重现问题的步骤：

1. 打开应用
2. 进入主页
3. 点击搜索
4. 键入关键词 继续追加关键词
5. 发现问题

## 截图
![image](https://user-images.githubusercontent.com/40233772/156926731-0b0268e8-0c4e-455c-90d3-23cb305a907a.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [ √] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}
2.2203.2.0
系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ √] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [ √] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 备注

我之前还申请过添加收藏夹里搜索功能 请问作者大大何时能实现呢 感谢作者大大

**Comment by Kimaru-bili** [comment]
![image](https://user-images.githubusercontent.com/40233772/156926850-c582d1c3-8dad-4fc7-a7a0-bc21d71a0369.png)
微软输入法就没有问题

**Comment by Richasy** [comment]
第三方输入法的支持不在应用的考虑范畴内，该行为无法通过应用内来解决

**Comment by Kimaru-bili** [comment]
好吧
