### ISSUE TITLE
视频播放结束会应用卡死[Bug]

### ISSUE THREAD

**Issue by Octomouch** [Richasy/Bili.Uwp#806]
## Bug 描述

播放视频结束前一秒，应用会黑屏，然后卡住，只能关闭再重新打开。

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 随便播放一个视频
3. 等到进度条到达视频结束前一秒
4. 发现卡死问题

## 预期的行为

视频播放结束后，能够正常退出，或者切换下一个视频等其他操作

## 截图

![image](https://user-images.githubusercontent.com/66351932/156989085-ddcbdcb1-6cb3-48ab-9cdf-6a002df9ca4b.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{2.2203.2.0}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

[applog.2022-03-07.log](https://github.com/Richasy/Bili.Uwp/files/8195719/applog.2022-03-07.log)

**Comment by Richasy** [comment]
与 #792 问题相同，合并处理
