### ISSUE TITLE
[Bug] 视频评论表情不能显示，展开全部后不能复制

### ISSUE THREAD

**Issue by DreamOfStars** [Richasy/Bili.Uwp#81]
## 截图

 
![Snipaste_2021-09-18_23-41-37](https://user-images.githubusercontent.com/25294404/133894489-208874e7-6e82-43ea-ae1e-b1989c9808d0.png)

## 环境

应用来源：

- [ x ] Github 

应用版本：{2.2109.1801.0}

系统版本：

- [ x ] 内测版本 ({22000.194})

运行设备：

- [ x ] 桌面/台式机

## 备注

希望增加进入视频页的默认行为项，使得默认显示是评论而不是关联视频

**Comment by Richasy** [comment]
关于文本表情混排的功能暂时还没做，属于后续要添加的功能。展开卡片的文本复制功能会在下次更新中添加
