### ISSUE TITLE
[Feature]单击显示控制

### ISSUE THREAD

**Issue by wqcblog** [Richasy/Bili.Uwp#818]
希望能够单击显示播放控制，而不是单击就会暂停，这样很容易误触。

**Comment by Richasy** [comment]
设置->播放器控制->双击行为，调整为播放/暂停

**Comment by monologconnor** [comment]
> 设置->播放器控制->双击行为，调整为播放/暂停

在Windows Store下安装的版本内并没有找到此设置, 版本号为2.2205.1.0

不知功能是否被移除?
![image](https://user-images.githubusercontent.com/38450642/170017428-f68ef2d1-d98d-4e1d-8ee2-7c99322ea87e.png)
