### ISSUE TITLE
[Feature] 倍速播放体验升级

### ISSUE THREAD

**Issue by achieve-dream1221** [Richasy/Bili.Uwp#820]
## 描述你想要解决的问题或者功能的使用场景

目前哔哩版本号: 2.2203.2.0
倍速播放一旦在一个视频中设置, 则会被配置到全局倍速中, 导致切换其他不需要倍速的视频, 都需要再手动切换

## 描述解决方案
可以对那些分p的视频进行倍速配置, 而对于全局可以用默认倍速1x, 类似于b站网页端那种倍速处理模式

**Comment by AAANSU** [comment]
建议给倍速的设置添加一个刻度条
