### ISSUE TITLE
[Bug] 播放界面内，鼠标指针放在播放器以外的地方时鼠标返回键无法触发

### ISSUE THREAD

**Issue by Miuzarte** [Richasy/Bili.Uwp#824]
## Bug 描述
播放界面内，鼠标指针放在播放器以外的地方时鼠标返回键无法触发

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '...'
3. 点击 '....'
4. 滚动至 '....'
5. 发现问题

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：2.2203.2.0

系统版本：19044.1586

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [x] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

**Comment by Richasy** [comment]
目前尚不支持鼠标返回键，这不算一个bug
