### ISSUE TITLE
一些不太重要建议

### ISSUE THREAD

**Issue by Kelejun** [Richasy/Bili.Uwp#832]
### 动画方面

这是一个非常棒的应用，但 Win 11 本身内置的 UI 动画好，希望能够做更好的动画效果

比如：点赞按钮可以像 MSStore 点赞的动画类似，点开视频也可以学一下进入 App 详情页的放大动画，返回时有滑动的动画

### 界面方面

个人觉得打开视频后优先显示评论而不是关联视频会更好？

播放列表如稍后再看连续播放能否也做一下？

## 描述解决方案

无。

## 描述可能的替代方案

无。建议的内容本身也可有可无。

## 备注和截图

无。

**Comment by Richasy** [comment]
标题有些模糊，不符合Issue发布标准，值得讨论的建议可以放在Discussions之中，不建议作为Issue发布
