### ISSUE TITLE
[Bug]无法返回标准视图

### ISSUE THREAD

**Issue by Tki-sor** [Richasy/Bili.Uwp#834]
## Bug 描述
![LW%B~$%{QH~(DI@Z3HSA_6A](https://user-images.githubusercontent.com/78548154/158309005-3a00e44f-ade0-4b0e-8bb3-cff2730a5324.png)
刚安装好时正常的，现在这个按钮怎么点就点不动，但是全屏正常

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）
不知道如何复现，进去就一直这样了
重现问题的步骤：

1. 打开应用
2. 随便打开个视频
3. 点返回视图，点不动

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{2.2203.2.0}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

## 日志记录

> 
[applog.zip](https://github.com/Richasy/Bili.Uwp/files/8250356/applog.zip)

**Comment by Richasy** [comment]
建议将应用拉宽。这个按钮只在特殊视图（比如全屏/小窗）有效，你现在截图展示的已经是标准视图了，如果你指的是完整的播放控制，拉宽应用即可。
