### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by FlyRenxing** [Richasy/Bili.Uwp#836]
## Bug 描述

因为想在xbox中安装bili所以选择了store上传内测版本。但在Store Application Review Results页面报告api不兼容。内容如下：

> API _CxxThrowException in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __C_specific_handler in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __CxxFrameHandler3 in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __std_exception_copy in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __std_exception_destroy in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __std_terminate in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API _purecall in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API memcmp in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API memcpy in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API memmove in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API memset in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API wcsrchr in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?_Xlength_error@std@@YAXPEBD@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?_Xout_of_range@std@@YAXPEBD@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrAssign@@YAXPEAXPEBX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrCopy@@YAXPEAXPEBX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrCopyException@@YAXPEAXPEBX1@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrCreate@@YAXPEAX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrCurrentException@@YAXPEAX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrDestroy@@YAXPEAX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrRethrow@@YAXPEBX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [x] 2022 (17.{版本号})

## 备注
搜索后发现需要将windowsSDK升级一下？？
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1868#issuecomment-953661664

希望可以帮忙解决这个问题或者发我一个store的兑换代码也可以呀嘿嘿嘿

**Comment by Richasy** [comment]
更新 SDK 意味着 Windows 10 用户将无法使用，在现阶段尚不适合升级。
另外，目前不建议上传到商店，特别是在官方已经开始开发UWP的情况下
