### ISSUE TITLE
稍后再看的建议

### ISSUE THREAD

**Issue by tjddbc** [Richasy/Bili.Uwp#847]
建议 稍后再看能放在左边，不要在点开头像，并且稍后再看支持里面的视频按照顺序播放。
谢谢。

**Comment by Richasy** [comment]
放在左边导航栏的都是无需登录即可使用的功能（动态除外），稍后再看对于部分人使用频率较高，但并不是一个对所有人都有必要的功能，所以目前还是觉得放在个人面板中比较好。
稍后再看顺序播放视情况在四月更新

**Comment by Richasy** [comment]
与 #713 合并处理
