### ISSUE TITLE
[Feature] 备用安装和更新包下载

### ISSUE THREAD

**Issue by Eggiverse** [Richasy/Bili.Uwp#848]
## 备选安装更新地址
目前安装更新依赖于github release，在中国大陆速度没有保障，希望可以有备选地址。

## 描述解决方案

个人觉得可以在gitee上再放一份仓库，或者用一些靠谱的网盘。

**Comment by Richasy** [comment]
我理解国内下载 Github 上的资源有一定的困难，但个人精力有限，不想维护多个下载入口。且这个应用的目的并不是 `让更多人使用它来看B站`，所以扩大受众并不是我需要考虑的事情，也不是哔哩未来的发展方向
