### ISSUE TITLE
[Bug]主界面能打开，点开视频闪退

### ISSUE THREAD

**Issue by dylumian** [Richasy/Bili.Uwp#85]
是不是 UWP依赖包安装不上的问题 我手动安装了下 X86的都能安装 X64的报错

App installation failed with error message: 错误 0x80073D02: 无法安装，因为需要关闭以下应用: Microsoft.XboxGamingOverlay_5.721.9121.0_x64__8wekyb3d8bbwe MicrosoftWindows.Client.CBS_1000.22000.194.0_x64__cw5n1h2txyewy MicrosoftWindows.Client.WebExperience_421.20019.195.0_x64__cw5n1h2txyewy 

除了XBOX的，其他的找不到如何关闭
![Snipaste_2021-09-19_07-15-29](https://user-images.githubusercontent.com/37278466/133910851-14f82138-013c-4161-b1da-033736160707.png)

我看了下 系统里是有这个X64的依赖包的
下面是日志记录

2021/09/19 07:19:01.280|Info|
系统信息：10.0.22000.194 | Windows.Desktop | X64
应用信息：2.2109.1801.0 | 中文(简体)
--------
控制器加载完成
|
2021/09/19 07:19:08.463|Info|
系统信息：10.0.22000.194 | Windows.Desktop | X64
应用信息：2.2109.1801.0 | 中文(简体)
--------
控制器加载完成
|

系统环境： Window11  beta 22000.194 X64

**Comment by Richasy** [comment]
与 #75 问题重复，暂时关闭，可以在另外的Issue上继续追踪该问题
