### ISSUE TITLE
播放视频控制栏显示问题

### ISSUE THREAD

**Issue by Amview** [Richasy/Bili.Uwp#850]
## 希望播放视频控制栏增加功能
*  鼠标不动的情况下，几秒后自动隐藏控制栏。鼠标滑动，显示控制栏。
*  设置里的这个媒体传输控制模式设置为自动，视频控制栏会一直显示不会隐藏
![image](https://user-images.githubusercontent.com/38485358/159107827-0a94fcc6-ff26-4d19-9679-b9f0e3826f45.png)

**Comment by Richasy** [comment]
没有复现这个问题，是不是你的鼠标一直在动？或者尝试将鼠标放在视频空白处或者页面空白处，避免和弹幕碰撞（概率发生触发MTC显示）
