### ISSUE TITLE
[Bug] 看视频闪退严重

### ISSUE THREAD

**Issue by dandandedd** [Richasy/Bili.Uwp#853]
[applog.2022-03-19.log](https://github.com/Richasy/Bili.Uwp/files/8310488/applog.2022-03-19.log)
日志已上传

**Comment by Richasy** [comment]
从日志记录来看，可能的原因如下：

日志显示你的系统是x86（32位），x86的Windows 10这个确实有些少见，其本身的架构限制也使得运行内存不高（2GB）。
而造成闪退的主要原因就是交换内存不足以支持播放高清视频。

通俗说法就是：配置较低，跑不起来 😢

我不确定你的硬件设备是否支持X64，如果支持，请将系统重装为X64系统，否则不光是哔哩 ，其他方面，比如玩游戏等都会受到影响。
而如果硬件配置不支持X64，这很遗憾，但建议使用网页版

**Comment by dandandedd** [comment]
这是我的系统配置

处理器	AMD Ryzen 7 4800H with Radeon Graphics            2.90 GHz
机带 RAM	16.0 GB (15.4 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器
是不是因为我下错了的原因呢？

**Comment by dandandedd** [comment]
难道我下成了32位的哔哩🤣🤣

**Comment by Richasy** [comment]
你可以尝试重新下X64的哔哩 😂
