### ISSUE TITLE
[Bug]无法显示播放速率高级控制

### ISSUE THREAD

**Issue by AlicestCarol** [Richasy/Bili.Uwp#855]
如图，并没有播放速率增强
![image](https://user-images.githubusercontent.com/95176448/159146857-0cd186c7-66e1-452f-9d7e-7de93a514187.png)
![image](https://user-images.githubusercontent.com/95176448/159146833-dade4dcd-8537-4a1e-9780-53f633c5a3e1.png)

**Comment by Richasy** [comment]
你这个是旧版本，请查看仓库说明安装新版
