### ISSUE TITLE
[Bug]登录二维码无法识别

### ISSUE THREAD

**Issue by SA-Root** [Richasy/Bili.Uwp#859]
## Bug 描述
登录的二维码手机无法识别

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 点击右上角的头像
3. 用手机扫描生成的二维码进行登录
4. 发现问题

## 预期的行为
识别二维码并成功登录

## 截图

![Screenshot 2022-03-20 165706](https://user-images.githubusercontent.com/73736681/159155424-8fbb494f-cf32-47ac-a8c4-e6c90dd9ca56.png)

## 环境

应用来源：

- [x] Microsoft Store
- [ ] Github
- [ ] 其他来源（请注明来源）

应用版本：2.2203.3.0

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [x] 内测版本 (22579)

运行设备：

- [ ] 桌面/台式机
- [ ] Xbox
- [x] ARM64 设备 
- [ ] IoT

## 日志记录

[applog.2022-03-20.log](https://github.com/Richasy/Bili.Uwp/files/8310907/applog.2022-03-20.log)

**Comment by Richasy** [comment]
这个是系统编译器的一个bug，目前我这边不太好修。你可以尝试先使用Github的X64版本，Windows 11 已经支持直接运行 x64 程序了
