### ISSUE TITLE
[Bug]无法使用用户名/手机号+密码登录

### ISSUE THREAD

**Issue by SA-Root** [Richasy/Bili.Uwp#860]
## Bug 描述
无法使用用户名/手机号+密码登录

## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 点击右上角头像
3. 点击 '用密码登录'
4. 输入用户名/手机号和密码
5. 发现问题

## 预期的行为
成功登录

## 截图
![image](https://user-images.githubusercontent.com/73736681/159155957-ad703617-675e-4b36-90b8-983878f887e9.png)

## 环境

应用来源：

- [x] Microsoft Store
- [ ] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [x] 内测版本 (22579)

运行设备：

- [ ] 桌面/台式机
- [ ] Xbox
- [x] ARM64 设备 
- [ ] IoT

## 日志记录
没有产生相关日志

**Comment by Richasy** [comment]
账户密码登录目前存在权限问题，以后会添加其它的登录方式

**Comment by samzrx123** [comment]
我这边这个版本扫码也登不上
