### ISSUE TITLE
[Feature]添加关注页分组以及鼠标中键返回上一页的建议

### ISSUE THREAD

**Issue by lislond** [Richasy/Bili.Uwp#861]
## 描述你想要解决的问题或者功能的使用场景

 
关注的用户较多，建议添加分组功能，便于更快找到用户
鼠标操作中键返回很便捷，建议添加

## 描述解决方案

添加关注页分组功能，鼠标操作中键返回功能

## 备注和截图

作者大大辛苦了

**Comment by Richasy** [comment]
感谢支持，但请参照置顶要求，将其分为两个 Feature request
