### ISSUE TITLE
[Bug]记忆播放速率失效

### ISSUE THREAD

**Issue by msycn** [Richasy/Bili.Uwp#864]
## Bug 描述

记忆播放速率失效

## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

是

重现问题的步骤：

1. 打开应用
2. 进入 '首页随机视频'
3. 点击 '下方导航栏播放速率'
4. 滚动至 '除1倍以外其他速率如1,5倍.'
5. 发现问题 点击其他视频会重置1倍

## 预期的行为

希望能跟之前版本一样能记忆播放速率

## 环境

应用来源：

- [ X] Github

应用版本：v2.2203.3.0

系统版本：

- [ ] Windows 11 22000.588

运行设备：

- [ ] 桌面/台式机

## 日志记录

[applog.2022-03-20.log](https://github.com/Richasy/Bili.Uwp/files/8312006/applog.2022-03-20.log)

**Comment by Richasy** [comment]
与 #849 合并处理

**Comment by msycn** [comment]
> 

感谢R大回复,期待新版👍
