### ISSUE TITLE
[Bug]win11下无法与服务器建立连接/无法加载推荐视频/无法登录

### ISSUE THREAD

**Issue by jichuan254** [Richasy/Bili.Uwp#87]
## Bug 描述

我在9月18日晚上新版本发布之后就立刻装在我的win11系统上，版本号是最新的DEV。我打开UWP进行了登录，甚至还尝试播放了视频，一切正常。然后我关机睡觉去了。9月19号早上起来，我照例打开电脑，发现UWP无法连接服务器了，不仅打开时推荐视频的首页只有一个圈圈在转，点登录头像也是毫无反应的转圈，照理来说他应该自动登录的。我尝试关机后再开机或者重启，仍然提示“推送视频时请求失败，在发送请求时出现了异常”，登录头像等一切需要联网的地方仍然转圈。多次重启仍未解决，查看日志发现日志记载没能连接到服务器，更多的就不知道了。

## 复现步骤

- [是 ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '...'
3. 点击 '....'
4. 滚动至 '....'
5. 发现问题

## 预期的行为

希望尽快修复，我仍然未能看上视频。

## 截图

![image](https://user-images.githubusercontent.com/89684979/133912109-dedd1d3c-48c1-4efe-8553-48e708a53150.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [ x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ x] Windows 11 (22458.1000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录
[applog.2021-09-19.log](https://github.com/Richasy/Bili.Uwp/files/7190823/applog.2021-09-19.log)

## 备注

因为事发突然，我没有尝试卸载后再重装，但是我觉得我昨天的安装过程毫无问题，第一次体验也丝滑流畅，这让我想到上几周Windows11的任务栏卡死事件，也是一觉睡醒，系统无了，现在想来还是心惊胆战啊

**Comment by jichuan254** [comment]
在我写下这段话的前几分钟，服务器恢复正常，在提交BUG之后我一直在尝试，一直未能成功，但是我在微软商店更新了Windows web  experience pack之后，再次打开UWP时就一切正常了，现在尚未知道恢复正常是否与这个有关。
（必须说的是，因为从22449版本后，系统更新采取的是完整包安装的模式，所以每次安装新系统之后一些系统的自带软件都是需要重新下载更新包的。因为星期五安装22458版本后，我还未更新商店里的这个包，所以这可能是引起问题发生的原因，特意在此提供给开发者）

**Comment by LiamSho** [comment]
我昨天也遇到过这个问题，我的情况是开了 Clash 代理。只要开启 Clash 代理（规则模式）就会连接失败，Clash 里面也看不到请求的连接，关了代理就正常了。不知道是 Clash 的问题还是 Windows 的问题，开了代理 Windows Sandbox 之类的所有 UWP 应用全部不能联网。

**Comment by Richasy** [comment]
看上去这个和哔哩无关，是系统或网络代理的问题，所以关闭这个issue，如果有需要，可以随时再打开
