### ISSUE TITLE
[Feature] 侧键返回、回到顶部、弹幕位置

### ISSUE THREAD

**Issue by Stapxs** [Richasy/Bili.Uwp#88]
## 描述你想要解决的问题或者功能的使用场景
1. 部分鼠标可以使用侧键（Mouse Button x2）来触发返回操作（用习惯了改不回来了）
2. 建议在大部分列表刷新边上加个回到顶部
3. 给滚动弹幕增加只占屏幕上方多少空间的设置（比如只占上方50% ）这种防遮挡功能（不太喜欢用透明度来防遮挡）

## 描述解决方案
已在描述中给出

## 描述可能的替代方案
这些在我看来都是非刚需功能
不过会稍稍影响体验
当然
2. 也可以换成点击标题文字回到顶部，但是这个操作没引导性，不是用习惯的人不引导压根不会知道

## 备注和截图
无

**Comment by WangPingAnG** [comment]
和我的观点完全一致
