### ISSUE TITLE
窄视图下点击关注的直播间无反应

### ISSUE THREAD

**Issue by tm0210** [Richasy/Bili.Uwp#880]
### Bug 描述

窄视图下点击关注的直播间无反应

### 复现问题的步骤

```plain text
1.打开应用，进入 '哔哩'
2.调整窗口大小，进入窄视图模式
3.点击导航栏上的直播，再点击关注的直播间（蓝色圈起来的部分），显示“获取用户关系失败”的文字提示，未能进入直播间
```

### 预期行为

窄视图下点击关注的直播间，正常进入直播间

### 截图

![mmexport1648046442473.png](https://user-images.githubusercontent.com/90995212/159906421-03f7b452-a8ac-4620-96f8-af27abf12acd.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
Hi, 你的图好像挂了

**Comment by tm0210** [comment]
> Hi, 你的图好像挂了

![mmexport1648046442473.png](https://user-images.githubusercontent.com/90995212/159906124-359e1a02-f2e5-4c92-ad44-bbde86bbfba5.png)

**Comment by tm0210** [comment]
> Hi, 你的图好像挂了

现在好了，之前我还以为是网络问题(●'◡'●)
