### ISSUE TITLE
[Feature] 希望提供一个更改媒体传输控件自动显隐的时间更改功能

### ISSUE THREAD

**Issue by xiaomengzaici** [Richasy/Bili.Uwp#881]
### 问题描述

媒体传输控件自动显隐的时间过于长了，影响个别视频的观看体验，虽然可以单击手动显隐，但是同时也会暂停视频，操作显得不是那么便利，不是所希望的操作反馈。

### 描述解决方案

提供媒体传输控件自动显隐的时间控制表，提供1s-10s的挡位选择或者提供自定义时间

### 备选方案

减少媒体传输控件显隐的时间至1s，或者更改灵敏度

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
这个设置的受众太少，而且体验不佳，会和 #654 合并处理
