### ISSUE TITLE
[Bug] 搜索框的搜索联想会挡住搜狗输入法的选词输入框

### ISSUE THREAD

**Issue by Nova-mist** [Richasy/Bili.Uwp#882]
### Bug 描述

在使用**哔哩**的搜索框功能时，先输入的词产生的**搜索联想框**会挡住搜狗输入法的**选词输入框**，而使用系统自带的微软拼音就无此问题。
- 将**哔哩**更新到了【三月更新 - 3】版本，搜狗输入更新到官网最新版本（11.8），仍就有此问题。
- 使用搜狗输入法默认皮肤，问题仍旧存在。

### 复现问题的步骤

```plain text
1. 切换到搜狗输入法
2. 打开应用
3. 鼠标点击搜索框
4. 先输入一个词，例如 “你”，此时搜索框下产生联想搜索框。
5. 再次尝试打字输入，发现输入法的选词输入框被联想搜索框遮住了。
```

### 预期行为

按照复现问题的步骤，最后搜狗输入法的选词输入框能够在搜索联想框前显示。

### 截图

![Snipaste_2022-03-24_12-09-43](https://user-images.githubusercontent.com/60425532/159840906-b7446fa5-61f6-4441-a258-0696ac750f90.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
这并不是哔哩能解决的问题，或者可以说是UWP的“通病”，我觉得让输入法厂商修复更靠谱
