### ISSUE TITLE
键盘快捷键

### ISSUE THREAD

**Issue by waitmeyzw** [Richasy/Bili.Uwp#884]
### 问题描述

希望能直接用esc当后退键，就是返回上一个界面，或者什么时候能够自定义快捷键按键

### 描述解决方案

现在适配了鼠标的快捷按键挺舒服的要是能自定义一下就更好了

**Comment by Richasy** [comment]
Esc按键用于 `将打开的东西关闭`，这听上去很像返回按钮实际在干的事情，但本质并不一样。

Esc快捷键目前被应用在弹出层，对话框以及特殊播放模式（全屏/全窗口）的关闭上，它跟页面导航并无瓜葛。

自定义快捷按键这个我觉得并不太适合哔哩这种视频播放软件，我更希望在应用内保持统一的按键命令，毕竟现有的快捷键称不上花样繁多。

我会借着这个 issue 提高鼠标快捷键的体验，额外提供鼠标中键作为快捷返回的按键
