### ISSUE TITLE
增加适用于Win10的亚克力效果

### ISSUE THREAD

**Issue by WonderAndroid324** [Richasy/Bili.Uwp#887]
### 问题描述

Win10系统不支持Win11的云母效果，Win10系统下显示为不透明灰色，建议增加一个可以随意开的关亚克力效果选项，可以随意开关

### 描述解决方案

建议增加一个可以随意开关的亚克力效果选项

**Comment by Richasy** [comment]
事实上，哔哩会在未来逐渐放弃对 Windows 10 的支持，虽然没有确定的日期，但就目前来说不会特别为 Win10 做出功能或样式上的修改
