### ISSUE TITLE
使用哔哩时屏幕显示出现问题[Bug]

### ISSUE THREAD

**Issue by yubius** [Richasy/Bili.Uwp#89]
![故障图片](https://user-images.githubusercontent.com/79253940/133912691-64a10857-eab1-4c62-9fdd-c63784bf3f3e.jpg)
系统版本：22000.194

**Comment by Richasy** [comment]
这个……应该是设备问题，可能和显卡有关？

**Comment by yubius** [comment]
> 这个......应该是设备问题，可能和显卡有关？

是硬件还是软件问题？显卡驱动不兼容Windows11？我是11代核显

**Comment by Richasy** [comment]
这个我无从知晓。但是应用的渲染问题一般发生在应用内部，这种把整个应用都割裂的情况不在应用渲染错误的范围内。可以尝试更新一下显卡驱动。
因为问题可能不是出在应用身上，我会暂时关闭这个Issue，如果你有更进一步的信息，随时可以再打开
