### ISSUE TITLE
[Bug] 播放几乎每次都是只有声音没有画面或者正常播放几秒画面卡住

### ISSUE THREAD

**Issue by zhchlx** [Richasy/Bili.Uwp#894]
### Bug 描述

播放几乎每次都是只有声音没有画面或者正常播放几秒画面卡住

### 复现问题的步骤

```plain text
播放几乎每次都是只有声音没有画面或者正常播放几秒画面卡住
```

### 预期行为

播放几乎每次都是只有声音没有画面或者正常播放几秒画面卡住

### 截图

![image](https://user-images.githubusercontent.com/73682869/160120347-45c37084-ad79-400f-bf20-cfae19034e9d.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 日志记录

[applog.2022-03-25.log](https://github.com/Richasy/Bili.Uwp/files/8350470/applog.2022-03-25.log)

**Comment by zhchlx** [comment]
https://www.bilibili.com/read/cv11307514
这个方法能解决这个问题，在英伟达控件3D效果里打开垂直同步

**Comment by Richasy** [comment]
用的独显还是核显？如果有独显，尝试在独显设置中让独显来处理哔哩的运行

**Comment by zhchlx** [comment]
电脑是台式电脑 外接独立显卡3060ti-asus，驱动为最新的游戏驱动。

**Comment by HiRA017** [comment]
我也遇到这个问题了。笔记本有独显直连，已经屏蔽核显，也按照Wiki里给出的去NVDIA控制面板找G-SYCN的设置，但笔记本不支持G-SYCN所以也没有那项设置，现在几乎处于无法正常播放视频的状态。
