### ISSUE TITLE
[Bug] win11 看直播会卡死 

### ISSUE THREAD

**Issue by dandandedd** [Richasy/Bili.Uwp#895]
### Bug 描述

使用笔记本的混合模式（核显+独显）解码器是avc h264 观看直播的时候会卡死闪退；
若切换成独显直连（屏蔽核显）则正常使用（也有时候会卡住 不过概率很小）
在任务管理器中发现是核显在工作 独立显卡占用为0
不知是不是核显的问题？
cpu型号R7-4800H

### 复现问题的步骤

```plain text
使用核显观看哔哩
哔哩会闪退（大概率）
在观看一阵以后吧
```

### 预期行为

看直播不闪退

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-03-25.log](https://github.com/Richasy/Bili.Uwp/files/8351640/applog.2022-03-25.log)

**Comment by Richasy** [comment]
有独显尽量使用独显，不必强求核显
