### ISSUE TITLE
播放器控制问题~

### ISSUE THREAD

**Issue by JINSHUtz** [Richasy/Bili.Uwp#90]
方向键快进快退和空格暂停混合使用会改变焦点的位置导致一些混乱……
1.当“媒体传输控件”显示时：在全屏播放界面快进快退，会导致焦点发生变化，这时候想要按空格播放/暂停视频时，触发了“媒体传输控件”中被焦点选中的某个其他操作。
2.当“媒体传输控件”隐藏时，在全屏播放下空格暂停操作是无效的，另外从动态或者其他页面点击一个视频进入播放页面，如果不点一下播放器的画面，焦点没有放到视频内容上，空格暂停就没有效果。如果此时快进快退，焦点会跑出视频，比如会选中侧栏推荐的某个视频，这时候如果按下空格暂停就打开了焦点框中的那个视频~
不知道我描述清楚没有…不是学相关知识的请谅解QAQ，作者佛系修复一下就好~感谢！

**Comment by Richasy** [comment]
全局监听空格键是一件比较复杂的事情，这可能会影响到一些UWP的默认行为。

当哔哩哔哩的快捷键和UWP的默认快捷键有冲突的时候，我是以UWP快捷键优先的。

即对于UWP来说，当焦点在一个可选中的元素上时，空格键的默认行为就是选中，跟播放无关。

播放的快捷键是Ctrl+P，你也可以通过双击视频来播放/暂停

**Comment by JINSHUtz** [comment]
您好，我明白，我认为的可能描述的不够清楚…，应该不是涉及到全局监听空格这种…… 这个操作在旧版哔哩是没有任何问题的啦，不论快进快退，最终焦点锁定都在媒体控制栏的播放/暂停上，而在新哔哩上焦点会跑掉qaq
***@***.***

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2021年9月19日 14:32
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Richasy/Bili.Uwp] 播放器控制问题~ (#90)


全局监听空格键是一件比较复杂的事情，这可能会影响到一些UWP的默认行为。

当哔哩哔哩的快捷键和UWP的默认快捷键有冲突的时候，我是以UWP快捷键优先的。

即对于UWP来说，当焦点在一个可选中的元素上时，空格键的默认行为就是选中，跟播放无关。

播放的快捷键是Ctrl+P，你也可以通过双击视频来播放/暂停

―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRichasy%2FBili.Uwp%2Fissues%2F90%23issuecomment-922423062&data=04%7C01%7C%7C3b6bdbb956c94c0545fb08d97b374db7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637676299737638349%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RETLthPcCtF65iXcMZsma9tBkjrhZpQCIgvZn4T2GWE%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALQ6XQJXSSNYAXSNGOINMM3UCV7ZFANCNFSM5EJZWCLQ&data=04%7C01%7C%7C3b6bdbb956c94c0545fb08d97b374db7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637676299737638349%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JAcZb0IryV0hGyAV%2B6sOLFl8feDlhSyK9%2BimqyZwKpk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C3b6bdbb956c94c0545fb08d97b374db7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637676299737648344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=50Ap%2Bex3UrICRWbtFK4KKkIk7%2B9bm1x7dxw1RIhVhPo%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C3b6bdbb956c94c0545fb08d97b374db7%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637676299737648344%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Tg5luidJrbxBlev7%2FtHeTfGvGElxgBhnVQgdDgqUcIM%3D&reserved=0>.

**Comment by Richasy** [comment]
旧版就是做的全局监听，但是这种方法是有风险的，即在播放视频的同时，在弹幕或搜索框输入文本的时候会有异常行为。

**Comment by Richasy** [comment]
暂时关闭这个问题，因为有替代方案。如果你认为有必要，可以再打开这个Issue
