### ISSUE TITLE
[Bug] 高码率直播原画使用核显播放无画面

### ISSUE THREAD

**Issue by SA-Root** [Richasy/Bili.Uwp#901]
### Bug 描述

使用核显观看直播时，部分直播（码率较高）的原画画质黑屏，仅有声音，切换为低画质后正常；或者设置软件在独显上运行，可以正常播放原画直播。
设备为Surface Book 2(UHD 620(驱动30.0.101.1631)+GTX 1060(驱动512.15))，解码器偏好为HEVC，商店中的所有解码器扩展均已安装。

### 复现问题的步骤

```plain text
见Bug描述
```

### 预期行为

使用核显即可播放所有直播

### 截图

![Screenshot 2022-03-26 165400](https://user-images.githubusercontent.com/73736681/160232625-9e9a21d5-9860-4e17-b63b-b3b19489c4c7.png)
如图所示，使用核显播放高码率直播黑屏，有弹幕和声音。

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [x] 其它 (需注明)

### 其它系统版本

Windows 11 22H2 Build 22581.100

### 运行设备

桌面/平板或笔记本

### 日志记录

没有产生相关日志

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
那……既然有解决方法，应该不必强求核显播放吧
