### ISSUE TITLE
输入框输入问题

### ISSUE THREAD

**Issue by justinzhuying** [Richasy/Bili.Uwp#902]
### Bug 描述

输入框输入后，失去焦点会显示联想提示框，在点击输入框输入会遮盖输入法

### 复现问题的步骤

```plain text
1输入框输入后，
2失去焦点会显示联想提示框，
3在点击输入框
```

### 预期行为

影响输入

### 截图

![屏幕截图 2022-03-26 171800](https://user-images.githubusercontent.com/40077808/160233102-c1c5c9ff-10eb-4473-aae6-f666f78f0d70.png)

### 应用来源

- [X] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

**Comment by Richasy** [comment]
第三方输入法不在应用的修复范畴内，这也是应用无法处理的问题
