### ISSUE TITLE
电脑端用户在一些小细节方面意见

### ISSUE THREAD

**Issue by blibilijojo** [Richasy/Bili.Uwp#906]
### 问题描述

1.在电脑端，我感觉下方菜单显示时间过久，在鼠标自动消失后还要很久，或许是为了触屏用户的体验，建议在设置中加一个设置，调整鼠标用户（和电脑b站网页端一样就行）和触屏用户的转换
2.当我点击清晰度切换之类按钮后，切换完毕后，下方大菜单自动消失，但是清晰度切换还是未消失
![image](https://user-images.githubusercontent.com/102420734/160242200-b2433aa0-a3e5-4f8f-9f6e-bdb6a3980283.png)

### 预期内容

1.当鼠标不动时，鼠标和下方菜单像网页端一样快速消失，当然了，触屏的用户可以通过设置切换，和现在一样
2.当清晰度切换完毕后，清晰度和下方大菜单一起消失
![image](https://user-images.githubusercontent.com/102420734/160242354-db60f212-8bf6-42f4-b717-cbcec9bb021f.png)

### 附加信息

都是我在使用过程中的一些小问题

### 人人为我，我为人人

是的，我希望其他人看到我写的文档

**Comment by Richasy** [comment]
这不是文档问题，播放器控制栏的体验问题会与 #654 合并处理
