### ISSUE TITLE
[Bug] 动态页面中 视频合集动态 功能异常

### ISSUE THREAD

**Issue by Samachurl** [Richasy/Bili.Uwp#907]
### Bug 描述

动态页面中，订阅的合集更新视频时，更新的动态：
1. 未正常显示视频，如P1
2. 无法点击评论按钮
3. 点击头像，错误链接至无关用户，如P2

### 复现问题的步骤

```plain text
1.订阅一个视频合集，如https://space.bilibili.com/7788379/channel/collectiondetail?sid=102
2.打开动态页
3.找到合集更新的动态
```

### 预期行为

1. 正常浏览合集视频和关联评论
2. 修复  点击头像错误链接至无关用户的问题

### 截图

![1](https://user-images.githubusercontent.com/48409650/160242909-0c9eda74-4486-4d6f-8473-4293863ec7e7.png)
![2](https://user-images.githubusercontent.com/48409650/160242958-a147419b-fe5f-4b07-ac87-d6c00f4b5d6a.png)

### 应用来源

- [ ] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Samachurl** [comment]
#776 #750

**Comment by Richasy** [comment]
与 #776 合并处理
