### ISSUE TITLE
[Bug] 视频提示不在版权地区

### ISSUE THREAD

**Issue by LosewaySama** [Richasy/Bili.Uwp#91]
## 复现步骤

- [x] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '...'
3. 点击 '....'
4. 滚动至 '....'
5. 发现问题

## 环境

应用来源：

- [ ] Microsoft Store
- [ ] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [ ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

**Comment by LosewaySama** [comment]
所以视频均显示不在版权地区

**Comment by Richasy** [comment]
请提供详细的复现步骤，在打开视频前， 是否点击了一些地区限制的番剧？或者是否打开了代理？

**Comment by Richasy** [comment]
暂时关闭该问题，因为新版已经修复。如果在新版本中仍观察到该现象，请重新打开这个Issue
