### ISSUE TITLE
[Bug] "稍后再看"页面内右键视频不能单独删除

### ISSUE THREAD

**Issue by Miuzarte** [Richasy/Bili.Uwp#912]
### Bug 描述

"稍后再看"页面内右键视频不能单独删除

### 复现问题的步骤

```plain text
"稍后再看"页面内右键视频
```

### 预期行为

"稍后再看"页面内右键视频能单独删除

### 截图

![image](https://user-images.githubusercontent.com/66856838/160267595-afdd2549-ef01-43a2-b90a-0aebfa01fe36.png)

### 应用来源

- [ ] Microsoft Store
- [x] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [x] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

**Comment by Peter1303** [comment]
正想反馈 哈哈哈

**Comment by Richasy** [comment]
与 #908 合并处理
