### ISSUE TITLE
[Bug] 动态中合集无法正常显示

### ISSUE THREAD

**Issue by Jason-Louzz** [Richasy/Bili.Uwp#913]
### Bug 描述

订阅合集在动态界面显示其他视频封面，点进去后也为其他视频，点击合集头像则跳转至不知名用户界面

### 复现问题的步骤

```plain text
1.打开应用
2.进入动态界面
3.点击更新的合集视频
4.显示为其他视频
```

### 预期行为

点击合集内容跳转至该合集最新更新视频，点击合集头像可以显示合集所有视频界面

### 截图

![微信截图_20220327145348](https://user-images.githubusercontent.com/73084580/160270299-f9f27c67-a620-418e-8c40-95125a5d620b.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
与 #776 合并处理
