### ISSUE TITLE
[Bug] UpDate时出错

### ISSUE THREAD

**Issue by SSDGXlin** [Richasy/Bili.Uwp#914]
### Bug 描述

App installation failed with error message: Deployment Add operation with target volume C: on Package Richasy.Bili_2.2203.5.0_neutral_~_0d2vm92gxvj9a from:  (App_2.2203.5.0_x64.msixbundle)  failed with error 0x80070570. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment issues. (0x80070570)

我的windows是win11 dev版22581

### 复现问题的步骤

```plain text
更新bili时App install报错
```

### 预期行为

兼容性强，添加自动更新功能，有的时候上不去Github真的是很头疼

### 截图

![image](https://user-images.githubusercontent.com/90437955/160271934-29b71c73-5626-40e6-8520-b57f1e4379e7.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

win11 22581

### 运行设备

桌面/台式机

**Comment by Richasy** [comment]
可以尝试商店版本：`ms-windows-store://pdp/?productid=9mvn4nslt150` 复制链接到浏览器地址栏打开
