### ISSUE TITLE
[Feature] 添加软件内下载

### ISSUE THREAD

**Issue by SSDGXlin** [Richasy/Bili.Uwp#916]
### 问题描述

BBdown下载太复杂

### 描述解决方案

添加软件内下载视频功能，把BBdown结合到bili里面，一键下载

**Comment by Richasy** [comment]
哔哩不会提供内建下载功能

**Comment by 6banlaobanzhang** [comment]
……为什么不支持直接从哔哩调起BBdown啊……

**Comment by Richasy** [comment]
Uwp不支持对命令行的直接调用
