### ISSUE TITLE
放大缩小界面后内容排列错位[Bug]

### ISSUE THREAD

**Issue by madman43** [Richasy/Bili.Uwp#92]
## Bug 描述
第一次安装最新版本后设置如下
![image](https://user-images.githubusercontent.com/19260034/133913565-7120937b-63e7-4163-9a6d-96fe07ef437c.png)
然后观看视频调整了界面大小以及测试了三个画面播放方式，结果发现内容错位

切换窗口播放方式时界面内容错位
## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '界面'
3. 点击 '随便一个视频'
4.随意调整界面大小及切换三个视频播放方式然后评论点击就会画面错位''
5. 发现问题

## 预期的行为
希望修复

## 截图
![image](https://user-images.githubusercontent.com/19260034/133913466-79f038bf-88cf-4155-8d36-2dc5039bd7ef.png)
![image](https://user-images.githubusercontent.com/19260034/133913480-85d7fd50-5788-4b5a-86b4-742d139a1d1d.png)
![image](https://user-images.githubusercontent.com/19260034/133913616-aaa22223-8211-4439-bd7c-6f2d21cb196d.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [x] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

2021/09/19 10:33:08.667|Info|
系统信息：10.0.22000.194 | Windows.Desktop | X64
应用信息：2.2109.1801.0 | 中文(简体，中国)

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [x] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录

[applog.2021-09-19.log](https://github.com/Richasy/Bili.Uwp/files/7190904/applog.2021-09-19.log)

**Comment by Richasy** [comment]
请检查新版本是否仍存在这个问题，我没有复现

**Comment by madman43** [comment]
> 请检查新版本是否仍存在这个问题，我没有复现
好的

**Comment by Richasy** [comment]
暂时先关闭这个问题，如果有需要可以再打开
