### ISSUE TITLE
[Bug] 稍后再看界面无法直接删除列表视频

### ISSUE THREAD

**Issue by RiChuanGangB** [Richasy/Bili.Uwp#926]
### Bug 描述

在稍后再看界面右键视频不再有删除选项，对于经常使用这一功能的我来说非常不方便，而且我记得上个版还可以删除的，更新之后变得和其他界面一样了，希望尽快修复。

### 复现问题的步骤

```plain text
打开应用进入稍后再看界面右键列表内视频
```

### 预期行为

恢复上版本的删除功能

### 截图

![稍后再看界面 BUG](https://user-images.githubusercontent.com/102510121/160349287-a9d38574-bb89-498a-857f-db97d7ca4a11.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
与 #908 重复
