### ISSUE TITLE
[Feature] 期待增加投稿功能

### ISSUE THREAD

**Issue by wqcblog** [Richasy/Bili.Uwp#927]
### 问题描述

Biliuwp作为客户端已经非常完善了，如果能够增加投稿功能，就更完美了

### 描述解决方案

参照这个开源项目：https://github.com/ForgQi/biliup-app

**Comment by Richasy** [comment]
啊……这个应该不阔能了，做得再好好不过B站官方，做的差了还很得罪人，短期内不会考虑
