### ISSUE TITLE
[Bug]小窗模式下侧边残留;点击关注直播间则直接跳转到浏览器

### ISSUE THREAD

**Issue by xianrengang** [Richasy/Bili.Uwp#93]
## Bug 描述

1.小窗模式侧边导航栏残留。
2.小窗模式点击关注直播间直接跳转浏览器。

## 复现步骤

1.小窗模式下打开应用，侧边残留。
2.小窗模式下打开应用，点击直播分区，点击关注直播间则直接跳转到浏览器；若点击推荐直播则可在应用内正常播放。

## 预期的行为

小窗模式下侧边导航栏无残留。
2.小窗模式下点击关注直播间可正常在应用内播放。

## 截图

![Snipaste_2021-09-19_10-39-36](https://user-images.githubusercontent.com/87941451/133913591-84672e07-1d2d-4b96-840c-62547421013d.png)

## 环境

应用来源：

- [ ] Microsoft Store
- [ x ] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ x ] Windows 10 ver.1904 (19042.1083)
- [ ] Windows 10 ver.2004 (19041)
- [ ] Windows 11 (22000)
- [ ] 内测版本 ({系统版本})

运行设备：

- [ x ] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

**Comment by Richasy** [comment]
该问题应该已经通过升级WinUI版本得到了修复，请确认。如果问题依然存在，请再打开这个问题
