### ISSUE TITLE
[Bug] 我的标题

### ISSUE THREAD

**Issue by miditao1987** [Richasy/Bili.Uwp#931]
### Bug 描述

App_2.2203.5.0_Test
这个版本，打开了之后是花屏的，怎么设置啊？我系统是Windows11，版本是22581.100，显卡是AMD RX590，驱动最新

### 复现问题的步骤

```plain text
1、打开app
2、随便点一个视频 都是花屏
```

### 预期行为

解决花屏问题

### 截图

![Snipaste_2022-03-28_19-38-50](https://user-images.githubusercontent.com/73865360/160390211-a48f09a2-f36d-4df5-9ede-5225458d494b.jpg)

### 应用来源

- [ ] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 人人为我，我为人人

是的，我希望我的代码出现在哔哩中

**Comment by Richasy** [comment]
视频花屏大概率是显卡问题，请更新显卡驱动，或者参照 Wiki 里的常见问题进行配置
P.S. 提Issue注意改下标题
