### ISSUE TITLE
[Feature] 希望能优化评论区时间显示

### ISSUE THREAD

**Issue by GaroneHuang** [Richasy/Bili.Uwp#932]
### 问题描述

目前评论区时间显示逻辑仅为时间，无法得知其评论日期，如下图所示。
![image](https://user-images.githubusercontent.com/65281345/160404877-d7bbc2d8-1cd6-4a0f-adb7-438ead85a222.png)

### 描述解决方案

希望评论区显示评论时间的逻辑能够与视频时间显示的逻辑一致（如下图所示）
![image](https://user-images.githubusercontent.com/65281345/160405451-514423ea-bbf3-417b-8cc6-71ad3383e40d.png)
即：
1. 距离现在1分钟以内的，显示“刚刚”。
2. 距离现在超过1分钟不满1小时的，显示“xx分钟前”。
3. 距离现在超过1小时不满一天的，显示“xx小时前”。
4. 距离现在超过一天不满两天的，显示“昨天”。
5. 距离现在超过两天的，显示日期“xxxx-xx-xx”。

**Comment by Richasy** [comment]
光标移上去即可显示完整日期
