### ISSUE TITLE
[Bug] 更新版后登录问题

### ISSUE THREAD

**Issue by xy0124** [Richasy/Bili.Uwp#935]
### Bug 描述

更新2203.50版本后，需要重新登录。
到手机验证码界面，无法点击接受验证码和下一步等按钮，只有取消，退出界面。
![image](https://user-images.githubusercontent.com/99000021/160544033-33efbaba-5d8f-46ad-a818-a97b572ab27a.png)

### 复现问题的步骤

```plain text
用户登录--密码登录--输入用户名密码之后跳出验证手机界面
```

### 预期行为

正常登录

### 截图

![image](https://user-images.githubusercontent.com/99000021/160544310-a5eb9bf4-e540-43e9-9872-512098f6a80d.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
Windows10的话，你可以尝试从 [这里](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section) 安装 WebView2 运行时，这玩意儿 Windows 11 自带，所以用 Win11 应该没这个问题

**Comment by Richasy** [comment]
刚刚找了台Win10机子测试了一下，看上去是WebView的问题，特定于平台，我这边不大好修（也可能不会再修复）。你如果能用扫码登录尽量扫码，或者升级至Win11系统

**Comment by xy0124** [comment]
好的，谢谢您。
