### ISSUE TITLE
[Bug] 视频播放亮度异常

### ISSUE THREAD

**Issue by Gaoyifei1011** [Richasy/Bili.Uwp#936]
### Bug 描述

1.视频播放界面当界面缩小时汉堡菜单就会出现，而这个按钮应该是多余的
2.视频播放的时候会出现屏幕亮度/对比度很亮，点击一下视频后亮度/对比度恢复正常，设备surface laptop 4
3.一个功能建议，就不重复开issue了，希望添加一键三连的功能

### 复现问题的步骤

```plain text
None
```

### 预期行为

None

### 截图

问题1截图
![屏幕截图 2022-03-30 110256](https://user-images.githubusercontent.com/49179966/160743625-41fa02a7-c910-407e-93a6-de9029378d93.png)
问题2截图
打开后视频亮度很亮
![屏幕截图 2022-03-30 110327](https://user-images.githubusercontent.com/49179966/160743814-8d009023-1a15-4f01-96b9-66f071e7d98d.png)
点击后视频亮度恢复正常
![屏幕截图 2022-03-30 110339](https://user-images.githubusercontent.com/49179966/160743821-702fed5c-01f6-408c-813a-cc967590be88.png)

### 应用来源

- [X] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

Dev 22581

### 运行设备

桌面/平板或笔记本

### 日志记录

[Uploading applog.2022-03-30.log…]()

### 备注

None

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
建议还是修改下，让标题明确反应问题。如果有多个问题，每个问题开一个issue。
关于第二点，这个可能是设备问题，比如电脑开了自动亮度，或者显示器设置开了自动亮度之类的
关于第三点，长按点赞，一键三连

**Comment by Gaoyifei1011** [comment]
> 建议还是修改下，让标题明确反应问题。如果有多个问题，每个问题开一个issue。 关于第二点，这个可能是设备问题，比如电脑开了自动亮度，或者显示器设置开了自动亮度之类的 关于第三点，长按点赞，一键三连

好的，我注意一下，我还是比较注意第二个问题，因为第二个问题对我日常的使用有一定的影响
但是我电脑上面安装的爱奇艺UWP、是哔哩哔哩动画官方的那个UWP或者是ZPlayer UWP在播放视频的时候就没有出现这一类的问题。

**Comment by Richasy** [comment]
爱奇艺使用的是旧版的MediaElement(应该)，哔哩哔哩官方和ZPlayer使用的是自定义的播放器（比如VLC或者基于网页的播放器），而哔哩使用的是微软自家的MediaPlayerElement，它跟系统深入集成。所以作为对比测试，你可以尝试下载视频后用Windows自带的媒体播放器播放

**Comment by Gaoyifei1011** [comment]
> 爱奇艺使用的是旧版的MediaElement(应该)，哔哩哔哩官方和ZPlayer使用的是自定义的播放器（比如VLC或者基于网页的播放器），而哔哩使用的是微软自家的MediaPlayerElement，它跟系统深入集成。所以作为对比测试，你可以尝试下载视频后用Windows自带的媒体播放器（UWP版本，Win10是电影与电视，Win11是Logo为橙紫渐变边框的媒体播放器）播放

好吧，我前几天已经使用了那个win11新的媒体播放器测试过了，的确是存在这个问题。可能是您们官方的封装的库的确存在这个自动亮度调节视频忽亮忽暗的问题，不知道这个问题是新库的特性还是bug。😂😂😂
目前是只能关闭自动调节亮度来解决这一问题吗？

**Comment by Richasy** [comment]
这种系统层面的调节看各自情况而定，但不管怎么说，这并不是应用本身的问题，所以我先关闭这个问题了
