### ISSUE TITLE
[Bug] 播放HDR视频为白屏

### ISSUE THREAD

**Issue by Luorunze** [Richasy/Bili.Uwp#937]
### Bug 描述

播放HDR视频为白屏，但是同一个视频播放4k没有问题

### 复现问题的步骤

```plain text
随便播放一个HDR视频都为白屏，但是同一个视频播放4k没有问题
```

### 预期行为

能够修复白屏

### 截图

![1](https://user-images.githubusercontent.com/44825558/160764591-4f16f735-2343-4607-a024-2b8e1336f593.png)

### 应用来源

- [X] Microsoft Store
- [ ] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 其它系统版本

Windows 10 21H2 Build 19044.1586

### 运行设备

桌面/平板或笔记本

### 备注

没有核显，只有独显的笔记本

**Comment by Richasy** [comment]
可能是设备不支持

**Comment by MemoryDewey** [comment]
遇到了同样的问题，在设置->屏幕->显示卡中将bili改为高性能模式就能解决，怀疑之前是Win自动判断使用了软解，没改之前GPU都没有调用的
![image](https://user-images.githubusercontent.com/38499618/174645894-1334d42e-f8e4-45c2-8823-3e98980288ac.png)
更改后正常使用硬解
![image](https://user-images.githubusercontent.com/38499618/174645998-878a328e-451b-494f-889b-46dcf4d76e10.png)
