### ISSUE TITLE
[Feature]关于收藏夹的自动连播

### ISSUE THREAD

**Issue by ColdTreee** [Richasy/Bili.Uwp#938]
### 问题描述

作者你好 
在最新版哔哩中 收藏夹没有自动连播功能 就像网页版那样 开启自动连播后可以选择按顺序、随机等一系列排列方法进行播放
这对于使用一些收藏歌曲的文件夹来说非常方便  
感谢您能听取我的建议

### 描述解决方案

在观看收藏夹中的某一视频时 右侧可以增加一个收藏夹的选项 然后进行自动连播
或者在选中收藏夹的时候添加一个播放全部 再进行播放顺序的调整

**Comment by Richasy** [comment]
与 #534 合并处理
