### ISSUE TITLE
[Bug] 播放界面点击分享没任何反应

### ISSUE THREAD

**Issue by xy0124** [Richasy/Bili.Uwp#959]
### Bug 描述

播放视频点击右下角 分享 按钮，没任何反应。

### 复现问题的步骤

```plain text
正常的观看环节
```

### 预期行为

希望可以正常分享
用客户端看视频无法分享出去好捉急

### 截图

![image](https://user-images.githubusercontent.com/99000021/161186068-1787dee0-7c1c-4d83-9afb-d5bd17719177.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
没有复现这个问题，在Win11和Win10上都可以正常弹出分享窗口
