### ISSUE TITLE
[Bug] 鼠标指针于UP主页面消失

### ISSUE THREAD

**Issue by Maxdontron** [Richasy/Bili.Uwp#961]
### Bug 描述

打开任意一个up主的主页，将指针移到主页上半部分，鼠标指针消失，除非将指针移动到屏幕最顶端或最底端
（此问题仅限于从视频进入up主主页）（不包括点击个人头像➡关注数➡up主主页这种方式，因为这种方式能正常显示鼠标指针）

### 复现问题的步骤

```plain text
1 打开应用
2 任意点进一个视频
3 点击up主头像
4 将鼠标移至弹出窗口上半部分
5 问题出现
```

### 预期行为

鼠标指针能正常显示

### 截图

![屏幕截图 2022-04-01 114305](https://user-images.githubusercontent.com/91769391/161191621-495d2167-7982-4013-8f5d-1b142abf67f1.png)
![屏幕截图(7)](https://user-images.githubusercontent.com/91769391/161191630-fcad2efa-fe66-464f-9f83-b86b71b27e7b.png)
![屏幕截图(9)](https://user-images.githubusercontent.com/91769391/161191631-62753408-8cf1-4ab2-95bf-1a484f3a4dcf.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-04-01.log](https://github.com/Richasy/Bili.Uwp/files/8394559/applog.2022-04-01.log)

### 备注

此bug不稳定出现，有时要等几秒才会出现问题

**Comment by Richasy** [comment]
与 #960 合并处理
