### ISSUE TITLE
[Bug] 播放传输控件显示效果

### ISSUE THREAD

**Issue by Maxdontron** [Richasy/Bili.Uwp#962]
### Bug 描述

控件直接半透明了，在某些情况下会影响操作

### 复现问题的步骤

```plain text
1 打开应用
2 打开任意一个视频
3 鼠标移至视频画面直到播放控件弹出
4 问题出现
```

### 预期行为

控件应为mica透明效果

### 截图

![屏幕截图(10)](https://user-images.githubusercontent.com/91769391/161192346-89ea8d9b-fa2d-4f4d-89eb-45e23d1d306a.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

### 日志记录

[applog.2022-04-01.log](https://github.com/Richasy/Bili.Uwp/files/8394586/applog.2022-04-01.log)

**Comment by Richasy** [comment]
请具体说明是什么情况会影响操作。

之前是亚克力材质，但是有人说会遮挡字幕。现在修改为了半透明，这属于设计让位于功能。所以如果想再改回亚克力材质，请给出足够的理由

**Comment by Maxdontron** [comment]
> 请具体说明是什么情况会影响操作。
> 
> 之前是亚克力材质，但是有人说会遮挡字幕。现在修改为了半透明，这属于设计让位于功能。所以如果想再改回亚克力材质，请给出足够的理由

例如在视频播放背景不足够亮时播放控件就其实不太好点击按钮，当然既然有这个原因那我也可以没有意见（或许加一个让用户自由选择的权利？）

**Comment by Maxdontron** [comment]
> 请具体说明是什么情况会影响操作。
> 
> 之前是亚克力材质，但是有人说会遮挡字幕。现在修改为了半透明，这属于设计让位于功能。所以如果想再改回亚克力材质，请给出足够的理由

例如在视频播放背景不足够亮时播放控件就其实不太好点击按钮，当然既然有这个原因那我也可以没有意见（或许加一个让用户自由选择的权利？）

**Comment by blibilijojo** [comment]
> > 请具体说明是什么情况会影响操作。
> > 之前是亚克力材质，但是有人说会遮挡字幕。现在修改为了半透明，这属于设计让位于功能。所以如果想再改回亚克力材质，请给出足够的理由
> 
> 例如在视频播放背景不足够亮时播放控件就其实不太好点击按钮，当然既然有这个原因那我也可以没有意见（或许加一个让用户自由选择的权利？）

或许你可以尝试用暗色模式

**Comment by Richasy** [comment]
@Maxdontron 那么，目前来看，这个问题我就标记暂不修复了。如果之后遇到了足以影响用户使用功能的情况，可以再打开它
