### ISSUE TITLE
媒体传输控件控制方式不能修改

### ISSUE THREAD

**Issue by zixulu** [Richasy/Bili.Uwp#963]
### Bug 描述

四月第一次更新版本，媒体传输控件控制方式（进度条）不能设置为手动，其他版本无此问题

### 复现问题的步骤

```plain text
.
```

### 预期行为

..

### 应用来源

- [ ] Microsoft Store
- [x] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [x] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

**Comment by Richasy** [comment]
新版本统一了播放控件的操作行为，与官方一致，不再提供手动/自动切换功能
