### ISSUE TITLE
[Bug] 播放提示弹出前进入全屏模式会闪退

### ISSUE THREAD

**Issue by Richasy** [Richasy/Bili.Uwp#970]
### Bug 描述

在在播放视频时，如果该视频有历史记录或下一视频的提示，在提示弹出前进入全屏会导致应用卡死并闪退

### 复现问题的步骤

```plain text
1. 打开应用
2. 开启关联视频播放
3. 进入任一视频，将进度条拖拽到尾部，距离视频结束大概2-3秒
4. 在视频即将播放完成时进入全屏
5. 观察应用行为
```

### 预期行为

应用正常播放，并弹出提示

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

是的，我希望我的代码出现在哔哩中

**Comment by blibilijojo** [comment]
这就是我之前在说关联视频bug的时候说可能闪退的原因�
![erinnnmrYI](https://user-images.githubusercontent.com/102420734/161364435-c25b12f2-63ee-4ec6-b31a-673f2853d9c8.gif)
�

**Comment by Richasy** [comment]
> 这就是我之前在说关联视频bug的时候说可能闪退的原因� ![erinnnmrYI](https://user-images.githubusercontent.com/102420734/161364435-c25b12f2-63ee-4ec6-b31a-673f2853d9c8.gif) �

是，但需要拆成两个issue，并进行更精确的描述。下个版本会修复这个问题
