### ISSUE TITLE
[Bug] 双击全屏鼠标不会消失

### ISSUE THREAD

**Issue by blibilijojo** [Richasy/Bili.Uwp#971]
### Bug 描述

双击视频全屏时,鼠标不会消失,下方媒体传输控件自动消失

### 复现问题的步骤

```plain text
1.打开应用
2.打开视频
3.双击全屏
4.重现bug
```

### 预期行为

鼠标和媒体传输控件一同消失

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

**Comment by Richasy** [comment]
关联PR已经修复
