### ISSUE TITLE
[Bug] 开启多线程下载合并音视频失败

### ISSUE THREAD

**Issue by songen2216** [Richasy/Bili.Uwp#972]
### Bug 描述

最新版4月更新-1，在高级选项中选择使用多线程下载，最后在合并音视频时提示合并失败，不能合成音视频。

### 复现问题的步骤

```plain text
1.打开应用
2.打开视频
3.点击下载
4.点击高级选项
5.选择使用多线程下载“开”
6.点击生成命令
7.通过BBDown下载
8.bug重现
```

### 预期行为

修好

### 截图

![多线程下载合并失败](https://user-images.githubusercontent.com/46448684/161371840-00e25d78-8844-48aa-80d0-7653bebf149d.jpg)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

**Comment by Richasy** [comment]
BBDown的问题请到 [BBDown](https://github.com/nilaoda/BBDown) 提交 Issue
