### ISSUE TITLE
[Bug] 音量显示bug

### ISSUE THREAD

**Issue by blibilijojo** [Richasy/Bili.Uwp#973]
### Bug 描述

全屏状态下音量调整显示不会消失，取消全屏也还有
并且只要应用不关闭会一直显示，哪怕你换视频

### 复现问题的步骤

```plain text
1.打开应用
2.打开视频
3.全屏
4.使用键盘上下键调整
5.bug重现
```

### 预期行为

音量调整显示自动消失

### 截图

![image](https://user-images.githubusercontent.com/102420734/161372435-4cd08b08-05c4-46d3-b3a0-b83cd524a684.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 备注

没想到吧，我又来上传bug了

**Comment by Richasy** [comment]
提及的PR已经修复了包括音量提示在内提示文本的消失问题

**Comment by blibilijojo** [comment]
> 提及的PR已经修复了包括音量提示在内提示文本的消失问题

o，666
