### ISSUE TITLE
[Bug] 更新版后，在视频播放页面点击up主头像后出校鼠标消失

### ISSUE THREAD

**Issue by xy0124** [Richasy/Bili.Uwp#981]
### Bug 描述

在视频播放界面，点击开up头像查看用户信息界面的时候开始，鼠标箭头就消失了。只能盲目操作。

### 复现问题的步骤

```plain text
如上
```

### 预期行为

正常操作

### 截图

![image](https://user-images.githubusercontent.com/99000021/161386740-49236f4d-6c30-4909-9fc2-0d95eebf0f48.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [X] Windows 10 21H1 (Build 19043)
- [ ] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/平板或笔记本

**Comment by Richasy** [comment]
更新到2.2204.2.0，该问题已在 #975 中修复
