### ISSUE TITLE
[Bug] 当视频有cc字幕时，播放到视频末尾，自动跳转下一p后字幕不会消失。

### ISSUE THREAD

**Issue by KrisowX** [Richasy/Bili.Uwp#983]
### Bug 描述

若视频一p最后一句话仍然有字幕，而下一p没有字幕时，跳p时字幕不会消失，一直留在播放界面。

### 复现问题的步骤

```plain text
1.打开应用
2.选择一个有cc字幕、多p的视频
3.播放视频，等待跳p
3.发现问题
```

### 预期行为

当分p视频切换时，若下一p不存在cc字幕，则字幕自动消失。

### 截图

![image](https://user-images.githubusercontent.com/58591281/161392591-e90438d4-47f1-48f3-82fb-5dc9d0581029.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

**Comment by KrisowX** [comment]
实际上不需要等待视频结束，直接打开一个有字幕的视频并切换分p就能看到这个bug了。
eg：https://b23.tv/BV1wu411q71c
可以先进第9p再进第10p，马上就能复现。

**Comment by Richasy** [comment]
@KrisowX  提供的视频好像不见了

**Comment by KrisowX** [comment]
> 实际上不需要等待视频结束，直接打开一个有字幕的视频并切换分p就能看到这个bug了。 eg：https://b23.tv/BV1wu411q71c 可以先进第9p再进第10p，马上就能复现。

https://b23.tv/BV1Eu411i7Pt
