### ISSUE TITLE
[Feature] 播放界面的UI建议

### ISSUE THREAD

**Issue by Degate** [Richasy/Bili.Uwp#985]
### 问题描述

一点个人想法，希望有所帮助。

### 描述解决方案

![屏幕截图(1)](https://user-images.githubusercontent.com/19262167/161396839-e3ade227-5b29-4378-b691-301643ca8846.jpg)
如图，目前视频信息部分的界面还是有些空，于是萌生了做一个意向图的想法。如此可以顶替掉工具箱中的封面下载，做一个单击封面放大并且独立显示封面的功能，然后添加下载封面按钮。

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
首先空并不是坏事，它能为自适应布局提供方便。
无论如何，视频播放界面始终应专注于播放视频，其它的功能能不要就不要。下载封面可以去工具箱里下载，播放界面没必要再整一个。
而且大多数视频的视频封面是未经设计的，不值得单独列出封面位来显示
