### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by XiaoNNNNNNNN** [Richasy/Bili.Uwp#987]
### 问题描述

那个能弄个保存用户数据嘛？每次都是扫码登陆有点麻烦

### 描述解决方案

或者也可以弄一个与www.bilibili.com关联账号。不用扫码，直接在网页登录

### 附加信息

希望哔哩越来越好~

### 人人为我，我为人人

提出问题就是我对哔哩的期许

**Comment by Richasy** [comment]
目前是保存了登录数据的，每次都登录可能和你的设备网络有关（比如开启了代理之类的）
