### ISSUE TITLE
[Bug] 双击全屏鼠标不会消失（事实上还是有）

### ISSUE THREAD

**Issue by blibilijojo** [Richasy/Bili.Uwp#988]
### Bug 描述

就是双击全屏后，下面的控件自动消失，但是鼠标不会自动隐藏

### 复现问题的步骤

```plain text
1.打开应用
2.打开视频
3.双击全屏
4.重现bug
```

### 预期行为

鼠标全屏后和下方媒体控件一同消失

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

**Comment by Richasy** [comment]
鼠标的有自己的消失逻辑，全屏后不会立刻消失，而是在无操作2s后消失

**Comment by blibilijojo** [comment]
> 鼠标的有自己的消失逻辑，全屏后不会立刻消失，而是在无操作2s后消失

问题是他半天都不关啊！！！

**Comment by Richasy** [comment]
我没有复现这个问题😂
