### ISSUE TITLE
[Feature] 关联视频建议

### ISSUE THREAD

**Issue by blibilijojo** [Richasy/Bili.Uwp#989]
### 问题描述

我觉得可以在立刻播放于上面的标题中间加一个视频的封面
还可以将立刻播放居中，显得更加美观（应该会把）

### 描述解决方案

.

**Comment by Richasy** [comment]
不大明白你的意思，请问有示意图吗？

**Comment by blibilijojo** [comment]
> 不大明白你的意思，请问有示意图吗？

![5VW427`7KPU$X3PGMRO2{%J](https://user-images.githubusercontent.com/102420734/164910156-3d9cb491-8f56-4701-8570-7751c82d964e.png)
就是把下一个视频的封面夹在立即播放和标题之间，下方的立即播放居中
