### ISSUE TITLE
[Bug]视频进度条无法正常打开

### ISSUE THREAD

**Issue by xiaomengzaici** [Richasy/Bili.Uwp#99]
## 复现步骤

- [ ] 这个问题是否能在最新版本中复现？（如果你的应用不是最新版，请在 [Release](https://github.com/Richasy/Bili.Uwp/releases) 中下载最新版）

重现问题的步骤：

1. 打开应用
2. 进入 '任意视频'
3. 点击 '视频中间部分'
4. 进度栏无法正常出现，出现一下又消失了
5. 发现问题

## 环境

应用来源：

- [x ] Microsoft Store
- [ ] Github
- [ ] 其他来源（请注明来源）

应用版本：{应用版本}

系统版本：

- [ ] Windows 10 ver.1809 (17763)
- [ ] Windows 10 ver.1903 (18362)
- [ ] Windows 10 ver.2004 (19041)
- [ x] Windows 11 (22000.194)
- [ ] 内测版本 ({系统版本})

运行设备：

- [ x] 桌面/台式机
- [ ] Xbox
- [ ] ARM64 设备 
- [ ] IoT

Visual Studio 版本:

- [ ] 2017 (15.{版本号})
- [ ] 2019 (16.{版本号})
- [ ] 2022 (17.{版本号})

## 日志记录

[applog.2021-09-19.log](https://github.com/Richasy/Bili.Uwp/files/7190934/applog.2021-09-19.log)

**Comment by xiaomengzaici** [comment]
应用来源是github，上面点错了

**Comment by Richasy** [comment]
在新版中问题是否依然存在？

**Comment by xiaomengzaici** [comment]
已经不会出现了
