### ISSUE TITLE
[Bug] 播放栏控制栏问题（依旧还有）

### ISSUE THREAD

**Issue by blibilijojo** [Richasy/Bili.Uwp#991]
### Bug 描述

媒体传输控件中，播放栏控制栏会提前于其他控制项消失

### 复现问题的步骤

```plain text
1.打开任意视频
2.点击媒体传输控件中随便一个设置选项
3.重现问题
```

### 预期行为

媒体控制栏和控制选项一起显现

### 截图

和之前那个一样
https://github.com/Richasy/Bili.Uwp/issues/954

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
这个虽然不算预期行为，不过我还是挺喜欢这个效果的，它能让我排除一些干扰项
