### ISSUE TITLE
[Bug] 互动视频严重bug

### ISSUE THREAD

**Issue by blibilijojo** [Richasy/Bili.Uwp#992]
### Bug 描述

看完互动视频之后看下一个，然后点击返回就播不了这个互动视频了

### 复现问题的步骤

```plain text
1.打开应用
2.进入互动视频
3.看完
4.随便点击右边视频
5.点击左上角返回
6.bug重现
```

### 预期行为

返回之后自动从开头播放互动视频

### 截图

![image](https://user-images.githubusercontent.com/102420734/161407870-05bef655-1d2c-494e-b1c4-7c984cd8e0c4.png)

### 应用来源

- [ ] Microsoft Store
- [X] Github
- [ ] 其它

### 系统版本

- [ ] Windows 10 1809 (Build 17763)
- [ ] Windows 10 1903 (Build 18362)
- [ ] Windows 10 1909 (Build 18363)
- [ ] Windows 10 2004 (Build 19041)
- [ ] Windows 10 20H2 (Build 19042)
- [ ] Windows 10 21H1 (Build 19043)
- [X] Windows 11 21H2 (Build 22000)
- [ ] 其它 (需注明)

### 运行设备

桌面/台式机

### 人人为我，我为人人

我更擅长发现问题

**Comment by Richasy** [comment]
问题可以修，但从头开始这一行为有待商榷。有些用户需要从上一次退出的地方开始。所以我倾向于保持现有的行为，对于需要返回开头的视频，点一下视频中的返回键即可
